### ISSUE TITLE
Bungee support

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#1002]
hello, lease can you add BungeeCord support ? I have bungee server but when i ban player from freeop server (gtfo,noob,tempban) etc all ban commands no work. 
I ban player and player can still join throught portal 

It is problem in plugin or It doesnt have bungee support?

**Comment by OnlineRepz** [comment]
It's doesn't have bungee support, so you going have to make one yourself.

**Comment by JeromSar** [comment]
TFM is currently incompatible with Bungeecord. I do not have plans to support it, since this feature does not apply to the Total Freedom server.

**Comment by Wild1145** [comment]
Actually, TFM is already compatible with Bungeecord providing you enable IP forwarding in the bungee config and the server configs... Just saying...

**Comment by JeromSar** [comment]
@Wild1145 That's interesting, I never knew that was possible. :)

**Comment by Wild1145** [comment]
@JeromSar Its something reasonably new, I found it when working on my IcarusMod plugin, it saved a lot of work trying to get the IP through the server, you can forward it and the server receives your IP as if you were directly connecting to it.
