### ISSUE TITLE
Cant ban players

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#1007]
hello, I tried server run normal (No bungee) but the bans still not working... I ban player (/noob /gtfo) etc
and player can still join ... (motd says to player you are banned) but can join  
I downloaded jar from releases and bans work well 
but if I download Zip and compile it (in netbeans) and put compiled jar to plugins Bans no work :((
and I really need compiled version no downloaded from Released  
I have translated words in my compiled version

please any helps?  
propablly is problem in code ? 

please how to fix it  I really need it :(

**Comment by DUFCLiam** [comment]
They users may be supred if they are on your IP ways to fix this problem

 - Use a VPN on an account.
 - Get a friend to join and try banning them


I hope this helped.

**Comment by WarrioR151** [comment]
players ar anothwr ip and doesn't have super admins 
Ban work on downloaded version in Released
but no work in Compiled version..

**Comment by DUFCLiam** [comment]
Have you changed code in it?

**Comment by DUFCLiam** [comment]
In the config?

**Comment by WarrioR151** [comment]
I only translated things from English to Czech  but some codes I added from pull requests (items in survival automatically adding into inventory, stop /op spam)
code in bans configs get no edit
BTW: sorry for really bad english

**Comment by DUFCLiam** [comment]
It's ok but try just downloading it and only translating.

**Comment by WarrioR151** [comment]
I tnslated all ... in few months  I don't want translate all again :(

**Comment by WarrioR151** [comment]
but I try compile it and add it on server without translation... originally 
if problem is in plugin or in my codes

**Comment by DUFCLiam** [comment]
Ok, try and test it.

**Comment by WarrioR151** [comment]
BTW: Downloaded version from releases need spigot 1.8.3 
compiled version need spigot 1.8.8

**Comment by ReelPattytothewatty** [comment]
If you're using TFM 5.0, don't use it yet. There is still alot of commands missing, ranks, glitches and etc. Get the 4.3 one.

**Comment by WarrioR151** [comment]
I have TFM Master, It is 4.3 or no ?

**Comment by xDestroyer217** [comment]
That's just the source tree, if you do /tfm in game, or in your server, it'll say the version.

**Comment by WarrioR151** [comment]
Version is 4.3.1072

**Comment by JeromSar** [comment]
@WarrioR151 Are you sure this player is not an admin? Admins bypass bans automatically.

**Comment by Wild1145** [comment]
Depending on how you have configured your bungee networking you may end up giving all players admin (as they all share the same IP) or if you have properly enabled IP forwarding it should resolve the issue. Its worth checking that setting first, then if you are IP Forwarding and still having an issue then we will be able to take a look and see whats gone wrong.

**Comment by WarrioR151** [comment]
hello I fixed it..
but gtfo only works
and Noob work on only few players no all... some players can bypass it (no admins)
+ Stop (AutoEject) 1 minute work amd another /stop 3minutes players can join

**Comment by JeromSar** [comment]
@WarrioR151 /noob or /tban not working is actually a current bug. It will be fixed in TFM 5.0.

With that said, I think this issue can be closed. :)
