### ISSUE TITLE
commands rename

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#1016]
Hello, when I rename command (command_adminworld) to command_saworld
/adminworld still works /saworld too but /adminworld too how to make it only work /saworld?

**Comment by JeromSar** [comment]
You can set a command alias in the `@CommandParameters` annotation. For an example, see https://github.com/TotalFreedom/TotalFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_stfu.java

Please comment if you have any more questions. :)
