### ISSUE TITLE
Worldedit 

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#1017]
hi, please how to allow WorldEdit blocked blocks to superadmins ?
in Master compile version I am superadmin and it says "you are not allowed to use water"
but in downloaded version from released I can use blocked commands Ops cant but I (SuperAdmin) can

how can I add it into compiled version ? what code allow WE blocked blocks to use for SuperAdmins?

**Comment by xDestroyer217** [comment]
This has to be somewhere in the config on the server plugins. Not in the source. @JeromSar

**Comment by WarrioR151** [comment]
please where ? In worldedit folder config or totalfreedom folder config?

ps: I want blocked blocks but I need allow it to only superadmins

**Comment by rsajeey** [comment]
WorldEdit's config.yml

**Comment by WarrioR151** [comment]
I know about Blocked blocks I have ids in but I want to allow Blocked blocks in config to Superadmin use

**Comment by JeromSar** [comment]
@WarrioR151 TFM does not support blocking certain blocks to superadmins.

**Comment by WarrioR151** [comment]
I do not want to block blocks for superadmin
I want to use superadmin blocked Blocks

**Comment by JeromSar** [comment]
@WarrioR151 Superadmins have access to all blocks.

**Comment by WarrioR151** [comment]
In the downloaded version yes
but not in compiled version

**Comment by WarrioR151** [comment]
and I need it in Compiled version

**Comment by JeromSar** [comment]
@WarrioR151 We don't provide support for non-official TFM features.

**Comment by WarrioR151** [comment]
why not ?

**Comment by JeromSar** [comment]
@WarrioR151 That's not the aim of this repository.

**Comment by WarrioR151** [comment]
I need it allowed for superadmins :( and I need it in compiled version because I translating texts to Czech language and in downloaded version I cant translate :(
