### ISSUE TITLE
Disable command feedback gamerule

### ISSUE THREAD

**Issue by Rufure** [TotalFreedom/TotalFreedomMod#1018]
/playsound is a rather spam-filled command as it is widely used and can be spammed to "clear" the chat, therefor making you scroll. Normally, this isn't a huge problem when its used about one time, but when two or more people use it frequently, it can be rather annoying, especially if a staff member is also doing so.

**Comment by PattyToTheWatty** [comment]
Then how will we know if someone is doing pkaysound to another player?

**Comment by JeromSar** [comment]
Actually, I think we need to disable command feedback by default. I believe that's a game rule.

**Comment by Rufure** [comment]
@PattyToTheWatty Commandspy, given you're an admin.
