### ISSUE TITLE
/seen showing IPs to OPs

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1028]
It's very important. This is probably a bug, when an online player is on that's only when /seen wont show their IP. Ops are able to see anyone who's offline's IP in /seen. Which is why this needs to be fixed. I am not sure if this is a bug or if it's suppose to be like that because these days people are ddosing admins and it's all thanks to /seen because that's the quickest way for them to get the target's IP down...

**Comment by DUFCLiam** [comment]
This has been discussed and I am 99% sure this is a duplicate

**Comment by Wild1145** [comment]
IP's are public information and should not be protected the way that we protect them. It defeats the entire point of what an IP address is...

**Comment by Wild1145** [comment]
I have just removed myself from admin, relogged into the server and had an online admin leave the server. I then ran /seen on them and was unable to recreate the issue, all I could see was their previous location (See https://goo.gl/aCqB5l) As such I am closing this until such a time it can be recreated.

**Comment by JeromSar** [comment]
It's important to note that you can always see the IP when running /seen as a superadmin.
