### ISSUE TITLE
Custom /seen command for TFM

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#1029]
To stop bugs allowing ops to see others ops and admin IPS, Why not make a custom /seen command in TFM?

**Comment by JeromSar** [comment]
@LegendIsAwesomes Can you not see that this is a clear duplicate?
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/1028

**Comment by LegendIsAwesomes** [comment]
@JeromSar that issue is reporting the bug, This one is suggesting a new command to maybe fix the bug.

**Comment by JeromSar** [comment]
@LegendIsAwesomes The fix should be presented in the original issue. Image how many issues we'd have if every possible solution for every problem was made in a new issue.
