### ISSUE TITLE
Rollbacking

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1030]
Hello, earlier today my a spawn mind friends and other staff made a spawn but it got greifed if you get the point all am asking is add more ids are something to rollback cause now my spawn is ruined becuase it wasnt worldedit and thats this stupid this is for the devs only and i want something change are rollback better are this freaking updated

**Comment by Sabermc7** [comment]
This suggestion makes no sense. Please explain it more clearer, are you suggesting for a system that rollbacks world edit or so?

**Comment by SlimeGamerMC** [comment]
No like instead of this rollbacking worldedit it rollbacks tnt or something like that not this something that is caused by worldedit

**Comment by Sabermc7** [comment]
TNT is disabled in the game, even if it is enabled rollback can still rollback TNT.

**Comment by Sabermc7** [comment]
TNT and explosives are disabled in the game, not needed.

**Comment by JeromSar** [comment]
We have rollback functionality.

**Comment by DUFCLiam** [comment]
@JeromSar, Is correct only staff may rollback users they can do "/rb <playername>" or "/rollback <playername>"

@ghost, Please review the commands before you make another issue.
