### ISSUE TITLE
Finally a Solution to stop The crashblocks! 

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1031]
I found a Sourcecode we can force spawner to refuse crashblock 

this plugin force spawners to refuse the eggs, same for all eggs includes the Painting and itemframe eggs can trasform the spawner in a crashblock, and when one player try to change the spawn with a egg, a custom message will appear

The message Can be setted in the config file...

here one message example Spawner can't accept Eggs, Due to Crash Eggs, please use /Spawner command to change mob spawner.

1) here the link of the plugin https://www.spigotmc.org/resources/mob-egg-spawner-blocker.2635/
2) here the plugin source https://github.com/Sothatsit/MobEggSpawnerBlocker

**Comment by Sabermc7** [comment]
How will this stop the crash blocks? It's not possible to change spawners using mob eggs, even if it was, players can still spawn crash blocks using /summon and /setblock.

**Comment by LegendIsAwesomes** [comment]
TFM already has this feature.

**Comment by marcocorriero** [comment]
@Sabermc7 i tried in my server , /Setblock and /summon dont support the custom mobspawner code, because the spawner can't accept the Crash Code, and the /summon is not possibile with a painting, i tried to spawn a painting in my server and i not crashed, because painting is not appearing, probably when one place inside the spawner the painting dont have the center entity and mc will crash.... 

i tried to summon a crashblock with /summon 53 1 9 and spawner appeared, but a normal spawner, same for /setblock, TFM the /setblock function is blocked!

/summon can summon only mobs, not a Crashentity...

and /Setblock is blocked for Ops

**Comment by Wild1145** [comment]
This should not be on github, this is not a TFM feature suggestion, but rather a server plug-in suggestion.

**Comment by marcocorriero** [comment]
StevenNL2000 said i need to post it here...

**Comment by PremintexMC** [comment]
Just /ro mob_spawner

**Comment by marcocorriero** [comment]
@PremintexMC this is preventing creating crashblocks ;P

**Comment by aggelosQQ** [comment]
@Wild1145, Steven told him to post this here as the plugin he is suggesting does more things than the one we need and it would drain a big amount of memory to features we do not need. So he said that we should not add the plugin as some ljnes of code would manage to do the same thing this plugin is supposed to do.

PS, sorry for the bad English, hope it makes sense.

**Comment by Wild1145** [comment]
@aggelosQQ The functionality request should be here, but this is just a request for us to add a new plugin, not something the TFM Repo is designed to have.

**Comment by aggelosQQ** [comment]
I believe he was confused and thought he should have posted the plugin here.
