### ISSUE TITLE
Add an [-b] to /setworldspawn

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1033]
As the title said

PR: #1032 {ON HOLD FORGOT THIS ISSUE NEEDS TO BE ACCEPTED}

**Comment by LegendIsAwesomes** [comment]
Mostly pointless.

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes, It makes administrating easier as we may forget to to it.

**Comment by LegendIsAwesomes** [comment]
Honestly; Why broadcast it, let ops find out themselves, publicly announcing a new spawn is just as good as saying 'Hey griefers, grief this new spawn'

**Comment by DUFCLiam** [comment]
That's why there is an option.

**Comment by JeromSar** [comment]
I don't think this is needed, sorry.
