### ISSUE TITLE
Fun command: /cookie

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1034]
███████████████████████████
Just like Cake but with a __*COOKIE*__   
███████████████████████████

**Comment by LegendIsAwesomes** [comment]
Not original atall, just no.

**Comment by DUFCLiam** [comment]
Cool ;)

**Comment by rsajeey** [comment]
No.

**Comment by Wild1145** [comment]
Duplicate Issue.

**Comment by JeromSar** [comment]
For fun features to be implemented, I require them to be original.
