### ISSUE TITLE
Bukkit.dispatchCommand(Bukkit.getConsoleSender(), command); question

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1427]
Why can't we use Bukkit.dispatchCommand(Bukkit.getConsoleSender(), command);

It is in overlord 

` 

            final String command = StringUtil.joinString(args, " ", 1);
           -->  Bukkit.dispatchCommand(Bukkit.getConsoleSender(), command);    <--
            playerMsg("ok");
            return true;
        }`

**Comment by JeromSar** [comment]
No you can not. See the contributing guidelines.

**Comment by Wild1145** [comment]
The *only* time you should use the dispatchcommand functionality is when there is absolutely no other option than to use it.

**Comment by DUFCLiam** [comment]
Thanks @Wild1145 

And @JeromSar Why avoid it?

**Comment by JeromSar** [comment]
@DUFCLiam In nearly all cases, there is a better alternative. Bukkit has an API to handle most Minecraft-related functionality and plugin functionality should be implemented in the form of a bridge (see TFM_EssentialsBridge for example).
