### ISSUE TITLE
When will suggestions be added? =)

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1429]
This isn't really a suggestion, it's a question. So i've seen a lot of suggestions now with the "Accepted" tag but they aren't here yet. E.g. HTTPd ban list and a automated bot that disables onlinemode every 30 minutes. When will all these issues be added? =)

**Comment by Wild1145** [comment]
When someone gets around to writing the code to create and resolve the issue...

**Comment by Sabermc7** [comment]
I mean, when will the suggestions be taken? As in, someone starts coding it because some of the suggestions i've seen are over month(s) old and there isn't any suggestions taken in place. TFM updates rarely happen, I haven't seen a update for months.

**Comment by LegendIsAwesomes** [comment]
When someone makes a PR for an accepted issue, if the code is fine, it compiles etc, @JeromSar will add a 'Ready to merge' label, he will eventually merge all the PR's with the 'Ready to merge' labels all at once.

**Comment by Wild1145** [comment]
Updates are not quick things, especially with the amount of behind the scenes work that goes into TFM. You may not be seeing much work on the Master Branch but the other branches have had major re-writes and feature additions, it is all intentional so as not to cause conflicts within branches.
