### ISSUE TITLE
Command Global Cooldown - /cake

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1430]
I think there should be a global cooldown for when an admin does /cake. A 1 minute cooldown minimum. So for example when I do it, no other admin can do it for the next 60 seconds with a message sent to them saying "You must wait [n] seconds to run this command again".

The reason I am suggesting this is because even though it may be a fun command, admins are starting to abuse it i.e. spamming it and when your inventory is spammed with cake it just gets really annoying, and chat gets spammed with the cake lyrics, i'm sure some others will agree with me, I have seen a lot of ops and admins getting really annoyed and saying "STOP WITH THE FUCKING CAKE". It's not fun if you use this command to grief or troll. Especially if someone is building, they can't be stacked so they flood everyone's hotbar/inventory when it's spammed.

**Comment by Wild1145** [comment]
There used to be a cooldown as a joke when @StevenLawson and @JeromSar were trying to out do each other on the cake command.

**Comment by ReelPattytothewatty** [comment]
I don't think its needed. All it is is text and cake, how can it lag?

**Comment by Sabermc7** [comment]
@ReelPattytothewatty please re-read my whole issue, I didn't say anything about it causing lag.

**Comment by ReelPattytothewatty** [comment]
@Sabermc7 Then whats the point of a cool-down?

**Comment by RobinGall2910** [comment]
I find it useless.

_Especially waiting for a min, the hell's wrong with you._

**Comment by Sabermc7** [comment]
~Facepalm Moment~

@ReelPattytothewatty please re-read my issue over again, you've obviously not read my entire issue, don't ask questions until you read the whole issue. The answer to your question is said.

@RobinGall2910 if it's useless, you don't seem to mind if someone floods your hotbar/inventory with cake? It's just annoying.

**Comment by Sabermc7** [comment]
@RobinGall2910 if it's useless, you don't seem to mind if someone floods your hotbar/inventory with cake? It's just annoying.

**Comment by Nova131** [comment]
@RobinGall2910 I totally agree
It gets so bloody annoying

**Comment by FilezPlays** [comment]
Completely and utterly agree. I'm doing something eg. checking grief and I find thousands upon thousands of pieces of cake in my inventory.

**Comment by Sabermc7** [comment]
Not only that, even if a admin does it once. The one who starts off doing /cake, then all other online admins copy them and do /cake as well which then gets really annoying and floods everyone's hotbar.

**Comment by RobinGall2910** [comment]
@Sabermc7 first of all, no one spams /cake, unless if I had, I had to do something in the Senior Lounge about it. Also, I could care less about me having cakes in my inventory, because no one does /wildcard cake or anything like that on TF. I still think this is a terrible recommendation.

**Comment by RobinGall2910** [comment]
@FilezPlays since when...

**Comment by vladvilcu2006** [comment]
god no object

**Comment by Wild1145** [comment]
I feel that this comes more down to an issue of admins being responsible and sensible on the server. We could add a cool down, but I dont feel it would be a valuable use of developers time...
