### ISSUE TITLE
Add a /speed limit.

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#1431]
I think we should limit /speed to about 5 or 4. This is to prevent lag issues that we've been having.

**Comment by vladvilcu2006** [comment]
Vouch. Great idea

**Comment by ChargedCreeper** [comment]
Yes this is a very serious issue, as people can crash the server near anonymously.

**Comment by Sabermc7** [comment]
Good idea @OutOfYourMind.

**Comment by Wild1145** [comment]
I thought @JeromSar had already put limits in place. This should really either be re-written into TFM or limited in Essentials.

**Comment by DUFCLiam** [comment]
People can still use /speed 10; I will make a PR if accepted.

**Comment by TheCool1Mike** [comment]
Vouch

**Comment by ShadowArmadyl** [comment]
This is a TFM-Essentials issue, /speed is not a TFM command.

**Comment by ShadowArmadyl** [comment]
This is also configurable in the Essentials configuration:
`#Set the max fly speed, values range from 0.1 to 1.0
max-fly-speed: 0.8`

**Comment by JeromSar** [comment]
You can now hard-set the limit in TF-Essentials: https://github.com/TotalFreedom/TF-Essentials/issues/8
