### ISSUE TITLE
bug in //Schem save

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1434]
I made a spawn, if i try to paste the schematic, the redstone doors seems broked, due schematic is not pasting the pistons.

**Comment by Sabermc7** [comment]
You posted this in the wrong section, please make a issue on TF-WorldEdit:
https://github.com/TotalFreedom/TF-WorldEdit

But yes, WorldEdit is bugged as it can't paste details e.g. words on signs, items in containers, etc.

**Comment by OnlineRepz** [comment]
@Sabermc7, not necessarily, TFM got a bridge from WorldEdit plugin to TFM, something like API.

**Comment by Sabermc7** [comment]
@OnlineRepz Yes but this is a WorldEdit issue. This has to be done in TF-WorldEdit.

**Comment by DUFCLiam** [comment]
I have made a issue please continue discussion: https://github.com/TotalFreedom/TF-WorldEdit/issues/17

@JeromSar, Please lock this.

**Comment by vladvilcu2006** [comment]
No. I looked at the logs, and the server was starting. It said the WorldEdit wont paste the items in chests that were at copy and paste due to the version.

**Comment by JeromSar** [comment]
The issue is due to a missing adapter that WE uses to edit the minecraft world. This issue has been pasted on the TF-WorldEdit repository by @DUFCLiam where it can be further discussed.
