### ISSUE TITLE
Cooldown /me

### ISSUE THREAD

**Issue by ReelPattytothewatty** [TotalFreedom/TotalFreedomMod#1435]
Hello, there!
I've noticed that /me only is used to Advertise and spam.
That's why I think we need a Cooldown on /me for about 2 - 4 seconds.

**Comment by Sabermc7** [comment]
Much better one: https://github.com/TotalFreedom/TotalFreedomMod/issues/1436

**Comment by JeromSar** [comment]
Implicitly to be fixed in issue https://github.com/TotalFreedom/TotalFreedomMod/issues/798
