### ISSUE TITLE
Throttle connections from similar IPs

### ISSUE THREAD

**Issue by supergameplayer** [TotalFreedom/TotalFreedomMod#1437]
This is a simple suggestion for stopping spambots.

**Comment by JeromSar** [comment]
@supergameplayer Good idea!

**Comment by Sabermc7** [comment]
Vouch, that'll teach 'em! ;)

**Comment by JeromSar** [comment]
@Sabermc7 No need to vouch. This is not TF forums. This is a developer collaboration platform.

**Comment by DUFCLiam** [comment]
@JeromSar, It makes it easier haha so you know if people like it.

**Comment by JeromSar** [comment]
@DUFCLiam True, but this repository is not for discussing whether players like or dislike certain additions. This repository is for discussing the applicability and possibility of adding said feature.

**Comment by DUFCLiam** [comment]
@JeromSar, Your one is also true.

**Comment by Wild1145** [comment]
Dont think it would be that productive. Most spambots will use very different IP Ranges to avoid this prevention method, all this will do is end up blocking players on unstable connections or with family that play at the same time.

**Comment by DUFCLiam** [comment]
I agree with @Wild1145

**Comment by RobinGall2910** [comment]
I really would like to say this would be a bad implementation, as said by @Wild1145 that it basically it'll just end up blocking users on unstable connections (used to be me) or with a fam. member playing at the same time

**Comment by JeromSar** [comment]
Actually, it wouldn't be that bad. Many server networks already have a similar threshold in place. Additionally, I've found that more often than I expected, spambots do use the same IP.

**Comment by RobinGall2910** [comment]
I'd guess this is definitely going through then.

**Comment by Wild1145** [comment]
I may well have misunderstood this. Are we wanting to set a delay between login requests from the same IP or disallow a user to login on the same IP as someone already connected?

**Comment by AvalancheYT** [comment]
@Wild1145, Jerom is trying to say that if a player join with a ip, the next player (with the same ip) tries to join, but can't because there is a delay.

I agree, this would help to stop the spambot.

**Comment by Wild1145** [comment]
@AvalancheYT Okay, that does make sense. It just makes it a pain if you disconnect and want to reconnect (Ie Kicked from the server)

**Comment by JeromSar** [comment]
Superseded by #1829.
