### ISSUE TITLE
[TCA]

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1439]
I just thought of it earlier, I think in the TotalFreedomMod there should be something like a TCA rank which is mainly like the other ranks, just a dark green prefix with [TCA] in /who and the tag might be 
/tag &8[&2Telnet Clan Admin&8] with a Telnet Clan Admin join message. I don't too much really know any permissions. &2[TCA] would be the same for adminchat.

**Comment by DUFCLiam** [comment]
If this is accepted I will make a PR :)

**Comment by OnlineRepz** [comment]
Duplicate.

**Comment by ReelPattytothewatty** [comment]
Thats really stupid.
STCA is apart of the telnet group.

**Comment by DUFCLiam** [comment]
@OnlineRepz, If this is a duplicate then reference the issue here.

**Comment by JeromSar** [comment]
I believe we've discussed this before but came to the conclusion that adding this rank would not be a good idea. Keep in mind that Telnet Clan Admins are just like regular Telnet Admins when it comes to permissions. They just have the added ability to restart the server. Thanks for contributing.
