### ISSUE TITLE
Ranks are mucked up

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1441]
GrannyMary is SA and Riyrah is SA idk who else.

**Comment by LegendIsAwesomes** [comment]
This is more likely to do with them logging in with more then 1 IGN, The superadmin.yml treats them as different people, causing IP conflicts, causing rank changes.

**Comment by RobinGall2910** [comment]
This normally breaks, it normally happens due to a duplicate player in the config, or it auto-deletes.

**Comment by LegendIsAwesomes** [comment]
@JeromSar What about as a solution, check if the superadmin.yml has multiple players in the superadmin.yml, if so delete all non-active ones and keep the latest one that logged on.

**Comment by JeromSar** [comment]
This has been fixed. The issue was a sideeffect of how UUIDs are stored, thus this bug report is invalid.
