### ISSUE TITLE
The Twitterbot System (Revamped)

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1442]
I got a suggestion. Twitterbot hasn't been around for years now. It's important we have it back. Instead of a verified impostor waiting all day, hours and hours until a telnet or senior comes on. They'll verify using Twitter. First they must set their twitter using **/twitter set [@Twitter]** then when they come on as an impostor, they login Twitter and tweet to @TFUpdates with a hashtag such as #superme to get automatically supered by Twitterbot instantly. This NEEDS to be added as it's been over year(s) now without it and supers are forced to wait hours until a senior/telnet comes on when they could've supered themselves instantly with Twitterbot.

**Comment by Wild1145** [comment]
Duplicate.

**Comment by OxLemonxO** [comment]
supers and telnets*

**Comment by JeromSar** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/issues/164
