### ISSUE TITLE
Block certain world edit commands

### ISSUE THREAD

**Issue by RobinGall2910** [TotalFreedom/TotalFreedomMod#1449]
http://totalfreedom.boards.net/thread/33956/

**Comment by Sabermc7** [comment]
I also suggest blocking /mask. Another griefing tool but can be binded so it's very hard for admins to find the griefer.

**Comment by Wild1145** [comment]
Limits are better than blocking...

**Comment by JeromSar** [comment]
The thread was deleted/removed.
