### ISSUE TITLE
Command Suggestion: /calculator

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1455]
As said in the title, as what you think. A in-game calculator. I suggest adding one. An alias would be /calc.

Command usage:
/calculator [expression]

How to use the command (examples):
/calculator 5 + 5 (5 plus 5)
/calculator 5 - 5 (5 subtract 5)
/calculator 5 * 5 (5 times 5)
/calculator 5 / 5 (5 divided by 5)

When you do it, they'll reply back the answer.
This command is useful for those who are building or those who require some maths in minecraft :P you may never know when it'll get involved. Better than nothing so.;p

**Comment by RobinGall2910** [comment]
Not needed, there's //calc in W/E lol

**Comment by The-Corrupt-Lord** [comment]
What is wrong with using a regular calculator or using the Windows/Mac/Linux calculator?

**Comment by Sabermc7** [comment]
Oh! We already have an in-game calculator. Okay.

/Closed/
