### ISSUE TITLE
Command suggestion: /hide

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1458]
Super+ It will make you fake leave and hide you from /list and /list -a tab and makes it like a vanish command aswell so you do not have particals

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/266

**Comment by DUFCLiam** [comment]
@JeromSar This is totally different so it is not a duplicate.

**Comment by JeromSar** [comment]
@DUFCLiam No, this issue is very similar, if not equal. If you wish to suggest the original issue to implemented differently, you'll have to suggest it as a comment there.
