### ISSUE TITLE
/warn bug

### ISSUE THREAD

**Issue by Adaptified** [TotalFreedom/TotalFreedomMod#1464]
The actual warning message is sent to the admin. A PR has been opened and is pending review regarding this issue.

**Comment by AvalancheYT** [comment]
I am pretty sure this is a duplicate

**Comment by DUFCLiam** [comment]
Wait he duplicated his own post?

**Comment by Wild1145** [comment]
@DUFCLiam Its easy enough to do... The original issue was from nearly 8 months ago... I'd have forgotten the issues I have opened that long ago.

**Comment by DUFCLiam** [comment]
xD Brother  again... Welp I may have even done it myself haha
