### ISSUE TITLE
Command Suggestion: /ptoggle

### ISSUE THREAD

**Issue by Sabermc7** [TotalFreedom/TotalFreedomMod#1466]
I think we should have a command called /ptoggle. It's exactly the same as the former command we had (/dtoggle). But instead of toggling Disguisecraft. This will be an admin command and it'll toggle PortalGun instead. An alias could be /pgtoggle and maybe also add an alias argument in /toggle, so we have /toggle portalgun.

It'll then announce a message in chat saying:
"[sender] - Disabling PortalGun" if disabling.

Every time an admin disables portal gun, the command sender must do /pg clear too to make sure that there wont be any portals left in the server until it's re-enabled again. To make sure it doesn't corrupt, an example code would be below where the player would clear all portals BEFORE the plugin gets disabled so that if they do it after they can't as the plugin is disabled, and portal guns would still remain in the world.

-----------------------------------------------------
Code:
Player player = (Player) sender;
player.performCommand("pg clear");
// whatever code that disables portal gun goes here
----------------------------------------------------

and:
"[sender] - Enabling PortalGun" if enabling.

**Reason to add**
This command's significance is to make sure players don't abuse it in a way to troll. Recently, trolls have been making portals right **at**, the key term "at" spawn that anyone who goes to spawn will fall into the portal and it could take them to a troll place such as the portals teleporting them to lava or a PVP arena so that anyone innocent in survival that goes to spawn is forced to teleport to a killing zone.

**Extra suggestion (optional)**
If it hasn't done so already, '/pg clear' must be an admin command only. It would also be great if there could also be an alias such as "/pgremove" or "/pgall" etc that WONT toggle portal guns but will remove them all and announce a message saying:
"[sender] - Removing all portals."

**Comment by xItsNickHD** [comment]
Yeah- good idea! :+1:

**Comment by RobinGall2910** [comment]
I wouldn't allow adding this, because what if PortalGun was removed in the near, near future? Also, this would be useless if a soon-to-be owner of a freedom server never wanted the PortalGun plugin.

**Comment by OxLemonxO** [comment]
object
just use /pg clear when you see one of them

**Comment by Wild1145** [comment]
I like the idea, we added /pgtoggle to CJFreedomMod back way back when and it made life a lot easier for everyone from supers to the system admins.

**Comment by ShadowArmadyl** [comment]
Object, players can't place multiple red/blue portals, I don't see this being an issue.

**Comment by Wild1145** [comment]
Given the fact that it is unlikely that Portal gun would be added (Even though it is a great plugin), we do always have /plc and I think that enough admins should know how to do that. And if we should add the portal gun plugin in the future then we can always re-open this issue.
