### ISSUE TITLE
Continuing #77

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1467]
# Continuing #77 

I will be trying to make the /config comm

**Comment by OxLemonxO** [comment]
wat?

**Comment by DUFCLiam** [comment]
FIXED: My mistake with the # haha

**Comment by DUFCLiam** [comment]
And @OxLemonxO I will try to make the /config command

**Comment by DUFCLiam** [comment]
Oops :P

**Comment by OxLemonxO** [comment]
Why are you continuing things from 2013?
We don't need it.

**Comment by RobinGall2910** [comment]
can you not fix things from 2013, its not needed

_be smart and go to the config by yourself_
