### ISSUE TITLE
/lockdown (and few other commands) dont work

### ISSUE THREAD

**Issue by bloxxingblocks** [TotalFreedom/TotalFreedomMod#1472]
and give me unknown command error.......

**Comment by bloxxingblocks** [comment]
Also for some reason some commands are gone and give unknown command error even on console, like /lockdown

**Comment by AvalancheYT** [comment]
TFM 5.0 is currently under development.

**Comment by bloxxingblocks** [comment]
Well why is /lockdown gone also?

**Comment by AvalancheYT** [comment]
it's /toggle lockdown not /lockdown
