### ISSUE TITLE
FrontDoor

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1473]
The TFM frontdoor has IP's that it randomly will say or other things.
The IP is outdated, just noticed that.
That's basically it, the IP of the TFM FrontDoor is outdated.

(Note: By IP I mean the message and signs the frontdoor places have an outdated IP on them.)

**Comment by DUFCLiam** [comment]
I know I tried to fix this before my PR was denied

**Comment by JeromSar** [comment]
This is intentional.

**Comment by DUFCLiam** [comment]
@JeromSar but in Minecraft it does not work and in your browser it does now work.

**Comment by OxLemonxO** [comment]
@JeromSar ForceIP will not allow you to join with tf.sauc.in.
