### ISSUE TITLE
AdminMode

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1478]
For some reason, ops were on after admin mode.
Screenshot is here.
![2016-02-06_09 39 34](https://cloud.githubusercontent.com/assets/15840630/12867544/cca1097e-ccb5-11e5-92ef-6a6a613d703d.png)

**Comment by AvalancheYT** [comment]
@JeromSar, I think it's a bug.

**Comment by OxLemonxO** [comment]
mark did /tfm reload, so tfm is reloaded and adminmode is purged. that's why.

**Comment by AvalancheYT** [comment]
@OxLemonxO, /TFM reload doesn't do that.
Maybe a glitch?

**Comment by rovertdude** [comment]
@OxLemonxO 
This was right after he did /adminmode on; they were questioning [and so was mark] why they were online still.

**Comment by OxLemonxO** [comment]
@AvalancheYT /tfm reload DOES do that
It silently removes adminmode.

**Comment by Wild1145** [comment]
TFM reload will reload the entire TFM plugin. Adminmode (Like command spy for example) is not persistent, as soon as you reload TFM or the server it will reset to the default state of offline unless the configuration file has been changes to change the default state.

**Comment by JeromSar** [comment]
@Wild1145 is right. Did mark use /tfm reload right after this?

**Comment by AvalancheYT** [comment]
@JeromSar, it doesn't affect the admin mode after the TFM is reloaded.

**Comment by rovertdude** [comment]
@JeromSar They were on during adminmode as they never got kicked from it as I did /list a small bit after adminmode
not sure if this will be approved as TFM 5.0 was released

**Comment by Wild1145** [comment]
It may need further investigation and testing with 5.0 then.

@AvalancheYT TFM reload would have reset the adminmode to off, adminmode is only set in config manually, not overwriting the config value every time adminmode is toggled.

**Comment by JeromSar** [comment]
Fixed. :)

**Comment by Wild1145** [comment]
Parts of this has been continued on #1830
