### ISSUE TITLE
/purgeall should purge particles

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#1479]
Well; Since we have a particles plugin why not make /purgeall purge particle effects.

**Comment by PacksGamingHD** [comment]
I think its a good idea

**Comment by AvalancheYT** [comment]
Well, there is a problem. What if the owner (Different server owner) doesn't wants particles plugin.

**Comment by LegendIsAwesomes** [comment]
There developers will have to manually remove it. This is for TF not any other server.

**Comment by AvalancheYT** [comment]
Actually, this is not just for TF. Other people use this if they can't develop and don't want any developers.

**Comment by LegendIsAwesomes** [comment]
The command just won't work, simple as.

**Comment by MrImmaculate** [comment]
This can be done, you can check if the plugin exists and if it does, loop the PP plugin and use a clear function.

**Comment by JeromSar** [comment]
No, I don't think we need this. Thanks for the suggestion!
