### ISSUE TITLE
Cancel pvp damage if in God or gmc

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1480]
This would make god and gmc pvp alot more difficult. Basically, when a player attacks another player, if the attacking player is creative or God mode, the attack event gets cancelled, and possibly warn admins of creative/God pvp attempt.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/287
