### ISSUE TITLE
Busy system

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#1483]
Why not have a busy system, If a player tries to message an admin but they have /busy enabled they get a message saying 'Adminame is busy please contact another admin' or such.

**Comment by RobinGall2910** [comment]
Basically just like DarthCraft's busy system, right @Wild1145?

**Comment by AvalancheYT** [comment]
I don't think that would be necessary as us, admins, can just use /afk.

**Comment by xItsNickHD** [comment]
I actually like it.

@AvalancheYT, if /afk actually let people not message you, then this would be denied. But instead it doesn't.

**Comment by Wild1145** [comment]
That is correct. Though this should be a duplicate as I believe I already raised the issue before...

**Comment by DUFCLiam** [comment]
Duplicate of #498
