### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1486]
I think there should be something in the config allowing the host console to use any command [other than something like player only commands] for servers that don't use Rcon.

**Comment by RobinGall2910** [comment]
"CONSOLE_ONLY" is one of the variables.

**Comment by rovertdude** [comment]
@RobinGall2910 
I know, but some commands have the host console blocked from using them, causing some people to try to do them, if they might be banned or something from a rogue admin on a different server, they can't /glist ban as it's blocked for the host console.

**Comment by xItsNickHD** [comment]
@rovertdude Then couldn't you just add or remove their name from the list in the configs on the telnet/root accessibility?

**Comment by rovertdude** [comment]
@xItsNickHD 
What if they had no idea?
This would help as all you would need is to make the option enabled in the config [if accepted]

**Comment by Wild1145** [comment]
We have actually decided to go the other way and block access to most commands from RCON and Console due to their ability to be used autonomously.

**Comment by JeromSar** [comment]
Also, this feature already exists. If you set `console_is_senior` to true, the host console gets senior level perms.
