### ISSUE TITLE
/blockcmd -s

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1487]
Essentially /stfu -s just for /blockcmd :P

**Comment by xItsNickHD** [comment]
Not really imo.

**Comment by AvalancheYT** [comment]
It is already implemented - see https://github.com/TotalFreedom/TotalFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_stfu.java#L57-L71

**Comment by LegendIsAwesomes** [comment]
This has been suggested to block all commands for non-sa's my PR is being reviewed.

**Comment by rovertdude** [comment]
@AvalancheYT @LegendIsAwesomes 
This is different.
/stfu -s smites the user and mutes.
If /blockcmd -s would be added, it would smite then block their commands.

**Comment by LegendIsAwesomes** [comment]
Not needed.

**Comment by Wild1145** [comment]
I agree with the previous comments, I don't think this is required or needed.
