### ISSUE TITLE
Balloons

### ISSUE THREAD

**Issue by ImJustLazyGH** [TotalFreedom/TotalFreedomMod#1488]
I think we should add another fun feature like color customizable balloons with a string, of course toggle-able. I spoke to @JeromSar about this and he thought it was a good idea.

**Comment by rovertdude** [comment]
not sure if this can be done too well without any bugs or anything.

**Comment by Adaptified** [comment]
@rovertdude It can.

**Comment by JeromSar** [comment]
@Adaptified How exactly do you propose to implement such a feature?

**Comment by Wild1145** [comment]
The problem you will have is a "balloon" is a circle, they are not very easy to make in MC...

**Comment by DUFCLiam** [comment]
No, @Wild1145 we can use stained clay also make an invisible mob in there so we can have the string effect with a lead; You do not have the item it follows you.

**Comment by DUFCLiam** [comment]
It's just a copy of a balloon plugin.

**Comment by Adaptified** [comment]
@JeromSar A listener.

**Comment by JeromSar** [comment]
@Adaptified You have got to be more specific than that. :P

**Comment by DUFCLiam** [comment]
@JeromSar @Adaptified Means you use a listener to summon the block and after so many ticks/blocks it will move.

**Comment by DUFCLiam** [comment]
Also it would lag.

**Comment by DUFCLiam** [comment]
@JeromSar please view #1502

**Comment by Wild1145** [comment]
I think on this occasion it would be better to add a 3rd party plugin for this, as it seems like a lot of development effort for something that has already been done, and wouldn't require any real customisation.
