### ISSUE TITLE
Announce mob purges

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#1494]
When you do /mp, it doesn't announce mob purges in the chat, it only messages you with how many mobs were removed. I think we should make it so that it announces when the admins does /mp, and if this issue gets accepted, I will make the pull request. What I mean by announce is a  TFM_Util.adminAction(sender.getName() addition when the player does the command.

**Comment by PieGuy7896** [comment]
Why would you need to broadcast this in the first place?

**Comment by JeromSar** [comment]
@OutOfYourMind Good idea.
