### ISSUE TITLE
Can't find a jar that works with compiling

### ISSUE THREAD

**Issue by CheaseMC** [TotalFreedom/TotalFreedomMod#1500]
**Hello!**
I can't find any jars that work for **compiling**.
Please give me the jar link I can use.
Thanks!

**Comment by AvalancheYT** [comment]
To get latest spigot, please visit http://spigotmc.org/
To get latest BukkitTelnet and others, please visit click TotalFreedom and click those plugins
To get latest stable TotalFreedomMod, go in source code and click release.

**Comment by JeromSar** [comment]
There's also a tutorial for compiling TFM [on the wiki](https://github.com/TotalFreedom/TotalFreedomMod/wiki/Compiling-TotalFreedomMod).
