### ISSUE TITLE
Feature suggestion: Security mode

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1504]
So in config we can have a new int called `security mode` it goes from 1-3, 1 being normal how it is now, 2, Being a bit more secure and 3, being very secure

1 = Normal running.

2 =  Will clean admins for 10 days inactivity, Can add more.

3 = Will remove admin on logoff and mark disabled so they need to re-verify, Can add more.

**Comment by AvalancheYT** [comment]
I don't think this is needed. Our system work fine, /saconfig clean and it deactivates the inactive admins.

**Comment by DUFCLiam** [comment]
I know but this will make security a bit better

**Comment by Wild1145** [comment]
I see no improvement here...

**Comment by JeromSar** [comment]
Sorry, but I don't think we need or want this.
