### ISSUE TITLE
All PRs closed

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1505]
WTF are you doing xD over 50 closures in 1s

**Comment by JeromSar** [comment]
@DUFCLiam What are you talking about?

**Comment by DUFCLiam** [comment]
You just closed all open PR's is this getting ready for 5.0? Or something? @JeromSar

**Comment by JeromSar** [comment]
Whoops, my bad. See this: http://totalfreedom.boards.net/thread/36260/whoops-closed-prs
