### ISSUE TITLE
TFM5.0 won't compile?

### ISSUE THREAD

**Issue by PacksGamingHD** [TotalFreedom/TotalFreedomMod#1510]
Not sure exactly what to do here since this is Mavenized

cd /Users/snip/NetBeansProjects/TotalFreedomMod-tfm50; JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home "/Applications/NetBeans/NetBeans 8.1.app/Contents/Resources/NetBeans/java/maven/bin/mvn" install
Scanning for projects...

Some problems were encountered while building the effective model for me.totalfreedom:TotalFreedomModMaven:jar:5.0
'dependencies.dependency.systemPath' for org.spigotmc:spigot:jar should not point at files within the project directory, ${project.basedir}/lib/Spigot-1.8.7.jar will be unresolvable by dependent projects @ line 70, column 25
'dependencies.dependency.systemPath' for net.totalfreedom:bukkittelnet:jar should not point at files within the project directory, ${project.basedir}/lib/BukkitTelnet-4.2.jar will be unresolvable by dependent projects @ line 78, column 25
'dependencies.dependency.systemPath' for net.totalfreedom:tf-worldedit:jar should not point at files within the project directory, ${project.basedir}/lib/TF-WorldEdit-6.1.0.jar will be unresolvable by dependent projects @ line 86, column 25
'dependencies.dependency.systemPath' for net.totalfreedom:tf-essentials:jar should not point at files within the project directory, ${project.basedir}/lib/TF-Essentials-2.0.jar will be unresolvable by dependent projects @ line 94, column 25
'dependencies.dependency.systemPath' for org.spigotmc:spigot:jar refers to a non-existing file /Users/snip/NetBeansProjects/TotalFreedomMod-tfm50/lib/Spigot-1.8.7.jar @ line 70, column 25
'dependencies.dependency.systemPath' for net.totalfreedom:bukkittelnet:jar refers to a non-existing file /Users/snip/NetBeansProjects/TotalFreedomMod-tfm50/lib/BukkitTelnet-4.2.jar @ line 78, column 25
'dependencies.dependency.systemPath' for net.totalfreedom:tf-worldedit:jar refers to a non-existing file /Users/snip/NetBeansProjects/TotalFreedomMod-tfm50/lib/TF-WorldEdit-6.1.0.jar @ line 86, column 25
'dependencies.dependency.systemPath' for net.totalfreedom:tf-essentials:jar refers to a non-existing file /Users/snip/NetBeansProjects/TotalFreedomMod-tfm50/lib/TF-Essentials-2.0.jar @ line 94, column 25

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.
Building TotalFreedomMod 5.0
BUILD FAILURE
Total time: 0.682s
Finished at: Mon Feb 29 21:03:17 PST 2016
Final Memory: 6M/245M
Failed to execute goal on project TotalFreedomModMaven: Could not resolve dependencies for project me.totalfreedom:TotalFreedomModMaven:jar:5.0: The following artifacts could not be resolved: org.spigotmc:spigot:jar:1.8.7-R0.1-SNAPSHOT, net.totalfreedom:bukkittelnet:jar:4.2, net.totalfreedom:tf-worldedit:jar:6.1.0-TF, net.totalfreedom:tf-essentials:jar:2.0-TF: Could not find artifact org.spigotmc:spigot:jar:1.8.7-R0.1-SNAPSHOT at specified path /Users/snip/NetBeansProjects/TotalFreedomMod-tfm50/lib/Spigot-1.8.7.jar -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by ItzLevvie** [comment]
You've to add the dependencies.

**Comment by PacksGamingHD** [comment]
How would I do that?

**Comment by DUFCLiam** [comment]
Get the dependencys needed and add it to the build path

**Comment by AvalancheYT** [comment]
With Maven prij ct, you don't need to add jars. It will compile by its own.

**Comment by DUFCLiam** [comment]
Just add jars :P

**Comment by Wild1145** [comment]
TFM 5.0 I believe was designed to be compiled using Jetbrains IntelliJ JDK instead of Netbeans (I think) either way its a Maven project and *most* dependencies will automatically be pulled down, some might not be depending on the dependencies used.

**Comment by JeromSar** [comment]
TFM 5.0 was designed to be compiled with Maven on any IDE (Eclipse, Netbeans, IntelliJ, etc.), however, it is not suitable for production yet. It is currently in heavy development. Please wait before it is released.
