### ISSUE TITLE
Feature suggestion: Track the original IP banned in GTFO's, Tempbans, Glist bans

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1511]
Track the IP that was original banned this will stop people being unbanned that are suppose to be banned.

**Comment by Wild1145** [comment]
Okay...? I dont really see what you are wanting for us to change...

**Comment by JeromSar** [comment]
/gtfo was designed to be a temporary ban. What exactly is the purpose of keeping these banned IPs tracked?

**Comment by DUFCLiam** [comment]
For range bans, as people are claiming to be range banned but then we check that .yml and see if they where.

**Comment by Wild1145** [comment]
GTFO doesnt range ban. The last to octaves are hidden for security...

**Comment by DUFCLiam** [comment]
Oh... xD
