### ISSUE TITLE
Fun commands toggle in config.yml

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1512]
We can do a search to check if it is true of false, And add another thing in one of the `@` annotations it can be ", funCommands = <Boolean value>"

**Comment by JeromSar** [comment]
What are the benefits of such a feature?

**Comment by DUFCLiam** [comment]
If people only want it for staff administration, And do not want fun commands they can be disabled.

**Comment by FoxIshDaBest** [comment]
Good idea, kind of like twitterbot?

**Comment by DUFCLiam** [comment]
Yeah, It will make them optional =D

**Comment by FoxIshDaBest** [comment]
Cool. I tried doing something like that before.

**Comment by DUFCLiam** [comment]
Cool, Wanna try thin on PFM?

**Comment by FoxIshDaBest** [comment]
I could maybe try working on it after I get home from school in a bit.

**Comment by DUFCLiam** [comment]
Ok, Also please go to that issue

**Comment by RobinGall2910** [comment]
I don't find this useful.

**Comment by FoxIshDaBest** [comment]
Robin it could be able for other freedom owner's servers, but then again, they should have developers to code them custom freedom mods...

**Comment by FoxIshDaBest** [comment]
It still could be a cool idea..

**Comment by DUFCLiam** [comment]
But there developers may only be able to do is add people to ranks in `TFM_Utils`

**Comment by JeromSar** [comment]
@FoxIshDaBest @DUFCLiam Please refrain from commenting if the comment does not apply to both TFM _and_ TotalFreedom. Thanks.

**Comment by DUFCLiam** [comment]
Okay :)

**Comment by ShadowArmadyl** [comment]
I don't think this would help at all, and what exactly do you refer to when saying "fun commands"?
It would be easier to block each individual command.

**Comment by DUFCLiam** [comment]
No, We can reference it in console as "STRICT_MODE"

**Comment by JeromSar** [comment]
I don't think TF desires such a feature. Thanks for the suggestion however! :)
