### ISSUE TITLE
Error in NetBeans

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1515]
>import net.minecraft.server.v1_8_R3.EntityPlayer;
import net.minecraft.server.v1_8_R3.MinecraftServer;
import net.minecraft.server.v1_8_R3.PropertyManager;

says there is an error.

Screenshot:
[Screenshot](http://i.imgur.com/ffn5yJD.png)

**Comment by AvalancheYT** [comment]
Use latest version of Spigot (1.8.8 or 1.8.9 is recommended) to resolve this issue.

**Comment by DUFCLiam** [comment]
Okay.

**Comment by DUFCLiam** [comment]
@AvalancheYT Can you supply the JAR for Spigot 1.8.* please.

**Comment by AvalancheYT** [comment]
I am not allowed to give you my jar, I haven't modified but you will need know...
Use this link - http://www.spigotmc.org/threads/minecraft-1-8-8-release.81138/

**Comment by JeromSar** [comment]
You can compile Spigot yourself if you follow the instructions on the page provided by @AvalancheYT. That should fix your problems. :)

**Comment by DUFCLiam** [comment]
I done it before :P Just can't be bothered but gotta do it for code :P

**Comment by DUFCLiam** [comment]
@JeromSar @AvalancheYT What is the code in git to do again for a Git bash
