### ISSUE TITLE
Enchancement Command Smite

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1521]
/smite Player : Reason, will be more useful, without using /say , when you type /smite player testing

will say Player was a naught naught boy

Reason: Dont Fastbow near spawn etc...

**Comment by Adaptified** [comment]
Duplicate

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848
