### ISSUE TITLE
(TFM 5.0) Cannot block players commands

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#1524]
It says they're a super admin, I might be able to fix this.

**Comment by Wild1145** [comment]
Can you explain how you re-created this? I cannot re-create it in game...

**Comment by LegendIsAwesomes** [comment]
A normal op was spamming command, I did /blockcmd (his name) and it came up saying he is a admin when he wasn't.

@Wild1145

**Comment by Wild1145** [comment]
I just tested it on Farrah_, I removed his admin, reloaded the adminlist, checked he was not admin and blocked his commands. TFM blocked the commands and proceeded to stop him being able to run commands... I am not sure why you had the bug (that should be a bug by the looks of #1525) and yet worked for me...

**Comment by JeromSar** [comment]
It was fixed some time ago.
