### ISSUE TITLE
Revert to the legacy tags

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#1526]
Currently there is a lot of hate over the new admin tags, personally I am not a huge fan myself and If possible I think we should look at reverting to the legacy 4.3 style.

**Comment by LegendIsAwesomes** [comment]
'The old tags were too long. They caused some admins to overflow messages to two lines very often. The new tags are the same as the ones used in /list.' - Prozza

**Comment by Wild1145** [comment]
I still think that we need to look at the design of the new tags and see if we can make the best of both worlds, try to make them look as close to the old ones as possible.

I also see nothing bad about two lines of text on the screen...

**Comment by LegendIsAwesomes** [comment]
I don't either, Prozza just said that.

**Comment by Wild1145** [comment]
There is some negotiation to be had, I dont mind them being [SA] etc, I think they should be more separated like the other ones (I remember them actually being prefixed instead of part of the nickname by the looks of it...).

**Comment by JeromSar** [comment]
That's a good point @Wild1145. I'll very well take that into consideration.

**Comment by ShadowArmadyl** [comment]
I agree to this - the new admin tags also make it hard to know which is which.

**Comment by Rufure** [comment]
#1537 may interest some of you as it removes the need for legacy.

**Comment by JeromSar** [comment]
TFM's tags have been updated and you can see the changes on TF.

Unless there are further objections. This issue will be closed in the near future.

**Comment by Wild1145** [comment]
I think the tags are greatly improved. There are a few tag related things to change in my opinion, but they should be raised separately.
