### ISSUE TITLE
Tab Screen Colours

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#1527]
For some reason the tab colours have been removed (The screen you see as you hold down tab), I am not sure why this is as the original issue of having their tags before was removed and resolved the issue. I assume this was just overlooked in the 5.0 release.

**Comment by ShadowArmadyl** [comment]
I'm pretty sure this was still an issue in TFM 4.3, and the player skins will not show in TAB either (but I'm assuming that it's a cracked/premium issue).

**Comment by Wild1145** [comment]
When it comes to the skins thats a spigot config issue. The tab colours were working on 1.8 (TFM 4.3) so I am not sure if it were "broke"

**Comment by rovertdude** [comment]
Aren't these done in /scoreboard?

**Comment by ShadowArmadyl** [comment]
rovert, that makes it very annoying to add every admin in /scoreboard.
Sometimes the scoreboards reset also.

**Comment by Wild1145** [comment]
Using /scoreboard is a very tedious way to do it. We can implement it with TFM, I am not however sure if @JeromSar did write it into TFM 5.0 or if it was overlooked.

**Comment by JeromSar** [comment]
@Wild1145 Bukkit has a scoreboard API of course. :)

**Comment by Wild1145** [comment]
@JeromSar Yes, however I was referring to manually adding and managing everyone through /scoreboard in game, TFM automation would make things a lot easier, just like it used to be.

**Comment by JeromSar** [comment]
This is actually a Spigot bug: https://hub.spigotmc.org/jira/browse/SPIGOT-1624

It has been resolved, so updating Spigot should fix the issue. Updating soon. :)

**Comment by Wild1145** [comment]
Makes sense, last night when I checked we were over 80 versions behind...

**Comment by JeromSar** [comment]
Solved. :)
