### ISSUE TITLE
ai not working

### ISSUE THREAD

**Issue by DominicPlayz** [TotalFreedom/TotalFreedomMod#1528]
please fix /ai because it doesn't work

**Comment by Adaptified** [comment]
You need to elaborate - what does it say?

**Comment by Wild1145** [comment]
The command has been removed, likely because we dont really like the whole walls of text commands... I am not sure if @JeromSar plans to reimplement anything like it, but right now its not even a command.

**Comment by LegendIsAwesomes** [comment]
/ai isn't broken; The problem is /ai is a acidfreedom command, the plugin AcidFreedom is no longer on the server.

**Comment by Wild1145** [comment]
I belive /ai was also a TFM command?

**Comment by LegendIsAwesomes** [comment]
No @Wild1145 It never was, It was only a AcidFreedom command. On associated servers there developers added it in, it was never in TF.

**Comment by Wild1145** [comment]
I stand corrected. In that case it is unlikely this will be implemented as it would not meet the contributing guidelines.

**Comment by JeromSar** [comment]
This is rather something that should be part of the /info command: https://github.com/TotalFreedom/TotalFreedomMod/issues/423
