### ISSUE TITLE
/tag with prefix

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#1530]
When an admin uses /tag set [tag], the prefix [SA] should appear after the tag instead of overriding it.
For example: /tag set [ShadowCrew]
The tag will still set to [ShadowCrew] however your assigned rank will still be present.
"<[ShadowCrew] [SA] Shadow>"

**Comment by OxLemonxO** [comment]
I like changing the tag to the legacy tag though, by overriding it

**Comment by Wild1145** [comment]
I think you need the best of both worlds or the option to either append or overwrite?

**Comment by JeromSar** [comment]
I cannot reproduce this.

**Comment by Wild1145** [comment]
I have managed to reproduce the issue. It is not totally clear.

Currently /tag set <tag stuff here> will overwrite your current tag regardless of what it may be. What @ShadowArmadyl is suggesting is that running /tag set <tag stuf here> will not overwrite but effectivly prefix the tag, so /tag set CoolStuff would have my title as CoolStuff [Dev] Wild1145>:

**Comment by ShadowArmadyl** [comment]
^, basically what I was saying.

**Comment by JeromSar** [comment]
I understand now.

While I can understand where you're coming from, you should note that the "rank tag" and the "tag" are essentially the same thing. Thus when setting the tag, it is overwritten. No distinction is made currently. However, if you would like to get both tags you can always set that with /tag set [Tag1] [Tag2].

**Comment by Wild1145** [comment]
I think that might be a good addition @JeromSar

**Comment by DUFCLiam** [comment]
I do not really like this idea sorry.

**Comment by Wild1145** [comment]
@DUFCLiam The idea is that you could as an admin add a second tag if you wanted... You wouldnt HAVE to use this change...

**Comment by DUFCLiam** [comment]
Yeah, That's what I was thinking try building the other command in it.

**Comment by JeromSar** [comment]
I don't really like the idea much, sorry.

**Comment by Wild1145** [comment]
@JeromSar It was your idea???

**Comment by JeromSar** [comment]
@Wild1145 No?

**Comment by Wild1145** [comment]
>I understand now.

While I can understand where you're coming from, you should note that the "rank tag" and the "tag" are essentially the same thing. Thus when setting the tag, it is overwritten. No distinction is made currently. However, if you would like to get both tags you can always set that with /tag set [Tag1] [Tag2].
