### ISSUE TITLE
Auto-Item-Wiping doesn't work (bug)

### ISSUE THREAD

**Issue by WilliePlaysMC** [TotalFreedom/TotalFreedomMod#1532]
Auto-wiping doesn't work. I can drop items when auto-wiping is off and when it is on. Please fix this minor issue.

**Comment by PacksGamingHD** [comment]
I tried it and it wipes items when its on and off

**Comment by JeromSar** [comment]
Two conflicting stories, @WilliePlaysMC, @PacksGamingHD?

**Comment by JeromSar** [comment]
I cannot reproduce this. The entity wiper works fine on TFM. :)
