### ISSUE TITLE
Error with Compiling

### ISSUE THREAD

**Issue by PacksGamingHD** [TotalFreedom/TotalFreedomMod#1533]
BukkitTelnet on the project (auto compile) is outdated and the WorldEdit hasn't been updated so its ```me.StevenLawson``` instead of ```me.totalfreedom```

Other than that I just get my normal errors with the dependencies

**Comment by JeromSar** [comment]
You need to update all dependencies, including BukkitTelnet.

**Comment by PacksGamingHD** [comment]
I did but I'm still getting an error

**Comment by Adaptified** [comment]
@PacksGamingHD Compiling worldedit is done with gradle. Look up a tutorial.
