### ISSUE TITLE
/Saconfig Setrank

### ISSUE THREAD

**Issue by jjkatz** [TotalFreedom/TotalFreedomMod#1539]
Is it possible to allow people with telnet to make themselves telnet through the command. It would only be available through Telnet.

**Comment by Wild1145** [comment]
You cant have access to telnet without being a telnet...

**Comment by WilliePlaysMC** [comment]
What? That isn't possible. You are saying that people that are not telnet aka supers can't access telnet in the first place.

**Comment by jjkatz** [comment]
@Wild1145 I mean like give telnets with telnet to have access to make themselves telnet through the command. Lets say they pherhaps are not supered on the server but still have telnet access. So lrt

**Comment by Wild1145** [comment]
I dont see how thats going to make a difference, you are giving yourself the ability to set yourself to a rank that you dont have in game, so you cannot set yourself to that rank because you would be promoting yourself as far as TFM is concerned.

**Comment by jjkatz** [comment]
@JeromSar Let me clarify. If your not supered as telnet in saconfig, telnet won't work for you?

**Comment by Wild1145** [comment]
@jjkatz Correct

**Comment by JeromSar** [comment]
Unless you have the password that is. Either way, TFM won't add such a system. Feel free to add it to your own fork if you like. :)
