### ISSUE TITLE
/skin set command

### ISSUE THREAD

**Issue by WilliePlaysMC** [TotalFreedom/TotalFreedomMod#1540]
Check out what mark said here:
http://totalfreedom.boards.net/thread/36669/skin-set-command?page=1&scrollTo=411721

**Comment by Wild1145** [comment]
This is not a TFM command, so I am not sure why it is "blocked"

**Comment by WilliePlaysMC** [comment]
Can we unblocked it though because i don't see it causing harm to the server.

**Comment by Wild1145** [comment]
I dont know where its even blocked

**Comment by WilliePlaysMC** [comment]
If you do /skin set ingame it says blocked? Is it in the config file?

**Comment by Wild1145** [comment]
Possibly... I dont know, I dont have FTP

**Comment by AvalancheYT** [comment]
It is blocked in config. Ask him to unblock it.

**Comment by OxLemonxO** [comment]
Just use /skin change. It has a 30 second delay so no one can spam it too.
