### ISSUE TITLE
gtfo not displaying reasons

### ISSUE THREAD

**Issue by graslej** [TotalFreedom/TotalFreedomMod#1541]
Willie wanted me to report this for him. Anyway after some testing willie  found out that gtfo apparently does not display reasons to the user

**Comment by WilliePlaysMC** [comment]
Yes. I asked Funky_Chicken_ to ban me on a alt so i didn't bypass bans. After the gtfo screen i relogged and only saw who banned me and not the reason.

**Comment by Wild1145** [comment]
GTFO should only list the reason when they attempt to login again, not on the initial kick screen.

**Comment by Adaptified** [comment]
@Wild1145 That's what he is describing - it's not showing up at all.

**Comment by rovertdude** [comment]
A similar thing happens for /glist ban reasons - doesn't work at all.

**Comment by JeromSar** [comment]
Superseded by https://github.com/TotalFreedom/TotalFreedomMod/issues/1546
