### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by DominicPlayz** [TotalFreedom/TotalFreedomMod#1544]
When you unfreeze a player, the server freezes. Can you fix this?

**Comment by JeromSar** [comment]
@DominicPlayz What do you mean exactly?

**Comment by Adaptified** [comment]
On the unfreeze action, it freezes everyone. @JeromSar

**Comment by JeromSar** [comment]
I just tested this on TFM. The latest release (not yet synced with the repo) does not have this bug.
