### ISSUE TITLE
Persist tags

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#1547]
Setting a /tag and then relogging will remove the tag, regardless of rank.
Since we already have the ability to clear all tags, there's no point of wiping it upon relog.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/208

**Comment by ShadowArmadyl** [comment]
@JeromSar - this is not a duplicate.

**Comment by AvalancheYT** [comment]
@ShadowArmadyl, if you read carefully, it is a duplicate.
Same thing but different phases.

**Comment by ShadowArmadyl** [comment]
@AvalancheYT, oops, sorry. I thought this was another issue.
