### ISSUE TITLE
Unblock /list for imposters

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1550]
Blocking /list for imposters is causing me and other admins confusion as we can't do /list when we are set as imposters. We cannot see if any telnets are online. The same thing a bit is with /report as we can try to /report gmc pvpers or more without them figuring out we are reporting them and getting away with it.

**Comment by DUFCLiam** [comment]
I agree with this suggestion.

**Comment by JeromSar** [comment]
Good idea.

**Comment by Wild1145** [comment]
Was this blocked as of 5.0? I never recall this being blocked before...

**Comment by JeromSar** [comment]
@Wild1145 It was not, but Impostors literally have no-permissions whatsoever. The rank is literally below non-op, so impostors could not use /list.

**Comment by jjkatz** [comment]
It should probably be restricted to list -a

**Comment by JeromSar** [comment]
@jjkatz I don't see why impostors should be banned from listing all players.

**Comment by Wild1145** [comment]
@JeromSar I think he is saying that they should only be allowed to run /list -a not just /list
