### ISSUE TITLE
Block /skinsrestorer

### ISSUE THREAD

**Issue by TheCool1Mike** [TotalFreedom/TotalFreedomMod#1554]
People can change other's skins. This works for Admins and OPs.

**Comment by DUFCLiam** [comment]
This can me changed to stop them changing other peoples skin.

**Comment by WilliePlaysMC** [comment]
I'd disagree because this is just like nicking others. A smite is worthy we don't need to block a whole command because of 1 little issue.

**Comment by rovertdude** [comment]
I think it should be blocked.
If /skin set is blocked,  this should be blocked.

**Comment by WilliePlaysMC** [comment]
Um /skin set is about to be unblocked.

**Comment by WilliePlaysMC** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/issues/1540

**Comment by JeromSar** [comment]
@WilliePlaysMC is right.
