### ISSUE TITLE
Ops can bypass any type of bans

### ISSUE THREAD

**Issue by jimzmodz** [TotalFreedom/TotalFreedomMod#1555]
Hello, i am running a modified stable version of TFM mod which is made for 1.8  and i am using it on 1.9 and every player that get any type of bans(/gtfo /glist ban /noob /tban) can bypass them all! even they are not admins!. Anyway i am having the same problem in 1.8 AND 1.9 any suggestions?

**Comment by DUFCLiam** [comment]
@jimzmodz Have you confirmed this bug? May we see a small video? Log proof? Screenshots?

**Comment by JeromSar** [comment]
What is the version of your TFM exactly (type /tfm)?
Is there a notification saying that you're running the wrong version at start up?

**Comment by jimzmodz** [comment]
My version of tfm  is : Version 4.0.44
Up to date error: 
WARN]: [BlueFreedomModV5] BlueFreedomModV5 is compiled for v1_8_R2 but the server is running version v1_9_R1! 
[20:13:26 WARN]: [BlueFreedomModV5] This might result in unexpected behaviour!

Ban error: http://imgur.com/HOIUABm

**Comment by jimzmodz** [comment]
Want a video or something?

**Comment by JeromSar** [comment]
WARN]: [BlueFreedomModV5] BlueFreedomModV5 is compiled for v1_8_R2 but the server is running version v1_9_R1! 

There's your problem. Try running Spigot 1.8.7 for this TFM version.

**Comment by jimzmodz** [comment]
There is anyway that i can like use it on 1.9

**Comment by jimzmodz** [comment]
I compiled it with 1.9

**Comment by jimzmodz** [comment]
and spiggot 1.9 and cbukkit 1.8.3

**Comment by jimzmodz** [comment]
issue was fixed(i think havent tried yet)
