### ISSUE TITLE
Lightnings broken

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#1559]
Lightning effects doesn't show up when using smite gtfo etc. I think 1.9 broke this.

**Comment by Wild1145** [comment]
Some description maybe?

**Comment by JeromSar** [comment]
Elaborate?

**Comment by DUFCLiam** [comment]
Maybe it does not kill them... Or something?

**Comment by JeromSar** [comment]
@Adamx120 ?

**Comment by WilliePlaysMC** [comment]
When i /smite people. The lightling doesn't come out of the sky like it used too.

**Comment by Adaptified** [comment]
Was this confirmed?

**Comment by TheCool1Mike** [comment]
I confirm this; I don't see the lightning bolt shooting the person.

**Comment by AvalancheYT** [comment]
Lightning does hurt the player but the Lightning doesn't shows.

**Comment by ray27890** [comment]
I agree with @AvalancheYT, @JeromSar

**Comment by DUFCLiam** [comment]
Just to let people know, The lightning is an effect and will work like normal but there is a 'player.setHealth(0,0)'

**Comment by vj13573** [comment]
I do not think this is the good place to submit this issue, better to submit the bug to Mojang. But yeah, it's true that no one can see lightning in 1.9, they can hear it though.

**Comment by Wild1145** [comment]
I have just tried it in game, as of the current build running on the server this is not still a bug. If anyone is able to re-create the issue in the future please re-open this issue.
