### ISSUE TITLE
Add a cooldown to clownfish

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1560]
The clownfish has been causing some bot attacks and mainly just spamming.
Perhaps a small cooldown should be added on it?

**Comment by JeromSar** [comment]
@rovertdude I don't see how the clownfish could be causing bot attacks? It's an admin-only feature.

**Comment by rovertdude** [comment]
I mean the "is a clown" part of it.

**Comment by JeromSar** [comment]
@rovertdude I don't understand. Only admins can do that, right?

**Comment by rovertdude** [comment]
@JeromSar I believe op's can as well. Going on with a VPN and seeing it rn.

**Comment by rovertdude** [comment]
Confirmed it does show it for ops

**Comment by rovertdude** [comment]
Misclicked, sorry

**Comment by PacksGamingHD** [comment]
if an op or sa clicks a clownfish it says "player is a clown"

**Comment by JeromSar** [comment]
Changing this to be a player-only message.

**Comment by Adamx120** [comment]
@JeromSar 
I did make it :c 10 secound cooldown is not enough?
