### ISSUE TITLE
FuriousDestroyer

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1561]
The user FuriousDestroyer isn't on /list -f.
http://i.imgur.com/V8Zb04Y.png

**Comment by Adaptified** [comment]
I do not know who that is!

**Comment by rovertdude** [comment]
@Adaptified https://www.youtube.com/user/PopularMMOs
FuriousDestroyer is his account on his channel

**Comment by ShadowArmadyl** [comment]
Question: is the famous players configurable?

**Comment by ItzLevvie** [comment]
@ShadowArmadyl Yes.
