### ISSUE TITLE
Command://(And blocking "super pickaxe"

### ISSUE THREAD

**Issue by WilliePlaysMC** [TotalFreedom/TotalFreedomMod#1566]
// activates "super pickaxe" a form of undetectable grief. Is this intentional. Also i recommend blocking /superpickaxe. This allows you to do undetecable grief when you use a pickaxe and break blocks with /superpickaxe on.

**Comment by rovertdude** [comment]
Do you mean to auto-block it by default in the TFM config?
It's blocked by default in TotalFreedom but not on github I believe

**Comment by DUFCLiam** [comment]
May you confirm that this has not been blocked.

**Comment by JeromSar** [comment]
`//` is blocked. See https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm43/src/config.yml#L109
