### ISSUE TITLE
OPs can do /spectator

### ISSUE THREAD

**Issue by CoolCraftPlayz** [TotalFreedom/TotalFreedomMod#1567]
Hi. I recently noticed that in TFM 5.0 we can now do /spectator. This gives us admins a better way to get closer to rule rulebreakers without them noticing we are there. The only problem is that OPs can do this command. I suggest that you block this command for OPs

**Comment by JeromSar** [comment]
@CoolCraftPlayz Is that really the case? I thought this was covered. Looking into it.

**Comment by JeromSar** [comment]
Just verified that this is not the case.

**Comment by DUFCLiam** [comment]
@JeromSar What do you mean? Is it blocked to supers+ in config?

**Comment by JeromSar** [comment]
@DUFCLiam No, it's simply a superadmin+ command.

**Comment by DUFCLiam** [comment]
Ok, Thank you for this confirmation :) @JeromSar
