### ISSUE TITLE
Show name in-game when using /gtfo

### ISSUE THREAD

**Issue by TheCool1Mike** [TotalFreedom/TotalFreedomMod#1570]
Currently, when /gtfo is used, it looks like this:

[name] has been a very naughty, naughty boy.
Banning [name] and IPs [rangedIP].

I suggest it be changed to so we know who is banning the player:

[name] has been a very naughty, naughty boy.
[Sender] - Banning [name] and IPs [rangedIP].

I realized I made a typo in the last PR. If people like this idea, I'd happily redo the PR.

**Comment by AvalancheYT** [comment]
No. It's fine how it is.

**Comment by Adaptified** [comment]
@AvalancheYT You have absolutely no authority, we want an opinion, not an answer.

Please elaborate, both messages you provided look the same.

**Comment by TheCool1Mike** [comment]
@Adaptified Fixed. The message didn't show up correctly.

**Comment by Adaptified** [comment]
This was suggested already, cannot find the issue but it definitely was as I made a PR for it in 2015.

**Comment by Wild1145** [comment]
I thought this was already a thing anyway... Shows about how much attention I pay to the ban messages I guess.

**Comment by AvalancheYT** [comment]
@Adaptified, I was giving my opinion. Now stop, you're annoying me.

**Comment by Adaptified** [comment]
@AvalancheYT No reason to get hostile. But "No" isn't an opinion.
