### ISSUE TITLE
Range Ban

### ISSUE THREAD

**Issue by jimzmodz** [TotalFreedom/TotalFreedomMod#1573]
so i got banend, did an appeal and it got accepted but they said it is a <<range>> ban. Can you please tell me that there is a way to get away with this <<rangeban>>
See: http://totalfreedom.boards.net/thread/37127/ban-appeal

**Comment by Wild1145** [comment]
This has nothing to do with the TotalFreedomMod project. Please raise the issue on the TotalFreedom Forums at www.totalfreedom.boards.net
