### ISSUE TITLE
Echest

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1574]
i noticed two command can't be used by ops and admins

/echest
/enderchest

I know this command allow you to edit other's enderchest. but enable it to admins, to check if enderchest have forbidden items inside.

**Comment by RobinGall2910** [comment]
Enderchests get wiped anyways, and I don't think this should be needed overall.

**Comment by DUFCLiam** [comment]
@RobinGall2910, It is not used but `Total Freedom`

**Comment by RobinGall2910** [comment]
@DUFCLiam doesn't prove my point

**Comment by marcocorriero** [comment]
@JeromSar mark unblocked echests,you can lock it
