### ISSUE TITLE
/mp message confusing?

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1578]
I think it should be saying purging all entities and mobs

```
[00:42:25] [Server thread/INFO]: WilliePlaysMC issued server command: /mp
[00:42:25] [Server thread/INFO]: WilliePlaysMC - Purging all entities
```

**Comment by WilliePlaysMC** [comment]
Yes. I believe there is no difference between "Purging all entities" and "Removing all server entities"

**Comment by AvalancheYT** [comment]
Duplicate to issue #1569

**Comment by ChargedCreeper** [comment]
@AvalancheYT updated it to be not a duplicate per se. I really think the wording could be improved to prevent confusion as to what's actually happening.

**Comment by Adaptified** [comment]
Rd does the same thing.

**Comment by JeromSar** [comment]
@ChargedCreeper I think rather that the command might be changed to prevent confusion. After all, this command _does_ really purge entities, including, but not limited to, mobs.
