### ISSUE TITLE
Voting rawsay

### ISSUE THREAD

**Issue by DominicPlayz** [TotalFreedom/TotalFreedomMod#1582]
Was just wondering if the server chould automatically add like an command /raysay Vote for this server for blah blah. Maybe this will make TF more popular? A suggestion.

**Comment by Adaptified** [comment]
A lot of the times, issues suggested here are suggested by users who aren't so fluent in english or just might not have sufficient grammar. What I am basically saying is that this makes absolutely no sense. 

What I am able to get from that is that you're suggesting a command that triggers an announcement for voting.

**Comment by DominicPlayz** [comment]
Yes, that's what i'm meaning.@adaptified

**Comment by Wild1145** [comment]
Given we now have the announcer, I will close this issue.

What I would suggest is someone posting on the forums or having a chat with Mark on the forums, and suggesting he adds an announcement to vote for the server, along with getting all the voting setup.
