### ISSUE TITLE
/Blockcmd Suggestion

### ISSUE THREAD

**Issue by xItsNickHD** [TotalFreedom/TotalFreedomMod#1584]
I have a suggestion; what if you can use /blockcmd to blockcmd a specific command onto a player?

It'll be like this; 

/blockcmd <player> <on/off> <command>

and if the command is left null, block all commands.

**Comment by ShadowArmadyl** [comment]
We already have /blockcommands, having /blockcmd as a separate command would start a lot of confusion.

**Comment by JeromSar** [comment]
@ShadowArmadyl One is an alias to the other. The command already exists.

@xItsNickHD While I like your suggestion, I don't think it is what we want for TF. Thanks for the suggestion!

**Comment by Wild1145** [comment]
Personally, I think this could be useful in some cases.
