### ISSUE TITLE
Add rank owner

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1585]
Title said it, i checked something and i saw something strange, in tfmod 5.0 rank owner dont exist, and i noticed this, when i helped 230Daniel to fix his rank position, can you fix this missing rank?

**Comment by JeromSar** [comment]
The rank owner does not exist because it is a title, not a rank in TFM.

**Comment by DUFCLiam** [comment]
@JeromSar, So "MarkByron" shows up as senior then sets his tag.

**Comment by marcocorriero** [comment]
@JeromSar but if a rogue senior will demoted and permbanned, mark can't demote same higher rank staff, rank owner give total access to tf commands, senior, telnet , and superadmin commands -.- like an override in all ranks access and rank commands.

**Comment by marcocorriero** [comment]
@JeromSar but if a rogue senior will demoted and permbanned, mark can't demote same higher rank staff, rank owner give total access to tf commands, senior, telnet , and superadmin commands -.- like an override in all ranks access and rank commands.

**Comment by JeromSar** [comment]
@DUFCLiam No, that's not the case.

@marcocorriero No, TFM does not provide such a feature. Mark has access to FTP, which he can use to edit the config manually, such such an event ever occur.

**Comment by Adaptified** [comment]
Owner just returns a tag, its not actual rank, understand this.
