### ISSUE TITLE
Clownfish issue

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#1587]
On totalfreedom with the clownfish it gives you a glitches block called "potato" and it doesn't crash you but it should be a real potato

**Comment by JeromSar** [comment]
@AlexFreedomMod I have no idea what you're talking about. Please be more specific.

**Comment by AlexFreedomMod** [comment]
Well after you do the clownfish thing as an op you get an item after it says you a clown and that item is gliched out, It doesn't work it has no texture and is just broken I think it should be a baked potato because potato item for some reason doesn't work

**Comment by JeromSar** [comment]
@AlexFreedomMod Will look into, thanks.

**Comment by AlexFreedomMod** [comment]
Your welcome

**Comment by DUFCLiam** [comment]
@JeromSar, You just need to add/remove  _ITEM in the code.

**Comment by Adamx120** [comment]
@DUFCLiam Just need to modify POTATO to POTATO_ITEM

**Comment by AvalancheYT** [comment]
I looked into this and you would need to remove _ITEM part away from clownfish.

**Comment by Adaptified** [comment]
We get it.

**Comment by Wild1145** [comment]
Is this still an issue?

**Comment by Alex33856** [comment]
I do not believe it's an issue anymore
