### ISSUE TITLE
Real and Fake Famous Players

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#1594]
If a famous player is real (Premium) announce that:
For Example: PewDiePie is real.
And if there's a famous player imposer announce that when join:
For Example: PewDiePie is not real.

Not very possible that famous players join TF, but it is good for credulous players to distinguish real and not real

**Comment by PacksGamingHD** [comment]
its not hard. all you have to do is create a listener and if one of the names is in the config then it'll announce else it won't

**Comment by LegendIsAwesomes** [comment]
Thing is Minecraft will struggle finding out if they're premium, Aslong as they have the exact same IGN as the premium account, it will act like they're premium (Even with /premium), though it will not let them log on when onlinemode = true.

**Comment by JeromSar** [comment]
The implementation of this feature is actually much more difficult than it sounds.


@PacksGamingHD I think you might be misunderstanding what @Adamx120 is suggesting.

**Comment by superhaystack** [comment]
This would be usefull, but how the heck would we implement it?

**Comment by DUFCLiam** [comment]
I do not get why we should implement this, As if a spambot/spam network login with they names (They change the "usernames.txt" file) it would majorly lag the server. And more than likely crash the server.

**Comment by ShadowArmadyl** [comment]
This would never be used as famous players never join the server, this is just giving them more attention.

**Comment by JeromSar** [comment]
I think @ShadowArmadyl is making a fair point. This feature would be really helpful, but it wouldn't be used. Additionally, its implementation is very difficult.

That being said, I don't think this issue should be implemented in TFM. Thanks for contributing!
