### ISSUE TITLE
GitHub suggestion: New team

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1595]
We can add a team of people (Trusted members of the TotalFreedom community and trusted with more powers on GitHub) who have more permissions that the regular user, They will be able to expand on the [Wiki](https://github.com/TotalFreedom/TotalFreedomMod/wiki) and people can tag them like this: @TotalFreedom/trusted or something like that. After the / will be the ranks name.

**Comment by Adamx120** [comment]
You want more permissions? ^^

**Comment by DUFCLiam** [comment]
Not me but people like @AvalanchYT

**Comment by JeromSar** [comment]
@DUFCLiam I don't think this is a good idea. Additionally, only members with push-access can edit the Wiki. There is no 'permission' system for Github teams.

**Comment by DUFCLiam** [comment]
@JeromSar, There is In team settings.you can make it so they have "Something, Write, Admin"

**Comment by JeromSar** [comment]
@DUFCLiam I am aware of that.
