### ISSUE TITLE
Feature suggestion: Super Client

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1598]
What do you think of a "Super Client" but there is a difference between Super and Telnet; Supers would only get Super Admin permissions, And it will scan for any thing such as rogue activity happening in it, There can be a list that will be blocked. Such as a punishment (If you have been suspended for going rogue, misusing the client, to many warnings, etc) you will have your privileges from Super Client removed.

**Comment by ItzLevvie** [comment]
successful client

**Comment by JeromSar** [comment]
What exactly do you mean with 'super client'? I have no idea what you're talking about. Please elaborate.

**Comment by DUFCLiam** [comment]
That super admins have a client but the forums clearly do not want it.

Issue closed.

**Comment by Wild1145** [comment]
This has been discussed via PM, I think there was some confusion around what Telnet actually is.
