### ISSUE TITLE
Saconfig Add isn't working?

### ISSUE THREAD

**Issue by WilliePlaysMC** [TotalFreedom/TotalFreedomMod#1599]
Check this out

http://totalfreedom.boards.net/thread/37908/rcon-telnet-working

it was wierd. This did not occur to this one admin only. It also occurred to FaZeMelonKing when i tried to super him it shows the message however it doesn't physically super him.

**Comment by JeromSar** [comment]
@WilliePlaysMC I just pushed a new version to the server. This bug shouldn't occur anymore.
