### ISSUE TITLE
Requesting closure of all currently opened PR's

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1601]
The title says it all; Close all PR's currently open as they are 4.3

**Comment by JeromSar** [comment]
No, some can be migrate to 5.0. :)

**Comment by JeromSar** [comment]
Upon reconsideration, I think that might be impossible in Githubs PR/merge system.

**Comment by JeromSar** [comment]
@DUFCLiam However, you _should never_ spam every PR with such a message. If you continue to spam this repository, you leave me no choice but to ban you from it.

**Comment by DUFCLiam** [comment]
@JeromSar. I noticed therefore I just made this thread. Rather than doing the other 9

**Comment by DUFCLiam** [comment]
@JeromSar, May you close them?

**Comment by RobinGall2910** [comment]
Some of these are hotfixes, not all of them should be closed. Don't assume all of them aren't compatible with 5.0.

**Comment by DUFCLiam** [comment]
@JeromSar, Will this be taken into action or will I close this issue?

**Comment by JeromSar** [comment]
@DUFCLiam All accepted issues will be acted up eventually. Closing them prematurely won't help.
