### ISSUE TITLE
Players can break blocks in protected areas

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1604]
If they break the block with a sword they will be able to break the block! @JeromSar

**Comment by RobinGall2910** [comment]
Yeah, and then this was hardly ever used now... Due to the problems that WorldEdit can just simply bypass the protected area.

**Comment by Wild1145** [comment]
Minecraft has disabled the ability to break blocks with a Sword now, so this bug should no longer be an issue.
