### ISSUE TITLE
Change ban message

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1607]
I suggest mostly we change the message from /gtfo from "GTFO" to something like "You have been banned" or something else.

**Comment by DUFCLiam** [comment]
I would like implementation of this. @rovertdude

**Comment by RobinGall2910** [comment]
I'd like it the way as is. It's been like that for a few years, why change the tradition?

**Comment by AvalancheYT** [comment]
I agree with Robin... Why change 'GTFO' when there is nothing wrong with it.

**Comment by JeromSar** [comment]
I like the way /gtfo is currently implemented. The ban reason can be viewed by attempting to log in again.
