### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by PacksGamingHD** [TotalFreedom/TotalFreedomMod#1608]
So the server is running TFM that was compiled on March 15 and the latest release is on March 13. However, the source code is outdated and doesn't contain the latest fixes and stuff like announce and smite reasons. Will the source code be updated to add all these features?

**Comment by DUFCLiam** [comment]
This is just like ChickenFreedom, They run a higher version to test it then they implement it to GitHub in mass amounts. @JeromSar Feel free to correct me.

**Comment by RobinGall2910** [comment]
You should stop tagging Jerom every time you post or comment anything in GitHub, I can tell it can get pretty annoying, and then this isn't probably the case, or sometimes its forgotten to be pushed into git.

**Comment by Adaptified** [comment]
He just had final exams, he is busy. Stop bugging him, be patient.

**Comment by PacksGamingHD** [comment]
Oh. I never knew :P

**Comment by JeromSar** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/releases
