### ISSUE TITLE
/verify

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1609]
I suggest whenever a impostor joins, it automatically will show up with the /verify message or automatically do the command.
Perhaps this can be toggled in the config for other servers that might not have /verify.

**Comment by AvalancheYT** [comment]
Actually no, the verify command is made in a plugin that wild made.

**Comment by rovertdude** [comment]
@AvalancheYT 
I know - I'm thinking for it to be automatically executed if they are an impostor and it is enabled in the config or similar.

**Comment by Wild1145** [comment]
This is an issue that you should take up on the DaedalusMod project as /verify is not a part of TFM. See https://github.com/Superior-Development/DaedalusMod

**Comment by Wild1145** [comment]
Given I don't feel this issue will meet the contributing guidelines (the whole it just being a wall of text), I will close this issue, however it is in the DaedalusMod issues.
