### ISSUE TITLE
/spectator other users

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1610]
I suggest we allow using /spectator on other people.
This can help for events or similar if we ever do one and a possible /opall -spec or similar.

**Comment by JeromSar** [comment]
@rovertdude I don't understand why we need such a feature. Could you provide a use case?

**Comment by rovertdude** [comment]
@JeromSar 
I think it can be used for events on TF or other servers using the TFM or allow certain users and undercover admins to /spectate themselves via telnet/rcon to possibly find griefers. Mostly that's what I thought of.

**Comment by xItsNickHD** [comment]
Well, we already have /gmsp.

**Comment by AvalancheYT** [comment]
@xItsNickHD, Ops can't use /gmsp because it's an admin use only.

**Comment by JeromSar** [comment]
Spectator mode was designed to be admin only for a reason: Spectators become invisible to players in Creative and Survival. For that reason, I don't think implementing this feature is a good idea.
