### ISSUE TITLE
./ov addme is broken

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1611]
Using /ov addme is broken.
It doesn't super you.
It just says "ok"

**Comment by Adamx120** [comment]
I swear it supers you, but why you need it?, It's for mark

**Comment by JeromSar** [comment]
The feature works.

**Comment by DUFCLiam** [comment]
@rovertdude https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/resources/config.yml#L320
