### ISSUE TITLE
Admin Management Broken

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#1612]
So for some reason, when a player changes their name (Granted irritating already) when you go to remove their old entry from admin and add their new one, it is not possible. When you attempt to remove their old one it removes them, however when you try to find their information on the old entry it does not exist. When you try to re-add the old entry it then says they are still admin. 

When you try to add their new entry, it says they are being added, and the messages go through, however they do not get superadmin nor are they viewable in /saconfig list or /saconfig info

No errors are being thrown.

**Comment by WilliePlaysMC** [comment]
Confirmed. Happened to me yesterday when my config entry jumped.

**Comment by CrafterSmith12** [comment]
I never changed my name and it's happening to me.

**Comment by JeromSar** [comment]
@Wild1145 I just pushed a new version to the server. Does the bug still occur?

**Comment by xItsNickHD** [comment]
If you have someone else using your IP, it might be the case or if you have a premium account and you're not using it.

**Comment by JeromSar** [comment]
@Wild1145 ?

**Comment by Wild1145** [comment]
@JeromSar I have not seen any further issues or been made aware of any, so I believe this is fixed.
