### ISSUE TITLE
Armorstands keep vanishing

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1613]
If i place one armorstand the armorstand keep vanishing, i can't make statues, or custom unique welcome messages, me and _obi tried to place an armorstand and OBi disabled the mob limiter, but keep vanishing...

**Comment by Wild1145** [comment]
They are classes as an entity and not a block, so the entity purge system will wipe them automatically. 

@JeromSar This is a bug not a enhancement.

**Comment by JeromSar** [comment]
@Wild1145 I believe they are explicitly marked as wipe-able, thus this issue should discuss whether that is desired behavior or not. Therefore, this is not a bug.

**Comment by marcocorriero** [comment]
@JeromSar i tried after doing toggle entitywipe, and entitywipe kept wiping armorstands and blocks after disabiling it

**Comment by PacksGamingHD** [comment]
/killall all gets rid of armor stands
