### ISSUE TITLE
Telnet Clan. Admin

### ISSUE THREAD

**Issue by Superior-tL** [TotalFreedom/TotalFreedomMod#1617]
I would like to add a new rank called
Telnet Clan. Admin from the fourms and I would like to create it, and I want to add it to /saconfig setrank TELNETCLAN_ADMIN.

**Comment by RobinGall2910** [comment]
no.

1) only for tf, no one else
2) clan admin is for *clanforge*
3) no.

**Comment by Superior-tL** [comment]
Why and clan admin is just a add on rank to totalfreedom I'm trying to help

**Comment by Adaptified** [comment]
@Superior-tL

This has been suggested and denied since it it technically not a real rank, as well as the fact that clanforge is being ditched soon for the vps.

**Comment by JeromSar** [comment]
@Superior-tL Thanks for your suggestion. However, I don't think we want a new rank for Clan admins. As you might already know, the ranks are effectively equal considering in-game permissions.

**Comment by Wild1145** [comment]
The only advantage to having a telnet clan rank would be to allow them to /wipeflatlands, however with that said if RCON can do it, the problem is solved.
