### ISSUE TITLE
Bug (Not sure what)

### ISSUE THREAD

**Issue by FilezPlays** [TotalFreedom/TotalFreedomMod#1619]
![](http://i.imgur.com/Us72rv7.png)

I was just doing some world editing in AW

**Comment by AvalancheYT** [comment]
I think it reached to your limit, have you tried changing the limit?

**Comment by DUFCLiam** [comment]
@AvalancheYT No shit Sherlock :P

ONT: Shouldn't this be in TF-World Edit?

**Comment by Wild1145** [comment]
@DUFCLiam Why dont you show just a little respect before making yourself look like a complete idiot on a public repo. If you havent got anything productive to say, get off the repo.

**Comment by DUFCLiam** [comment]
@Wild1145 I questions in the `ONT:` area.

PS: I don't really mind looking like a complete idiot... You can't really damage my emotions can you. (Maybe to other people but not me)

**Comment by RobinGall2910** [comment]
@DUFCLiam just get off before this shit gets worse.

**Comment by Wild1145** [comment]
@DUFCLiam Then get the hell off of this development platform and stop wasting peoples time by acting like a dick. Either be somewhat productive, or get out.

**Comment by AvalancheYT** [comment]
I have confirm the bug, the error occurs when the worldedit have reached to your max limit.
The way to solve it is to set your limit to -1 (Unlimited) ```//limit -1```

**Comment by JeromSar** [comment]
Should be on TF-WorldEdit repo, and it is: https://github.com/TotalFreedom/TF-WorldEdit/issues/18
