### ISSUE TITLE
How do you make people Superadmin

### ISSUE THREAD

**Issue by Cleinad119** [TotalFreedom/TotalFreedomMod#1624]
I have no clue on how to make people superadmin. I also, created a server, and want to show up as owner. But the way the mod is built, markbyron will show up as owner.

**Comment by AvalancheYT** [comment]
To super players, it's ```/saconfig add <player>

To add yourself to owner, open FTP with your user, pass, hostname. Go in ```plugin```, go in ```TotalFreedomMod``` folder, and open ```config.yml```. Scroll down under ```server``` until you reach ```owners:
    - markbyron``` and add your username in.

**Comment by Cleinad119** [comment]
Thank you!

**Comment by Cleinad119** [comment]
Wait. How do you make people Senior Admin?

**Comment by AvalancheYT** [comment]
To set a player a specific rank - ```/saconfig setrank <player> <rank>```
Example - ```/saconfig setrank Cleinad199 Senior_admin```
```/saconfig setrank IllX Telnet_admin```

**Comment by Cleinad119** [comment]
Ok thanks. That's all I needed.

**Comment by WilliePlaysMC** [comment]
Uh? Issue resolved?

**Comment by DamonOnYT** [comment]
use the command

/saconfig setrank [username] Owner
