### ISSUE TITLE
/cmdspy should automatically turn on upon join

### ISSUE THREAD

**Issue by TheCool1Mike** [TotalFreedom/TotalFreedomMod#1626]
Pretty self-explanatory I think:

Basically, /cmdspy will be on as soon as an admin joins.

**Comment by WilliePlaysMC** [comment]
Why?

**Comment by RobinGall2910** [comment]
Should stay as is, makes the admin to remember to do something, not everything should be automated..

**Comment by Wild1145** [comment]
I fully agree, its something we always did on CJF and I think it makes admins more alert to what is going on. I know @JeromSar was not keen as he wanted it to be "opt in" not "opt out", I know the compromise was to have it continue its setting from where you left it, but thats another issue that this would then duplicate.

**Comment by JeromSar** [comment]
@Wild1145 Actually, I've always been quite fond of auto enabling it. Either way, duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/652
