### ISSUE TITLE
Suggestion: Personal jumppad settings.

### ISSUE THREAD

**Issue by 50GHz** [TotalFreedom/TotalFreedomMod#1630]
When building on Total Freedom, I find it quite annoying to have jump-pads enabled. Other users might enjoy jump-pads. This can possible start unnecessary drama for no reason. A solution to this problem is allowing players to personally disable and enable jump-pads. Admins should be able to change other player's jump-pad settings. Very similar to the /speed command.

Thank you.

**Comment by DUFCLiam** [comment]
This is a duplicate I do not know what the issue number is though.

**Comment by 50GHz** [comment]
Thank you @DUFCLiam. I didn't this was commonly suggested. Hopefully this feature gets added soon.
