### ISSUE TITLE
/tellraw

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1632]
I suggest we have something like /rawsay only can be used ingame by superadmins - can help a bit instead of having to use /wildcard gcmd ? ping (msg) which causes console spam or having to use /tellraw perfectly with only one color.

**Comment by AvalancheYT** [comment]
/rawsay is for seniors+ only to stop from Super Admins trolling/abusing.

**Comment by JeromSar** [comment]
This was done on purpose. /rawsay will stay as is. Thanks for contributing!
