### ISSUE TITLE
Updating github tfmod source

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1635]
I mean, electrum 5.0 is bugged after our edit why you dont update github and let's get us the fixed tfmod with all issues fixed?

**Comment by JeromSar** [comment]
@marcocorriero I hope to update and release TFM Electrum in one commit. :)

**Comment by marcocorriero** [comment]
Thanks
Will be useful to fix marcofreedommod

**Comment by JeromSar** [comment]
@marcocorriero The source for TFM Electrum has been posted: https://github.com/TotalFreedom/TotalFreedomMod/releases
