### ISSUE TITLE
/ban

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1637]
Mostly suggesting to possibly add /ban as a alias of /gtfo - can help for things such as family members learning or other servers using the TFM that might not know how to ban and simply default ban users.

**Comment by Wild1145** [comment]
Im not sure if we want to have alias's? I know we did go through a period of removing all but a few a little while ago?

**Comment by JeromSar** [comment]
I don't think we want this as an alias. It's important to know the difference between /gtfo and /ban (as seen on many other servers). Making /ban an alias would instead rather confuse new admins in my opinion.
