### ISSUE TITLE
Approved Issues

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1638]
Possibly I think we should close issues that have been approved and they have been added to the TFM, whether in the server or on github.
I see a lot of approves issues that are already in the TFM now - can help with confusion and developers finding things to add or other things.

**Comment by Wild1145** [comment]
If said issues have been implemented and are live on this repo now, then they should be closed. If they are not then double check and if you are 100% sure it has already been implemented tag a developer in the issue saying its been implemented. If its only live on the server then it is possible another plugin handles it (Like DaedalusMod or Essentials for example) or that it is coming soon to the Github, and when pushed will close the issue.
