### ISSUE TITLE
Revamp TwitterBot

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#164]
TwitterBot is old, outdated, counter-intuitive, slow and fails to work on occasion. The entire system needs to be redesigned.

**Comment by DUFCLiam** [comment]
@JeromSar, May we just remove "TwitterBot" it is never used.

**Comment by JeromSar** [comment]
@DUFCLiam It has been removed in TFM 5.0.

**Comment by Wild1145** [comment]
@JeromSar If it has been removed should this issue not be closed?

**Comment by Wild1145** [comment]
@JeromSar Do you still think working on Twitterbot is worth it? Or should we migrate to Discord all together?

**Comment by aggelosQQ** [comment]
I prefer Discord.

**Comment by Wild1145** [comment]
@aggelosQQ As do I, and its why I am somewhat tempted to close this in favour of it. But I'd rather @JeromSar decide if its something he wants to revive or let die off.

**Comment by Wild1145** [comment]
@JeromSar Do you still think this would be valuable to the project. Given how many people are now using Discord or just the forums, and how long since we've had this running, im not sure if time would be better spent working on a Discord implementation of this idea?

**Comment by JeromSar** [comment]
@Wild1145 You're right. I think it's best to abolish the system. Instead, we should work on #1833 in the future.
