### ISSUE TITLE
/doom destroys blocks on explosion.

### ISSUE THREAD

**Issue by 50GHz** [TotalFreedom/TotalFreedomMod#1644]
I'm not quite sure if this is a feature or a bug. When using /doom it destroys blocks. The issue with this is it can cause unwanted grief.

**Comment by 50GHz** [comment]
I had some free time so I made a video explaining the bug. I have always developed a very simple fix. If this issue is accepted, I will be glad to share.

[YouTube video 1:08 seconds](https://youtu.be/_cQQrHhezLs)

**Comment by WilliePlaysMC** [comment]
This isn't a bug. It was intended. However it is still an Enhancement and I believe it shouldn't just explode. As I have ruined many builds on my server while messing around with TFM.

**Comment by rovertdude** [comment]
I think it should disable the explosion doing damage - it can cause griefing accidentally and irreparably  quite a bit.

**Comment by JeromSar** [comment]
@WilliePlaysMC How exactly was this intended behavior?

**Comment by WilliePlaysMC** [comment]
@jeromstar I am pretty sure this had been the case since TFM 4.3 or even earlier.

**Comment by AvalancheYT** [comment]
Actually, explosion won't occur if the explosion toggle is turned false, @WilliePlaysMC.

**Comment by Wild1145** [comment]
I think it was intended to create an explosion effect but not break any blocks...

**Comment by rovertdude** [comment]
@AvalancheYT My server had explosions toggled false however /doom still broke spawn when we /doom'd someone.
