### ISSUE TITLE
Command Suggestion: /requestop

### ISSUE THREAD

**Issue by samennis1** [TotalFreedom/TotalFreedomMod#1649]
/requestop

This command will notify that the player has become OP.

I am already using this command on my server, if any player joins and there is no staff on or a staff forgets to OP them and they go AFK, /requestop will op them! (alias, /reqop)

I dont know if you would find this useful, but I definetly would for my server :)

Thanks,
Sam

**Comment by CrafterSmith12** [comment]
Not really necessary. Ops can easily just ask for op in chat.

**Comment by ItzLevvie** [comment]
Doesn't seem to be that useful as it can run into issues.

**Comment by CrafterSmith12** [comment]
@ItzLevvie how so?

**Comment by DUFCLiam** [comment]
I would like it to message this to all admins online;

`[OP] {Players name} is requesting to be opped!`

**Comment by Wild1145** [comment]
I smell a PegasusMod /reqop command at hand here.

**Comment by RobinGall2910** [comment]
I see no use of this. Can be easily spammed, too.

**Comment by DUFCLiam** [comment]
@RobinGall2910, We can add a cooldown.

**Comment by marcocorriero** [comment]
Bad idea, if player will be smited and punished? It will do /requestop and continue.

**Comment by CreeperSeth** [comment]
All a player needs to do is simply say "Can I please be opped" and a player will op them. Simple.

**Comment by Wild1145** [comment]
This issue has been superseded by / is a duplicate of #340
