### ISSUE TITLE
Bug: Command Permissions

### ISSUE THREAD

**Issue by samennis1** [TotalFreedom/TotalFreedomMod#1650]
(Please read my other post also)

Hello,

I tried today to set " @CommandPermissions(level = Rank.SENIOR_ADMIN, source = SourceType.BOTH, blockHostConsole = true)" on my coding but when I tried to use it as the rank "Owner" ingame, It said I wasn't able to...

Is this a bug or am I just stupid?

Thanks,
Sam

**Comment by JeromSar** [comment]
@samennis1 Owner is not a rank, it is a title. Are you sure your rank is set to `SENIOR_ADMIN` in the config?

**Comment by samennis1** [comment]
I have exactly  "@CommandPermissions(level = Rank.SENIOR_ADMIN, source = SourceType.BOTH, blockHostConsole = true)" for the command permissions. My rank is set to owner in the config along with my editing the colour  in title. I haven't touched anything else in regards to Owner rank. I simply have what is stated above as my permission and it wont work ingame. I also tried to set it to TELNET_ADMIN and it didnt work either.

**Comment by JeromSar** [comment]
@samennis1 As I said, Owner is not a rank. It does not affect your permissions whatsoever. What does affect your permissions is your actual rank (non-op, op, super admin, telnet admin, senior admin). Please verify that you have been added to senior admin correctly.

**Comment by samennis1** [comment]
@JeromSar Oh I am sorry, I completly realise now. I appoligise.

This is not a bug.

**Comment by samennis1** [comment]
No longer an issue.
