### ISSUE TITLE
How do you use /myadmin setlogin?

### ISSUE THREAD

**Issue by Cleinad119** [TotalFreedom/TotalFreedomMod#1681]
I am having trouble with that command. Is it in the current release? I need it for my own TFM server.

**Comment by AvalancheYT** [comment]
The latest code is uploaded but not the compiled version. You would need to compile it.

**Comment by WolfieYTReal** [comment]
There is a version of totalfreedommod that does add this. Also the command is /myadmin setlogin (message) Here Is What It Would Look Like (YOURNAME) is (YOURTEXT)

**Comment by JeromSar** [comment]
@Cleinad119 Make sure you're running the latest version. :)
