### ISSUE TITLE
/saconfig setrank can set to a console rank

### ISSUE THREAD

**Issue by WolfieYTReal** [TotalFreedom/TotalFreedomMod#1721]
Hi There TotalFreedom! I Have Found A Bug Possibly.
A Person In The Console Can Set Their Rank To Console In Game.
/saconfig setrank (player) SENIOR_CONSOLE
This Might Not Be A Bug But It Still Might Be Serious

**Comment by rovertdude** [comment]
This also works with TELNET_CONSOLE - they cannot do any console commands ingame, and TELNET_CONSOLE has telnet admin perms, while SENIOR_CONSOLE has senior perms like normal.

**Comment by PacksGamingHD** [comment]
@rovertdude I'm guessing here but this might be because TFM checks to see if a player is executing the command and prevents them from doing it

**Comment by AvalancheYT** [comment]
There's player variant - https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/java/me/totalfreedom/totalfreedommod/rank/Rank.java#L101-L114
So basically, it will check if players is in-game or on console
