### ISSUE TITLE
adminmode -sra

### ISSUE THREAD

**Issue by jjjaguar2000** [TotalFreedom/TotalFreedomMod#1722]
Not a major one but could there be an arguement added to adminmode for sra only?

**Comment by TheCool1Mike** [comment]
Can't telnets/supers still watch the conversation through Telnet or Logviewer? 

Although, still an interesting idea.

**Comment by AvalancheYT** [comment]
What's the point of senior adminmode when we can view it on Telnet/Logviewer...

**Comment by JeromSar** [comment]
Thanks for your suggestion.

After some thinking, I don't think we need or want this feature in TFM. Thanks for your suggestion however.
