### ISSUE TITLE
Shows ban reason ingame when /glist ban is used

### ISSUE THREAD

**Issue by TheCool1Mike** [TotalFreedom/TotalFreedomMod#1726]
Pretty much what the title says:

It would look something like this.

If /glist ban thecool1mike is used, it will still look like this: TheCool1Mike - Banning TheCool1Mike and IPs: <IP>

If /glist ban TheCool1Mike is used, it will look like this: TheCool1Mike - Banning TheCool1Mike and IPs: <IP>. Reason: <reason>

I've began this project, and I'll handle this (if accepted).

**Comment by Wild1145** [comment]
This issue has been superseded by #1834
