### ISSUE TITLE
Discord Bot for Verification

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#1727]
I suggest that we build a discord bot to help handle verification.

Basically, admins assign their discord member id to their saconfig entry, and when the bot (which is hosted by the server) receives !verify from the handle, they are added to saconfig.

**Comment by Wild1145** [comment]
I like the sound of this... Come the summer holidays I'll properly investigate this. Would work as an alternative to TwitterBot.

**Comment by Hockeyfan360** [comment]
@Wild1145 Since the bot would be hosted on the server as TFM, we could also use it for your irc styled thing.

**Comment by JeromSar** [comment]
I like this idea, but for this system to be in place, I do have one requirement, the ranks on Discord server will need to automatically updated to reflect the TotalFreedom server. This prevents old and rogue admins from regaining access once their status is removed.

Alternatively, we could have the discord bot verify that the admin is in fact added (through the JSON API of TFM).

As a last thought, there will have to be some method to assign Discord users to TFM admins. TFM admins could probably use a command such as /myadmin discord set [name] to setup linkage.

What do you think, @Wild1145 ?

**Comment by Hockeyfan360** [comment]
@JeromSar This could be implemented through a separate plugin. Discord just added a developer feature which will allow you to get your member id easily. They just copy and paste that code with the discord command to register it to their name. If the admin is not enabled, it ignores all verification attempts. Ranks do not have to be synced for this to be implemented, although it is entirely possible. Since TFM does have a json api, it would just make it all the easier to do this through a separate plugin.

**Comment by Wild1145** [comment]
@JeromSar I like the idea of the bot being able to manage everything, its deciding if its practical or not. The easiest option as @Hockeyfan360 said would be to check if they are even set to superadmin = true in the superadmin.yml before proceeding. In the event that it is false it doesnt allow the verification and could post something in an administration chat on Discord so we can check to see if they should or should not be admin. I like both ideas, one to have it as part of TFM, and one to have it separate... Both have their pro's and cons... I think this just needs a bit more thinking through, and as I say, I'll have more time in the summer to look at it so thats always an option.

**Comment by Hockeyfan360** [comment]
@JeromSar I really do think that this will be easiest to implement through a separate plugin. It would also prevent confusion for new servers starting up.

**Comment by JeromSar** [comment]
@Hockeyfan360 I understand where you're coming from, but from a developer's standpoint, I believe this go in TFM. Much as the log viewer, this can be a separate module that is left disabled by default.

Keep in mind that more plugins means more maintaining. I want to keep the effort of maintaining TF at a minimum.

**Comment by Hockeyfan360** [comment]
@JeromSar I'd like to work on this issue, but when I compile TFM, it gives me errors in the code. I've got all the dependencies working, but should this be happening?

**Comment by OxLemonxO** [comment]
What's the errors?

**Comment by Hockeyfan360** [comment]
@OxLemonxO The version of TotalFreedomMod that I had working went haywire, and so I need to know which TF-WorldEdit version I use. Is it just the normal worldedit-core?

After that, it is issues with the code not finding certain methods, I can get to that later.

**Comment by Wild1145** [comment]
This issue has been superseded by #1833
