### ISSUE TITLE
How do I check for ranks?

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1731]
How would I do something like this:

`if (isAtleast(Rank.SUPER_ADMIN))
{
//CODE HERE!
}`

**Comment by Wild1145** [comment]
There is no such method that I know of in TFM...

**Comment by DUFCLiam** [comment]
@Wild1145, I mean how would I check they are above a certain rank? In an external plugin using TFM as a library.

**Comment by Wild1145** [comment]
@DUFCLiam You don't... You would need to build their own method.

**Comment by DUFCLiam** [comment]
@Wild1145 Would you be able make me a method please?

**Comment by LegendIsAwesomes** [comment]
@DUFCLiam, as @Wild1145 once said. Developers don't grow on trees, making this method is easy. I don't think @Wild1145 would want to waste his time doing that without some sort of reward for example, money.
