### ISSUE TITLE
/tempban

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1732]
I suggest the kick message for being /tempban'd to be something different.
Currently it disconnects you with this:

:[20:07:04 INFO]: Ouidjette lost connection: rovertdude - Temporarily banned Ouidjette until 2016-05-21 at 20:07:05 CEST, Reason: "relog nerd (rovertdude)"

I suggest it should say something similar to
"You have been temporarily banned until (time), Reason: "(insert reason here)""
so it would say

"You have been temporarily banned until 2016-5-21 at 20:07:05 CEST
Reason: "relog nerd (rovertdude)"

**Comment by JeromSar** [comment]
No I don't think we need to change that.
