### ISSUE TITLE
Ranks 

### ISSUE THREAD

**Issue by Cleinad119** [TotalFreedom/TotalFreedomMod#1733]
What are ALL of the Ranks available in TFM?

And if you can't use /saconfig setrank to get the rank, please include how to get it.

**Comment by DUFCLiam** [comment]
Super Admin: `/saconfig setrank SUPER_ADMIN`
Telnet Admin: `/saconfig setrank TELNET_ADMIN`
Senior Admin: `/saconfig setrank SENIOR_ADMIN`
Console: `/saconfig setrank CONSOLE`
Owner: https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/resources/config.yml#L21

**Comment by rovertdude** [comment]
Console: /saconfig setrank CONSOLE
naw
/saconfig setrank SENIOR_CONSOLE
or
/saconfig setrank TELNET_CONSOLE

**Comment by AvalancheYT** [comment]
/saconfig set rank <rank>_CONSOLE won't think they are the console instead they would be a player.
