### ISSUE TITLE
Block /saconfig setrank from Rcon

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1735]
I suggest we block /saconfig setrank from Rcon or blockHostConsole.

**Comment by AvalancheYT** [comment]
And how are we suppose to set someone's rank? We can't do it from Telnet.

**Comment by rovertdude** [comment]
@AvalancheYT 
Seniors.
Or this could be temporary.

**Comment by DUFCLiam** [comment]
This was due to Rcon being hacked and using /execute to force it.

**Comment by Wild1145** [comment]
Its already blocked from RCON...

**Comment by JeromSar** [comment]
@Wild1145 is right.
