### ISSUE TITLE
Console Spammer Logger Ignorer

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1749]
Example we can add The error on logviewer

Like

TFM Config

IgnoreErrors:

PutYourErrorHere

And if the error appears on Logviewer/console, will be ignored and dont written in logviewer 

we can use this idea temporarily due to This Mod named LogSpammer.

**Comment by JeromSar** [comment]
Well, this bypasses the entire goal of logging errors. Sorry, this is not happening.
