### ISSUE TITLE
Adminchat implement

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1751]
Lets add adminchat can support colors, oblivious let's add filters, and seniors can change default adminchat with `/myadmin` `adminchat` `[<colorcode>]` `bold[<true/false>]`

**Comment by trustthepie** [comment]
So because this hasn't been commented on in forever, I'll comment. I know we have it on marco freedom, but there isn't much point to this other to get noticed more in adminchat?

**Comment by robingall2910** [comment]
It should be configurable in the config file instead of doing it by command. Don't want it to like change every 5 seconds either because some senior wants it that way. Don't add bold. please don't

**Comment by Wild1145** [comment]
I think this will simply cause spam and will make reading admin chat exceptionally difficult.

**Comment by JeromSar** [comment]
I agree with @Wild1145 I like admin chat as-is.
