### ISSUE TITLE
Update to Spigot 1.10

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#1756]
Spigot 1.10 has just been released, and it's about time to update TFM and Aero to the Spigot 1.10. I will be glad to create a pull request for both of these plugins to be updated.

**Comment by PacksGamingHD** [comment]
Or we could simply update ViaVersion to 0.9.2 and TFM and Aero to 1.9.4 and we have a 1.9.x and 1.10 server

worked for me

**Comment by Wild1145** [comment]
ViaVersion is a hacky nasty thing anyway that goes against the rules of versioning... 

TFM will have a 1.10 update when @JeromSar is ready to push out the updates, its not a quick fix.

**Comment by Wild1145** [comment]
The server has already been updated in the last update to 1.10
