### ISSUE TITLE
Plug.DJ Bot Integration?

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#1759]
Plug.dj has a front end api that you can access by injecting javascript code. If you want to demo it, use your browser console (in inspect element) on plug.dj and do something like API.sendChat('test');

For example, we could have it send announcements saying that THIS song is being played, TF admins are djing right now, etc. I think this would be a lot of fun, although un-necessary.

...

Of course though, we'd need to wait until they confirmed that they'd be funded.

**Comment by JeromSar** [comment]
@Hockeyfan360 According to the Contributing Guidelines, changes should be aimed at the official TotalFreedom server. Does TotalFreedom have an official plug.dj? @Hockeyfan360

**Comment by Hockeyfan360** [comment]
There's nothing official or with mark's blessings atm, no.

**Comment by JeromSar** [comment]
@Hockeyfan360 Then unless that becomes the case, I don't think we should have official TFM integration wich plug.dj. Thanks for your suggestion however. :)
