### ISSUE TITLE
CommandSpy

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1761]
I suggest that we add something such as a /cmdspy on only specified players - like ingame I can try /cmdspy rovertdude and it will only show up with my commands.
I think it can also help if it also can see admin commands if it is specified to a player that is an admin.

**Comment by DUFCLiam** [comment]
They can make it like this

`commandspy` - Global spy
commandspy add playername` - Adds a player to the list.
`commandspy remove playername` - Remmoves a player from the list.

**Comment by JeromSar** [comment]
Why would this be beneficial? @rovertdude

**Comment by rovertdude** [comment]
This can help admins watch potential trolls - and with Liam's addition, it could add admins to commandspy or remove commandspy on a trusted person. @JeromSar

**Comment by DUFCLiam** [comment]
@JeromSar We could maybe make it like this and it would be beneficial

`/commandspy add <playername> <chatcolor>` it would then display like this

&<color>NAME: <command>

**Comment by mr-lukas** [comment]
Perhaps we could make it so administration could toggle it on and off for trusted OPs so rulebreaker reporting on the forums and in game would be easier?

**Comment by Wild1145** [comment]
Superseded by #1840
