### ISSUE TITLE
Highlighting words in chat/commands that may be counted important

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1762]
If someone was to say `terrorism`, `suicide`, etc we could then highlight that so an admin can then watch that player.

**Comment by Wild1145** [comment]
Or you just tell the player to stop being a dick, and take appropriate action? This would do nothing but cause hell for admins trying to administrate and having random words in different colours...

**Comment by Wild1145** [comment]
Superseded by #1830
