### ISSUE TITLE
/opme for non-ops

### ISSUE THREAD

**Issue by SkateSack** [TotalFreedom/TotalFreedomMod#1764]
I believe that people that are not opped should be able to op themselves.

It'll be useful in these 2 situations.

A: Admins are AFK.

B: Players are not opping you.

I believe that because anyone with OP can OP another player, then so should non-ops.
There could be a command that would block this from another player or make /deop lock them out until someone /ops them again.

**Comment by DUFCLiam** [comment]
Duplicate to #508 (I think)

**Comment by CreeperSeth** [comment]
If admins deop ops then the op could just do /opme and op themselves again.

**Comment by AssassinDude** [comment]
then implant special perms that if a admin de-ops u then if the deoped player tries to op himself it will say "You have been De-Oped by an Administrator"

**Comment by ShadowArmadyl** [comment]
What @AssassinDude in more simple words:
Add a cooldown timer to the command when (or if) a player was smited.

**Comment by MasterVelyk** [comment]
They have a block commands command.

**Comment by JeromSar** [comment]
No, de-opping a player is actually an administrative measure. OPs shouldn't (in all cases) be able to op themselves. A better system is underway.
