### ISSUE TITLE
Admin.java Not Complete

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#1769]
Take a look at AdminEntry.java, for example. It calls target.setName(), target.getRank(), and others, yet these methods are not implemented in Admin.java.

**Comment by JeromSar** [comment]
@Hockeyfan360 I don't understand. What exactly do you mean? Is this a bug, feature request?

**Comment by Hockeyfan360** [comment]
Methods like getRank() in AdminEntry cannot be found in the class Admin. Admin.java is missing methods, I believe. @JeromSar

**Comment by JeromSar** [comment]
There's no AdminEntry class in TFM, @Hockeyfan360. Could you be more specific on what the problem actually is?

**Comment by Hockeyfan360** [comment]
@JeromSar AdminList.java, not AdminEntry, my apologies.

**Comment by JeromSar** [comment]
@Hockeyfan360 I now understand wherein the confusion lies. The getters and setters for the fields in Admin.java are automatically generated by the [Lombok](https://projectlombok.org/) library before compilation.
