### ISSUE TITLE
TotalFreedomMod: v5.0 running Spigot 1.10

### ISSUE THREAD

**Issue by Superior-tL** [TotalFreedom/TotalFreedomMod#1770]
I really suggest to add Spigot 1.10 so players can use the new items in the new update it runs smoothly on my server.

**Comment by Cleinad119** [comment]
First, it is mandatory that we figure out how to deal with the structure block issue. I have seen some admins saying just to block them, but eh.
Until then, we should probably not update the server.

**Comment by RobinGall2910** [comment]
@JeromSar seems like you can close this since you've done the commit yourself lol
