### ISSUE TITLE
blocking a specific command in TFMOD config

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1771]
like
`  - 'n:b:s_b:/summon witherboss:_'`

We can add

s_b as specific command, like this, ex 

I want to block (/summon witherboss);

And s_b it logs as specific command, not a Generic command.

**Comment by AvalancheYT** [comment]
It always been in TFM, check for yourself.

**Comment by marcocorriero** [comment]
Avalanche, is not in TFM, is blocking generic commands, not specific commands...

**Comment by AvalancheYT** [comment]
@marcocorriero, check for yourself, https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/resources/config.yml#L91

**Comment by marcocorriero** [comment]
Yeah, but if you add more like /summon lightningbot it will make a conflict and will dont block it

**Comment by Wild1145** [comment]
Yeah, sub-command blocking is not something we have, I know it was on a to-do list, but I think it was of a lower priority...

**Comment by JeromSar** [comment]
Sub-command blocking was one of the original features, but it was removed by Madgeek some time ago. I readded it in a recent update because it was needed. You do not need a special "type", you simply specify the full command. :)
