### ISSUE TITLE
cant build TFM5.0-1.10

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#1778]
Hello please help, i cant build TotalFreedom 
(Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project totalfreedom: Cannot get the branch information from the scm repository :
Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "git" (in directory "/home/dominik/NetBeansProjects/TotalFreedomMod-tfm5.0-mc1.10"): error=2, Folder or file doesnt exists
-> [Help 1])

Please how can i fix it?

**Comment by WarrioR151** [comment]
I Found solution, it works now :3

**Comment by cuijk** [comment]
how do you fix it? i got this issue now , thx

**Comment by JeromSar** [comment]
@cuijk Make sure you have Git SCM installed.
