### ISSUE TITLE
World edit may need to be updated

### ISSUE THREAD

**Issue by adamvandyck** [TotalFreedom/TotalFreedomMod#1780]
In the logs I get this message:
[13:58:50] [Server thread/WARN]: [WorldEdit]
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************

Like the message says, when copying and pasting things like chests and signs they go blank which needs to be fixed.

**Comment by ShadowArmadyl** [comment]
This belongs in the TF-WorldEdit issues:
https://github.com/TotalFreedom/TF-WorldEdit/issues
