### ISSUE TITLE
Clearchat Command

### ISSUE THREAD

**Issue by jjkatz** [TotalFreedom/TotalFreedomMod#1788]
So you know those times we have a problem with spam. So maybe we can add this command that clears text in chat. Heres code: http://pastebin.com/2mqgH2Sv

**Comment by robingall2910** [comment]
no

**Comment by AvalancheYT** [comment]
This feature have always been suggested and been denied.

**Comment by CreeperSeth** [comment]
I see loads of sins in your code let me help you out by correcting them so in the future in case you want to attempt to contribute to total freedom you won't be automatically denied on first look.
`FUtil.bcastMsg(ChatColor.DARK_RED + "Chat cleared! " + ChatColor.GOLD + "~" + ChatColor.GREEN + sender.getName());` Completely unneeded just use `FUtil.adminAction(sender.getName(), "Cleared the chat");` `Player player = sender_p;` What is this for? That is completely useless you never even used it. ```if (senderIsConsole)
{
            msg("You must be in-game to use this command.");
}``` 
Why would you need to block anyone in the console? This will be denied but please take this knowledge for any future things you might need it for

**Comment by JeromSar** [comment]
Nope, I think the chat is fine as-is.
