### ISSUE TITLE
Banning after caging

### ISSUE THREAD

**Issue by jjkatz** [TotalFreedom/TotalFreedomMod#1789]
Today, I caged someone and then I banned them a minute after and they left the server but the cage was still there and I was forced to manually get rid of the glass and fix the now griefed area.

**Comment by JeromSar** [comment]
It's very possible that this is because there was a reload or a server restart in between. Such events reset the changed-blocks.

**Comment by Wild1145** [comment]
I can confirm this does happen. Im not sure exactly *why* it happens, but it does happen quite often.

**Comment by Wild1145** [comment]
I have identified the issue, cages are only removed if the player LEAVES the server (quits), not kicked. I'll account for this.
