### ISSUE TITLE
Add /uall and /dtoggle

### ISSUE THREAD

**Issue by CreeperSeth** [TotalFreedom/TotalFreedomMod#1793]
Mark recently added Libsdisguises to the server and we need /uall and /dtoggle I am re-adding those commands now

**Comment by supergameplayer** [comment]
Vouch. I would use wildcard to do it, but that's a bit spammy.

**Comment by robingall2910** [comment]
sure, we could always bring back the actual command from the dead and fix it @CreeperSeth

**Comment by marcocorriero** [comment]
Tested, ./dtoggle having a bug as toggling it.

Not good @JeromSar

**Comment by marcocorriero** [comment]
@JeromSar , /uall works fine,  but ./dtoggle seems LibsDisguises Dont accepts any form of disabling/enabling again.

basically it makes a bugged disguises until the server will be reloaded with /rl

**Comment by CreeperSeth** [comment]
I can remove /dtoggle, I can't fix the buggy results of it because that is something to do with LibsDisguises

**Comment by OxLemonxO** [comment]
i'm adding /dtoggle in LibsDisguises

**Comment by JeromSar** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/commit/cadf4e4fc7d51da72f1dd3424d61ef31d1a4ff08
