### ISSUE TITLE
World Saving Command

### ISSUE THREAD

**Issue by jjkatz** [TotalFreedom/TotalFreedomMod#1795]
Sometimes I have done a big project in adminworld and I don't want to lose it. In the past, the server has crashed before it has had time to save. Can we make a command to save the world.

**Comment by robingall2910** [comment]
Or, don't make one, just unblock it.

**Comment by Wild1145** [comment]
Yeah, I dont know why it got changed to a complete block, it used to be admin only...

**Comment by JeromSar** [comment]
@Wild1145 What do you mean?

**Comment by Wild1145** [comment]
@JeromSar Yeah, it used to be admin only, then it got totally blocked... It was handy for saving adminworld after working on a project...
