### ISSUE TITLE
Contact admins

### ISSUE THREAD

**Issue by notanoperator** [TotalFreedom/TotalFreedomMod#1804]
Could we possibly have a thing where whenever you put @ before a message, it contacts all administrators on? /report always isn't reliable, and when someone griefs, but you don't know who it is, you can't use /report. I suggest this be added. It is on various csgo servers and garry's mod servers, and I feel it could work here aswell

**Comment by notanoperator** [comment]
See forum post http://totalfreedom.boards.net/thread/43328/contact-administrators

**Comment by robingall2910** [comment]
most likely gonna get rejected because /report exists for a reason.

**Comment by notanoperator** [comment]
The point is that you can't always /report.
Let's say I was griefed, BUT I don't know who did it. I can't just report some random player to get admins attention.

Read more: http://totalfreedom.boards.net/thread/43328/contact-administrators#ixzz4GEcwilQH

**Comment by robingall2910** [comment]
You are basically making another command if so, though. That's why 
people are saying no.

**Comment by Wild1145** [comment]
Maybe report needs to be updated to account for this then?

**Comment by notanoperator** [comment]
in reply to wild
That would be good

**Comment by Scribbles4321** [comment]
What about things that don't need reporting? Like maybe an OP wanted to tell an admin to protect their spawn or similar to that?

**Comment by Wild1145** [comment]
@Scribbles4321 Then tough titties... Its a free build server, use worldedit to save shite.

**Comment by Wild1145** [comment]
This issue has been superseded by #341 and #1832
