### ISSUE TITLE
Update in TFM

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1813]
This TFM update will contain those function

Coded 

- Marco
- Mafrans
- OxlemonxO

- added /adminhelp
- Added Color supporting/filters for adminchat
- implemented smite to say the sender to player smited.
- implemented Whohas to support Clear, it clears the specified item from the player inventory.
- implemented gmsp, you can put other players in GMSP If required eg Helpers, Trusted players etc.
- Tban alias /noob supports and shows reason
- Glist says the reason in public and ip is showed as client-side
- Fixed /dtoggle thanks to oxlemonxo
- updated tag filtering
- colorized SENIOR_CONSOLE as Pink as asked by mashedPotato.
- Colorized Telnet_Console as Dark_green
- added Block to written_book
- lifted Block for Structure_block (not structure_void, those blocks can help building)
- added a FUTIL Filtering for banned colors.

@JeromSar

**Comment by marcocorriero** [comment]
#1815

**Comment by JeromSar** [comment]
Please make individual issues for each suggested feature. Be sure to read the (https://github.com/TotalFreedom/TotalFreedomMod/wiki/Contributing)[Contributing Guidelines]. Most of the issues suggested here do not fit into TotalFreedomMod's goals.
