### ISSUE TITLE
Update WorldEdit to 1.10

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#1818]
TF-WorldEdit needs to be updated as the current version cannot properly `//copy` item metadata.

**Comment by marcocorriero** [comment]
wrong Section, post it on TF-worldedit repo

@JeromSar locking?

**Comment by ShadowArmadyl** [comment]
@marcocorriero I believe issues in the TF-WorldEdit repo aren't maintained.

**Comment by JeromSar** [comment]
This is an issue for the TF-WorldEdit repo.
