### ISSUE TITLE
gmsp implement

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1837]
let's make a feature

gmsp can like any other gamemodes
but only admins can set it to other players.

Like when a trusted op will ask gmsp to see what is the problem the admin can do easily /gmsp op

or teleporting the op into adminworld? 

the admin can do easily /gmsp op  and /blockcmd op to avoid cmd grief.

**Comment by Wild1145** [comment]
See #856
