### ISSUE TITLE
Using /myadmin clearips on another admin gives them the sender's IP

### ISSUE THREAD

**Issue by Obi2** [TotalFreedom/TotalFreedomMod#1841]
An admin had two supered IPs - using /myadmin -o clearips on the admin for some reason gave them my (the sender's) IP.

I don't think targetIp ([line 34](https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/java/me/totalfreedom/totalfreedommod/command/Command_myadmin.java)) is updated if the target is changed to another player.

**Comment by AvalancheYT** [comment]
If you read bit further, it actually does change. [Line 41](https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/java/me/totalfreedom/totalfreedommod/command/Command_myadmin.java#L41)

**Comment by JeromSar** [comment]
You're right. It's on the TODO list. :)

**Comment by AvalancheYT** [comment]
Oh, I was mistaken.
