### ISSUE TITLE
Complex CommandSpy suggestion

### ISSUE THREAD

**Issue by uyscutix** [TotalFreedom/TotalFreedomMod#1843]
This is a similar to wild's suggestion on commandspy. This is the suggestion:

When CommandSpy automatically detects a world edit command (or a command beginning with //), it would also show by the side in another colour how many blocks a player attempted to use.

Example of how it would be shown:
[WorldEdit] [284624 blocks] Griefer12345: //set dirt

This is useful, instead of having to open up the logviewer every time or so, you can see how large a world edit attempt has been by another player with the in-game command spy.

To reduce the flood/spam, if it was an obvious grief/crash attempt like "[8565748375843 blocks]" the maximum it would go is 1m and displayed like this:

[WorldEdit] [1,000,000+ blocks] Griefer12345: //hsphere bedrock 10000000000

**Comment by AvalancheYT** [comment]
Shouldn't this issue be suggested in issue #1830 as it's similar?

**Comment by JeromSar** [comment]
@AvalancheYT is right.
