### ISSUE TITLE
Masterbuilder rank features

### ISSUE THREAD

**Issue by marcocorriero** [TotalFreedom/TotalFreedomMod#1844]
Instead of allowing masterbuilder to editing adminworld , why not making a world named "masterbuilder's paradise" and admins can add like adminworld guests in this world , instead of coding ranks? Rank uneeded.

Facts:

1) masterbuilder ranks can be easily bugged, they can override the verification system, if we add the saconfig setrank master_builder
And a imp will join with a masterbuilder account

Fact we fucks admin,yml entries.

2) why not adding titles? Like a new ranking system, telnets and higher can do easily /saconfig addtitle &lt;player&gt; masterbuilder , after done this in server will appear &lt;sender&gt; - giving masterbuilder 's perms to &lt;player&gt; and player can do /mastworld to explore it, ops too, but if is a op without title and perms unlocked, they will forced to go in gamemode spectator, a d they can just chat, and they can't break blocks/edit or doing commands , just /flatlands, /spawn and /op &lt;player&gt;

After doing this and the op left, the perms on his leaving, will be automatically revoked.

For this feature, devs can do a new file named title.yml
It refuses trusted ips, they need to verify  like normal admins everytime they want to join in masterbuilder world.

If the masterbuilder is an admin, they can be added without doing addtitle , admins have already all perms, the admin can do /myadmin setlogin a masterbuilder and etc....

**Comment by AvalancheYT** [comment]
Shouldn't this issue be suggested in issue #1798 as it's similar?

**Comment by JeromSar** [comment]
@AvalancheYT is right. This issue is a duplicate.

**Comment by AvalancheYT** [comment]
@JeromSar, close?
