### ISSUE TITLE
/dtoggle still needs fixing

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedom/TotalFreedomMod#1846]
/dtoggle says Enabled enabled or Enabled disabled and does not turn on or off Libs Disguises... lol

Note: the pr/1800 branch works fine, but the one on the server does not

**Comment by lemonsked** [comment]
it's not supposed to disable the plugin.
it's supposed to not allow anyone to disguise, and undisguise everyone, till it's re-enabled, since LibsDisguises does not like being reloaded.
The first part is a bug though.

**Comment by lemonsked** [comment]
Well apparently the  commit is gone now..

**Comment by JeromSar** [comment]
@Wild1145 Is this bug current? This issue was closed with https://github.com/TotalFreedom/TotalFreedomMod/commit/2008871658e1bd127dbdd8adbbdb8bd7cc3274d0

**Comment by Wild1145** [comment]
@JeromSar Im not 100% sure, I re-opened it due to a recent PR that had been made, so I was under the impression that the bug still existed, but I'd need someone to confirm it.

**Comment by JeromSar** [comment]
@PacksGamingHD Could you verify that the bug has been fixed?

**Comment by Telesphoreo** [comment]
line 37 is the issue it says enabled enabled or enabled disabled

**Comment by Wild1145** [comment]
Superseded by #1872
