### ISSUE TITLE
/gtfo -s 

### ISSUE THREAD

**Issue by EthanYT** [TotalFreedom/TotalFreedomMod#1851]
(Admin on TF)
aka Officincy
This is a wanted command
If you add -s to the end of a command, it makes the ban silent
So only admins see the ban (add (SILENT) to the bc for admins)

**Comment by OutOfYourMind** [comment]
I believe that it isn't necessary.

**Comment by Wild1145** [comment]
I dont see any value to it other than causing drama when non-ops call out why a player was disconned, banned and it was hidden. This just sounds like a recipe for disaster.

**Comment by ghost** [comment]
The only reason you would want to do this is to hide ip's and even then, this can be done a different way.
Object.

**Comment by JeromSar** [comment]
Thanks for contributing!
I don't see a good use for this, sorry.
