### ISSUE TITLE
Remove LogViewer access once an admin is removed from the admin.yml or in-game

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#1852]
I believe there should be a feature within TFM that prohibits LogViewer access due to being removed from the admin list. What if a rogue could see someones IP and wanted to DDoS them or see stuff they aren't supposed to in the adminchat?

**Comment by EthanYT** [comment]
I would like this.

**Comment by script-head** [comment]
I believe we should have a complete re-write of the log viewer, @JeromSar can do the scripting, and @aggelosQQ can take care of the design. We can then host the new log viewer on the VPS that holds totalfreedom.me

**Comment by 44444444444444444444444444444444444444** [comment]
I would like this I am FuryWasHere

**Comment by aggelosQQ** [comment]
I'm all up for this.

**Comment by DUFCLiam** [comment]
I agree because Ex. Admins are getting access and @StevenLawson isn't the most active admin.

**Comment by LegendIsAwesomes** [comment]
@StevenLawson isn't active, though he visits sometimes, mark will not remove him as he is the co founder basically, and the original TFM creator.
@DUFCLiam

**Comment by DUFCLiam** [comment]
@LegendIsAwesomes I did not say to remove him.

**Comment by Wild1145** [comment]
Due to the nature of the issue I have pushed this as a High Priority Issue.

**Comment by JeromSar** [comment]
From http://totalfreedom.boards.net/conversation/47910?page=1&scrollTo=151406

`
Change line 39 of httpd's Module_players.java from:
```java
for (Admin admin : plugin.al.getAllAdmins().values())
```

to:
```java
for (Admin admin : plugin.al.getActiveAdmins())
```

Read more: http://totalfreedom.boards.net/conversation/47910?page=1#ixzz4iRdz9Ns9 (closed convo).
