### ISSUE TITLE
Don't show full IP when using /glist ban or /glist unban

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#1853]
For protection of players, I think we should change /glist ban and /glist unban so it doesn't show their full IP, instead block it parts of it off with asterisks or just make it say "(Un)banning (player)" with no IP displayed.

**Comment by Wild1145** [comment]
IP's are public information and serve no purpose to be disguised.

**Comment by ghost** [comment]
However, it is still a good security measure.

**Comment by foxcqrn** [comment]
I heard one of my friends got ddosed a while ago because they got unbanned with glist

**Comment by ghost** [comment]
More reason to accept #1822

**Comment by Wild1145** [comment]
As an IP is public information and serves absolutely no security improvement to players I am closing this issue as it adds nothing of value to the server.

**Comment by JeromSar** [comment]
@Wild1145 This is not an invalid issue though. :P
