### ISSUE TITLE
/rd issue

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#1859]
/rd is not clearing item drops... or any other entities for that matter.

No errors show up in the logs.

**Comment by JeromSar** [comment]
The EntityWiper now dynamically wipes entities in chunks that contain too many entities. This is (in my opinion) a better solution than wiping everything. However, /rd should indeed wipe all entities regardless https://github.com/TotalFreedom/TotalFreedomMod/commit/c10b08df272c488ceda77479acf0465142fd7a6f fixes this.
