### ISSUE TITLE
Wildcard ? is broken

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1861]
? it doesn't select all online players, but one..

Look

:wildcard ping ?
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell
:Running Command: ping KillerFromHell
:[07:10:42 INFO]: marcocorriero11 issued server command: /ping KillerFromHell
:KillerFromHell

**Comment by Wild1145** [comment]
Interesting. How many players were online at the time?

**Comment by notanoperator** [comment]
its "/wildcard gcmd ? ping message" - what you did was invalid this can be closed @Wild1145

**Comment by Telesphoreo** [comment]
@notanoperator no. What he is saying is that when doing ? it only selects one player to send the message back to marco. This has nothing to do with ping. I think there are some issues with the revamped wildcard command

**Comment by ghost** [comment]
@Wild1145 it was 20 ppls on , something is wrong with wildcard , because ? Selects one , instead of all players online.

**Comment by mayokek** [comment]
It seems to be working fine for me.

**Comment by ghost** [comment]
@AvalancheYT try to run the wildcard cmd with ? when multiple players are on.

**Comment by mayokek** [comment]
I did it. It's working fine.

**Comment by mayokek** [comment]
Maybe TotalFreedomMod needs to be reloaded?

**Comment by lemonsked** [comment]
@AvalancheYT The version of TFM on TF was downgraded.

**Comment by rovertdude** [comment]
the bug appears patched so far

**Comment by ghost** [comment]
@rovertdude , mark downgraded tf
