### ISSUE TITLE
Auto Smite if no online admins

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#1867]
meant to be w/ #1866 but cant edit on mobile apparently
Perhaps a system could be added to automatically smite a user if no admins are on and someone does the following:
Kill someone in gmc or god
Nick another user
Clear someone elses inventory
and other events that happen when no admins are on.
Example:
happyfyfig7hf6 killed yryjgtigey in creative mode, it would auto smite them for:
[TotalFreedomMod] Creative pvp is not allowed. [Automatic Smite]
or something similar.

**Comment by Wild1145** [comment]
Merged into #1866
