### ISSUE TITLE
/saconfig add 

### ISSUE THREAD

**Issue by peter00f** [TotalFreedom/TotalFreedomMod#1868]
HELP I can't use /saconfig add in the game i am Senior_CONSOLE
and i am owner rank but i am using /saconfig add someone
it saying you only can use it on the console.
please someone know how to fix it??

**Comment by Wild1145** [comment]
Can you explain exactly what it is you're trying to do? I understand you're trying to add someone to admin, are you saying that your rank is Senior_CONSOLE?

**Comment by lemonsked** [comment]
you have to use saconfig add from telnet/console, you cant do it in-game.

**Comment by peter00f** [comment]
Yes my rank is Senior_CONSOLE and also Owner

**Comment by peter00f** [comment]
you mean i have to be a telnet_console to use saconfig add??

**Comment by samlau123** [comment]
# m

**Comment by ghost** [comment]
No, what they are saying it has to be done via Telnet Client or Console.

**Comment by peter00f** [comment]
How I install telnet client?

**Comment by foxcqrn** [comment]
Download BukkitTelnet and then run it on your server

**Comment by peter00f** [comment]
Thanks BTW  install a custom TFM so I can use /saconfig add now

**Comment by ghost** [comment]
> samlau123 commented 7 hours ago
> Thanks BTW install a custom TFM so I can use /saconfig add now

Why don't you do it yourself.

**Comment by foxcqrn** [comment]
Fenix I think he left out the "I" in that on accident.
