### ISSUE TITLE
Suggestion: Different color for // commands in CommandSpy

### ISSUE THREAD

**Issue by Alco-RS11** [TotalFreedom/TotalFreedomMod#1869]
I have a suggestion to make WorldEdit commands in /cmdspy a different color rather than &7. A easy-to-see color is &c, which I use on my server, and it is very effective in finding server crashers. This could make it easier to find players who use brush commands or other untraceable methods to grief, or easily find server crashers who use commands such as //sphere 5 10000 or //replacenear 100000 2,3 5.

~Alco_Rs11

**Comment by peter00f** [comment]
great

**Comment by foxcqrn** [comment]
Or you could just block brush. Simple. Plus, I think //brush is already blocked.

**Comment by notanoperator** [comment]
This is already in an issue, it was actually accepted
#1830 
This can be closed as duplicate

**Comment by Wild1145** [comment]
This issue has been superseded by #1830
