### ISSUE TITLE
Command_disguisetoggle.java

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1872]
Line 37 of the file located at: TotalFreedomMod/src/main/java/me/totalfreedom/totalfreedommod/command/Command_disguisetoggle.java from the branch tfm5.1-mc1.10 reads this:

`msg("Enabled " + (DisallowedDisguises.disabled ? "enabled." : "disabled."));`

This results in an error.
When the plugin is disabled/enabled it displays the opposite message of it's state,  that is, when the plugin is enabled it says it messages you that it is disabled, and vice versa. Also, when you are messaged it does not message you "Disguises enabled" as it should, instead it messages you "Enabled enabled" and "Enabled disabled", which in my opinion doesn't make much sense. 

To fix these errors simply changed line 37 to read this:

`msg("Disguises " + (DisallowedDisguises.disabled ? "disabled." : "enabled."));`

or

`msg("Disguises " + (!DisallowedDisguises.disabled ? "enabled." : "disabled."));`

Thanks for reading!

**Comment by lemonsked** [comment]
Or just use !DisallowedDisguises.disabled
