### ISSUE TITLE
Remove /deafen?

### ISSUE THREAD

**Issue by HugMyPug** [TotalFreedom/TotalFreedomMod#1875]
I see deafen as a trollish command with no usage -- Requesting to be removed. It's just a short term of "Ear rape" honestly.

**Comment by foxcqrn** [comment]
It is a fun command. (I personally use it for trying to get an afk person's attention.)

**Comment by lemonsked** [comment]
There's a reason it's for seniors only- so that it won't be abused.

**Comment by HugMyPug** [comment]
Yes, I  know that @OxLemonxO but, I still do not see any reason for the command itself.

**Comment by JeromSar** [comment]
In TFM there are quite some commands that serve no or only very little purpose. These commands were added in just for fun. As long as they're not abused, I see no reason to remove them.
