### ISSUE TITLE
Major bug: Can't use admin commands when brother is on.......

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#1880]
As the title fucking says...... FIX IT.

**Comment by AvalancheYT** [comment]
You can't just say that, you need more information.

**Comment by DUFCLiam** [comment]
This is a duplicate #1783

**Comment by DUFCLiam** [comment]
I had to be removed so my brother didn't have permissions he is now under family policy but I would like him removed.
