### ISSUE TITLE
Add command /ghost for invisibility

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1881]
It does give you invisibility when you type it in, and /ghost clean to clean the invisibility from admins, that command can be done from console, and when you type in /invis it shows that OPs: invisibleop1 invisibleop2 Admins: invisibleadmin1

**Comment by JeromSar** [comment]
Duplicate of/alternate to https://github.com/TotalFreedom/TotalFreedomMod/issues/266
