### ISSUE TITLE
Add /cleanup

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1882]
It does:
- Purge mobs
- Purgeall
- Remove drops
- Opall
- Nickclean
- Remove blocks like: piston, redstone, redstone torch etc, what can make lag machines

like: <admin> - Started server-cleaning process.
When ends: an msg to the sender: Done!
That would be a console only command with a 300 sec cooldown.

**Comment by aggelosQQ** [comment]
Well, /purgeall does the first and the third of that list, /opall on a cleaning up command doesn't sound right.
The 6th statement could easily grief.

**Comment by JeromSar** [comment]
I agree with @aggelosQQ, this command would be redundant.
