### ISSUE TITLE
Tweak To JSON API

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#1884]
Right now, the players json api (http://play.totalfreedom.me:28966/players) gives us the arrays "developers", "players", "telnetadmins", "superadmins", and "senioradmins". This is definitely helpful if you want to make an application that hooks into TFM, but you lack the ability to get a list of online admins.

For example, the TF website just looks for the list of admins; in this case, that's perfectly fine. However, if I want to create command permissions in an external plugin, I'd need to know what players are online, and which are admins. I can check to see if players online are listed as admins, but I can't tell if any of them are imposters.

I suggest that you add the array "onlineadmins" so that external programs can tell what players online are true admins. It shouldn't take but a few minutes to implement.

**Comment by DUFCLiam** [comment]
I agree as this would help be able to create a browser extention for Telnet+ and it sends a notification when an online admin is an imp.

**Comment by Hockeyfan360** [comment]
Also, we should allow requests with proper OAuth tokens to access material like admin ips. I'd be more than happy to write a library for using this API, if you'd like. This would take a bit longer to implement, but it might be worth it.

**Comment by JeromSar** [comment]
@Hockeyfan360 Can't you simply compute the intersection of the list "players" and "superadmins" to get this list?

**Comment by Hockeyfan360** [comment]
@JeromSar No, because there's no way to tell if someone listed in "players" is an imposter. This would allow anyone that poses as an admin to gain admin perms in external plugins that use the TFM api.

**Comment by JeromSar** [comment]
@Hockeyfan360 You're right. I like this idea. :)
