### ISSUE TITLE
Rawsay

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1885]
Why dont make rawsay for telnets instead of seniors? 
is being discussed here
http://totalfreedom.boards.net/thread/46152/rawsay

**Comment by ghost** [comment]
What would be the point of giving rawsay to telnets?
It is a purely 'fun' command and serves no purpose in performing admin duties on the server.
It has no real application for Telnet Admin's anyway, so I say once again, whats the point?

**Comment by ghost** [comment]
@Commodore64x is because we can use it instead of wildcard?

**Comment by ghost** [comment]
??? rawsay prints a message in chat without any formatting, and wildcard executes a command as every player on the server, how can you use in place of wildcard and if so, why is it better?

**Comment by ghost** [comment]
@Commodore64x is because wildcard gcmd ? Ping is same thing

**Comment by Wild1145** [comment]
I think we need to block being able to gcmd ping someone...

**Comment by ghost** [comment]
@Wild1145 and block the only way admins can express their only fun way? I will object

**Comment by Wild1145** [comment]
@marcocorriero your job is not to have fun, its to administrate. And bypassing restricted commands is just unacceptable.

**Comment by JeromSar** [comment]
Thanks for contributing!

This command is obviously very susceptible to abuse. In addition, super admins do not really require it to administrate effectively. For those two reasons, I don't think this is a good idea.
