### ISSUE TITLE
/tfm not work properly

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#1895]
Hello,
When i type /tfm in game it says
Version null null.null (null)
Compiled null by null

How can i fix it please?

**Comment by Commodore64x** [comment]
This error occurs when you compile the TFM with netbeans, but it is a legitimate bug. Thanks for your contribution

**Comment by WarrioR151** [comment]
@Commodore64x is possible to fix it? 

If i change
                build.codename,
                build.version,
                build.number,
                build.head), ChatColor.GOLD);

to
                build.codename,
                TotalFreedomMod.pluginVersion,
                build.number,
                build.head), ChatColor.GOLD);

in /tfm is 
Version null 5.0.null (null)
Compiled null by null

soo change   build.version, to TotalFreedomMod.pluginVersion, fixed version  show, but i dont know how to fix others like build.codename, build.number etc :(

I need it, please if you know how to fix all tell me :/ i need it

thanks in advance

**Comment by Commodore64x** [comment]
Lucky for you I know how to fix it then :) What you want to do is open the TotalFreedomMod.java file and towards the bottom you should see something like this:
`    public static class BuildProperties
    {

        public String author;
        public String codename;
        public String version;
        public String number;
        public String date;
        public String head;`

If you scroll down you will see where those strings are defined. The easiest way to fix this is next to where it has program.build.{variable} there is a null, these are the defaults that the mod falls back to when it cannot find the definition of those variables. For example:

`author = props.getProperty("program.build.author", "null");`

to

`author = props.getProperty("program.build.author", "yournamehere");`

That should fix the issue 🍡

**Comment by AvalancheYT** [comment]
You should find ```build.properties``` in the project folder, change the build author but don't mess with the build number.

**Comment by Commodore64x** [comment]
That method does not work XD

**Comment by AvalancheYT** [comment]
@Commodore64x, it does for me... You probably done something wrong.

**Comment by Commodore64x** [comment]
AvalancheYT do you use netbeans?

**Comment by AvalancheYT** [comment]
Yes, I do use netbeans.

**Comment by JeromSar** [comment]
No, you do not need to edit any files except buildnumber.properties @Commodore64x.

Are you using the latest TFM version from this repository, or are you compiling someone else's fork?

Did you edit any other files (pom.xml, package structure)? Have you done any renaming?

Lastly, what are the message that show up in console?

**Comment by AvalancheYT** [comment]
@JeromSar, do you mean build.properties?

**Comment by JeromSar** [comment]
@AvalancheYT Yes.

**Comment by PacksGamingHD** [comment]
Ok. So this is a widespread problem. Its an issue because TFM is not able to detect/create/find (one of those) the build properties. I've tried manually creating and adding the fields so I'm pretty sure it can't detect/find despite being manually created

**Comment by Commodore64x** [comment]
See? @PacksGamingHD is right, atm the easiest way is just to edit the default settings. It does not harm any other features of the TFM

**Comment by PacksGamingHD** [comment]
To make /tfm work, you would have to modify the TFM command which is violating the license.

**Comment by Commodore64x** [comment]
No you don't.... The part I am talking about is line `262 to 267 of TotalFreedomMod.java` Not editing the TFM command... Don't know where you got that from XD

**Comment by PacksGamingHD** [comment]
No. You have to modify some part of the tfm command or it will always return null

**Comment by Wild1145** [comment]
@PacksGamingHD You do not need to modify the plugin source code at all.

**Comment by Commodore64x** [comment]
@Wild1145 unfortunately for some users edting build.properties does not work so you have to use the method described above

**Comment by JeromSar** [comment]
For the record, it is of paramount importance that you compile with Maven. That means, if you're using Netbeans, that the project is open as a Maven project, and if you're using Eclipse or some other IDE, you use a plugin, or inbuilt technology to compile with Maven. That said, if you do not compile with Maven, you will likely find many bugs in TFM, the lacking build number being one of them.

Lastly, I personally reccomend that you don't find a way to workaround the problem (i.e. hardcode the build data), but rather find a solution to the actual problem. While this workaround might work temporarily, in programming, this will more often than not bite you in the butt later.
