### ISSUE TITLE
/wildcard not working despite what devs say

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1898]
Ok so, /wildcard DEFINENTLY ISN'T WORKING. I have gone through the main branch (server) and copied all the code from /wildcard and put it in a test TFM, the code still does not work and instead of executing a command from everyone on the server it executes a command from how many players are on the server. For example if there are three players on the server: Gupta, Bob and Jeff then instead of doing below if I did the command /wildcard say hi
[Gupta] Hi
[Bob] Hi
[Jeff] Hi
 It will do this if Gupta was the sender
[Gupta] Hi
[Gupta] Hi
[Gupta] Hi

I believe the error is in line 57 where it says:
`server.dispatchCommand(sender, runCommand);`

**Comment by Mafrans** [comment]
Actually, what you are describing is how the command is supposed to work, it sends the command once FOR every online player, not AS every online player,

To simulate the results you want you can use "/wildcard gcmd ? say hi", which would return:
[Gupta] Hi
[Bob] Hi
[Jeff] Hi

**Comment by ghost** [comment]
I thought that was what the purpose of /wildcard was... It would certainly be way more useful than what it is now .-.

**Comment by ghost** [comment]
Wait a minute, if what you say is true then the command description is misleading!
The description states: Run any command on all users, username placeholder = ?.
According to what you say then this must be incorrect and should be changed to:
Run any command according to the amount of players on the server.
Confusing or wrong?

**Comment by mayokek** [comment]
No, @Commodore64x... `Username placeholder = ?` means it would select every player on the server to execute a command.

**Comment by JeromSar** [comment]
@Commodore64x What you want can be achieved by combining /wildcard and /gcmd. 
You can run: `/wildcard gcmd ? say Hello` to accomplish this.

 Now, please stop opening more issues on this same matter. You're spamming the repository.
