### ISSUE TITLE
Block GCMD from Console

### ISSUE THREAD

**Issue by ExactObject** [TotalFreedom/TotalFreedomMod#1899]
If there's a way to block use of GCMD from the console, that would greatly help in preventing it's mis-use during a Clan breach.

**Comment by ghost** [comment]
Yes, there is a way to do this. I have seen it successfully implemented on many servers.

**Comment by ghost** [comment]
More suggestions and further reading #1900

**Comment by JeromSar** [comment]
@markbyrn There's not an easy config tweak, unfortunately. It's on the TODO list.

**Comment by ghost** [comment]
Its not a config tweak but you only have to do is to change the source type from BOTH to ONLY_IN_GAME so /gcmd can't be executed from console, its not that complicated.... I would say that method is just about as easy as editing the config

**Comment by ghost** [comment]
@Commodore64x You've to find another way of doing that instead of changing the SourceType.

**Comment by JeromSar** [comment]
@danielhoset27 What are you talking about?

**Comment by mayokek** [comment]
@danielhoset27, if you change SourceType from `BOTH` to `ONLY_IN_GAME`, it will prevent the console from using it.

**Comment by Wild1145** [comment]
This issue has been superseded by #1909
