### ISSUE TITLE
Message for /gcmd

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1900]
A good idea for the gcmd command would be if when you get gcmd'ed it sends you a message. For example if Player x gcmd's player y to do /say hello then it should say in player y's chat something like : Player x has forced you to do the command: /say hello
This should also work through telnet so no matter whether someone is ingame or on clanforge it will say the name of the player and the command sent. GCMD's should also be able to be logged in console in a different color to standout. Also, commands like /gmcd playerx gcmd playery say hi should be blocked.

**Comment by mayokek** [comment]
If you are on ClanForge, it would come out as Rcon.
Anyway, please suggest this on #1899 and stop opening issues that is similar, you are spamming the repo.

**Comment by ghost** [comment]
.... How am I spamming the repo??? This is a completely new issue that is different from #1899. I do not appreciate this comment at all.

**Comment by mayokek** [comment]
You can always suggest it on #1899 for workaround.

**Comment by ghost** [comment]
This is a completely different issue, it deserves its own thread. Please respect that. Unless you have anything useful to add to this idea please refrain from commenting on this issue.

**Comment by mayokek** [comment]
@Commodore64x, how about we ask @JeromSar... Jerom, isn't this issue duplicated to #1899

**Comment by JeromSar** [comment]
@AvalancheYT @Commodore64x The goal of the issues are different: one is a indication that a command should be blocked for console, and one is a suggestion for adding a message to a command.

**Comment by ghost** [comment]
See? Told you @AvalancheYT, anyway thoughts @JeromSar?

**Comment by mayokek** [comment]
@Commodore64x, it doesn't matter if I am wrong. I am just stating my thought.
This could help us find who gcmd'd us instead finding it off the logviewer/telnet.

**Comment by ghost** [comment]
If this enchanement was combined with #1899 then gcmding from telnet or clanforge would not be a problem

**Comment by lemonsked** [comment]
@Commodore64x Gcmding of Clanforge would return "Rcon".

**Comment by ghost** [comment]
@OxLemonxO No offence but did you not read the last post I made, if you block gcmd from console that won't be a problem... Regardless, I am working on this and I will make a PR later.

**Comment by Wild1145** [comment]
This issue has been superseded by #1909
