### ISSUE TITLE
When banned in hell, go forth and show thy IP

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1904]
I know issues about this have been made before but this time I cannot stress how important this issue is, I for the sanity of everyone I hope it gets fastracked and fixed pretty quick. First the issue: IP's showing when someone is banned, e.g. Gupta has been a very naughty boy, Banning ips 10.10.10.10
I know some think ips are public info and this shouldn't be rectified. I have seen reports and been able to test various clients that install ransomware on a person's PC, all they need is an IP and away they go. True hackers may be able to get ips different ways but the LEAST we can do to the players of TotalFreedom is to mitigate their potential exposure to DDOS and virus. I plead with either Wild or Jerom to fix this quick smart. Comments are welcome. This is not just a security member, but a courtesy and I hate for the server and the people that play their find out the hard way. Also, I know this is a duplicate of many issues in the past which have all been closed. I would just like for the TF community to have a say on this issue instead of getting shot down straight away for being 'invalid' or being a duplicate.

**Comment by zapteryx** [comment]
@JeromSar @Wild1145

**Comment by Wild1145** [comment]
This has been raised and discussed before.
