### ISSUE TITLE
Gcmd command blacklist

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1905]
Like the wildcard command I think it would be a good idea to add a command blacklist. I.e. User x tries to gcmd player to doom themself would be blocked because of /doom being on the blacklist. Also, gcmding multiple users, e.g /gcmd gupta gcmd gupra2 say hi should be blocked.

**Comment by ghost** [comment]
Have finished working on this, will make a PR now.

**Comment by ghost** [comment]
PR made.

**Comment by Wild1145** [comment]
This issue has been superseded by #1909
