### ISSUE TITLE
Out of date TF-Worldedit

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1907]
We urgently need to update to the latest Worldedit or coupling with Async will be impossible. I will work on this issue.

**Comment by ghost** [comment]
I am currently migrating all TF files to the new version of W/E

**Comment by lemonsked** [comment]
this needs to be in the TF-WorldEdit repo.

**Comment by ghost** [comment]
Moving to Worldedit repo
