### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1912]
Ok so I have this issue where the TFM cannot find any methods from the admin class. For example say I have admin.getRank() The IDE cannot find that method, and when I go into Admin.java no such method exists! This is the same on github, so can anyone tell me why this occurs? I have also searched the entire TFM for a method definition but have found none. I tried importing an original TFM and it worked fine, so what is the problem? @JeromSar @Wild1145 @OxLemonxO  ? Here is the thing though, I can still compile and run the TFM fine but no matter what IDE I use it still errors.

**Comment by mayokek** [comment]
Pictures, logs, anything similar for us to view?

**Comment by ghost** [comment]
Not really, the issue is basically that all methods from the Admin class are 'unavailable' although they clearly are when the plugin compiles.

**Comment by mayokek** [comment]
There is a statement where you would need to tell where to check - e.g

``` java
Admin admin = plugin.al.getEntryByName(player/sender.getName())
```

etc.

**Comment by ghost** [comment]
This is not the issue but anyway...

**Comment by JeromSar** [comment]
@Commodore64x Have you downloaded/installed [lombok](https://projectlombok.org/)? This should happen automatically when you build with Maven.

**Comment by ghost** [comment]
I do not believe I have.. What should I be doing? I have the lombok jar in my libs folder and the pom points to that but it does not fix the issue

**Comment by lemonsked** [comment]
@Commodore64x Like for dependencies such as Aero, do the same thing for Lombok.

**Comment by mayokek** [comment]
You should not need to add lombok as it will compile by it own.

``` xml
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.6</version>
    <scope>provided</scope>
</dependency>
```

**Comment by ghost** [comment]
Nope, that is what I had already.
