### ISSUE TITLE
UUID as a replacement to IP and names

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1914]
So I had this thought, and I have seen it done on a couple servers. What happens if we start using UUID's for banning, admins, etc. For everyone with a premium account that would be fine, e.g. player x was griefing so UUID is banned for 1 day, and that would not be that hard to do. However since TF can be offlinemode as well, we can use the old IP and name method for those users, and have a simple test to find if they are premium or not (from the /prem command) Anyway I just had this thought so yeah.

**Comment by mayokek** [comment]
Before TFM 5.0 was released, we had the uuid system but I believe @JeromSar had said that the system is useless or something.

**Comment by JeromSar** [comment]
You cannot fully rely on UUIDs because they can be spoofed by hacked clients. This issue has been extensively discussed, and I don't think we'll be switching back.
