### ISSUE TITLE
Can't find methods

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1915]
For some reason I cannot find multiple methods in the TFM code, the methods setRank() (admin.setRank)
and getConfigKey() (admin.getConfigKey()) are the ones in particular I would like to know the location of.

**Comment by mayokek** [comment]
Use this code before using admin variable
`Admin admin = plugin.al.getEntryByName(sender/player.getName());`

**Comment by ghost** [comment]
-_- That. Was. Not. The. Question.

**Comment by ghost** [comment]
Anyway, even with the original TFM when I ctrl + click the method (Which normally sends me to where the code is located) it does nothing? Is the code for these methods in Aero or another plugin?

**Comment by ghost** [comment]
Strangely enough all the methods I cannot find in the Vanilla TFM are the exact same methods that gives me errors in my custom TFM.

**Comment by mayokek** [comment]
@Commodore64x, I know you are not asking the question. Just see if you got the admin variable otherwise that would be the reason.

**Comment by ghost** [comment]
@AvalancheYT If that variable did not exist then it would show a different error, and hence I would be asking a different question.

**Comment by mayokek** [comment]
Can you screenshot the code please?
With errors.

**Comment by lemonsked** [comment]
Make sure you have Lombok(https://projectlombok.org/)

**Comment by mayokek** [comment]
What version of JDK are you currently using?

**Comment by ghost** [comment]
-_- Listen. I download an unmodified TFM, I run it on NetBeans with JDK 8 installed. I find the methods in question. I ctrl + click which would normally send me to where the method is created. I then realise that it cannot find it. I search the whole project for the method and nothing comes up. Where are the methods?

**Comment by mayokek** [comment]
That's why... TFM project uses JDK 7 not 8.

**Comment by lemonsked** [comment]
@Commodore64x Make sure you have Lombok installed as a dependency .-.

**Comment by mayokek** [comment]
Lombok isn't required as it will install on compiling stage. He was using JDK 8 instead of using JDK 7.

**Comment by lemonsked** [comment]
@AvalancheYT I use JDK 8 and it's perfectly fine. If you don't have Lombok installed, it will error in the IDE, and be fine while compiling. He said it's fine when he's compiling, but when he edits the code it says the method does not exist.

**Comment by ghost** [comment]
For the last time I have lombok installed! It isn't anything to do with my project that is the problem. The simple fact is if I download a clean TFM and browse to where the method is referenced and ctrl + click on it the method cannot be found.

**Comment by lemonsked** [comment]
@Commodore64x Lombok generates the methods, they don't actually exist. Don't you see those `@Getter` and `@Setter` statements?

**Comment by ghost** [comment]
I do not know how lombok works.

**Comment by lemonsked** [comment]
@Commodore64x https://projectlombok.org/features/GetterSetter.html

**Comment by ghost** [comment]
ooooh. This explains a hell of a lot. Thanks @OxLemonxO, so what if for some reason my plugin cannot find these generated methods for some reason?
