### ISSUE TITLE
Help i am getting a error 

### ISSUE THREAD

**Issue by Barkpuppy1** [TotalFreedom/TotalFreedomMod#1917]
i am getting the error Could not load 'plugins/TotalFreedomMod.jar' in folder 'plugins' and i have aero can anyone help me

**Comment by Wild1145** [comment]
Can you provide more information please?

**Comment by Barkpuppy1** [comment]
@Wild1145 that is all that i know. the plugins i have : BukkitTelnet, Essentials, EssentialsSpawn, EssentialsChat, EssentialsGeoIP, Aero, DaedalusMod

**Comment by Barkpuppy1** [comment]
its fixed now
