### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1918]
1) ew counter is bugged, it wipes entities, but it doesnt say how much entities, as he says 0

2) whohas clear looks is not working without the counter (add a counter for cleared items)

3) stfu and blockcmd can be bypassed if you relog in-game with your main alt or with your second alt , you need just two clients....

**Comment by JeromSar** [comment]
@marcocorriero Can you create a separate issue for each bug?

**Comment by ghost** [comment]
Sure, @JeromSar

**Comment by ghost** [comment]
@JeromSar done.
