### ISSUE TITLE
Error with SkinsRestorer

### ISSUE THREAD

**Issue by Barkpuppy1** [TotalFreedom/TotalFreedomMod#1924]
the error is  Could not load 'plugins/SkinRestorer.jar' in folder 'plugins'

**Comment by mayokek** [comment]
The error is on SkinsRestorer side not TFM.

**Comment by Barkpuppy1** [comment]
@JeromSar i do not see the issues page on SkinsRestorer so i do not know where to report the issue

**Comment by lemonsked** [comment]
@Barkpuppy1 https://github.com/Th3Tr0LLeR/SkinsRestorer---Maro
