### ISSUE TITLE
New Ranks

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1925]
Considering there are multiple ranks on the forums that are not ingame, why not add them? Firstly, how about adding Telnet Clan Admin, so admins who are this rank can easily be identified ingame. Also, a master builder rank could be added in preparation for new features to be added to them (unlimited w/e blocklimit, etc) As well, an executive rank should be added for all senior admins that are execs on the forums.

**Comment by Wild1145** [comment]
Telnet Clan is mearly a title, not an actual rank. Its the same with the master builder rank, its just a title. There is obviously the scope for telnet clan to be a rank, but what TFM differences would there be other than a title and tag? As for builders it would then involve people being in multiple ranks at once, something that TFM does not currently support. I just personally cannot see any real advantage to having something like this implemented, especially not the telnet clan rank.

**Comment by ghost** [comment]
But @Wild1145 what is the point of having a rank on the forums that noone can easily recognise ingame?

**Comment by Wild1145** [comment]
@Commodore64x Telnet Clan is not a rank. It is a title. It gives no additional permissions in game, only access to Clanforge. Therefore there would be little point adding a TFM rank for it.

**Comment by ghost** [comment]
Doesn't matter, Developer and Owner are purely look-for-show ranks, they have no specific command perms assigned to them.

**Comment by mayokek** [comment]
Owner or developer isn't extended to a rank, but Telnet Clan is extended from Telnet Admin.

**Comment by Wild1145** [comment]
Owner and developers are just titles. They hold no actual rank in the server. Developers are there due to issues we ran into where people were ripping the plugin off and claiming it as their own, so this is a deterrent. And owner is configurable because Mark asked for it. Telnet Clan is just a title really, and to create a new rank for a title would be silly.

**Comment by ghost** [comment]
Well then create a new title for it, regardless of what the title says that is what I am trying to say.

**Comment by mayokek** [comment]
@Commodore64x, there is no point of doing it.

**Comment by Wild1145** [comment]
As far as I am concerned, this is a total waste of development time, a title for the sake of a title is a pointless waste of time, and as such i am closing this PR.
