### ISSUE TITLE
Github suggestion

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1930]
So I have noticed there are ALOT of inactive PR's, so what about the implementation of a specified amount of time the PR creator has to fix the changes or sign the CLA before the PR is closed. Thoughts?

**Comment by Wild1145** [comment]
PR's are closed for inactivity when we feel that there is no chance that the OP will look at resolving the issues in the PR's.

**Comment by ghost** [comment]
Most of the PR's are one year old, and they all have issues which will probably never be fixed. A little stale perhaps?

**Comment by Wild1145** [comment]
I have gone through and cleaned up anything over 6 months old that was pending changes. I will start going through and testing the code on the remaining issues soon.

**Comment by Wild1145** [comment]
As a cleanup has occurred and some future suggestions on how to prevent this happening again have been raised, I will close this issue otherwise its a long term never ending issue.
