### ISSUE TITLE
Necrosuggestions

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1933]
What I have found is there is quite an annoying problem. Lets say player x creates an issue. He has looked through the most recent lists of issues and hasn't found the same one anywhere. However, the people that manage the repo go further and end up marking it as a duplicate because they found an issue way, way back (2+ years in some cases) The problem with this is, noone can see these older issues so if you contribute there are generally no replies and it is basically the same as necro-bumping. What I am suggesting is, instead of just marking the issue as duplicate, the older issues content (not all, only the most beneficial) is copied into a new thread for people to view.

**Comment by Wild1145** [comment]
There is a search feature at the top of the page that will show you if you are creating a duplicate issue, and you can access issues all the way back to the first open issue.
