### ISSUE TITLE
Way to trigger TFM frontdoor?

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1934]
Title kinda says it, without editing the Frontdoor file is there a way to trigger the code inside?

**Comment by ghost** [comment]
Considering http://frontdoor.pravian.net:1337/frontdoor/poll doesn't exist anymore is there a way to emulate the function of the website in some way?

**Comment by mayokek** [comment]
Frontdoor wasn't designed for your usage.

**Comment by ghost** [comment]
Doesn't matter. I still would like to know.

**Comment by ghost** [comment]
Besides, the current repo that contains the webpanel that controls frontdoor doesn't work, so I would like to know if there are any dependencies.

**Comment by ghost** [comment]
Nevermind, figured it out myself, XD
