### ISSUE TITLE
Automated report system?

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedom/TotalFreedomMod#1935]
What if we had a system where all of the reports were logged. It wouldn't be hard as you'd have to log it and save the information to a config file. Once you've done that you can use NanoHTTPD (like for permbans) and view all of the reports

Original thread: http://totalfreedom.boards.net/thread/47637/current-archive-reports-dec-2

**Comment by ghost** [comment]
Hey, thats a great idea, but I reckon we can expand this idea to the whole system! I have seen many servers which logs bans, mutes, etc. This should be a milestone for TFM 5.2

**Comment by Telesphoreo** [comment]
Create your own issue. This suggestion is for the report system only

**Comment by ghost** [comment]
No need to create a new issue, I am saying that this idea could be expanded on.

**Comment by ghost** [comment]
It would be a waste just to use it for 1 punishment system, this has potential.

**Comment by ghost** [comment]
@PacksGamingHD also the title isn't really relevant to what you are saying in your first post, you are talking about better logging of reports, not automating the system.

**Comment by PacksGamingHD** [comment]
Hence the question mark at the end, I wasn’t sure. Stop stirring drama

**Comment by Commodore64x** [comment]
??? I'm not stirring drama...

**Comment by AvalancheYT** [comment]
@PacksGamingHD, he's not stirring any drama, he was simply stating his opinion. Any issues that is similar to this can be suggested/reported here.

**Comment by falceso** [comment]
Bruh you steal my issue xD mine didn't post when I hit post.. Anyways I would like to suggest some Mysql and Php with a bit of bootstrap.

**Comment by Telesphoreo** [comment]
I linked the thread

**Comment by falceso** [comment]
I can tell xD
Off topic: slowly adding in Dec 5 & 6

**Comment by ghost** [comment]
You wanna go that complicated @falceso? Have fun.

**Comment by AvalancheYT** [comment]
I was going to create a plugin which would do that but... My computer is completely dead.

**Comment by Commodore64x** [comment]
What happened? Did lightning strike it?

**Comment by AvalancheYT** [comment]
@commodore64x, I believe that the display adapter didn't install properly.

**Comment by Telesphoreo** [comment]
Actually if I recall correctly CJFreedomMod had a MySQL logging system. If we were to use MySQL we would have to add a SQLite option as well or else the latest version of TFM wouldn't be used

**Comment by mayokek** [comment]
The CjFreedom plugin was designed with MySQL integrated system.

**Comment by Wild1145** [comment]
That is correct. CJFreedom was designed from the ground up using MySQL. So for us its not an issue, but for TFM its just not a quick integration.

**Comment by Wild1145** [comment]
This issue has been superseded by #1832
