### ISSUE TITLE
TFM Frontdoor not working

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1936]
So this is what I did:
1. Installed Node.js
2. Downloaded Frontdoor javascript files to run with node.js
3. Ran the server.js file through node.js which started the server
4. Opened the admin panel and added my servers ip
And it doesn't work?
Note: I did change the ip that the TFM detects whether it is blacklisted or not from

**Comment by ghost** [comment]
@Wild1145 ?

**Comment by Wild1145** [comment]
Ask @JeromSar however as far as I am aware we offer no support for frontdoor as it shouldnt be being used.
