### ISSUE TITLE
Chat Limit for TFM 5.1 1.11

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1941]
When you updated you forgot to change the chat limit from 100 to 256. As in all previous Minecraft versions leading up to 1.11 the chat limit was 100, but in 1.11 it was changed to 256. In all previous TFM versions, you have prevented chat overflow by limiting the number of characters that can be expressed in chat to the client limit, but now since you have updated the TFM to 1.11 you need to update this limit to fit with the new client threshold of 256 characters.

**Comment by Wild1145** [comment]
Was this previously an issue?

**Comment by ghost** [comment]
No, as the chat limit was only upgraded in 1.11

**Comment by Wild1145** [comment]
@Commodore64x Ahh, I just re-read the original issue, that makes sense. Have you got any source as to where this announcement was made? I haven't seen anything obvious in any chance logs as to the character limit being changed?

**Comment by ItzLevvie** [comment]
http://minecraft.gamepedia.com/1.11
http://minecraft.gamepedia.com/Multiplayer#History

**Comment by Wild1145** [comment]
Updated initial comment to reflect the issue raised on the PR by @JeromSar
