### ISSUE TITLE
Revamp ProtectArea

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1942]
I have a decent suggestion that I believe should be revamped. Suggestions about the /protectarea command:

1. Ability to protect area via World Edit selection.
I believe that ProtectArea should have the ability to protect a specific area selected via WorldEdit just like WorldGuard. Why I think it's useful: It's not easy to identify when you protect an area the point where it ends. The radius can remain but I also think there should be additionally an option in the command where you can protect a specific location yourself instead of having a radius do it for you which may not fully protect a build like the spawn (if it's a huge one).
Therefore, we could have a new sub-command/argument in the command named "select".
Usage & example = /protectarea select <name>
<name> = your protected area name. Sub-command/argument "select" will be used to tell TFM to protect the person who executed the command's world edit selection. If the selection is null (not selected), then it'll give them a message saying "Make a region selection first" just like WorldEdit.

2. Ability to add players to a protected region
This is probably the most frequent suggestion requested (if i'm correct); the only reason I say this, is because multitude of people ask admins in-game (mostly spawn builders who volunteer to build a server spawn) to 'add' them to the protected area. However, they don't realise that us admins are not able to add certain players to protected areas. The /adminworld command also has the ability to add players (guests) into the world; therefore, we should do the same for /protectarea as well; especially if a spawn builder wants to do some little changes but is unable to and since they're the spawn builder, they are trustworthy to be added to protected areas.

3. Alias command idea (/pa)
Finally, perhaps we could also have an alias command, which is /pa. Short for /protectarea. Followed by other aliases such as /protect, /protecta. /pa is the first alias and /protect and /protecta are optional.

----------------------------

Notes:
For suggestion 1 (world edit selections), the devs can take all the time they need if it requires a lot of hard work as this wont be a rush =)

**Comment by mayokek** [comment]
#981
