### ISSUE TITLE
Smite Suggestion

### ISSUE THREAD

**Issue by mandar-ghade** [TotalFreedom/TotalFreedomMod#1943]
My suggestion is to make the system keep track of the Creative PvPers and smite them at an instant. Having this already coded in the system would help enforce the server rules when admins are on and reduces the amount of work that admins do (which saves them time).

**Comment by ghost** [comment]
Duplicate.

**Comment by JeromSar** [comment]
@Commodore64x Which issue?

**Comment by mayokek** [comment]
This issue is duplicate to #287

**Comment by Wild1145** [comment]
This issue has been superseded by #287
