### ISSUE TITLE
Could not load plugin TotalFreedomMod

### ISSUE THREAD

**Issue by mgflames** [TotalFreedom/TotalFreedomMod#1947]
Hi there, I've successfully compiled the latest version of TotalFreedomMod however I am experiencing an issue on my server, when I launch it the plugin won't start.

In the logs, I get this error:

EDIT: Too long, pasting on pastebin.com

http://pastebin.com/N0kwujUn

Thank you in advanced,

InfamousYT.

**Comment by JeromSar** [comment]
Please make sure you have WorldEdit enabled on your server.

**Comment by mgflames** [comment]
Normal worldedit or TF-Worldedit?

**Comment by mgflames** [comment]
If I'm supposed to use normal worldedit, this error pops up:

http://pastebin.com/FWRyCAXA

**Comment by ItzLevvie** [comment]
You've to use TF-WorldEdit (https://github.com/TotalFreedom/TF-WorldEdit)

**Comment by mgflames** [comment]
This fixed it however I get this error:

http://prnt.sc/drj350

This is my plugins directory:

http://prnt.sc/drj2aw

**Comment by ItzLevvie** [comment]
Second screenshot:

Is that the TF's WorldEdit or the one from https://dev.bukkit.org/projects/worldedit/files/956525?

You need to make sure you use TF's WorldEdit

**Comment by mgflames** [comment]
TotalFreedom's.

**Comment by ItzLevvie** [comment]
By looking at the plugin name on the second screenshot, it seems like you're using the official one and not the one from https://github.com/TotalFreedom/TF-WorldEdit

**Comment by ItzLevvie** [comment]
Confirmed that you're not using TF-WorldEdit: see https://github.com/TotalFreedom/TotalFreedomMod/issues/1947#issuecomment-270417818 is the same as

http://prnt.sc/drj350

**Comment by InfamousYT** [comment]
I personally compiled it using gradlew.bat

**Comment by InfamousYT** [comment]
I got it from C:\Users\TM-PC\Desktop\TF-WorldEdit-tfm50\worldedit-bukkit\build\libs\worldedit-bukkit-6.1.1-TF.jar

**Comment by mgflames** [comment]
Nevermind, I've now got a worldedit-bukkit-6.1.1-TF.jar. However, when I launch the server TotalFreedomMod doesn't launch

**Comment by mgflames** [comment]
Therefore, it ends up coming with error:

org.bukkit.plugin.UnknownDependencyException: WorldEdit
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.2.jar:git-Spigot-7d78b81-613be0d]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by mgflames** [comment]
OK, I currently have worldedit-bukkit-6.1.1-TF-dist.jar and TotalFreedomMod.jar in my directory - I'm still getting: http://prnt.sc/drj350

**Comment by mgflames** [comment]
With the additional errors of: 

[TotalFreedomMod] Uncaught exception executing command: setlimit
[TotalFreedomMod] null

and

http://prntscr.com/drk3sh

**Comment by mayokek** [comment]
Are you using the TF WorldEdit to compile your plugin?

**Comment by mgflames** [comment]
I'm not sure - if I attempt to re-compile it should I use the dist or the normal version in the lib folder?

**Comment by ItzLevvie** [comment]
dist
