### ISSUE TITLE
Bug with /disguise

### ISSUE THREAD

**Issue by JackGrylls1** [TotalFreedom/TotalFreedomMod#1965]
For some reason when I do /d itemframe, it crashes my game. I have no idea if this happens to anyone else,
but it can be very annoying as it restarts your game.

**Comment by Wild1145** [comment]
This is not within the scope of this project. Please raise an issue with the Disguisecraft team directly.

**Comment by OxLemonxO** [comment]
@Wild1145, we don't use Disguisecraft, we use LibsDisguises.
It might also be the fact that we are using the 1.10 version, and we still allow 1.11 players to join.
