### ISSUE TITLE
Compass item allowing players to move if they're frozen

### ISSUE THREAD

**Issue by KingDragonRider** [TotalFreedom/TotalFreedomMod#198]
Continues from: http://www.totalfreedom.boards.net/thread/12511/players-use-compasses-when-frozen

I believe it's just a setting which can be changed in the Essentials config file, I may be wrong though.

**Comment by Wild1145** [comment]
Bumping to find out if anyone checked into the WorldEdit thing? I believe its something to do with the config and if you disable it then there wont be any issue.

**Comment by JeromSar** [comment]
Resolved in 7da543f7fbd89d1baaa2f47f06ef6be85dedd1d9
