### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by robingall2910** [TotalFreedom/TotalFreedomMod#1983]
I wonder, should someone develop a REST API so we can get some statistics of the server, like status, ping time, tps, etc? Seems like a great idea if you're running TFM on a server and you want to link it to a service like a discord bot or a website of some sort. I can't really explain myself a lot on this, but it looks like this plugin can post some useful stats to some kind of an API.

**Comment by Wild1145** [comment]
I like where you're going with this. A Restful API would open up a lot of options for those wishing to develop features and also web-applications that we can use to pull different statistics and such. It would give us a lot of flexibility, and as I say, I like it.

**Comment by Wild1145** [comment]
This issue has been superseded by #2038
