### ISSUE TITLE
Clearmychat Command

### ISSUE THREAD

**Issue by savnith** [TotalFreedom/TotalFreedomMod#1988]
Add a simple clearchat command that clears the senders chat. 

for (int i = 0; i <= 150; i++)
{
      msg("");
}

**Comment by mayokek** [comment]
That's apparently spamming them with nothing.

**Comment by lemonsked** [comment]
CTRL + D does the same thing.

**Comment by Wild1145** [comment]
As the functionality is already built into MC as previously mentioned, this would serve little purpose.
