### ISSUE TITLE
Players cant join on another version

### ISSUE THREAD

**Issue by jclgc** [TotalFreedom/TotalFreedomMod#1993]
So as i stated in the title, players are unable to join the server in higher verisions of minecraft. I compiled spigot 1.10.2 and enabled aero, but I still can't join on 1.11. Does this have anything to do with TFM or Aero?

**Comment by ItzLevvie** [comment]
It's nothing to do with TFM or Aero.

You'll need [ProtocolSupport](https://build.true-games.org/job/ProtocolSupport/lastSuccessfulBuild/artifact/target/ProtocolSupport.jar) to allow ```1.11.y``` and below to join your server.

**Comment by jclgc** [comment]
Alright, I'm sorry for the unrelated post. Thanks.
