### ISSUE TITLE
TFM patch actually loaded on server

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#1995]
https://www.dropbox.com/s/xf7b1t8jdohvtd2/TFM-V2.rar?dl=0

@markbyrn dont wants all edits gets lost

soo here

**Comment by Wild1145** [comment]
As I talked to you about, we wont simply merge every change together. A lot of the changes I believe have been made are not suitable for TFM, and should never have been added. As part of my updates to the plugins I will be looking to first get everything stable, and then any functionality that is deemed necessary and is still required, can be reviewed and looked at then, but we wont just merge in hundreds of file changes without any sort of review.

**Comment by Telesphoreo** [comment]
Honestly Wild pretty much sums up how I feel. I don't think that all of these patches should be added, but rather iron out the long standing bugs, and then add more functionality. Else, this will turn out similarly to how Windows Vista turned out (features>stability)

**Comment by Wild1145** [comment]
Now that all the issues have been individually raised, I will close this issue down and let it be superseded by the other issues raised. I wont tag them all here as I'd be here until tomorrow listing them.
