### ISSUE TITLE
Create rank

### ISSUE THREAD

**Issue by ShRules** [TotalFreedom/TotalFreedomMod#2003]
I'm not good in developing, but how do i create a new rank/title for my server?

**Comment by savnith** [comment]
xD

**Comment by savnith** [comment]
Use titles, and do this:

Add the rank in title.java
`RANK("a", "Rank", ChatColor.<What chat color u want the tag>, "Rank"); `

Add the Rank to the FUtils.java
`public static final List<String> RANK = Arrays.asList("Username");`

Then add it to the RankManager.java
`
        if (FUtil.RANK.contains(player.getName()))
        {
            return Title.RANK;
        }
`
And on line 161 in rankmanager.java
`
if (isAdmin || FUtil.RANK.contains(player.getName())
||FUtil.DEVELOPERS.contains(player.getName()))
`

There u go that is the best way!

**Comment by Telesphoreo** [comment]
a better way if you want to use /saconfig setrank:
go into Ranks.java and copy one of the lines
paste it in the order you want so it could be like this
IMPOSTOR
NONOP
OP
SUPER
TELNET
SENIOR
<YOUR RANK>
TELNET_CONSOLE
SENIOR_CONSOLE

so it would have permissions of a senior admin if you put your rank there, but if you want it to have super admin permissions put it under super admin
