### ISSUE TITLE
Add Command_adventure

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2014]
Issue for relevant PR
Details:
Add a command that allows players to set themselves to adventure mode

**Comment by Wild1145** [comment]
If possible, could you please confirm if this has been made as an unofficial patch that is already running on the server, or if this is simply a suggestion for added functionality.

**Comment by Wild1145** [comment]
Added in https://github.com/TotalFreedom/TotalFreedomMod/commit/baf73df4f9be81f0cb39b71e6e1809425db649b8
