### ISSUE TITLE
Add Command_blockedit

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2015]
Issue for relevant PR
Details:
Add a command that can toggle a players ability to place blocks

**Comment by Wild1145** [comment]
If possible, could you please confirm if this has been made as an unofficial patch that is already running on the server, or if this is simply a suggestion for added functionality.

I again must question the value of this? Surely there should be no need to stop someone building on the server? It simply opens up more issues than it solves...

**Comment by Wild1145** [comment]
As per my last comments, I can not see the value to this... Closing as declined.
