### ISSUE TITLE
Add Command_blockpvp

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2016]
Issue for relevant PR
Details:
Add a command that allows admins to block a players pvp

**Comment by Wild1145** [comment]
If possible, could you please confirm if this has been made as an unofficial patch that is already running on the server, or if this is simply a suggestion for added functionality.

Once again, all this does is restrict peoples freedom... If I were to even consider wanting this sort of thing personally, you'd need to do what we did for CJFreedom and have a Creative PVP blocker, other than that this just restricts peoples freedom with no good reason

**Comment by Wild1145** [comment]
Again, nobody has chimed in to say they disagree that this unnecessarily restricts players freedom so I am closing this issue as declined.
