### ISSUE TITLE
Add Command_blockredstone

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2017]
Issue for relevant PR
Details:
Command to toggle all redstone based functionality

**Comment by Wild1145** [comment]
If possible, could you please confirm if this has been made as an unofficial patch that is already running on the server, or if this is simply a suggestion for added functionality.

I also must say I dont think this adds any value to the plugin, and simply restricts players freedom unnecessarily.

**Comment by Wild1145** [comment]
Based on the fact nobody has argued against my previous comment I am declining this issue as it unnecessarily restricts a players freedom.
