### ISSUE TITLE
Add Command_wipecoredata

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2023]
Issue for relevant PR
Details:
Command that allows for modification of CoreProtect database.

**Comment by Wild1145** [comment]
This issue requires a link to the CoreProtect plugin, something that TFM does not have. This should be raised as a new issue for proper and complete Core Protect Implementation and this issue should be a part of that new issue.

**Comment by ghost** [comment]
we have.
@Wild1145

**Comment by Wild1145** [comment]
No, you have not. This issue would not work in the current TFM builds, as I said above, a new issue needs to be raised addressing core protect implementation properly, not just a single command.

**Comment by ghost** [comment]
@wild is it. if you look in the commie's PR there is coreprotect incorporation.

**Comment by Wild1145** [comment]
@marcocorriero That PR does not meet the contributing guidelines by any stretch of the imagination. Raise a proper issue here, explaining what you're trying to do, the pro's con's and all that. Thats what Github is for, so we can discuss feature implementation, not just add a shit load of random code to the repo without any idea of what it does.

**Comment by Wild1145** [comment]
Worth raising this sort of thing as part of #721
