### ISSUE TITLE
Edit_Allow structure void

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2026]
Issue for relevant PR
Details:
The block structure void is now allowed

**Comment by Wild1145** [comment]
If possible, could you please confirm if this has been made as an unofficial patch that is already running on the server, or if this is simply a suggestion for added functionality.

Please also add more information to the description, it is exceptionally vague.

**Comment by Wild1145** [comment]
@Commodore64x Reason for close?
