### ISSUE TITLE
Edit_Command_cake

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2029]
Issue for relevant PR
Details:
Now uses method shared by Command_rainbowtag and Command_rainbownick to generate colors instead of being random

**Comment by Wild1145** [comment]
If possible, could you please confirm if this has been made as an unofficial patch that is already running on the server, or if this is simply a suggestion for added functionality.

I dont see how this adds any value at all? Its basically exactly the same as it already does?
