### ISSUE TITLE
/gcmd bypasses target permissions.

### ISSUE THREAD

**Issue by mayokek** [TotalFreedom/TotalFreedomMod#2044]
Along this line - https://github.com/TotalFreedom/TotalFreedomMod/blob/devel/src/main/java/me/totalfreedom/totalfreedommod/command/Command_gcmd.java#L32 - it shows that it checks for sender's permission, where it should check for the player's permission.

**Comment by JeromSar** [comment]
I think this was added as a safety measure: Do not allow admins to run commands for others that they are themselves not allowed to run. When the command actually executes, its permission checks are still executed and thus the target command sender can never bypass permissions.

**Comment by mayokek** [comment]
@JeromSar, and that's how people become rogue by framing people. For example, if I execute this `/gcmd <op's name> rl`, it will make them reload the server because I have that permission to execute. If I am on telnet and I execute `gcmd <op's name> saconfig add <someone>`, that target will add someone to admin because I have that permission.

Maybe add another line to check for player's permission as well?

**Comment by lemonsked** [comment]
@mayokek the command still goes through the perms check in the players side.

**Comment by mayokek** [comment]
@OxLemonxO, that is correct but how can an op reload the server when gcmd'd?

**Comment by JeromSar** [comment]
@mayokek OPs shouldn't be able to do so. If they are, this is a bug, and that should be fixed. Are you sure that this is the case?

**Comment by mayokek** [comment]
Yes, I am sure. @JeromSar
