### ISSUE TITLE
Let normal players go to the adminworld

### ISSUE THREAD

**Issue by kobetricee** [TotalFreedom/TotalFreedomMod#2051]
Let normal players go to the adminworld but not edit it

**Comment by ghost** [comment]
object. it would be bypassable with worldedit.

**Comment by Wild1145** [comment]
@marcocorriero Then implement a system to check what world they are in before allowing the command to execute?

Also, we already have this with the admin world guest system. Admin world is not designed for normal players, but for the server admins and any close friends of them, so I dont think this is a great idea myself.

**Comment by JeromSar** [comment]
Is this desirable behavior? As far as I'm aware, admins want to have some place to be left alone, and probably not be followed by many players.

**Comment by StevenLawson** [comment]
I agree that adminworld should only be for admins and carefully selected guests. Closing issue.
