### ISSUE TITLE
Disregarded

### ISSUE THREAD

**Issue by mgflames** [TotalFreedom/TotalFreedomMod#2076]
Disregard

**Comment by InfamousYT** [comment]
I was going to see if the 2.x branch of TF-Essentials worked while I waited, but that just came with issue:

Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project EssentialsParent: An Ant BuildException has occured: The following error occurred while executing this line:
C:\Users\Infam\Downloads\TF-Essentials-2.x\EssentialsGroupManager\nbproject\build-impl.xml:1206: Javadoc returned 1
around Ant part ...<ant antfile="build.xml" dir="EssentialsGroupManager"/>... @ 5:58 in C:\Users\Infam\Downloads\TF-Essentials-2.x\target\antrun\build-buildgm.xml
-> [Help 1]

**Comment by mayokek** [comment]
Did you edit it? If not, use the released jar. https://github.com/TotalFreedom/TF-Essentials/releases/download/v2.1-TF/Essentials-TF.jar

**Comment by InfamousYT** [comment]
The problem with that is I wanted to use the latest versions of all of the TFMs.

**Comment by InfamousYT** [comment]
Is there any way of that?
