### ISSUE TITLE
Marked as an imposter

### ISSUE THREAD

**Issue by mgflames** [TotalFreedom/TotalFreedomMod#2079]
Hi,

I've been marked as an imposter on my own server, how can I verify myself?

Thanks.

**Comment by mayokek** [comment]
Simply do /saconfig add <your name> from your console.

**Comment by mgflames** [comment]
@mayokek Also, a little off-topic, but do you know how I can also get the coloured staff chat? For example, superadmins get blue colour chat when they speak?

Thanks.

**Comment by Wild1145** [comment]
@InfamousYT All chat formatting is purged through the chat event, to only allow white text. You could change this without too much effort, but it might make chat difficult / impossible to read especially if its in the public chat.

**Comment by LiamTownsley** [comment]
DO you require anymore help? If not please close this issue.
