### ISSUE TITLE
Let non-ops do /opme

### ISSUE THREAD

**Issue by savnithyt** [TotalFreedom/TotalFreedomMod#2082]
Let non-ops be able to do /opme when they are deop, http://totalfreedom.boards.net/thread/53382/meop-plugin

**Comment by ghost** [comment]
This has been denied in various suggestions on the forums, it is unlikely to be added.

**Comment by Wild1145** [comment]
There is another issue raised that outlines the potential implementations of this, this issue does not cover one of those implementations. 

This issue has been superseded by #1764
