### ISSUE TITLE
Could not load build properties!

### ISSUE THREAD

**Issue by mgflames** [TotalFreedom/TotalFreedomMod#2085]
Hi there,

I've successfully compiled TotalFreedomMod but when I try running it on my server, I get this error:

`20.07 01:08:30 [Multicraft] Received start command
20.07 01:08:30 [Multicraft] Loading server properties
20.07 01:08:30 [Multicraft] Starting server!
20.07 01:08:30 [Multicraft] Loaded config for "Mod: Spigot"
20.07 01:08:30 [Multicraft] Updating eula.txt file
20.07 01:08:30 [Server] INFO Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
20.07 01:08:30 [Server] INFO Loading libraries, please wait...
20.07 01:08:33 [Server] INFO Starting minecraft server version 1.12
20.07 01:08:33 [Server] INFO Loading properties
20.07 01:08:33 [Server] INFO Default game type: SURVIVAL
20.07 01:08:33 [Server] INFO This server is running CraftBukkit version git-Spigot-7228328-af1c013 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
20.07 01:08:33 [Server] INFO Server Ping Player Sample Count: 12
20.07 01:08:33 [Server] INFO Using 4 threads for Netty based IO
20.07 01:08:33 [Server] INFO Debug logging is disabled
20.07 01:08:33 [Server] INFO Generating keypair
20.07 01:08:33 [Server] INFO Starting Minecraft server on 37.187.161.221:25624
20.07 01:08:33 [Server] INFO Using epoll channel type
20.07 01:08:33 [Server] INFO Set PluginClassLoader as parallel capable
20.07 01:08:33 [Server] INFO [WorldEdit] Loading WorldEdit v6.1.7-SNAPSHOT;no_git_id
20.07 01:08:33 [Server] INFO [Aero] Loading Aero v2.0
20.07 01:08:33 [Server] INFO [TotalFreedomMod] Loading TotalFreedomMod v5.0
20.07 01:08:33 [Server] ERROR [TotalFreedomMod] Could not load build properties! Did you compile with Netbeans/ANT?
20.07 01:08:33 [Server] ERROR [TotalFreedomMod] null
20.07 01:08:33 [Server] INFO java.lang.NullPointerException: null
20.07 01:08:33 [Server] INFO at java.util.Properties$LineReader.readLine(Unknown Source) ~[?:1.8.0_45]
20.07 01:08:33 [Server] INFO at java.util.Properties.load0(Unknown Source) ~[?:1.8.0_45]
20.07 01:08:33 [Server] INFO at java.util.Properties.load(Unknown Source) ~[?:1.8.0_45]
20.07 01:08:33 [Server] INFO at me.totalfreedom.totalfreedommod.TotalFreedomMod$BuildProperties.load(TotalFreedomMod.java:276) [TotalFreedomMod.jar:?]
20.07 01:08:33 [Server] INFO at me.totalfreedom.totalfreedommod.TotalFreedomMod.load(TotalFreedomMod.java:122) [TotalFreedomMod.jar:?]
20.07 01:08:33 [Server] INFO at net.pravian.aero.plugin.AeroPlugin.onLoad(AeroPlugin.java:72) [Aero-2.0%20(1).jar:?]
20.07 01:08:33 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [spigot.jar:git-Spigot-7228328-af1c013]
20.07 01:08:33 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-7228328-af1c013]
20.07 01:08:33 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-7228328-af1c013]
20.07 01:08:33 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
20.07 01:08:33 [Server] INFO [Aero] Enabling Aero v2.0
20.07 01:08:33 [Server] INFO [Aero] Aero v2.0.249 by Prozza initialized
20.07 01:08:33 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
20.07 01:08:35 [Multicraft] Skipped 86 lines due to rate limit (30/s)
20.07 01:08:35 [Server] INFO Preparing spawn area: 80%

20.07 01:08:36 [Server] WARN [WorldEdit] 
20.07 01:08:36 [Server] INFO **********************************************
20.07 01:08:36 [Server] INFO ** This WorldEdit version does not fully support your version of Bukkit.
20.07 01:08:36 [Server] INFO **
20.07 01:08:36 [Server] INFO ** When working with blocks or undoing, chests will be empty, signs
20.07 01:08:36 [Server] INFO ** will be blank, and so on. There will be no support for entity
20.07 01:08:36 [Server] INFO ** and biome-related functions.
20.07 01:08:36 [Server] INFO **
20.07 01:08:36 [Server] INFO ** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
20.07 01:08:36 [Server] INFO **********************************************
20.07 01:08:36 [Server] INFO [TotalFreedomMod] Enabling TotalFreedomMod v5.0
20.07 01:08:36 [Server] INFO [Aero] Registered Aero plugin: TotalFreedomMod
20.07 01:08:36 [Server] INFO [TotalFreedomMod] Created by Madgeek1450 and Prozza
20.07 01:08:36 [Server] INFO [TotalFreedomMod] Version 5.0.null (null)
20.07 01:08:36 [Server] INFO [TotalFreedomMod] Compiled null by null
20.07 01:08:36 [Server] WARN [TotalFreedomMod] TotalFreedomMod is compiled for v1_11_R1 but the server is running version v1_12_R1!
20.07 01:08:36 [Server] WARN [TotalFreedomMod] This might result in unexpected behaviour!
20.07 01:08:36 [Server] WARN [TotalFreedomMod] Missing configuration entry allow.frostwalker. Using default value.
20.07 01:08:36 [Server] WARN [TotalFreedomMod] Missing configuration entry allow.frostwalker. Using default value.
20.07 01:08:36 [Server] ERROR [TotalFreedomMod] Plugin TotalFreedomMod v5.0 has failed to register events for class me.totalfreedom.totalfreedommod.ServerInterface because net/minecraft/server/v1_11_R1/MinecraftServer does not exist.
20.07 01:08:36 [Server] INFO -------- World Settings For [flatlands] --------
20.07 01:08:36 [Server] INFO Cactus Growth Modifier: 100%
20.07 01:08:36 [Server] INFO Cane Growth Modifier: 100%
20.07 01:08:36 [Server] INFO Melon Growth Modifier: 100%
20.07 01:08:36 [Server] INFO Mushroom Growth Modifier: 100%
20.07 01:08:36 [Server] INFO Pumpkin Growth Modifier: 100%
20.07 01:08:36 [Server] INFO Sapling Growth Modifier: 100%
20.07 01:08:36 [Server] INFO Wheat Growth Modifier: 100%
20.07 01:08:37 [Multicraft] Skipped 50 lines due to rate limit (30/s)
20.07 01:08:37 [Server] INFO [TotalFreedomMod] Loaded 3 admins (3 active,  4 IPs)
20.07 01:08:37 [Server] INFO [TotalFreedomMod] Loaded 114 commands.
20.07 01:08:37 [Server] WARN [TotalFreedomMod] Not blocking: /pp - Duplicate entry exists!
20.07 01:08:37 [Server] WARN [TotalFreedomMod] Not blocking: /pp - Duplicate entry exists!
20.07 01:08:37 [Server] INFO [TotalFreedomMod] Loaded 63 blocked commands (20 known).
20.07 01:08:37 [Server] INFO [TotalFreedomMod] Loaded 0 IP bans and 0 username bans.
20.07 01:08:37 [Server] INFO [TotalFreedomMod] Loaded 38 unbannable usernames.
20.07 01:08:37 [Server] INFO [TotalFreedomMod] Loaded 3 perm IP bans and 3 perm username bans.
20.07 01:08:37 [Server] INFO [TotalFreedomMod] TFM HTTPd started. Listening on port: 28966
20.07 01:08:37 [Server] ERROR [TotalFreedomMod] Could not register service class: CoreProtectDatabase
20.07 01:08:37 [Server] ERROR [TotalFreedomMod] java.lang.reflect.InvocationTargetException
20.07 01:08:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
20.07 01:08:37 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
20.07 01:08:37 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
20.07 01:08:37 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source)
20.07 01:08:37 [Server] INFO at net.pravian.aero.component.service.ServiceManager.registerService(ServiceManager.java:68)
20.07 01:08:37 [Server] INFO at me.totalfreedom.totalfreedommod.TotalFreedomMod.enable(TotalFreedomMod.java:217)
20.07 01:08:37 [Server] INFO at net.pravian.aero.plugin.AeroPlugin.onEnable(AeroPlugin.java:81)
20.07 01:08:37 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
20.07 01:08:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
20.07 01:08:37 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
20.07 01:08:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:378)
20.07 01:08:37 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
20.07 01:08:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
20.07 01:08:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
20.07 01:08:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
20.07 01:08:37 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
20.07 01:08:37 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
20.07 01:08:37 [Server] INFO at java.lang.Thread.run(Unknown Source)
20.07 01:08:37 [Server] INFO Caused by: java.lang.NullPointerException
20.07 01:08:38 [Server] Startup Done (4.388s)! For help, type "help" or "?"`

I compiled with NetBeans.

Thanks.

**Comment by Wild1145** [comment]
That error you can ignore, its the second one that you cant. TFM all of a sudden has a dependency on Core Protect

**Comment by mgflames** [comment]
@Wild1145 I've fixed the second error but now I have a new one. I use apex minecraft hosting and they claim that all of their ports are open, yet I get the error below when I try connecting through bukkit telnet.

Connecting to **.***.***.***:58146
Connection refused: connect
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:182)
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:203)
	at me.mayo.telnetkek.ConnectionManager.lambda$startConnectThread$1(ConnectionManager.java:177)
	at java.lang.Thread.run(Thread.java:748)

Disconnected

NOTE: I changed the port in the config.yml of Bukkit Telnet to 58146 and the address option is just " ".

**Comment by mgflames** [comment]
Fixed,  changed address option to "0.0.0.0"
