### ISSUE TITLE
Null route management

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#2087]
I think it'd be nice if TFM could add IPs to a temporary null route, especially for Unix like OS's. (most servers use this anyways). Null routing an IP of someone while they are connected has an interesting effect. It causes them to time out just as I thought it might and has proven effective in slowing down ban bypassing trolls.

**Comment by Wild1145** [comment]
Given that nullrouting is handled at a firewall level, and this sits within an application layer, I feel that this is probably outside the scope of this project, and that utilising a decent firewall system should give this same functionality in a far more refined and efficient system.

**Comment by JeromSar** [comment]
Maybe there is an abstraction/general API we could use to communicate to the link layer we could use? If there's no general solution on Linux, I don't think we can solve this efficiently.

**Comment by lemonsked** [comment]
There's one way, send a terminal command that nullroutes the player's IP.

**Comment by Wild1145** [comment]
What if TFM is running on a Windows based server? As I say, this is something that should be handled imo on a server by server basis by the Systems Administrator / Engineer that has built the server. Same goes for if you're on shared hosting. I dont feel that this is appropriate for TFM to attempt to handle as-is.

**Comment by JeromSar** [comment]
I agree with @Wild1145 here. There is no clean/efficient/applicable solution in this case.

Thanks for contributing. Closing the issue, please don't be offended. :)
