### ISSUE TITLE
GTFO Spam

### ISSUE THREAD

**Issue by LiamTownsley** [TotalFreedom/TotalFreedomMod#2093]
We can just make the server dispatch `co rb [NAME] t:1d r:#global #silent` and you do not get the massive spam.

**Comment by Wild1145** [comment]
TFM currently does not support CoreProtect, and as such this is a server specific modification. You will need to raise this with the server based developers.

**Comment by LiamTownsley** [comment]
It does with /gtfo. @Wild1145

**Comment by ghost** [comment]
well, it has been loaded with coreprotect support ages ago, madgeek already loaded the fix on the server branch

**Comment by Wild1145** [comment]
The server branch is not an officially supported branch, it is not supported features of the TFM development team. The server branch is 3rd party changes that were made to the TF Server. CoreProtect functionality is not officially supported in TFM and as such we are unable to offer support for such 3rd party changes.

**Comment by LiamTownsley** [comment]
I am meaning for the server as its effects our ability to read chat if we are spammed with 150+ messages everytime we ban someone.

**Comment by LiamTownsley** [comment]
(This is for TOTALFREEDOM)

**Comment by JeromSar** [comment]
@Wild1145 is right. We don't officially support the 'server' version of TFM.
