### ISSUE TITLE
Git not running with Netbeans

### ISSUE THREAD

**Issue by hitzzaf** [TotalFreedom/TotalFreedomMod#2097]
Trying to compile TFM right now and I keep getting this error:
```
Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project totalfreedom: Cannot get the branch information from the scm repository :
Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "git" (in directory "C:\Users\hailey\Documents\NetBeansProjects\TotalFreedomMod-devel"): CreateProcess error=2, The system cannot find the file specified
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
I've already tested my PATH and it's set up correctly, I'm not sure how to fix it.

**Comment by hitzzaf** [comment]
I've also read somewhere that Git only works with certain versions of maven, I'm running netbeans obviously and im not sure

**Comment by lemonsked** [comment]
You need to have Git installed and in your PATH. Type git in command prompt, what does it show?

**Comment by hitzzaf** [comment]
"I've already tested my PATH and it's set up correctly, I'm not sure how to fix it."
@OxLemonxO 
It's in the PATH

**Comment by lemonsked** [comment]
I mean, what's the output of git in command prompt? Does it show something  like l`lC:\Users\Lemon\Desktop>git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
:`

**Comment by hitzzaf** [comment]
```
C:\Users\hailey>git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

@OxLemonxO

**Comment by hitzzaf** [comment]
any suggestions?

**Comment by hitzzaf** [comment]
computer restart fixed it
