### ISSUE TITLE
/requestadmin (Alternative/Addon to /report)

### ISSUE THREAD

**Issue by hitzzaf** [TotalFreedom/TotalFreedomMod#2098]
Recently operators have been coming to me saying they have questions, but no admins listen to them in the normal chat. Some resort to abusing /report on innocent players just to get their attention. I suggest a command called /requestadmin or /question (possible aliases) to ask administrators questions without having to abuse commands or spam chat. This could improve many things, causing less spammers and less confusion. It's a simple addition, (which i've already done) and wouldn't give any bugs and would be just like /report, but you don't have to report anyone. Easily added, and helps the server.

I gave this idea back in 2015, and it was added but then removed for some reason. (I'm Heyitsthatonekid, NotAnOperator, Mac_OS_X).

I suggest doing this by adding another type of report feature in ChatManager.java then making the command.

I made the command already just can't be added until it's accepted if I remember correctly

**Comment by Wild1145** [comment]
This sounds more like an issue with poor administration on the server, and that admins need to be better trained / disciplined for failing to do their jobs...

**Comment by hitzzaf** [comment]
I agree @Wild1145 now-a-days thats what happens, but maybe even with more discipline or not adding as many administrators it could still be helpful and seems to cause no harm.

**Comment by Wild1145** [comment]
@hitzzaf I dont see the value to spending time on implementing features, when server owners can just manage their staff better... Thats why I am inclined not to add this.

**Comment by fionnn** [comment]
I believe this should be a feature, I also believe it should have bright colors.
I get around 2-3 messages at the same time everyday, and it would be really helpful if we had this.

**Comment by TangoMangoMC** [comment]
I agree with Wild, the administrators should see a report or request for help in chat

**Comment by Wild1145** [comment]
I dont feel that this will add any value to offset the time that it will take to build from the time it'll save in game. Admins will just ignore this if they are that way inclined. Better training on the servers is needed.

**Comment by JeromSar** [comment]
I agree with @Wild1145. You seem to be proposing something that the /report command was designed to solve. It might be that the /report command has shortcomings. If so, you could make another issue describing how you would instead solve the problems with /report.
