### ISSUE TITLE
Get a players gamemode easier

### ISSUE THREAD

**Issue by hitzzaf** [TotalFreedom/TotalFreedomMod#2113]
We could have a command that simply displays the players gamemode without the other spam of /seen. Simple command and it does not wrong to the server and I believe it could help. If we wanted to we could also color code the answers so if they are in Survival its green if its Creative red etc.

**Comment by lemonsked** [comment]
The essentials command /whois already shows this with other information included.
It's not very spammy,  and why do we need a dedicated command for this? We could just have a solution to creative PvP overall (if that's what this is supposed to help with)

**Comment by Wild1145** [comment]
I think given this functionality already exists we do not need to create more work for ourselves by re-inventing the wheel.
