### ISSUE TITLE
TFM Not working when JAR is re-names

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#2120]
It has been reported that TFM failed to start if the JAR is re-named from totalfreedommod.jar so we need to look into why this is happening and if it is a recurring issue.

**Comment by Gusted** [comment]
dont rename 👍 :)

**Comment by ncurran02** [comment]
It seems to work for me with RigelMCMod.

**Comment by Wild1145** [comment]
I've just done some basic testing, and havent been able to replicate. Can anyone confirm if this issue is still happening and if so please provide a bit more information?

**Comment by Wild1145** [comment]
I have been unable to replicate the bug, and all functionality appears to be working as expected even when renamed.
