### ISSUE TITLE
Marcocorriero --> Developer Title

### ISSUE THREAD

**Issue by mandar-ghade** [TotalFreedom/TotalFreedomMod#2130]
Marcocorriero should be added as a Developer in the FUtils class.

(Refer to http://totalfreedom.boards.net/user/12918 and https://github.com/TotalFreedom/TotalFreedomMod/blob/devel/src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java)

**Comment by lemonsked** [comment]
No, as he is only a TF developer and not a TFM developer, he will not be added. 
Thanks for the suggestion :)
