### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ezAxeG** [TotalFreedom/TotalFreedomMod#2140]
I already have Git installed and it still says this

BUILD FAILURE
------------------------------------------------------------------------
Total time: 36.434s
Finished at: Sun Dec 24 17:12:23 ICT 2017
Final Memory: 12M/30M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project totalfreedom: Cannot get the branch information from the scm repository :
Exception while executing SCM command. Error while executing command. Error while executing process. Cannot run program "git" (in directory "C:\Users\xD\Documents\NetBeansProjects\TotalFreedomMod-TFM1.12-Alpha"): CreateProcess error=2, The system cannot find the file specified
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

What should i do with the Git?

**Comment by ItzLevvie** [comment]
@ezAxeG Are you sure you actually have Git installed?

This is how it should look like in your Control Panel

![image](https://user-images.githubusercontent.com/11600822/34326568-3f7b23b6-e8a8-11e7-89c1-5dfc3af15dd3.png)

**Comment by ezAxeG** [comment]
@ItzLevvie Okay, it's fixed.
