### ISSUE TITLE
./tptoggle can be used to toggle other peoples as well as yours

### ISSUE THREAD

**Issue by samennis1** [TotalFreedom/TotalFreedomMod#2145]
Hi, 

Not sure if this has been already discussed, but might aswell be sure;

Other players can do /tptoggle <name> and it will toggle that persons TP.

**Comment by aokod** [comment]
TF-Essentials.

**Comment by Mafrans** [comment]
/tptoggle is part of TF-Essentials and this problem should thus be posted there.
Other than that I believe as long as we can get a good bridge to TFM (which right now doesn't exist) it should be fairly simple to fix this problem.

**Comment by Gusted** [comment]
@Wild1145 Close this 

this issuesie is setted to TF-Essentials
