### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by Decyj145** [TotalFreedom/TotalFreedomMod#2149]
COMPILATION ERROR : 
-------------------------------------------------------------
me/totalfreedom/totalfreedommod/util/DepreciationAggregator.java:[18,38] incompatible types: java.util.HashSet<java.lang.Byte> cannot be converted to java.util.Set<org.bukkit.Material>
1 error
-------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 14.851s
Finished at: Wed Jan 10 16:07:25 GMT 2018
Final Memory: 33M/415M
------------------------------------------------------------------------
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project totalfreedom: Compilation failure
me/totalfreedom/totalfreedommod/util/DepreciationAggregator.java:[18,38] incompatible types: java.util.HashSet<java.lang.Byte> cannot be converted to java.util.Set<org.bukkit.Material>
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by lemonsked** [comment]
Which version of Spigot are you trying to compile with?

**Comment by Decyj145** [comment]
1.12

**Comment by lemonsked** [comment]
which branch?

**Comment by Decyj145** [comment]
@ItzLevvie Thanks, fixed.
