### ISSUE TITLE
Version 4.3 (Auto Admin)

### ISSUE THREAD

**Issue by hy3064** [TotalFreedom/TotalFreedomMod#2154]
Hello,

When i run freedom op ver 4.3 on spigot 1.8.3, everyone seems to be super admin?

When a new player joins it says "[Username] is a senior admin" and when they talk it has a [Super Admin] prefix in front?  Even though I never added them to the super admin list 

Proof:  https://gyazo.com/fcb4c658f5ee2fa97c5ce521c9e6f6a1
How can you fix?

**Comment by hy3064** [comment]
The problem has been solved

**Comment by Wild1145** [comment]
@hy3064 Can you elaborate on what the solution to the problem was in case other people get this in the future?

**Comment by ncurran02** [comment]
The solution was to remove an entry with the ip of 127.0.0.1
