### ISSUE TITLE
Person on same wifi network gets the same rank as me

### ISSUE THREAD

**Issue by iGaps** [TotalFreedom/TotalFreedomMod#2156]
Whenever there are people on my wifi network playing on the server it just adds them to the same rank as I am (Btw I am on TotalFreedomMod 1.12 pre release).

**Comment by Wild1145** [comment]
This is intended functionality as we match by IP if the server is in onlinemode = false. If you switch to onlinemode = true I think it should resolve the issue but it is intended functionality of TFM.

**Comment by iGaps** [comment]
It's happening with onlinemode = true

**Comment by Wild1145** [comment]
Matching by IP appears to be working on both the onlinemode = true / false in that case which is intended functionality. Only way to work around this would be to have two different home networks running but this is 100% intended functionality.

**Comment by aokod** [comment]
The best way to combat this is by utilising a VPN (virtual private network), considering this issue isn't unique to TFM.
