### ISSUE TITLE
NetBeans won't open latest TFM source files

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2160]
[messages.log](https://github.com/TotalFreedom/TotalFreedomMod/files/2005462/messages.log)
![error](https://user-images.githubusercontent.com/17501381/40064595-277487c6-5860-11e8-826d-31cdccbe54fc.PNG)
This never happened to me when i tried compiling TFM, it happens when i select the tfm folder from open project

**Comment by JeromSar** [comment]
This seems to me like a NetBeans issue, and not a TFM issue.
