### ISSUE TITLE
Error occurred while enabling TotalFreedomMod v5.2 (is it up to date?)

### ISSUE THREAD

**Issue by Creeperdude2409** [TotalFreedom/TotalFreedomMod#2177]
I have the plugins TF-Worldedit, Essentials-TF, Aero 2.0, and TFM installed on my server, and TFM appears when I do /pl, but there are no commands, and I also get this error: https://pastebin.com/XurnDUL0

In the error, I see that it mentions AeroPlugin a lot, so I think maybe I'm using the wrong Aero, and if I am, where can I find the download for the correct Aero?

Thanks,

~ Creeperdude2409
EDIT: The commands are working now

**Comment by JeromSar** [comment]
You might not have the latest (or correct) version of Aero installed. Make sure that your version of Aero has at least this class: `net/pravian/aero/command/handler/SimpleCommandHandler` having this method: `int loadFrom(java/lang/Package)`.

**Comment by Creeperdude2409** [comment]
> You might not have the latest (or correct) version of Aero installed. Make sure that your version of Aero has at least this class: `net/pravian/aero/command/handler/SimpleCommandHandler` having this method: `int loadFrom(java/lang/Package)`.

Oh, I don't have the latest Aero xD I got that one from the 1.10 one what was I thinking. Do you know a link to the 1.13.2 Aero? I can't seem to find it.

**Comment by ncurran02** [comment]
I have updated Aero to support 1.13.2 and made some modification to make it work - https://github.com/Focusvity/Aero although I don't recommend you to use it until the PR (https://github.com/Pravian/Aero/pull/14/) has been approved and merged.

**Comment by Creeperdude2409** [comment]
Okay I will use my netbeans to make it a jar file and try it with TFM

**Comment by Creeperdude2409** [comment]
Where can I find an Aero with the SimpleCommandHandler because I keep getting this error: https://pastebin.com/gwuKkLYB

**Comment by Creeperdude2409** [comment]
I keep getting this error: https://pastebin.com/6j0xjc6q

**Comment by Creeperdude2409** [comment]
Oh, now my TF WorldEdit's acting up. From the error, I am seeing a lot about craftbukkit. Is it a plugin or something?

**Comment by Creeperdude2409** [comment]
I reinstalled TFM and Aero and got these 7 errors: https://pastebin.com/X6uRLFV6

**Comment by ncurran02** [comment]
You need to get WorldEdit

**Comment by Creeperdude2409** [comment]
Oh right I forgot I needed that when I reinstalled TFM and Aero (I had it before I reinstalled the two)

**Comment by Creeperdude2409** [comment]
Okay, that seemed to fix it but I'm still getting these 6 other errors: https://pastebin.com/6j0xjc6q

**Comment by Creeperdude2409** [comment]
Okay I just got WorldEdit and the commands are working now
