### ISSUE TITLE
How do I add owners to the list

### ISSUE THREAD

**Issue by FruztalProjects** [TotalFreedom/TotalFreedomMod#2179]
I want access to all of the commands on my server but I can't use commands like "/ban"

**Comment by Wild1145** [comment]
@FruztalProjects You will need to still be added as an admin (saconfig add <username>) as the owner settings is nothing more than a title, it comes with no additional permissions. If you're in the owner list, added as an admin and use saconfig setrank to set yourself as a senior admin, you should have all the required permissions and show up as an owner.

**Comment by JeromSar** [comment]
@Wild1145 is correct. Let us know if you have any other questions.
