### ISSUE TITLE
serious issue

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/TotalFreedomMod#2182]
When u do /v and u are vanished u can just do /invis and it'll show who is in vanish and also u can just see particles

**Comment by ncurran02** [comment]
Wrong repo, please report it at https://github.com/TFPatches/TotalFreedomMod

**Comment by ghost** [comment]
ok

**Comment by Wild1145** [comment]
This is not functionality supported in TFM I'm afraid, I would suggest posting it on https://www.totalfreedom.boards.net and asking them to assist.
