### ISSUE TITLE
Command blocker not working

### ISSUE THREAD

**Issue by DragonSlayer2189** [TotalFreedom/TotalFreedomMod#2184]
For some reason, In the latest version of tfm, if you add arguments to blocked cmds it won’t be blocked

There’s a forum post about it from TotalFreedom 
https://totalfreedom.boards.net/thread/66156/tfms-command-blocker-marcod

**Comment by Wild1145** [comment]
@DragonSlayer2189  -  Could you confirm if that is running the latest TFM release from this repo or if that is the TF-Patches one?

**Comment by ncurran02** [comment]
@Wild1145 It’s for TFPatches

**Comment by Wild1145** [comment]
Perfect. In that case I'll close this and suggest the issue be raised on the TF patches repo.
