### ISSUE TITLE
TF doesn't work at all

### ISSUE THREAD

**Issue by godveno** [TotalFreedom/TotalFreedomMod#2186]
I want to get the newest version of TF (5.0.2) but it is not working 

*
![TotalFreedom](https://user-images.githubusercontent.com/80982209/111830561-75824e00-88ee-11eb-9ca5-cd887d248c9a.png)

What should I do?

**Comment by Wild1145** [comment]
The error there is that you're missing the "Aero" plugin which is a requirement for the original versions of TFM which are on this project. Aero can be found here - https://github.com/Pravian/Aero 

There are more up to date versions of TFM which can be found here - https://github.com/AtlasMediaGroup/TotalFreedomMod Which is what currently runs on TotalFreedom and supports newer Minecraft versions.

**Comment by JeromSar** [comment]
Talking about Aero, @Wild1145: is it still being used? Is the latest version recent enough?

**Comment by Wild1145** [comment]
@JeromSar It isn't any-more, the previous set of developers moved away from it some time ago if memory serves me right, the only TFM repo that still uses it is this one, the "TFPatches" and the one in the ATLAS Media Group Repo's don't use Aero at all.

**Comment by JeromSar** [comment]
Ah, got it. I hope your question is answered @godveno.
