### ISSUE TITLE
You need a plugin that cant be downloaded.

### ISSUE THREAD

**Issue by commandarmy** [TotalFreedom/TotalFreedomMod#2188]
Im right now running a test build of TFMod [for some new project ideas im making] And it says i need to have "Aero". But then when i try and get the "required" plugin it just wont download. You cant access the website to download it [it says its down]. Any help?

**Comment by commandarmy** [comment]
or any "aero" plugin downloads

**Comment by ghost** [comment]
try searching for an archived version of the webpage with archive.org

**Comment by Wild1145** [comment]
It's worth noting that this repo for TFM is no longer actively maintained, the version running on the TotalFreedom server is now https://github.com/AtlasMediaGroup/TotalFreedomMod which is actively maintained. 

If you do want to compile / play with this older version though, you can find Aero here: https://github.com/Pravian/Aero

**Comment by commandarmy** [comment]
thank you. closed
