### ISSUE TITLE
Tweak the tab colour system

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#236]
As http://www.totalfreedom.boards.net/thread/13634/color-thing-tab-button-imposters I will be adding in a yellow color in the tab screen for imposters and a bright yellow [IMPOSTER] prefix.

This is more here to remind me that I need to do it, so please dont just close it ;)

**Comment by JeromSar** [comment]
Closing due in favor of persistent tags: https://github.com/TotalFreedom/TotalFreedomMod/issues/236
