### ISSUE TITLE
Adding region information to WorldEdit commands shown in cmdspy

### ISSUE THREAD

**Issue by KingDragonRider** [TotalFreedom/TotalFreedomMod#240]
I think it would be a great feature if we could see the areas and dimensions of WorldEdit commands shown in command spy. This would really help when determining if a worldedit could be malicious.

![](https://www.screenshottr.us/v/acc64d2a88c565f4cf8ae2fa18efed3ac8c8eeb1/05156dbc60fa228fd98847c84b9c0ebb.png)

**Comment by Wild1145** [comment]
Superseded by #1840
