### ISSUE TITLE
Extra time difference parameter to certain commands.

### ISSUE THREAD

**Issue by KingDragonRider** [TotalFreedom/TotalFreedomMod#278]
For example (command suggested by aggelosQQ)
aggelosQQ: /stfu Random123 6m
aggelosQQ has muted Random123 for 6 minutes.

Some other commands which could have an extra <time> parameter (suggested by vj13573):
/blockcmd [player] [time]
/halt [player] [time]
/fr [player] [time]
/fr [time] - Temporarily freezes everyone (not sure how this one will work, since we need a way to determine if the numbers represent part of a player's name or the time difference)
/cage [player] [time]
/orbit [player] [power] [time]

Original thread: http://www.totalfreedom.boards.net/thread/14813/stfu-player-time

**Comment by JeromSar** [comment]
/fr and /blockcmd already reset after 5 minutes. For consistency, I don't think we should make this customizable by admins. Thanks for contributing.
