### ISSUE TITLE
/saconfig setmessage

### ISSUE THREAD

**Issue by StevenLawson** [TotalFreedom/TotalFreedomMod#286]
Mark wants a command to set admin login messages. I suggest something along the lines of:

`/saconfig setmessage <adminName> <message &cwith color &2codes>`

http://www.totalfreedom.boards.net/post/150190/thread

**Comment by DUFCLiam** [comment]
@Voidjasper It working?

**Comment by Wild1145** [comment]
I am going to go with the original person who was going to handle this is no longer doing so... I guess that makes it fair game for anyone that wants to take it on and open a respective PR

**Comment by LegendIsAwesomes** [comment]
@Wild1145 this has already been done, login messages in the superadmin.yml

**Comment by DUFCLiam** [comment]
No, @LegendIsAwesomes they mean like do

`/saconfig setmessage <message &cwith color &2codes>`

**Comment by Wild1145** [comment]
Exactly what @DUFCLiam has said, the superadmin.yml functionality has been there since this issue was created, however this would allow seniors to also amend the superadmin.yml file with the new login messages without the need for someone with FTP access to the server.

**Comment by Wild1145** [comment]
I am going to take over working on this I think. @JeromSar If you could assign this one to me that'd be great.

**Comment by DUFCLiam** [comment]
Good luck @Wild1145

**Comment by Wild1145** [comment]
This was added as part of /myadmin
