### ISSUE TITLE
glist ban reason parameter

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#288]
/glist ban name reason

This would be nice so the banned player can see why they got banned if they try to relog. gtfo already has this, so why not glist ban also?

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848

**Comment by DUFCLiam** [comment]
@JeromSar This is the original issue this is #288 and the duplicate is: #848

**Comment by JeromSar** [comment]
@DUFCLiam Corrected.

**Comment by DUFCLiam** [comment]
Thank you :) @JeromSar
