### ISSUE TITLE
Schematic Manager - Broken?

### ISSUE THREAD

**Issue by VjGamingUK** [TotalFreedom/TotalFreedomMod#299]
Is the Schematic Manager "Upload Section" http://tf.madgeekonline.com:28966/schematic/upload
link bugged? Whenever you try upload a schematic it'll say "Error uploading schematic" even if it's spelt right with the ".schematic" at the end.

**Comment by JeromSar** [comment]
@StevenLawson Could you take a look?

**Comment by Wild1145** [comment]
Can anyone confirm if this bug is still happening? I havent heard anything for some time that this has been an issue...

**Comment by aggelosQQ** [comment]
@Wild1145 Just uploaded a schematic and it seems to be working.
The file is called testschemAgg.schematic

**Comment by Wild1145** [comment]
In that case I will close this issue. If anyone can reproduce the issue in the future feel free to re-open it.
