### ISSUE TITLE
//copy //paste sand to crash server

### ISSUE THREAD

**Issue by Voidjasper** [TotalFreedom/TotalFreedomMod#308]
Players can copy a wide field of sand then paste it in the sky to create lag and crash the server. You can prevent this by using simar args that are used in a protected area but instead of if the selection contains a protected area it could be if the selected area contains material.sand

**Comment by JeromSar** [comment]
Sand should be blocked in TFM.

**Comment by Wild1145** [comment]
@JeromSar Is it blocked when coppy pasting? It never used to be I dont know if thats something you added recently?
