### ISSUE TITLE
Assign players to protected areas

### ISSUE THREAD

**Issue by Obi2** [TotalFreedom/TotalFreedomMod#331]
Protectarea is only really used for protecting spawnpoints as regular players cannot edit blocks in protected areas. It would be useful to be able to assign non-admins to protected areas so that individual buildings can be protected.

**Comment by JeromSar** [comment]
I was thinking we could give player a unique custom plot to build in somewhere in the flatlands world. They could control the permissions on their own plot and could always return home with a command. What do you think? @StevenLawson

**Comment by AlexFreedomMod** [comment]
I think that will be very cool

**Comment by Wild1145** [comment]
Against the idea of "Plots" because then you may as well go on a creative plots server.

**Comment by JeromSar** [comment]
Superseded by https://github.com/TotalFreedom/TotalFreedomMod/issues/981
