### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Windows-i7** [TotalFreedom/TotalFreedomMod#336]
In Contributing.md there is a typo: Features that have very similar alternatives **fill** not be added

**Comment by Wild1145** [comment]
@JeromSar Should this not be "Bug" instead of "Enhancement"?

**Comment by JeromSar** [comment]
@Wild1145 I only list items as "Bug" when they have a moderate to high impact to the game experience. In this case, a typo is only very minor.

**Comment by Wild1145** [comment]
@JeromSar To be fair this is not really an enhancement either...
