### ISSUE TITLE
Time to change the smite and GTFO to person instead of boy?

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#358]
- Girls be like "ooh I'm a boy"
- Others, "why can't it be person?"
 

_I think it's time?_

**Comment by JeromSar** [comment]
Nah, I don't think this needs to be implemented. The message was designed to be somewhat cynical and changing that would destroy its purpose.

**Comment by StevenLawson** [comment]
> somewhat cynical

Spot on.
