### ISSUE TITLE
Caching UUIDs is slow

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#373]
Caching UUIDs is slow and takes up a lot of memory.

This should probably be done through a MySQL-lite DB.

**Comment by JeromSar** [comment]
I need some feedback for https://github.com/TotalFreedom/TotalFreedomMod/commit/05e50cfc3382c8f59d2f69c930cfeee919ed8aef @StevenLawson @WickedGamingUK @Wild1145

**Comment by WickedGamingUK** [comment]
This is a good idea. I think moving a lot of data to a MySQL database is something that should be done as well.

**Comment by Wild1145** [comment]
Migrating to SQL should speed up the accessing of the data. The only possible issue that I thought of is if Mark wants to change anything, it may be harder to do so if there are going to be less configuration files...

**Comment by WickedGamingUK** [comment]
@Wild1145 It isn't too hard to access a database and change the variables as needed. Mark can use Sequel Pro, MySQL Workbench, etc. to manage the database.

**Comment by Wild1145** [comment]
@WickedGamingUK But why would he want to, when there are already incredibly easy to use YAML files. My point is that whatever is stored in SQL should be stuff that nobody will ever want or need to modify manually.

**Comment by WickedGamingUK** [comment]
@Wild1145 Really you should have as much information in one place as possible. I guess leaving configuration settings in a YAML file and move everything else to MySQL would be the best way forward.

**Comment by Wild1145** [comment]
@WickedGamingUK If all that you care about is speeding up the loading of data then yes, storing everything in SQL would be the best. If you want to keep it reasonably easy for Mark to make modifications, or to keep it relativity easy for other servers to be able to use it, you then should only be storing information that you will not be required to edit.

**Comment by JeromSar** [comment]
This change should avoid having to cache hundreds of player UUIDs at load time. The JDBC driver should keep UUID lookups less RAM intensive and thus this change should increase performance.

**Comment by JeromSar** [comment]
I need  code review and beta testers @WickedGamingUK @Wild1145 @StevenLawson

**Comment by WickedGamingUK** [comment]
Can I ask why you've opted to use SQLite instead of MySQL?

**Comment by JeromSar** [comment]
@WickedGamingUK Performance and less points of failure. :)

**Comment by WickedGamingUK** [comment]
@JeromSar Alright. From what I've seen the code is good, however you may want to look at https://github.com/VisionWare-Studios/JDBLib/blob/master/src/com/visionwarestudios/database/mysql/MySQL.java#L117 for simplifying using Prepared Statements, it works a treat :)

**Comment by WickedGamingUK** [comment]
Also I noticed you've mixed Allman and K&R in your code. May want to change that ;)

**Comment by StevenLawson** [comment]
@WickedGamingUK For what we're doing here, the overhead of running or connecting to a MySQL server would completely defeat the purpose of having this data stored in a relational database. SQLite is definitely the way to go.

@JeromSar I don't have time right now to read through this code, but I have done extensive work with SQLite and Java. I'll try to offer some input this coming weekend, and find you some samples of using prepared statements and other such things that have worked well for me in the past.

**Comment by JeromSar** [comment]
@WickedGamingUK That's some nice utilities class you have there, but it fails to use prepared statements properly. The concept of "prepared statements" is as follows: Prepared statements are prepared when the client connects to the database. Those individual statements could then be reused for speed and efficiency. Your code creates a new prepared statement every time the `query` method is called. Completely bypassing the benefits of reusing the prepared statement.

@StevenLawson Awesome, Thanks.

**Comment by WickedGamingUK** [comment]
@JeromSar I always thought the main concept of prepared statements was the improved security. I wasn't aware that you could reuse them.

**Comment by JeromSar** [comment]
Please continue discussion in https://github.com/TotalFreedom/TotalFreedomMod/pull/406
