### ISSUE TITLE
Update Nodepend

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#375]
Looking at #371 it might be worth updating the nodepend branch to be in sync with the master branch. I dont know if this was already planned or not, but its something that probably needs to be looked at, ideally before any re-writes?

**Comment by JeromSar** [comment]
Nodepend will be updated when Release 4.3 is published.

**Comment by Wild1145** [comment]
@JeromSar This probably should be done... Its quite a few versions behind. If needs be I can do it myself, but I wont do it if you either dont want it done yet or intend to do it yourself soon...

**Comment by JeromSar** [comment]
Updated nodepend: https://github.com/TotalFreedom/TotalFreedomMod/commit/8c8f9ada0dc1e091314f750e944e6d23b09dbf4f
