### ISSUE TITLE
Gadmin doesn't work with spoofed UUIDs

### ISSUE THREAD

**Issue by Obi2** [TotalFreedom/TotalFreedomMod#380]
Gadmin list doesn't correctly display spoofed UUIDs. As UUID hashes are the first 4 characters of a player's UUID, players that have a spoofed UUID have their hash displayed as "dead", and there can be multiple players online who all share that hash, rendering gadmin commands unusable on them.

**Comment by JeromSar** [comment]
@Obi2kanobi Interesting point, will look into. Thanks!
