### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by BestMcPlayers** [TotalFreedom/TotalFreedomMod#391]
Hi, I was thinking you should update the releases for people who can't or don't know who to code or compile things.

http://totalfreedom.boards.net/thread/18742/help-me-totalfreedommod-forums

**Comment by Wild1145** [comment]
Releases are updated when @JeromSar or @StevenLawson feel that a significant enough stage / change has been made. Granted it would make sense to do a release as it has been updated to 1.8 since the last release, I dont know if any hugely significant changes have actually been made...

**Comment by JeromSar** [comment]
The next release (4.3) will be made public when this milestone has all its issues resolved: https://github.com/TotalFreedom/TotalFreedomMod/milestones/Release%204.3
