### ISSUE TITLE
Admins can't bypass ban.

### ISSUE THREAD

**Issue by BigDaddyUS** [TotalFreedom/TotalFreedomMod#394]
Long story short, I don't know if a imposter came on, and got banned but for some reason I couldn't join. Admins are suppose to be able to bypass bans right? Luckily Lynx was on FreedomOp and unbanned me from console. He didn't have to super me because I was already a Super admin. It's a weird bug.

Fish out the logs you'll see what I mean.

**Comment by JeromSar** [comment]
@BestMcPlayers Was there any ban message? Any errors in console?

**Comment by Wild1145** [comment]
@JeromSar This sounds like it was a issue here on TF and as such if he did not have admin at the time he could not see telnet / access logs. If @BestMcPlayers can give a date and time then the logs can be pulled.

**Comment by BestMcPlayers** [comment]
I couldn't pull the logs fast enough because I'm only a Super admin. I was Super at the time. If I remember correct the logs said said "you're banned" (Madgeek's log viewer)as it would say to a usually OP. @JeromSar @wild1145. 

This happen about two or three days ago.

**Comment by BestMcPlayers** [comment]
I forgot to add, I didn't play around and ban myself or anything. I wasn't even banned so that's why I think it's the possibility of a imposter.

**Comment by BestMcPlayers** [comment]
@JeromSar
@wild1145

I had my hacked client on by accident and clicked a few buttons. I didn't bypass the nuker ban. I have logs this time.
[spoiler]
[13:27:18] [User Authenticator #61/INFO]: UUID of player BestMcPlayers is a9c2d8d2-f7a5-33db-a1a9-277d5e9dd50a

[13:27:18] [Server thread/INFO]: [TotalFreedomMod] Hostname: play.totalfreedom.me:28965

[13:27:18] [Server thread/INFO]: [TotalFreedomMod] Match Hostname: play.totalfreedom.me:28965

[13:27:18] [Server thread/INFO]: Disconnecting net.minecraft.util.com.mojang.authlib.GameProfile@22620e2e[id=a9c2d8d2-f7a5-33db-a1a9-277d5e9dd50a,name=BestMcPlayers,properties={},legacy=false] (/69.143.218.167:58451): You are temporarily banned from this server.

Appeal at http://totalfreedom.boards.net/

Reason: You are breaking blocks too fast. Nukers are not permitted on this server.

Your ban will be removed on 2015-01-14 at 13:28:09 GMT

[13:27:18] [Server thread/INFO]: net.minecraft.util.com.mojang.authlib.GameProfile@22620e2e[id=a9c2d8d2-f7a5-33db-a1a9-277d5e9dd50a,name=BestMcPlayers,properties={},legacy=false] (/69.143.218.167:58451) lost connection: You are temporarily banned from this server.

Appeal at http://totalfreedom.boards.net/

Reason: You are breaking blocks too fast. Nukers are not permitted on this server.

Your ban will be removed on 2015-01-14 at 13:28:09 GMT
[/spoiler]
http://imgur.com/ckLsjfb

**Comment by JeromSar** [comment]
Could you run the command _/uuid recalculate admin_ through console and then verify the error persists, @BestMcPlayers ?

**Comment by BestMcPlayers** [comment]
I can't, I'm only a Super admin. Would it work if I get a Senior to do it for me?

**Comment by JeromSar** [comment]
@BestMcPlayers  Yes. :)

**Comment by BestMcPlayers** [comment]
@JeromSar @Wild1145 

The error still persist, right now I'm banned for grief. I couldn't join the servers for hours and I'm still banned. Someone must have a close IP to me, but I'm suppose to bypass bans.

**Comment by JeromSar** [comment]
@BestMcPlayers Could you ensure that the TFM version running on the server is the latest?

**Comment by BestMcPlayers** [comment]
It's TotalFreedom, it's not my server. @JeromSar

**Comment by Robolawrence** [comment]
This happens to me too. I cannot login to telnet, I can't do senior commands via clanforge, and I can't login when the server is full, in adminmode, whitelisted (unless added), or my IP range is banned.

**Comment by JeromSar** [comment]
@Robolawrence Does this still happen after the latest update?

**Comment by Scuph** [comment]
@JeromSar No

**Comment by JeromSar** [comment]
I was asking @Robolawrence
