### ISSUE TITLE
ShadowDemon cannot bypass freeze... sometimes bans and full servers as well.

### ISSUE THREAD

**Issue by CrafterSmith12** [TotalFreedom/TotalFreedomMod#397]
![2015-01-09_16 44 01](https://cloud.githubusercontent.com/assets/5395698/5687841/ec1e4f40-981e-11e4-997d-8558d52d7076.png)

**Comment by Wild1145** [comment]
IP has probably changed...

**Comment by CrafterSmith12** [comment]
I froze all players to ban someone (while he was super) and he got frozen as well.

**Comment by Wild1145** [comment]
Then he was not actually added to SA... Its as simple as that...
