### ISSUE TITLE
Commands to be blocked

### ISSUE THREAD

**Issue by Robolawrence** [TotalFreedom/TotalFreedomMod#403]
IMO these aren't too extreme but can be real annoying when a lot of people know about them.

/defaultgamemode - Sets the default game mode that players spawn in. Obvious why this one should be blocked.
/difficulty - Sets the server difficulty. Only admins should be able to use this.
/playsound - plays any sound from the game to any person. Basically used for trolling, should only be available to seniors, if that.
/summon - Pretty self-explanatory, we have /mob
/seen - Should only be available to admins

Repost of my suggestion on the forums

**Comment by JeromSar** [comment]
@Robolawrence Covering each suggestion one by one:
/defaultgamemode - This should be an admin command, yes.
/difficulty - I don't see why this should be blocked.
/playsound - Should be limited to playing sounds just to your self, in my opinion.
/summon - This is actually a very useful and purposeful command for summoning non-mob entities. I don't think blocking this would be a very good idea.
/seen - Is very useful and won't be blocked. Currently, the IP isn't shown to non-admins.

**Comment by Robolawrence** [comment]
@JeromSar As per http://totalfreedom.boards.net/thread/21065/server-conduct-policy-players-admins, section 1, paragraph d among others, trolling really isn't allowed. It's part of what separates Total Freedom and Total Anarchy. Also for /seen I did test it just the other day and it still shows the IP to non-admins if the said player is offline.

**Comment by JeromSar** [comment]
@Robolawrence You're right. /playsound should be blocked too.

**Comment by JeromSar** [comment]
/playsound is blocked in TFM Electrum. /seen and /whois have been updated to hide the IP for non-superadmins. :)
