### ISSUE TITLE
Package doesn't exist

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TotalFreedomMod#408]
I tired to compile TotalFreedomMod using netbeans, When i uploaded all my resources to the library,
There is still few missing.
I got my TotalFreedomMod directly from git{https://github.com/TotalFreedom/TotalFreedomMod.git}

~~~In me.StevenLawson.TotalFreedomMod.Bridge/ TFM_WorldEditBridge
It states this
      -import com.sk89q.worldedit.world.World; {Package does not exist} Line 8
      - catch (IncompleteRegionException ex) {Remove catch cause} Line 160
~~~In me.StevenLawson.TotalFreedomMod.Listener/ TFM_TelnetListener
     -import me.StevenLawson.BukkitTelnet.api.TelnetRequestDataTagsEvent; {Package does not exist} Line 7
   



Am I still missing some resources? Pleases reply asap

**Comment by looperXD** [comment]
I also wanted to add Player Tags in PlayerListner, PlayerRanks, and few commands,
But those errors are kept getting in my way ;C

**Comment by Wild1145** [comment]
This means that you have not included the WorldEdit Dependency correctly. 

To build TFM properly I believe you need to build the no-depend branch, then build the custom world edit, then the normal TFM. 

You havent got WorldEdit or the custom telnet for that matter.

**Comment by looperXD** [comment]
I added WorldEdit 5.6.2 and the latest bukkit telnet already.

**Comment by looperXD** [comment]
So i have to build world edit first?

**Comment by Wild1145** [comment]
You require the custom world edit. So you will need to compile the TFM no depend branch, then compile the custom world edit, then using the custom world edit compile the latest TFM.

**Comment by looperXD** [comment]
What about the Telnet?
Ps: i got the WorldEdit fixed Thanks ;D

**Comment by Wild1145** [comment]
Im not sure about telnet to be honest, @StevenLawson or @JeromSar would be the ones to ask there, as they know more about that than I do.

**Comment by looperXD** [comment]
http://imgur.com/xoZ1spQ Here is an image in case you need it :smile:

**Comment by Wild1145** [comment]
@JeromSar Care to assign the question label please?

**Comment by Wild1145** [comment]
@JeromSar Bumping this issue.

**Comment by JeromSar** [comment]
@looperXD You'll have to use the TF WorldEdit here: https://github.com/TotalFreedom/worldedit

Because TF and WorldEdit are a cyclic dependency (they depend on eachother), you should compile the TFM nodepend branch first. Then use that to compile TF WorldEdit. Once you have TF WorldEdit, you can proceed to compile the regular TFM as before. :)

**Comment by WickedGamingUK** [comment]
@JeromSar Any chance of releasing compiled binaries of WorldEdit so developers don't need to go through this convoluted process?

**Comment by JeromSar** [comment]
@WickedGamingUK When the time is right corporal, when the time is right.

**Comment by looperXD** [comment]
Solved
