### ISSUE TITLE
Player Bypass Bans

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TotalFreedomMod#409]
Notch/ and player that used hacked client to log in as them, cannot be banned,
and yes, i removed all players from the Unbannable Players in config.yml
http://imgur.com/1fap86B
ps: its not just notch, all players can't not be banned, they just get kicked and join back

**Comment by Wild1145** [comment]
Any errors in the logs / console / on screen?

**Comment by looperXD** [comment]
Not a bug to TotalFreedomMod. Its a bug with my custom mod.

**Comment by JeromSar** [comment]
@looperXD Alright, closed.
