### ISSUE TITLE
Total Freedom Mod Neatbeans Editing/Bukkit Telnet Error

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TotalFreedomMod#410]
http://imgur.com/xoZ1spQ
I have already edited the TFM, but the Telnet comes up as an error, :cry:

**Comment by looperXD** [comment]
@StevenLawson  @JeromSar  Pleases help me, i crie everytim :cry:

**Comment by looperXD** [comment]
Here is what is in my TelnetListner
http://pastebin.com/qECY2nwZ

**Comment by ItzLevvie** [comment]
You will need the latest BukkitTelnet.

**Comment by looperXD** [comment]
Jar or Zip? Link me up plz :smile:

**Comment by ItzLevvie** [comment]
https://github.com/updatePackages/updatePackages/releases/download/v4.1/BukkitTelnet.jar

**Comment by looperXD** [comment]
Still the same error :cry:

**Comment by ItzLevvie** [comment]
You are using FreedomOPMod which you will have to ask one of the Developers to help you.

**Comment by BestMcPlayers** [comment]
You'll have to compile the latest Bukkit Telnet. The latest release doesn't work with development of Total Freedom Mod.

**Comment by TaoistMiner** [comment]
:/

**Comment by JeromSar** [comment]
@looperXD Please ensure you're compiling with the latest BukkitTelnet. That should resolve your error.  :)

**Comment by looperXD** [comment]
Solved
