### ISSUE TITLE
LegendFreedom

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#412]
http://www.mediafire.com/download/o9cdmxl62k4g4u2/LegendFreedom.jar is the download link
Its a plugin i made. It will add new commands like /support where it gives you support and gives you a link to totalfreedom.me ect. I will be adding more commands maybe daily or when i get bored (Basically everyday) @JeromSar  i think this is up to ya.

**Comment by Wild1145** [comment]
@LegendIsAwesomes Is the source on Github / Bitbucket / similar to view?

**Comment by Wild1145** [comment]
@LegendIsAwesomes Just downloaded it and it appears that you have not compiled the source correctly... Might want to check that.

**Comment by LegendIsAwesomes** [comment]
Oh okay, ill look now
Thanks for letting me know.

**Comment by LegendIsAwesomes** [comment]
Maybe my pc is running like a bagga crap i forgot

**Comment by LegendIsAwesomes** [comment]
@Wild1145 try http://www.mediafire.com/download/o9cdmxl62k4g4u2/LegendFreedom.jar and if its doesnt work i failed. (Im using eclipse if you have any tips ;).)

**Comment by Wild1145** [comment]
@LegendIsAwesomes Its downloading as a compressed zip file for me...

**Comment by Wild1145** [comment]
@JeromSar

**Comment by JeromSar** [comment]
@LegendIsAwesomes If you wish for a certain feature to be added to a server, it should be implemented within TFM and such a contribution should follow the contribution guidelines.

Thanks for the suggestion, however. :)

**Comment by Wild1145** [comment]
@JeromSar Does that mean all existing plugins should be being looked to be merged in to TFM?

**Comment by JeromSar** [comment]
@Wild1145 AcidFreedom will likely be reimplemented in TFM in the future. Other plugins like Essentials and WorldEdit won't be merged in for obvious reasons. :)
