### ISSUE TITLE
Anything regarding bukkit size doesn't work.

### ISSUE THREAD

**Issue by BestMcPlayers** [TotalFreedom/TotalFreedomMod#413]
Recently I've notice TotalFreedomMod has going through a lot of updates. After the big release everything regarding Bukkit size doesn't work. I don't think it's my side because I have tried compiling with Spigot, Craftbukkit and Bukkit 1.8. None of them fixed the problem. I might still be doing something wrong but I don't see the problem.

One exammple would be like this:    
onlineStats.append(ChatColor.BLUE).append("There are").append(ChatColor.RED).append(server.getOnlinePlayers().size());

Everything works but the .size part.

**Comment by Wild1145** [comment]
Netbeans didnt flag any errors when I did my initial update to 1.8 in an earlier commit... Are you using the latest built one?

**Comment by BestMcPlayers** [comment]
I'm sorry Wild. My mistakes, what happen was I had Bukkit 1.7 and 1.8 loaded up. Go ahead and close this. My bad.
