### ISSUE TITLE
Gamemode Aliases

### ISSUE THREAD

**Issue by Robolawrence** [TotalFreedom/TotalFreedomMod#414]
http://totalfreedom.boards.net/thread/6383/gamemode-switching-aliases

Found this post from a year ago and realized it hasn't been brought in yet. I'd still be up for it.

**Comment by Wild1145** [comment]
I asked about aliasing before, and I think @JeromSar and @StevenLawson are going more for a "One command" setup to make it very clear and remove any question of what commands alias other commands...

**Comment by JeromSar** [comment]
_/gmc_ and _/gms_ are short enough an can take a player as a parameter. :)
