### ISSUE TITLE
GTFO

### ISSUE THREAD

**Issue by TaoistMiner** [TotalFreedom/TotalFreedomMod#417]
GTFO doesn't work it says an internal error occured while attempting to perform this command

**Comment by JeromSar** [comment]
Could you possibly get the error from the console? @TaoistMiner

**Comment by ItzLevvie** [comment]
You'll need the latest WorldEdit @ https://github.com/TotalFreedom/WorldEdit

**Comment by looperXD** [comment]
You would need worlededit 5.6.2 not the latest, the 5.6.2 supports rollback and is the stable one

**Comment by Wild1145** [comment]
Make sure you use the worldedit from the tf github and no others

**Comment by xDestroyer217** [comment]
@TaoistMiner, is the command '/gtfo'  modified?

**Comment by JeromSar** [comment]
Closing as invalid, tried and tested on TF.
