### ISSUE TITLE
Text-based help command: i.e. /info

### ISSUE THREAD

**Issue by VjGamingUK** [TotalFreedom/TotalFreedomMod#423]
Idea of having a command to show players how to save their builds.
https://github.com/TotalFreedom/TotalFreedomMod/pull/424

**Comment by JeromSar** [comment]
@vj13573 While I like the idea, I think we should combine all of the text-based commands into a /info command. This way, more information  (e.g. About obtaining superadmin, map wipes, etc) could be combined into a single command. Perhaps these info topics could be stored in a configuration file. What are your thoughts, @vj13573 @StevenLawson ?

**Comment by Wild1145** [comment]
@JeromSar If memory serves me correctly, there is an issue about having one big config defined info command / similar somewhere...

**Comment by vj13573** [comment]
"/info" is a worldedit binding command, when executed, then when you right click it'll show the position ID.
Thats why to make its own command.
"/ai" is the same, because thats a text-based command even though its a AcidFreedom command.

**Comment by JeromSar** [comment]
@VjGamingUK Then use any other command name, or override it with TFM. :)

**Comment by JeromSar** [comment]
@Wild1145 I don't think there's an issue with large configs. `MemoryConfiguration` stores them efficiently in a Map. Essentials has a very large configuration and it doesn't show any problems either.

**Comment by Wild1145** [comment]
@JeromSar I am not saying there is anything wrong with having one big config. From my understanding the idea would be to have one (Or it built into the current config) that will allow you to configure multiple sub commands of the /info command.

**Comment by JeromSar** [comment]
@Wild1145 Yes correct.

@VjGamingUK Are you still considering implementing the issue?

**Comment by JeromSar** [comment]
This is actually a duplicate: https://github.com/TotalFreedom/TotalFreedomMod/issues/317
