### ISSUE TITLE
/whohas

### ISSUE THREAD

**Issue by ValenciaOrange** [TotalFreedom/TotalFreedomMod#427]
I know that /whohas checks who has {item} but how do I smite the players with /whohas?

**Comment by Wild1145** [comment]
By using /smite (player that shows up in the list)

Then telling them off. Simple

**Comment by JeromSar** [comment]
I think /whohas -s <item> would be a good idea.

**Comment by looperXD** [comment]
Agree,  when player has splash potion of invis and they are spamming pots on other players,  admin could just use /whohas (thepotid) -s them use /potion clearall

**Comment by JeromSar** [comment]
TFM already supports this, as it turns out: https://github.com/TotalFreedom/TotalFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_whohas.java#L26
