### ISSUE TITLE
Senior Chat

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#429]
So what about a senior chat so seniors can chat about a super admin they want a senior to watch if they are not online. The senior chat allows seniors to chat about super and telnet admins about there administrating and how well/not well they are doing here is a bit of the code. The command could be /p instead of /o

_[snip snip don't need implementation here]_

**Comment by Wild1145** [comment]
Pointless... It would be logged and shown in telnet, so telnets would see it, or supers would just look in logs. We have had it before on CJF and it was used just like current admin chat, spam, crap, sexual references, inappropriate links and just crap, no actual administrative conversations would be had in anything like this. 

The forums should be where these sorts of things are discussed.

**Comment by JeromSar** [comment]
Hey @LegendIsAwesomes 

In all honesty, I don't like the idea of Senior admins having a separate chat to discuss senior-level things for several reasons. Namely the following:
* Added confusion. _What chat am I in now?_ _Who online can see this chat?_ _How do I quickly toggle between chats?_
* Implementation problems. _What if I toggle both chat's on?_
* Ethnics problems. _Senior and super admins both have one role: Moderation of the server. Why should they have different chats?_
* Enforcement problems. See @Wild1145's point above.

All in all I don't think this is worth implementing, and results in too many problems if it is.

Sorry your suggestion didn't make it. Better luck next time!

Thanks for contributing!
