### ISSUE TITLE
Switch Permban to UUID

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#430]
I have just realized that in its current state, the permban list is rather in-effective. Simply because if you have a VPN or Dynamic IP, all you now need to do is change your name and then there is no more permbans for that player... 

This also should probably be done sooner rather than later to get damage control underway from people that will have thought of this already...

**Comment by zD12** [comment]
This isn't exactly essential, however, remains as extremely valuable and would be of high priority.  The issue then comes to..  How will administrators obtain the UDID?  We'd have to redesign the /seen command to include the UDID, as well with..  Would it be possible, similar to the bans.yml, to have:

- '245d2f30-61fb-4840-9cd3-298b3920f4a4:Cobrex:DarthSalamon:2-20-15:Reason'
- '{UDID}:{Offender}:{Whom submitted}:{Date}:{Reason}'

This would be the redesigning of the whole permbans, so..  For the new update?

**Comment by Wild1145** [comment]
The /seen command already checks previous name changes and tells you that, that part would not be a problem. Everything, including admin applications, should now be done through UUID's and UUID's should completely replace IGN for the most part. As for getting the UUID, you can use a website (and there are a lot of them) or even call the API directly: https://api.mojang.com/users/profiles/minecraft/wild1145 

Both works, but this really will be a critical issue in about 2 weeks when the risk of people joining that should have been permbanned will just be HUGE and really, not something that should be left alone.

**Comment by JeromSar** [comment]
We're actually switching back to username based now. UUIDs are very unreliable in a offline-mode server.
