### ISSUE TITLE
Worldedit Restrictions

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TotalFreedomMod#431]
How do I make it so some world edit blocks are disabled/forbidden? I know this is should to be under the TotalFreedom/WorldEdit but no one checks it there.
What i meant is Worldedit Restrictions on blocks. Like lava, bedrock.
Ex:
If I use a forbidden block, it would auto de-op be and broadcast that i tried to use it
looperXD tried to use : lava
You are now no longer OP
something like that

**Comment by Wild1145** [comment]
By using the worldedit under TotalFreedom/WorldEdit

**Comment by JeromSar** [comment]
I think this is a duplicate of https://github.com/TotalFreedom/worldedit/issues/6?
