### ISSUE TITLE
UUID history

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#432]
Continued discussion from http://totalfreedom.boards.net/thread/20070/use-mojang-api-tfm

**Comment by WickedGamingUK** [comment]
I've had good success with this class in my project for getting the history of UUIDs, you may want to take a look at it when you decide to implement it: https://github.com/TranxCraft/iTranxCraft/blob/master/src/main/java/com/wickedgaminguk/tranxcraft/util/FetcherUtils.java#L96

**Comment by Wild1145** [comment]
UUID is no longer in use for the server.
