### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#435]
I think it may be time to convert TotalFreedomMod to a Maven project. Using maven instead of Ant has several benefits, namely:
1. Unified build process. All builds are exactly equal, no matter what.
2. Better dependency management.
3. Standardisation of the build system

In short, I think using Maven will improve TFM's quality.

**Comment by WickedGamingUK** [comment]
I agree that using Maven would improve TFM. However how would you go about hosting all of the custom dependencies that the project has like WorldEdit and whatnot? Host a Maven repo on GitHub?
