### ISSUE TITLE
Delay Loading Protected Areas on Startup / Reload

### ISSUE THREAD

**Issue by Obi2** [TotalFreedom/TotalFreedomMod#438]
In particular, ```TFM_ProtectedArea.autoAddSpawnpoints()```. After a restart (flatlands wipe or map reset), spawn points are automatically protected before custom worlds such as flatlands are loaded.

**Comment by Wild1145** [comment]
Im not quite getting what your tying to say?? Is it that they are loaded prior to other worlds and thats a problem or they should be loaded before other worlds or what??

**Comment by Obi2kanobi** [comment]
Automatically protecting spawnpoints should be delayed or done after custom worlds such as flatlands are loaded, otherwise the flatlands and such won't have their spawnpoints protected.

**Comment by Wild1145** [comment]
From my understanding, the spawnpoints shouldnt be protected in the other worlds... It was not the original design anyway.

**Comment by Obi2kanobi** [comment]
Ah, okay. It's just a little annoying having to protect the spawnpoints again after the protected areas are purged.

**Comment by JeromSar** [comment]
I think that all spawnpoints should be prptected by default.

**Comment by Obi2kanobi** [comment]
This hasn't happened - after a map reset the flatlands' spawn point wasn't protected automatically, only the main world.

**Comment by JeromSar** [comment]
All fixed now. :)
