### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by BigDaddyUS** [TotalFreedom/TotalFreedomMod#440]
This doesn't happen all the time, but it's happening frequently. The log stick isn't picking up much data. A player was breaking blocks in front of my face with their hand and the log stick didn't pick up anything. I've notice it does this when the server is lagging. It doesn't even have to be lagging a lot.

That's just what I think, I'm not sure though. I apologize if this is already an issue.

**Comment by Wild1145** [comment]
Probably means someone reloaded, restarted or similar to the server. If not @JeromSar created Logstick and could explain if there is any other reasons why it would not be logging everything.

**Comment by JeromSar** [comment]
@BigDaddyUS The log stick's data is reset when the server restarts or reloads. Additionally, break/places by admins aren't logged at all. Does that fix your issues?
