### ISSUE TITLE
Block WorldEdit commands

### ISSUE THREAD

**Issue by Explosives** [TotalFreedom/TotalFreedomMod#492]
/br
/mask
/tool 

All of the commands used to do the sphere griefing. Very annoying and needs to be blocked.

**Comment by Nobody-11** [comment]
Agreed, it is really annoying, and needs to be blocked,

Seen someone did Sphere griefing.

**Comment by Windows-i7** [comment]
Dont forget about lrbuild

**Comment by JeromSar** [comment]
@Explosives Some commands like /lrbuild may be blocked, but /br and /tool have a proper usage which is not only used for griefing.
