### ISSUE TITLE
Forge Mod Loader workaround

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#493]
[01:37:18] [Server thread/INFO]: [TotalFreedomMod] Hostname: play.totalfreedom.meFML:28965]

Forge Mod Loader appends FML to the hostname in the log, which is  what prevents a player using at least certain versions FML from joining TotalFreedom.  I dont get how they are even managing to establish a connection though with the suffix. I would think that it would fail to resolve the domain with meFML.

Anyways, this is why some FML users are getting kicked for not joining with the correct IP/domain.

**Comment by JeromSar** [comment]
Oh, that explains it, thanks!

**Comment by Wild1145** [comment]
This explains a lot, as Forge were saying the code we have was doing what it should be, but to look at forges setup, Thanks for flagging this :)

**Comment by JeromSar** [comment]
@ChargedCreeper Regarding the hostname lookup. I think that hostnames are resolved as usual, but the player joins using the spoofed hostname with "FML" appended to flag the server that the player is using FML.

**Comment by Wild1145** [comment]
@JeromSar That looks to be correct. Meaning TFM goes "Wrong Hostname" and the person connecting gets that message, and is sat there tying to figure out what the hell just happened. I just applied a workaround to DCMod to handle this problem.

**Comment by WickedGamingUK** [comment]
Any update on this? I suppose checking if the hostname that the player is joining on starts with play.totalfreedom.me will be a sufficient solution to the problem.

**Comment by Wild1145** [comment]
@WickedGamingUK Or you can just add the FML bit to the end of it as an or statement if needs be, its how I patched the issue on DCmod.
