### ISSUE TITLE
1.8 Bypass Bans

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#495]
I tried to use the 1.8 version on one of my private servers and I got a guy on and tried to ban him but it didn't work. I think there is something seriously wrong with banning via UUID's or something that you may wanna check out.

**Comment by xDestroyer217** [comment]
Yes, but on TF, tempbans don't work and gadmin stuff doesn't work as well,
people just simply bypass.

**Comment by xDestroyer217** [comment]
This is still happening from today, just with less pepole. GTFO is sucessful on ban.

**Comment by Wild1145** [comment]
Please check you are using the correct version of Craftbukkit / Spigot, and if there are any errors that you post them here.

**Comment by JeromSar** [comment]
@xDestroyer217 @tylerhyperHD is this only occurring with /tban. If so, the bug is known and there's a working PR that'll fix this issue.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/499
