### ISSUE TITLE
Add IP Bans to /noob and /tban

### ISSUE THREAD

**Issue by looperXD** [TotalFreedom/TotalFreedomMod#499]
The Command /noob or /tban only bans players name for 5 minutes, or I think it is 5 mins.
Suggestion: Add 5 mins IP Ban to /noob 
Some Players that have hack client could login in as some other usernames. 
https://github.com/looperXD/TotalFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_tban.java
        TFM_BanManager.addIpBan(new TFM_Ban(playerIp, player.getName(), sender.getName(), TFM_Util.parseDateOffset("5m"), ChatColor.RED + "You have been temporarily banned for 5 minutes."));

**Comment by xDestroyer217** [comment]
You should of kinda made a PR and not a Issue. I'll do the PR if I can do it correctly :p
