### ISSUE TITLE
/findip Improvement

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#503]
I was thinking that instead of it getting an online player's IP, it gets that player's IPs (whole IP list) from their player-data file.

If there is an alternative already implemented, please state and close ;)

**Comment by xDestroyer217** [comment]
Hey hockey, from right now, I dont see there's an alt implemented, and I do like this to implement.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/437
