### ISSUE TITLE
Owner Prefix

### ISSUE THREAD

**Issue by XxSkydevil06xX** [TotalFreedom/TotalFreedomMod#504]
My Owner Prefix Does Not Show Instead Its Senior Admin Please Someone Fix This!

**Comment by zD12** [comment]
You're required to change the actual owners inside the config.yml, add your username and it'll override your senior tag with the owner tag.

**Comment by Nobody-11** [comment]
It actually in player listener

**Comment by JeromSar** [comment]
@XxSkydevil06xX Edit your config.yml and add your username to owner. :)

**Comment by Nobody-11** [comment]
Soz for late comment, go in TFM_PlayerListener.java and add
``` java
if (player.getName().equals("XxSkydevil06xX"))
        {
            player.setPlayerListName(ChatColor.BLUE + player.getName()); // Just list name Color
            TFM_PlayerData.getPlayerData(player).setTag("&8[&9Owner&8]");
        }

**Comment by JeromSar** [comment]
@Nobody-11 @Wild1145  Interesting, I just checked the code and it seems that the owner prefix isn't added by default, resulting in players listed as owners getting the SRA prefix. Should we turn this into a bug issue?

**Comment by Nobody-11** [comment]
Yeah, I have to agree with you @JeromSar

**Comment by Wild1145** [comment]
@JeromSar Well lets put it this way, I wouldnt call it an enhancement :P

**Comment by XxSkydevil06xX** [comment]
Is This FIX Now
