### ISSUE TITLE
Add limit to/block //regen and //cut

### ISSUE THREAD

**Issue by Explosives** [TotalFreedom/TotalFreedomMod#511]
This is mainly a flatlands server, so //regen is nothing but a griefing tool that can bypass limits. We don't need to block //cut but it desperately needs a limit. Could we block //regen altogether or just implement limits into the command?

**Comment by Explosives** [comment]
Oops, forgot to put this in worldedit section. Could this be moved please?

**Comment by Wild1145** [comment]
You would need to re-create the entire issue on the WorldEdit Github, issues cannot be moved (I think)

**Comment by JeromSar** [comment]
@Explosives Will do for you. :)

**Comment by JeromSar** [comment]
https://github.com/TotalFreedom/TF-WorldEdit
