### ISSUE TITLE
Clear Minecarts and Boats

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#512]
I know that /rd will purge these, but TotalFreedomMod's automatic entity clearing does not, even when there is way too many entities. I am suggesting that when the entity count for the server exceeds a certain number, that the autoclear purges these entities too. This would make lag machines a lot less effective while still allowing players to ride minecarts and boats (as long as nobody spams them).

**Comment by zD12** [comment]
I disagree, Minecarts are used for traveling, as with boats are used for traveling, thus, only allow it to be purged past a certain amount of Minecarts.  I'd say 26 Minecarts would exclude the limitation, it wouldn't be laggy and it's extremely doubtful that 50 percent of the server.   Make sure we include all the types of Minecarts.

**Comment by Wild1145** [comment]
I think if we can do it as @zD12 said where they are purged after a set limit is reached this would work well. Obviously we do still have /rd as mentioned in the OP but this would be handy to keep entity spam down. Does something like 50 mine-carts / Boats sound somewhat reasonable as a limit?
