### ISSUE TITLE
1.8.3 API now here

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#519]
The craftbukkit api for 1.8.3 is now here:
http://tcpr.ca/files/craftbukkit/craftbukkit-1.8.3-R0.1-SNAPSHOT-latest.jar
Also the spigot one is here:
http://tcpr.ca/files/spigot/spigot-1.8.3-R0.1-SNAPSHOT-latest.jar

I don't know if we are planning anytime soon to upgrade, but we might as well soon.

**Comment by JeromSar** [comment]
@tylerhyperHD I've been working on updating all TFM plugins to CraftBukkit 1.8. Currently, only Essentials is left. Once that's done, we can start updating the plugins to 1.8.3.

P.S. We'll be obtaining Spigot from the (official sources)[http://spigotmc.org], not a shady URL. I suggest you do the same.

**Comment by Wild1145** [comment]
Obtaining Spigot from a reliable source is the best thing to do, either build it yourself, or know someone that builds it themselves and use theirs.

**Comment by tylerhyperHD** [comment]
Currently, all I see when I loaded 1.8.3 is a whitelist error in the server
interface, meaning the API is nearly identical to it.

**Comment by tylerhyperHD** [comment]
Also, clients that have 1.8.1 can still login to the server with this API.

**Comment by JeromSar** [comment]
@tylerhyperHD If you were to have _actually_ read https://spigotmc.org, you would have known there were no API breakages. And yes, bugfix version number changes are backwards and forwards compatible.

**Comment by JeromSar** [comment]
TF now compiles with Spigot 1.8.3 since https://github.com/TotalFreedom/TotalFreedomMod/commit/aacf37aa565617f05d79dc04537fdb7596428059
