### ISSUE TITLE
Update / Remove TFupdate

### ISSUE THREAD

**Issue by Wild1145** [TotalFreedom/TotalFreedomMod#520]
The TF Update command seems to have been somewhat neglected and forgotten. As all projects should now be on Github, I think it would be potentially worth updating it to get all the latest releases directly from github (As I believe there is a way to do that) or simply removing the command as its not often used on TF.

**Comment by xDestroyer217** [comment]
I prefer updating it than removing it, it can be a good use.

**Comment by Wild1145** [comment]
This has been removed as of one of the latest updates.
