### ISSUE TITLE
Colorful MOTD not working

### ISSUE THREAD

**Issue by ArcticHumboldt** [TotalFreedom/TotalFreedomMod#529]
The MOTD option provided by TFM isn't working.
![untitled](https://cloud.githubusercontent.com/assets/7342823/6954676/3a1201d8-d889-11e4-97c7-c491bf945955.png)
My config:

server:
  # You should change this to your server's name
  name: ArcticFreedom

  # The address your server is located at. Please do not include the port.
  address: afreedom.us.to

  # Shown at the server list
  motd: Arctic Freedom &8- Bukkit 1.8 & 1.7

  # Every word in the MOTD will be a different color unless prefixed by a color code
  colorful_motd: true

**Comment by FlexxPro** [comment]
I think it's a spigot issue from what I've heard

**Comment by Nobody-11** [comment]
Mines is working well. Perhaps the mods/forge. Otherwise, it may be spigot issue.

**Comment by JeromSar** [comment]
Jerom please remember to log out

:)

**Comment by ArcticHumboldt** [comment]
I'/m actually using Spigot, I just left Bukkit in there accidentally.

**Comment by Wild1145** [comment]
There should be no problems because its Spigot. By the looks of it it *could* be due to the fact you're mixing color codes and no color codes...

**Comment by ArcticHumboldt** [comment]
Can you explain a little further, @Wild1145

**Comment by Wild1145** [comment]
Never mind, I was talking crap. Im not too sure exactly why this isnt working. Are you getting any errors in console?

**Comment by ArcticHumboldt** [comment]
I'm not getting any that have to di\o with the MOTD, but I am getting this:
3:57:04 PM CONSOLE: ERROR]: Could not pass event ServerListPingEvent to TotalFreedomMod v4.4
3:57:05 PM CONSOLE: Source) [?:1.7.0_75]
3:57:05 PM CONSOLE: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/MinecraftServer
3:57:05 PM CONSOLE: Method) ~[?:1.7.0_75]
3:57:05 PM CONSOLE: Source) ~[?:1.7.0_75]
3:57:05 PM CONSOLE: Source) ~[?:1.7.0_75]
3:57:05 PM CONSOLE: Source) ~[?:1.7.0_75]
3:57:05 PM CONSOLE: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.MinecraftServer
(I believe it occurs when a user looks at their player list)
(Should I post this as an issue too?)
@Wild1145

**Comment by Wild1145** [comment]
That looks to be the error... You're running a different Spigot version than your TFM supports.

**Comment by ArcticHumboldt** [comment]
Do you know where I can get the right version? (I got the spigot from the BuildTools package, with Git Bash.) @Wild1145

**Comment by Wild1145** [comment]
The best thing I think would be to update the NMS versions in TFM

**Comment by JeromSar** [comment]
@ArcticHumboldt Follow the instructions at http://spigotmc.org, you should be able to get it just fine. :) Good luck!

**Comment by XxSkydevil06xX** [comment]
My Colorful MOTD Don't Work To .-.

**Comment by ArcticHumboldt** [comment]
@XxSkydevil06xX Message me, maybe I can help.

**Comment by Wild1145** [comment]
@XxSkydevil06xX This is probably the same with a load of other things. MC 1.8.0 is buggy as hell. Use 1.8.1 or later

**Comment by XxSkydevil06xX** [comment]
No My Error That The Colorful Motd Is Still The Minecraft Default Motd
