### ISSUE TITLE
Some errors (NPE in online-mode)

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#530]
:[22:55:29 INFO]: Disconnecting /105.155.139.73:56281: Failed to verify username!
:[22:55:29 WARN]: Exception in thread "User Authenticator #316" 
:[22:55:29 WARN]: java.lang.NullPointerException
:[22:55:29 WARN]: 	at net.minecraft.server.v1_7_R4.ThreadPlayerLookupUUID.run(ThreadPlayerLookupUUID.java:61)
:[22:55:29 INFO]: /105.155.139.73:56281 lost connection: Failed to verify username!
:[22:55:30 INFO]: [PREPROCESS_COMMAND] AcidicCyanide(AcidicCyanide): /purgeall
:[22:55:30 INFO]: AcidicCyanide - Purging all player data
:[22:55:30 INFO]: net.minecraft.util.com.mojang.authlib.GameProfile@23536fb7[id=<null>,name=Y3ll0w_J4ck3t61,properties={},legacy=false] (/189.84.112.20:50363) lost connection: Internal Exception: net.minecraft.util.io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(31) + length(1) exceeds writerIndex(31): UnpooledHeapByteBuf(ridx: 31, widx: 31, cap: 31)
:[22:55:31 INFO]: net.minecraft.util.com.mojang.authlib.GameProfile@3acb697f[id=<null>,name=Y3ll0w_J4ck3t35,properties={},legacy=false] (/202.53.254.99:38228) lost connection: Internal Exception: net.minecraft.util.io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(31) + length(1) exceeds writerIndex(31): UnpooledHeapByteBuf(ridx: 31, widx: 31, cap: 31)
:[22:55:32 INFO]: [CONSOLE_COMMAND] PhantomOediv215: /list 
:[22:55:32 INFO]: net.minecraft.util.com.mojang.authlib.GameProfile@174aeae6[id=<null>,name=Y3ll0w_J4ck3t19,properties={},legacy=false] (/176.126.252.12:62963) lost connection: Internal Exception: net.minecraft.util.io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(31) + length(1) exceeds writerIndex(31): UnpooledHeapByteBuf(ridx: 31, widx: 31, cap: 31)

**Comment by Wild1145** [comment]
@ChargedCreeper Is this from TF or another server?

**Comment by ChargedCreeper** [comment]
TotalFreedom

**Comment by ChargedCreeper** [comment]
@Wild1145 TotalFreedom, I was on telnet when it happened.

**Comment by JeromSar** [comment]
This is not a TFM error, I believe
