### ISSUE TITLE
Lockdown

### ISSUE THREAD

**Issue by DaBoyTM** [TotalFreedom/TotalFreedomMod#532]
When i tried to join TF, it would kicked me out and i can't join... is this just a error or something (I have joined before).

**Comment by JeromSar** [comment]
Are there any errors in console? @DaBoyTM

**Comment by AlexFreedomMod** [comment]
@JeromSar, I think he was on TotalFreedom.

**Comment by DaBoyTM** [comment]
I meant on TotalFreedom

**Comment by JeromSar** [comment]
@DaBoyTM Are you admin on TF? Could you get anyone to check the console while you log in?

**Comment by DaBoyTM** [comment]
Yes, I am...

**Comment by JeromSar** [comment]
@DaBoyTM You're not helping here...

**Comment by DaBoyTM** [comment]
Oh Never mind...
