### ISSUE TITLE
omg we need bury

### ISSUE THREAD

**Issue by PacksGamingHD** [TotalFreedom/TotalFreedomMod#535]
/bury name teleports the victim to the bottom of the map, freezes and mutes them. If a non-admin uses the command, it buries themselves instead

i would write the code but i dont know a single thing about the new TFM and netbeans is being a bitch.

**Comment by DaBoyTM** [comment]
Bad Idea Bad Idea! OBJECTION! This can cause bad things to happen!

**Comment by PacksGamingHD** [comment]
@DaBoyTM how?

**Comment by DaBoyTM** [comment]
Well, it may be useless and this server may not getting new players...

**Comment by GotNoFriends** [comment]
It was part of Disdfreedom, I still have a copy of this if anyone wants it :P

**Comment by Wild1145** [comment]
From a server side perspective there would be no real performance damage that I can think of to add this in, the problem you are going to have is the same problem that you have with commands like /emf where admins abuse it, or use it inappropriately, ending up with players leaving the server and never returning. I am against this idea and think its an utter waste of development time and effort.

**Comment by TheRevalation** [comment]
@Wild1145 I agree, I wish /emf would be changed to /ep (english plz) and send the player a broadcast msg to speak english if possible.

**Comment by xDestroyer217** [comment]
@Scuph, this has been discussed many times, just stop trying to recommend it.
