### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#539]
I got the zip and imported the ZIP into my netbeans. 

I started to work on the mod and it had NO errors. When i compiled it the build was a success but when i added the .jar to the server it showed up in /pl but none of the commands worked like opall! (It didnt give a error message it said that the command didnt exist!) I recompiled and tried again still no luck and none of the commands (Except the ones i added) have been touched.

**Comment by Wild1145** [comment]
Compiling right now is a tad complex due to the way that different plugins are slightly out of sync with one another. Best to use releases really for now.

**Comment by JeromSar** [comment]
@LegendIsAwesomes Check your console. What are the errors there?

**Comment by LegendIsAwesomes** [comment]
@JeromSar I do not get a error its the default 'Unknown command use /help ' from default minecraft

**Comment by AlexFreedomMod** [comment]
Thats weird.

**Comment by TheRevalation** [comment]
Its not weird, Your packages or your lines have to be off, check your endings, your extensions, the actual coding.

**Comment by LegendIsAwesomes** [comment]
@TheRevalation  I have checked everything its all fine.

**Comment by xDestroyer217** [comment]
Must be the deps that has to be ran in mc..?

**Comment by JeromSar** [comment]
@xDestroyer217 What are talking about?

**Comment by JeromSar** [comment]
@LegendIsAwesomes I meant the errors at startup.

**Comment by xDestroyer217** [comment]
@JeromSar As in what he needs to run within his minecraft server ex. Essentials, Ess-Spawn, BarAPI (if needed as a dep)



Or you just need a plugin.yml if it isnt there.

**Comment by JeromSar** [comment]
@xDestroyer217 Netbeans should tell you what dependencies you need, if you haven't messed with the project files.

**Comment by Wild1145** [comment]
@JeromSar I think he means running those plugin based dependencies on the server its self. Theres no good running a plugin on a server with no dependencies.

**Comment by LegendIsAwesomes** [comment]
Close this please, It suddenly started working i might of had a plugin missing!

**Comment by Wild1145** [comment]
@LegendIsAwesomes Just click the close button under the comments box.
