### ISSUE TITLE
Custom Command Error: Cannot Load command

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#544]
Hello! 
I've recently compiled  the 1.8R01 of TFM.
I've Just copyed a /doom command over to  mine to test and it says
Command Error: cannot load command: Awesome
It Also Says This For /list.

On my Server i have spigot 1.8 R01 running.
I hope you can help me!

**Comment by JeromSar** [comment]
@PattyToTheWatty Are you compiling with Netbeans? Additionally, are you compiling with the right dependencies (spigot-server 1.8). Lastly, are there any startup errors?

**Comment by Wild1145** [comment]
Also worth checking that you're running the same version of Spigot both to compile the plugin and run it. As over the different versions they have made some changes to the way that it works.

**Comment by PattyToTheWatty** [comment]
Oh! i did'nt run it as spigot-server 1.8 if i do that it might fix the problem.

**Comment by PattyToTheWatty** [comment]
I'm getting errors in netbeans:
import net.minecraft.server.v1_8_R1.MinecraftServer;
import net.minecraft.server.v1_8_R1.PropertyManager;

Im getting errors in the net

**Comment by Wild1145** [comment]
Are you running the latest version of spigot? Because 1.8.3 spigot is R2 not R1

**Comment by PattyToTheWatty** [comment]
Yes i am. I think im running spigot 1.8 R01 from yives mirror

**Comment by Wild1145** [comment]
Download http://gaming.superior-networks.com/jars/Spigot/Spigot-Server/target/spigot-1.8.3-R0.1-SNAPSHOT.jar and use that. Then change it from R1 to R2.

**Comment by PattyToTheWatty** [comment]
Ok Thank you!

**Comment by PattyToTheWatty** [comment]
then do i compile it to my tfm?

**Comment by Wild1145** [comment]
@PattyToTheWatty You will need to use that jar for both. To compile the plugin, and run it on the server. Once you do that you should have no further problems :)

**Comment by PattyToTheWatty** [comment]
Okai!

**Comment by PattyToTheWatty** [comment]
Im on the road again!
Thank you very very much!

**Comment by Wild1145** [comment]
No problem, glad to have been able to help :)

**Comment by PattyToTheWatty** [comment]
Wait nevermind. It still gives me errors...

**Comment by AlexFreedomMod** [comment]
Hmmm

**Comment by Wild1145** [comment]
@AlexFreedomMod Please dont comment if its only going to be hmmm and serve no productive value.

@PattyToTheWatty Can you check the console when you execute the command and send through any errors (Upload the errors to pastebin and link is)
