### ISSUE TITLE
/croncmd

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#546]
Basically the idea is a command that would schedule a command to be executed after a specified amount of time (so like croncmd 2m wipeflatlands would do a delayed wipeflatlands). Permission for it should probably be restricted to Sr or something.

**Comment by Wild1145** [comment]
Not so keen on this for a few reasons:

1) Logistically, all you need to really do is reload the server and its all reset
2) Practically, I dont feel there would be a major need for this
3) Realistically, we already should have something like this in Clanforge that Mark could enable if he should so desire.

**Comment by JeromSar** [comment]
I think @Wild1145 is right here. If we wanted to make a delay, it should be per-command.
