### ISSUE TITLE
1.8 - Tab color issues

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#547]
Today, when i was on totalfreedom i looked in tab to see how many admins were on then i saw no one but then a admin said something.. So then i did /who -a and it said there were 2 admins online. Then i looked at tab again and saw no Colored name in tab.

**Comment by AlexFreedomMod** [comment]
And when i joined mineplex, and then joined totalfreedom... The tab didnt update

**Comment by DaBoyTM** [comment]
It's just a bug on 1.8 version, what version are you using? 1.8, 1.8.1, 1.8.2, 1.8.3?

**Comment by AlexFreedomMod** [comment]
1.8

**Comment by DaBoyTM** [comment]
Yeah, I would use 1.8.3 as they solved the bug issues out... if that didn't work, please let me know!

**Comment by Wild1145** [comment]
From my own testing, there is no such issue on any 1.8 versions.

This only happens when an admin logs in as an imposer because tab will not automatically update. Thats the only "Bug" but if an issue is raised it really would come under enhancement as well.

**Comment by DaBoyTM** [comment]
@Wild1145 1.8 does not update tab name on every cracked servers after joining a public server. That a problem...

**Comment by Wild1145** [comment]
@DaBoyTM I dont test on Cracked servers, there should be no issues with the way that tab is set.

**Comment by JeromSar** [comment]
@DaBoyTM This is a known Spigot 1.8 issue (see [here](http://www.spigotmc.org/threads/1-8-1-tab-colors.36232/)). Update to a new Spigot version to fix this. :)

**Comment by AlexFreedomMod** [comment]
I was on totalfreedom.........

**Comment by JeromSar** [comment]
@AlexFreedomMod My bad, I meant to say: MC-1.8 issue. Update your MC to fix it. :)

**Comment by AlexFreedomMod** [comment]
Oh

**Comment by Wild1145** [comment]
1.8.0 is a very buggy releases. Signs also do not work properly there. You should not really run anything under 1.8.1

**Comment by AlexFreedomMod** [comment]
Ok, @Wild1145
