### ISSUE TITLE
Why dont we have a pvp world

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#548]
I think there should be a pvp world, it would be useful for the people who want to PVP, they could go there and there would be other people. Instead of them just spamming chat asking for someone to pvp with them

**Comment by TheRevalation** [comment]
It would be the same thing, it would just make an area of PvP, and we all know trolls will go there to make problems.

**Comment by DaBoyTM** [comment]
Yeah nah... People can grief there without anyone noticing it, and also what about the new ops? they would never know!

**Comment by AlexFreedomMod** [comment]
Oh.

**Comment by Wild1145** [comment]
Not really worth it...

**Comment by StevenLawson** [comment]
There are plenty of servers geared toward PVP. I suggest you use one of those, and just accept that there is going to be too much chaos on TF for structured PVP to ever be possible. Sorry :P
