### ISSUE TITLE
onTelnetRequestDataTags(TelnetRequestDataTagsEvent error

### ISSUE THREAD

**Issue by ArcticHumboldt** [TotalFreedom/TotalFreedomMod#551]
I have no idea how to fix this:

    @EventHandler(priority = EventPriority.NORMAL)
    public void onTelnetRequestDataTags(TelnetRequestDataTagsEvent event)
    {
        final Iterator<Map.Entry<Player, Map<String, Object>>> it = event.getDataTags().entrySet().iterator();
        while (it.hasNext())
        {
            final Map.Entry<Player, Map<String, Object>> entry = it.next();
            final Player player = entry.getKey();
            final Map<String, Object> playerTags = entry.getValue();

            boolean isAdmin = false;
            boolean isTelnetAdmin = false;
            boolean isSeniorAdmin = false;

            final TFM_Admin admin = TFM_AdminList.getEntry(player);
            if (admin != null)
            {
                boolean isActivated = admin.isActivated();

                isAdmin = isActivated;
                isTelnetAdmin = isActivated && admin.isTelnetAdmin();
                isSeniorAdmin = isActivated && admin.isSeniorAdmin();
            }

            playerTags.put("tfm.admin.isAdmin", isAdmin);
            playerTags.put("tfm.admin.isTelnetAdmin", isTelnetAdmin);
            playerTags.put("tfm.admin.isSeniorAdmin", isSeniorAdmin);

            playerTags.put("tfm.playerdata.getTag", TFM_PlayerData.getPlayerData(player).getTag());

            playerTags.put("tfm.essentialsBridge.getNickname", TFM_EssentialsBridge.getNickname(player.getName()));
        }
    }

There is an error on the "    public void onTelnetRequestDataTags(TelnetRequestDataTagsEvent event)" line.

**Comment by JeromSar** [comment]
You need to include the latest version of BukkitTelnet to the compile classpath. TFM already has this by default if compiling with Netbeans.

**Comment by ArcticHumboldt** [comment]
@JeromSar, ah, I hate NetBeans. All I did to fix it, was recompile BukkitTelnet, and use that.
