### ISSUE TITLE
Telporting issues.

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#560]
i think /tpo and /tpohere should be blocked from ops due to Operators telporting to admins or ops tpoing other ops to them.
Also ./tptoggle should not allow others to disable someone's tptoggle, only admins should be able to do that

**Comment by AlexFreedomMod** [comment]
:package: <--- contains 10530 commits after i found out there is /dtpohere and /btpohere, /ctpohere... etc

**Comment by Wild1145** [comment]
Essentials plz

**Comment by AlexFreedomMod** [comment]
Well... People use /tpo and /tpohere for..... Telporting people in th void, Telporting to admins without their permission, you know

**Comment by AlexFreedomMod** [comment]
Closing for being inactive.

**Comment by JeromSar** [comment]
@AlexFreedomMod Issues are never inactive. Only PRs are inactive when they don't get updated as requested.

**Comment by Wild1145** [comment]
This issue has been superseded by #713
