### ISSUE TITLE
Simply just colors

### ISSUE THREAD

**Issue by TheRevalation** [TotalFreedom/TotalFreedomMod#564]
Whenever an admin runs a command, its either aqua and red, OPs commands mostly aqua, I'm thinking changing the colors? Just a small thing, we just had these for so long, just a little cosmetic change, I know exactly where to do it.

**Comment by Wild1145** [comment]
Dont really see a productive point... They are like that based on the type of command thats being executed normally, and I think its just going to cause more confusion to change than not.

**Comment by TheRevalation** [comment]
@Wild1145 Its just changing the ChatColor in the UTIL, maybe &e(Yellow) and &6(Gold) or something, @JeromSar's decision to choose, he made this an enhancement.

**Comment by Wild1145** [comment]
@TheRevalation I am aware that its simple, All I am saying is that its pointless and will lead to confusion. You dont need to fix whats not broken when theres about 100 other open issues that need attention more.

**Comment by TheRevalation** [comment]
@Wild1145 Issues don't just have to be important, this can be labeled with low priority or not important, but jerom made it an enhancement, which means he agrees it's time for a cosmetic change, read my comment on the PR for more.

**Comment by Wild1145** [comment]
@TheRevalation If you care to read my comment, it has not been given the "Issue: Accepted", meaning that all that has happened is it has been put into the category of enhancements instead of bugs or anything else.

**Comment by TheRevalation** [comment]
@Wild1145 I get it, but if he agreed with you, he would have put Issue: Invalid, which means he doesn't entirely agree with me, just a little.

**Comment by Wild1145** [comment]
@TheRevalation An invalid issue is for an issue that it invalid. This is a suggestion and thus an enhancement. It is a fully valid request, but does not automatically mean it will be approved. I could suggest we block the /op command, it would be an enhancement and probably not even invalid, whereas if I reported a bug that was not a bug, it would be invalid.

**Comment by TheRevalation** [comment]
@Wild1145 I now see where you are coming from, but as for the point of this, I think this is worth a shot.

**Comment by Wild1145** [comment]
@TheRevalation Its easy enough to do (as you did in the PR), I just think its going to be more confusing, and there is no point fixing what is not broken.

**Comment by TheRevalation** [comment]
@Wild1145 I already said, issues don't have to be something that's broken, It's a cosmetic change, which can be cool, and fun, if it's confusing, fix the confusing parts, while leaving the color changes.

**Comment by Wild1145** [comment]
@TheRevalation But its not "cool" or "Fun". Thats my point. The color change is the confusing part along with the issues I flagged as line notes in the PR. There is no use, benefit or bonus to us changing the chat colors, other than to confuse the players used to aqua and red.

**Comment by TheRevalation** [comment]
@Wild1145 A simple two bound color change won't confuse anybody.

**Comment by Wild1145** [comment]
@TheRevalation What makes you think that? Most of us (That have been playing the server for any length of time) are used to red notifications and aqua notifications for nearly everything. Suddenly changing that will just cause confusion.

**Comment by TheRevalation** [comment]
@Wild1145 I've been here since 2012, I haven't payed any attention to the colors, and if you think it will  cause confusion, and I think it won't, isn't that an even better reason to test our theories?

**Comment by Wild1145** [comment]
@TheRevalation There probably is not any easier way to test this. As far as I am concerned, its a pointless change that will do nothing but confuse people. If people do not pay attention to the colors as you have said, then why bother wasting a commit to change them then? But I see it as something to cause additional confusion, and really do nothing to help the server in any way shape or form.

**Comment by TheRevalation** [comment]
@Wild1145 I think that we both have valid points, and we should leave it up to Jerom.

**Comment by xDestroyer217** [comment]
Since it is kinda pointless, I do go with Wild on this one. It will cause confusion, I bet ya.

**Comment by AlexFreedomMod** [comment]
@xDestroyer217, i have to agree with you too, Changing the colors will just cause confusion.

**Comment by JeromSar** [comment]
I don't think we really need to change the color scheme at the moment. It is merely a cosmetic change, and isn't really needed to improve TFM as it is.
