### ISSUE TITLE
Allow colons in command parameters.

### ISSUE THREAD

**Issue by ArcticHumboldt** [TotalFreedom/TotalFreedomMod#575]
Hi. TFM is not allowing users to do some WE operations, because they have ":" (colon) in them. Is there a way to disable this?

**Comment by DaBoyTM** [comment]
Do you mean enabling it?

**Comment by ArcticHumboldt** [comment]
Sorry, yes.

**Comment by JeromSar** [comment]
@ArcticHumboldt Currently, they're disabled in code (hardcoded). What operations are disabled exactly?

**Comment by ArcticHumboldt** [comment]
Plugins, such as worldedit, that make use of item and block ID's. Worldedit, for example. I could make a sphere of diorite, by doing //sphere 1:3 5. But, TFM would block the ":"

**Comment by JeromSar** [comment]
Ah yes, TFM should only be blocking colons in the actual command, not the parameters. Will fix.

**Comment by ArcticHumboldt** [comment]
Thanks!

**Comment by JeromSar** [comment]
This is more of a bug, actually. :)

**Comment by JeromSar** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/commit/42266c37eafc11115616e1ce9905c6f9c53cf176 Github is glitching auto-closes for some reason.
