### ISSUE TITLE
Cannot Load Command: Sapling

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#576]
Im Currently Gettings errors In my console Because of my Commands. Whenever i try to Run my command in console. It gives me this:

26.04 00:39:22 [Server] INFO Command Error! Could not load command: Sapling
26.04 00:39:22 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
26.04 00:39:22 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandLoader$TFM_DynamicCommand.execute(TFM_CommandLoader.java:307) [TotalFreedomMod.jar:?]
26.04 00:39:22 [Server] INFO at me.StevenLawson.TotalFreedomMod.TotalFreedomMod.onCommand(TotalFreedomMod.java:213) [TotalFreedomMod.jar:?]
26.04 00:39:22 [Server] INFO at me.StevenLawson.TotalFreedomMod.Commands.TFM_CommandHandler.handleCommand(TFM_CommandHandler.java:47) [TotalFreedomMod.jar:?]
26.04 00:39:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
26.04 00:39:22 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_72]
26.04 00:39:22 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot18.jar:git-Spigot-c3c767f-33d5de3]
26.04 00:39:22 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_72]
26.04 00:39:22 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
26.04 00:39:22 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
26.04 00:39:22 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_72]
26.04 00:39:22 [Server] INFO java.lang.ClassNotFoundException: me.StevenLawson.TotalFreedomMod.Commands.Command_sapling
26.04 00:39:22 [Server] ERROR null
26.04 00:39:22 [Server] ERROR Could not load command: Sapling

**Comment by PattyToTheWatty** [comment]
i have spigot1.8 essentials 1.8 worldedit 6.0 bukkittelnet 

Tell me what im doing wrong please!

**Comment by Wild1145** [comment]
>26.04 00:39:22 [Server] INFO java.lang.ClassNotFoundException: me.StevenLawson.TotalFreedomMod.Commands.Command_sapling

It cant find the classfile. Whats the name of the file you have?

**Comment by JeromSar** [comment]
Is /sapling even a TFM command?
@PattyToTheWatty Did you modify TFM at all?

**Comment by AlexFreedomMod** [comment]
I'm pretty sure it's not a TFM command

**Comment by PattyToTheWatty** [comment]
Well, no. I was following tylers tutoral on how to make commands.

**Comment by JeromSar** [comment]
@PattyToTheWatty In that case, you created the command wrongly, and TFM couldn't find it. Try studying other commands and see how they work. :)

**Comment by PattyToTheWatty** [comment]
Ok, Sure. Also when i make ranks in tfm i go into tfm_playerrank blah blah blah i add my name to the util i think, i build it put it on my server... AND.. It doesnt work, Again, i followed hockeys tutorial

**Comment by JeromSar** [comment]
@PattyToTheWatty You're making no sense. Please describe your problems in more detail. I can't help you with just _blah blah blah_.

**Comment by TheRevalation** [comment]
@PattyToTheWatty Learn basic java before trying anything

**Comment by PattyToTheWatty** [comment]
Aw, So what do you mean. Wait intill i know java. Or quit coding? Im fine with quiting

Atleast i tried

**Comment by JeromSar** [comment]
@PattyToTheWatty Try following some Java Tutorials.
I suggest starting with TheNewBoston's beginner java tutorials on YouTube. :)

**Comment by PattyToTheWatty** [comment]
Ok sure! That helped me alot thnx
