### ISSUE TITLE
Spectator mode command (for 1.8 update)

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#579]
Since there is a /survival, /creative, etc commands, I think it would be logical to have one for spectator also for when TFM is 1.8-ready.

http://totalfreedom.boards.net/post/246979/thread

**Comment by Wild1145** [comment]
Probably also worth having it admin only. That way it should act like a really good vanish I think, as only other people in GM3 can see where other GM3 players are.

**Comment by AlexFreedomMod** [comment]
@Wild1145 you are right, that would be useful for admins instead of using invis potions

**Comment by JeromSar** [comment]
Migrated to https://github.com/TotalFreedom/TotalFreedomMod/issues/856
