### ISSUE TITLE
IPs can be seen on whois.

### ISSUE THREAD

**Issue by Scuph** [TotalFreedom/TotalFreedomMod#583]
We have it so OPs can't see IPs on /seen, but they can on /whois, So....

**Comment by ChargedCreeper** [comment]
Ops can see it on /seen too if the player is offline.

**Comment by TheRevalation** [comment]
Well then fix it, the last thing we'd want is players blaming us for Distributed Denial of Service.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/583

**Comment by Scuph** [comment]
@JeromSar this is a duplicate of itself?

**Comment by JeromSar** [comment]
Sorry, my bad, this has been fixed in: https://github.com/TotalFreedom/TF-Essentials/commit/7068cfb84695b54bd04f4b4686855cf6566152e7
