### ISSUE TITLE
Command blocker is broken.

### ISSUE THREAD

**Issue by ImALuckyGuy** [TotalFreedom/TotalFreedomMod#586]
I just tested TFM and it appears the command blocker does not work, and no errors are logged in console. Any ideas?

**Comment by TheRevalation** [comment]
I think that's just 1.8 being stupid

**Comment by tylerhyperHD** [comment]
I tested this out too and it is confirmed.

**Comment by Wild1145** [comment]
Which version of Spigot?

**Comment by ImALuckyGuy** [comment]
1.7 and 1.8. Neither work.

**Comment by tylerhyperHD** [comment]
Well I found reverting it from a previous commit did the trick and solved the problem.

**Comment by JeromSar** [comment]
Confirmed. Fixing soon.
