### ISSUE TITLE
Explosions Working with 1.8

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#587]
So I have a custom command that I use that is supposed to "blowup" the player on my server. But when I used it in 1.8, it actually blows up the area around it, meaning explosions are working for some odd reason.

**Comment by Scuph** [comment]
It seems 1.8 is breaking everything, so just support the 1.8 version, don't use it. Wait until TFM is 1.8 Ready.

**Comment by tylerhyperHD** [comment]
I am using the 1.8 version cause I am trying to remove all the bugs and help you guys, otherwise I wouldn't be on this version if I wasn't debugging it.

**Comment by JeromSar** [comment]
Fixed in the latest Essentials: https://github.com/TotalFreedom/TF-Essentials/commit/7068cfb84695b54bd04f4b4686855cf6566152e7
