### ISSUE TITLE
CommandSpy highlighting

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#596]
Wild had a great idea here: https://github.com/Superior-Development/IcarusMod/issues/26

**Comment by Scuph** [comment]
I like it!


@JeromSar What will be highlighted in our mod?

**Comment by JeromSar** [comment]
How about commands like /stop and /reload?

**Comment by Scuph** [comment]
@JeromSar the point of that? They auto eject anyway.

**Comment by Scuph** [comment]
I'm thinking worldedit commands, /bigtree, /tpo, etc.

**Comment by ArcticHumboldt** [comment]
That would be useful. It should also highlight the player, or command, which could be configurable.

**Comment by Wild1145** [comment]
Superseded by #1830
