### ISSUE TITLE
<unrecongnized project; missing plug-in?>

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#600]
When i was trying to import TotalFreedomMod into my netbeans IDE 8.0.2, Then i hit the open project Button then the project name said "<unrecongnized project; missing plug-in?>" I don't know why Could you help me? . I also tryed going to Team>Git>Clone and after i cloned it in it said "Do you want to create an IDE project from the cloned sources? [Button ] Open Sources in favorites  [Create Project Button] [Close Button] So then i hit "Create Project" Then a window came (of course)  it looked like the picture below
![nb](https://cloud.githubusercontent.com/assets/8379108/7574267/e32c2ca0-f7e0-11e4-8ddd-838d9929f305.png) So then i put tryed to put something in the Description but i couldn't it didnt let me.
And i hit help but it wasn't very helpful

**Comment by xDestroyer217** [comment]
Delete the Folder from NetBeansProjects in My Documents, then clone again.

**Comment by AlexFreedomMod** [comment]
Ok

**Comment by AlexFreedomMod** [comment]
@xDestroyer217 The Folder is back

**Comment by AlexFreedomMod** [comment]
@JeromSar or @xDestroyer217 can someone help me with making a project. I don't know how i mean it doesnt let me make one after i enter something in one box and the other boxes don't work

**Comment by xDestroyer217** [comment]
Close Netbeans first.. lul

**Comment by xDestroyer217** [comment]
Then Team>Git>Clone 

https://github.com/TotalFreedom/TotalFreedomMod

**Comment by AlexFreedomMod** [comment]
i cant. if netbeans is closed.

**Comment by xDestroyer217** [comment]
Ahem
try.

**Comment by xDestroyer217** [comment]
Delete with _*Windows Explorer*_

**Comment by AlexFreedomMod** [comment]
Ok First, Team>Git>Clone then enter https://github.com/TotalFreedom/TotalFreedomMod.git in the link area?

**Comment by AlexFreedomMod** [comment]
Wait first delete with Win Explorer then second Team>Git>Clone then enter the link above.

**Comment by AlexFreedomMod** [comment]
@xDestroyer217 What branch do i pick??

**Comment by xDestroyer217** [comment]
master, always master..

**Comment by AlexFreedomMod** [comment]
ok

**Comment by AlexFreedomMod** [comment]
Then hit finished?

**Comment by AlexFreedomMod** [comment]
@xDestroyer217 What do i do after it says 
![nb](https://cloud.githubusercontent.com/assets/8379108/7575997/8978992e-f7ee-11e4-8726-9061113b7e69.png)

**Comment by xDestroyer217** [comment]
How about downloading the zip, then do File> Export ZIP from somewhere

**Comment by AlexFreedomMod** [comment]
ok
i downloaded it earlyer

**Comment by AlexFreedomMod** [comment]
and its file> Import> from ZIP

**Comment by AlexFreedomMod** [comment]
it says "No Netbeans projects added.
![nbno](https://cloud.githubusercontent.com/assets/8379108/7576377/c203cc34-f7f1-11e4-89fa-4dd7aaefe4f4.png)
Didn't have enough time to edit it!

**Comment by AlexFreedomMod** [comment]
@JeromSar, can you help me with this error? I'm using Netbeans IDE 8.0.2 Java EE.

**Comment by AlexFreedomMod** [comment]
Fixed issue
