### ISSUE TITLE
Allow armor stands to be cleared with /rd

### ISSUE THREAD

**Issue by RobinGall2910** [TotalFreedom/TotalFreedomMod#603]
- Armor stands don't clear, also untrackable. (Including banner:*)

(star) = as all of the colors

**Comment by JeromSar** [comment]
What do you mean, they don't clear? How are they untrackable? @xDestroyer217

**Comment by xDestroyer217** [comment]
/ro doesn't clear them. I have to manually use worldedit to do so. And untrackable because, it doesn't show with the logstick who did it.

**Comment by Wild1145** [comment]
Thats because its an entity and not a block I would guess. Why /ro doesnt pick it up im not too sure though....

**Comment by AlexFreedomMod** [comment]
@Wild1145 is right.

**Comment by JeromSar** [comment]
Turning this into an enchantment: Allow banners to be cleared with /rd.
