### ISSUE TITLE
Other issues

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#605]
- Block /kick for OPs
- Remove on changing other players' gamemodes
- Remove /gamemode, to use my recommendations and /gmc, /gms, /survival and /creative
- Remove of /killing other players, and remove to kill all players from OPs, etc.
- Remove /ban from OPs, or just block.

Wew, I'm like spamming the repo with issues xD

**Comment by AlexFreedomMod** [comment]
@xDestroyer217, Pretty much, but spam is like making 50 issues at once and you didnt make 50 issues *lags* *laughs*

**Comment by xDestroyer217** [comment]
Oh please, if I haven't made this, I'll be done with 10 issues/day.
