### ISSUE TITLE
Invalid stats

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#606]
:[21:35:20 INFO]: UUID of player Airsuits is a6c1163f-11ac-37fa-8685-51e017156e1c
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.279 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.breakItem.310 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.53 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.4 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.17 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.breakItem.313 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.58 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.397 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.145 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/a6c1163f-11ac-37fa-8685-51e017156e1c.json: Don't know what stat.useItem.276 is
:[21:35:20 INFO]: [TotalFreedomMod] Obtaining UUID for new player: Airsuits
:[21:35:20 INFO]: [TotalFreedomMod] Generating spoof UUID for airsuits
:[21:35:20 INFO]: [JOIN] Airsuits (deadbeef-ea8e-7924-dd0e-f7cfd8ffe466) joined the game with IP address: 76.198.44.240
:[21:35:20 INFO]: [TotalFreedomMod] Added new player: Airsuits (deadbeef-ea8e-7924-dd0e-f7cfd8ffe466)
:[21:35:20 INFO]: Airsuits[/76.198.44.240:56502] logged in with entity id 1519 at ([flatlands]-935531.0550297018, 62.284450696337146, -30199.637146035882)
:[21:35:20 INFO]: UUID of player theglooper is 0da579c2-aefa-3639-9b2e-73413af5dc05
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.49 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.5 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.271 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.88 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.397 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.145 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.35 is
:[21:35:20 WARN]: Invalid statistic in ./TsuchiIwa/stats/0da579c2-aefa-3639-9b2e-73413af5dc05.json: Don't know what stat.useItem.276 is

**Comment by JeromSar** [comment]
This is a Minecraft bug:
https://bugs.mojang.com/browse/MC-51870
