### ISSUE TITLE
Command removals

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#609]
- /kill ** and /kill - infintely used
- Remove /gamemode, to use my recommendations and /gmc, /gms, /survival and /creative
- Remove on changing other players' gamemodes
- block /tellraw
- Remove /ban - #611 
:[21:50:54 INFO]: H0tdog_moisi3_2 issued server command: /ban RobinThePenguin
:[21:50:54 INFO]: [PREPROCESS_COMMAND] H0tdog_moisi3_2(H0tdog_moisi3_2): /ban RobinThePenguin
:[21:50:54 INFO]: [EXIT] RobinThePenguin left the game.
:[21:50:54 INFO]: RobinThePenguin lost connection: You are banned from this server.

**Comment by AlexFreedomMod** [comment]
Ops can not use /ban i tested it earlyer.

**Comment by AlexFreedomMod** [comment]
@xDestroyer217 What branch to i get for #600

**Comment by xDestroyer217** [comment]
Please don't reference other issues that are entirely irrelevant to each other.

**Comment by AlexFreedomMod** [comment]
Sorry.

**Comment by xDestroyer217** [comment]
@JeromSar

**Comment by AlexFreedomMod** [comment]
So much more per second 

:black_circle:                            :black_circle: 
                       :large_blue_circle:

**Comment by Wild1145** [comment]
>/kill ** and /kill - infintely used

The kill commands are essentials, this should be raised there.

    >Remove /gamemode, to use my recommendations and /gmc, /gms, /survival and /creative

Again, this should be raised in the essentials repo's.


    >Remove on changing other players' gamemodes

Again, this needs to be raised on Essentials Repo...


    >block /tellraw

Simple config change there.

    >Remove /ban - #611 :[21:50:54 INFO]: H0tdog_moisi3_2 issued server command: /ban >RobinThePenguin :[21:50:54 INFO]: [PREPROCESS_COMMAND] >H0tdog_moisi3_2(H0tdog_moisi3_2): /ban RobinThePenguin :[21:50:54 INFO]: [EXIT] >RobinThePenguin left the game. :[21:50:54 INFO]: RobinThePenguin lost connection: You are >banned from this server.

This again should already be blocked and disabled in Essentials and should be raised there as an issue.

**Comment by xDestroyer217** [comment]
Yeah but all of them are kinda on the Spigot-side, but alright.

**Comment by Wild1145** [comment]
@xDestroyer217 Oooooh, Okay. My mistake, they are also Essentials commands so I had assumed that Essentials had overwritten the commands. Just simple config additions should fix this then :)

**Comment by JeromSar** [comment]
Superceded by issue: https://github.com/TotalFreedom/TotalFreedomMod/issues/611
