### ISSUE TITLE
Limit spam of moving too fast

### ISSUE THREAD

**Issue by RobinGall2910** [TotalFreedom/TotalFreedomMod#610]
:[21:44:21 WARN]: Biggbro moved too quickly! 0.0,-0.07840000152587834,0.0 (15.90625504443274, 1.2495683414761176, 1.4267360158208795)
:[21:44:21 WARN]: Biggbro moved too quickly! 0.0,-0.2336320060424768,0.0 (14.474692507591934, 0.2336320060424768, 1.2983298118146414)

-Rest got cut off

**Comment by Wild1145** [comment]
Vanilla Bug

**Comment by tylerhyperHD** [comment]
You can simply change the spigot.yml configs to make it so that it doesn't spam this at all.
