### ISSUE TITLE
Wiki not complete

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#612]
When i looked at the wiki it was not complete! The part were it say This way your making sure....
Making sure of what?, @JeromSar could you fix this?

**Comment by xDestroyer217** [comment]
What SHOULD be there lol

**Comment by AlexFreedomMod** [comment]
( Copyed from Wiki )
There are two ways to obtain a copy of TotalFreedomMod. The first and easiest is to download the latest version from the releases page. By obtaining your TotalFreedomMod copy through this method, you ensure that you always

**Comment by Wild1145** [comment]
Probably going to be re-designed either way for TFM 5.0

**Comment by AlexFreedomMod** [comment]
OK

**Comment by JeromSar** [comment]
I'm working on it. :)

**Comment by JeromSar** [comment]
@AlexFreedomMod Wiki is now updated. :)

**Comment by AlexFreedomMod** [comment]
Thanks
