### ISSUE TITLE
Summon

### ISSUE THREAD

**Issue by RobinGall2910** [TotalFreedom/TotalFreedomMod#613]
:[22:01:11 INFO]: [PREPROCESS_COMMAND] maxdog08(maxdog08): /summon LightningBolt
:[22:01:11 INFO]: [maxdog08: Object successfully summoned]

Lightning can me summoned, same as for TNT = PrimedTNT

**Comment by AlexFreedomMod** [comment]
True the lighting now works, and so does TNT. @JeromSar Looks like you need to block some more commands. Now the config will have to be longer :O

**Comment by AlexFreedomMod** [comment]
and @xDestroyer217 You made 12 issues today please slow down. I can not keep up!

**Comment by Wild1145** [comment]
Quick config change should fix this :)

**Comment by AlexFreedomMod** [comment]
Thats what i am doing :)

**Comment by JeromSar** [comment]
I don't know why summoning lightningbolts should be a problem.
Primed TNT can be spawned, but does not explode, so it's an issue.

**Comment by xDestroyer217** [comment]
It explodes. PrimedTNT does explode.

**Comment by JeromSar** [comment]
It explodes, but no block damage.

**Comment by xDestroyer217** [comment]
@JeromSar well it used to work, but not anymore.

**Comment by JeromSar** [comment]
@xDestroyer217 As far as I know, TFM has always blocked explosions.
