### ISSUE TITLE
Weather is toggable

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#617]

**Comment by Wild1145** [comment]
Raise on the Essentials repo.

**Comment by AlexFreedomMod** [comment]
its eweather i think!

**Comment by xDestroyer217** [comment]
Okay wild.

**Comment by tylerhyperHD** [comment]
This again is commandblocker not working. If someone would have listened to me and rolled back commandblocker to a previous commit we wouldn't have this issue happening.

**Comment by Wild1145** [comment]
@tylerhyperHD Maybe you should bother to listen to us? You know that often works. Weather is again an Essentials command and can be fixed there, or by fixing the command blocker here, either would work. Reverting it is just a waste of the time that was taken to improve on it.

**Comment by tylerhyperHD** [comment]
I have actually configured Essentials before and I am here to tell you that
it does not completely block the command. Neither does /ban completely
block the command through Essentials. It is a thing that has to be done
through the mod.

**Comment by Wild1145** [comment]
I never said you should "Block" the command, you should simply edit it to only allow it to admins as this is the "TF-Essentials"

**Comment by JeromSar** [comment]
@tylerhyperHD The issue you suggested has nothing to do with the issue with commandblocker currently. Reverting the commit would have no effect. This is a Spigot issue.
