### ISSUE TITLE
Remove effect messages

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#619]

**Comment by JeromSar** [comment]
Why is this a problem?

**Comment by Scuph** [comment]
Probably just reduces chat spam, we already have ops chat, ops commands (cmdspy), admins chat, adminchat itself, admin's commands. (/opall, /smite, etc.) Just reduce unneeded chat.

**Comment by JeromSar** [comment]
I don't think this should be implemented.
