### ISSUE TITLE
Telnet Admins not being recognized as Telnets 

### ISSUE THREAD

**Issue by markbyrn** [TotalFreedom/TotalFreedomMod#623]
Seems in 1.8 that many Telnet admins are only getting recognized as super admins.  Seems the only way to fix is completely erase them out of the config file and start fresh.  Is there an easier way to fix?

**Comment by GotNoFriends** [comment]
I have had this problem @markbyrn I was even desupered.

**Comment by Scuph** [comment]
Lots of telnets have this problem, 1.8 fucks with the superadmin.yml

**Comment by JeromSar** [comment]
@markbyrn Are you sure this is a telnet-admin only problem, or is has it just coincidentally happened with telnet admins. Truth is, Telnet admins really are only super-admins with Telnet-access. They don't have commands they can access and superadmins can't.

There might be some admin issues, especially with the latest changes in UUID handling. The system was completely revamped and there's no clean way to migrate over.

**Comment by notchface72** [comment]
I was told to comment on this if I have this problem, so...

~Trucy_Wright

**Comment by JeromSar** [comment]
There's not much we can do about this bug, as it currently stands, I'm afraid.
