### ISSUE TITLE
Ops having permissions for /tpall

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#624]
Well, We have a problem. Ops have permissions to /tpall and keep abusing it.

**Comment by AlexFreedomMod** [comment]
@LegendIsAwesomes, @JeromSar fixed this in TF43.

**Comment by JeromSar** [comment]
Fixed here: https://github.com/TotalFreedom/TotalFreedomMod/commit/632f3647a839fe026df6a65e073d9522f6c064ef
