### ISSUE TITLE
Minechat Users cannot Join

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#626]
Hello, I was going to Chat with The people of Tf via Minechat.
minechat users Cannot join Because the server is "cracked"
Can you fix this Please?

**Comment by PattyToTheWatty** [comment]
Well, i guess theres noway to fix this. But if you can, Please fix it ASAP

**Comment by DaBoyTM** [comment]
Well basically, the server is "cracked" so you have to use offline mode in "TF" setting and then use your username in username/e-mail area, Password doesn't really matter... Otherwise, send a message to MineChat Developer group about that problem

**Comment by PattyToTheWatty** [comment]
Oh! okay! Thanks for responding!
