### ISSUE TITLE
Auto-Op the non-op on join

### ISSUE THREAD

**Issue by OnlineRepz** [TotalFreedom/TotalFreedomMod#627]
Well, i am not sure if someone have requested it, but i just want to request it, it might be a good idea to added Auto-Op when non-op have joined, it will help to reduce the spam of screaming non-op (e.g "WHERE IS MY OP!" "ADMIN! PLEASE OP ME!" "SOMEONE OP ME!" <- then someone else said no etc.)

I will make a pull request if this is enhancement

**Comment by PattyToTheWatty** [comment]
Hmm, This could be Useful for griefers. if they get Banned for five minutes rejoin and auto get op again and grief.

I may be wrong.

**Comment by Wild1145** [comment]
Yeah, the only way I could see this being handy is doing it for players that have never joined before, that way brand new players get OP, everyone else has to be manually added to OP status.

**Comment by PattyToTheWatty** [comment]
Or if they're ip hasnt joined before.

**Comment by AlexFreedomMod** [comment]
Yeah, it could check if no one on there ip has joined it returns true; (No one joined on their ip before) 
it will Op them 
- [ ] Cool!
- [X] test

**Comment by PattyToTheWatty** [comment]
Yeah, i hoe this is implemented.

**Comment by AlexFreedomMod** [comment]
same

**Comment by JeromSar** [comment]
After some thought, I've come to the conclusion that this would not be a good idea. There are several reasons why OPs shouldn't always be opped when they join the server.
Thanks for contributing!
