### ISSUE TITLE
Revamp TFM rank system

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#628]
There's several rank definitions in TFM:
* AdminLevel
* TFM_PlayerRank
* TFM_CommandBlocker.CommandBlockerRank
* TFM_AdminList.isSuperAdmin()
* TFM_AdminList.isSeniorAdmin()

This system causes ambiguities and errors, it needs to be migrated to one uniform system.

**Comment by AlexFreedomMod** [comment]
Yeah, @JeromSar once when i was coding it gave me errors with TFM_AdminList.isSuperAdmin() and
TFM_AdminList.isSeniorAdmin() it wanted me to change it to something diffent

**Comment by JeromSar** [comment]
@AlexFreedomMod That is completely irrelevant, open a new issue please. :)

**Comment by AlexFreedomMod** [comment]
ok
