### ISSUE TITLE
Block /execute

### ISSUE THREAD

**Issue by supergameplayer** [TotalFreedom/TotalFreedomMod#630]
"Executes a command with a different user and position, with delegated permissions." -Minecraft wiki

This command can easily cause trouble. It should also be auto-ban.

**Comment by ChargedCreeper** [comment]
Auto-ban will lead to more trolling. Best to just have it blocked.

**Comment by Hockeyfan360** [comment]
Mark tried blocking it today, it wouldn't work. I am pretty sure you were able to use the command after it was blocked. If this is tested and it doesn't work, I have a solution that might work.

I am not up for compiling spigot. However, I looked at the source. In the VanillaCommandWrapper, you could check to see if commandLabel.equalsIgnoreCase("execute") and then return/return true.

I do not know if that will work, but it is a start.

**Comment by JeromSar** [comment]
@Hockeyfan360 @supergameplayer @ChargedCreeper Execute is now blocked on the server, https://github.com/TotalFreedom/TotalFreedomMod/pull/631 is a pull request that syncs the TFM repo, and will be merged soon.

Mark didn't block /execute properly.
