### ISSUE TITLE
Calling twice

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#632]
:[22:49:56 INFO]: Creating empty config: /.rw/games/minecraft/beta/299668/plugins/Essentials/userdata/63141acf-6844-4a84-836e-45d59b3c1a95.yml
:[22:49:56 INFO]: [CONSOLE_COMMAND] Rcon: /say WARNING: Server is restarting, you will be kicked
:[22:49:56 INFO]: Server is going offline.
:[22:49:56 INFO]: [EXIT] Elephants111 left the game.
:[22:49:56 INFO]: Elephants111 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] Elephants111 left the game.
:[22:49:56 INFO]: Elephants111 left the game.
:[22:49:56 INFO]: [EXIT] StevenNL2000 left the game.
:[22:49:56 INFO]: StevenNL2000 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] StevenNL2000 left the game.
:[22:49:56 INFO]: StevenNL2000 left the game.
:[22:49:56 INFO]: [EXIT] MidnightMemory left the game.
:[22:49:56 INFO]: MidnightMemory lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] MidnightMemory left the game.
:[22:49:56 INFO]: MidnightMemory left the game.
:[22:49:56 INFO]: [EXIT] CoolNinjaGolden left the game.
:[22:49:56 INFO]: CoolNinjaGolden lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] CoolNinjaGolden left the game.
:[22:49:56 INFO]: CoolNinjaGolden left the game.
:[22:49:56 INFO]: [EXIT] AcidicCyanide left the game.
:[22:49:56 INFO]: AcidicCyanide lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] AcidicCyanide left the game.
:[22:49:56 INFO]: AcidicCyanide left the game.
:[22:49:56 INFO]: [EXIT] MissSherryVine left the game.
:[22:49:56 INFO]: MissSherryVine lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] MissSherryVine left the game.
:[22:49:56 INFO]: MissSherryVine left the game.
:[22:49:56 INFO]: [EXIT] TARClanrules left the game.
:[22:49:56 INFO]: TARClanrules lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] TARClanrules left the game.
:[22:49:56 INFO]: TARClanrules left the game.
:[22:49:56 INFO]: [EXIT] lilGoyaBro left the game.
:[22:49:56 INFO]: lilGoyaBro lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] lilGoyaBro left the game.
:[22:49:56 INFO]: lilGoyaBro left the game.
:[22:49:56 INFO]: [EXIT] jessica_pugs left the game.
:[22:49:56 INFO]: jessica_pugs lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] jessica_pugs left the game.
:[22:49:56 INFO]: jessica_pugs left the game.
:[22:49:56 INFO]: [EXIT] SniperSauce left the game.
:[22:49:56 INFO]: SniperSauce lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] SniperSauce left the game.
:[22:49:56 INFO]: SniperSauce left the game.
:[22:49:56 INFO]: [EXIT] I_am_Gamer_4life left the game.
:[22:49:56 INFO]: I_am_Gamer_4life lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] I_am_Gamer_4life left the game.
:[22:49:56 INFO]: I_am_Gamer_4life left the game.
:[22:49:56 INFO]: [EXIT] RobinThePenguin left the game.
:[22:49:56 INFO]: RobinThePenguin lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] RobinThePenguin left the game.
:[22:49:56 INFO]: RobinThePenguin left the game.
:[22:49:56 INFO]: [EXIT] Sn00pD0gg left the game.
:[22:49:56 INFO]: Sn00pD0gg lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] Sn00pD0gg left the game.
:[22:49:56 INFO]: Sn00pD0gg left the game.
:[22:49:56 INFO]: [EXIT] _Kale left the game.
:[22:49:56 INFO]: _Kale lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] _Kale left the game.
:[22:49:56 INFO]: _Kale left the game.
:[22:49:56 INFO]: [EXIT] MiniMage321 left the game.
:[22:49:56 INFO]: MiniMage321 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] MiniMage321 left the game.
:[22:49:56 INFO]: MiniMage321 left the game.
:[22:49:56 INFO]: [EXIT] killerstier1000 left the game.
:[22:49:56 INFO]: killerstier1000 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] killerstier1000 left the game.
:[22:49:56 INFO]: killerstier1000 left the game.
:[22:49:56 INFO]: [EXIT] spikeboy1218 left the game.
:[22:49:56 INFO]: spikeboy1218 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] spikeboy1218 left the game.
:[22:49:56 INFO]: spikeboy1218 left the game.
:[22:49:56 INFO]: [EXIT] Jenna028 left the game.
:[22:49:56 INFO]: Jenna028 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] Jenna028 left the game.
:[22:49:56 INFO]: Jenna028 left the game.
:[22:49:56 INFO]: [EXIT] Stampy100 left the game.
:[22:49:56 INFO]: Stampy100 lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] Stampy100 left the game.
:[22:49:56 INFO]: Stampy100 left the game.
:[22:49:56 INFO]: [EXIT] Mahl_Trollbait left the game.
:[22:49:56 INFO]: Mahl_Trollbait lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] Mahl_Trollbait left the game.
:[22:49:56 INFO]: Mahl_Trollbait left the game.
:[22:49:56 INFO]: [EXIT] gorloxian left the game.
:[22:49:56 INFO]: gorloxian lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] gorloxian left the game.
:[22:49:56 INFO]: gorloxian left the game.
:[22:49:56 INFO]: [EXIT] NoScopeSwagMoney left the game.
:[22:49:56 INFO]: NoScopeSwagMoney lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] NoScopeSwagMoney left the game.
:[22:49:56 INFO]: NoScopeSwagMoney left the game.
:[22:49:56 INFO]: [EXIT] datchainsawdo left the game.
:[22:49:56 INFO]: datchainsawdo lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] datchainsawdo left the game.
:[22:49:56 INFO]: datchainsawdo left the game.
:[22:49:56 INFO]: [EXIT] detonatorcole left the game.
:[22:49:56 INFO]: detonatorcole lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] detonatorcole left the game.
:[22:49:56 INFO]: detonatorcole left the game.
:[22:49:56 INFO]: [EXIT] bigheadmagoo left the game.
:[22:49:56 INFO]: bigheadmagoo lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] bigheadmagoo left the game.
:[22:49:56 INFO]: bigheadmagoo left the game.
:[22:49:56 INFO]: [EXIT] xXStudKidXx left the game.
:[22:49:56 INFO]: xXStudKidXx lost connection: Server is going offline, come back in about 20 seconds.
:[22:49:56 INFO]: [EXIT] xXStudKidXx left the game.
:[22:49:56 INFO]: xXStudKidXx left the game.
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 WARN]: handleDisconnection() called twice
:[22:49:56 INFO]: [TotalFreedomMod] Obtaining UUID for new player: minediamond336
:[22:49:56 INFO]: [JOIN] minediamond336 (ac612f42-793d-412e-8eaf-b6378d0f9ecf) joined the game with IP address: 74.72.181.113
:[22:49:56 INFO]: minediamond336[/74.72.181.113:46009] logged in with entity id 9987 at ([Woosh]508.5, 87.0, -731.5)
:[22:49:56 INFO]: [TotalFreedomMod] Obtaining UUID for new player: adam816
:[22:49:56 INFO]: [JOIN] adam816 (49692a88-7362-4e4e-85be-603a23b221ec) joined the game with IP address: 70.92.186.201
:[22:49:57 INFO]: [TotalFreedomMod] Added new player: adam816 (49692a88-7362-4e4e-85be-603a23b221ec)
:[22:49:57 INFO]: adam816[/70.92.186.201:62612] logged in with entity id 9988 at ([Woosh]512.5, 87.0, -729.5)
:[22:49:57 INFO]: [TotalFreedomMod] Obtaining UUID for new player: MHF_Tree
:[22:49:57 INFO]: Disconnecting com.mojang.authlib.GameProfile@bce3545[id=312d57a3-e48b-4c78-9073-8ee52280f1ea,name=MHF_Tree,properties={textures=[com.mojang.authlib.properties.Property@44fd4afb]},legacy=false] (/50.152.132.207:56073): Your IP address is permanently banned from this server.
Release procedures are available at
http://bit.ly/TF_PermBan
:[22:49:57 INFO]: Stopping server

Exit called twice.

**Comment by JeromSar** [comment]
This is a Spigot bug, no can fix. :/

**Comment by Wild1145** [comment]
Post the issue here: http://www.spigotmc.org/forums/bugs-feature-requests.8/
