### ISSUE TITLE
Imposter system not working properly

### ISSUE THREAD

**Issue by OxLemonxO** [TotalFreedom/TotalFreedomMod#633]
We had multiple imposters today, imposing as Prozza, they were not marked as imposter but in /saconfig info their ip didn't exist and there was another person in /seen. They were supered

**Comment by OxLemonxO** [comment]
They were supered.

**Comment by JeromSar** [comment]
Looking into this now.

**Comment by AlexFreedomMod** [comment]
Imposters were supered?????

**Comment by PattyToTheWatty** [comment]
That hppend to me about 3 weeks ago

**Comment by JeromSar** [comment]
The issue has been resolved.
