### ISSUE TITLE
Twitterbot Not Needed

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#636]
So we currently have Twitterbot still on TFM, which right now Twitterbot is not going to be used anytime soon, so since it isn't, we should remove it, plus another reason is Twitter updated it's API and other things. We also don't have a server for it to run on and it is completely disabled on TF.

**Comment by Wild1145** [comment]
Twitterbot is being re-written from the ground up. 

I also do not understand your obsession with removing features and functionality from TFM, it just confuses me, because I dont understand why anyone that would call themselves a developer sees it as a good idea just to remove features and functionality because its not used often or is being worked on...

**Comment by tylerhyperHD** [comment]
I remove features that aren't necessary because the general public and myself do not use them. Plus twitterbot initializes on command, and if you are rewriting it, then why don't you disable its initialization until you are done rewriting it?

**Comment by Wild1145** [comment]
It is disabled... It has been for months. Just because it is not currently used is no reason to remove it. Else half the features I write or am working on would just have to be removed by your logic.

**Comment by tylerhyperHD** [comment]
I'll leave you with this, why are you placing a variable if the variable is disabled and hasn't been updated for quite some time? It seems silly to me, but it's your call on this one.

**Comment by JeromSar** [comment]
@tylerhyperHD No commands are initialized until they're used.

**Comment by tylerhyperHD** [comment]
The last modification was last year BTW, so when you say you are rewriting
it I don't really think you are attempting to rewrite it that hard.

**Comment by JeromSar** [comment]
@tylerhyperHD We're doing our best to make TotalFreedomMod work, alright. Criticism isn't much appreciated.

**Comment by Scuph** [comment]
@TylerhyperHD I'm sure to hell these developers have more experience than you and starting an argument that they inevitably win is unnecessary

**Comment by tylerhyperHD** [comment]
Well since you guys never commit to github, it becomes pretty clear to me you are making no progress in re-creating twitterbot. Yet I can see why you are focused on TFM, it is still odd to me why you never rewrote it. That is why I am questioning it.

**Comment by Wild1145** [comment]
Because some of us have other things to do, Twitterbot is not a priority, its not something that was ever widely used, but would be great to have. TFM on the other hand is "Mission Critical" and needs to be working, else twitterbot isnt worth pot.
