### ISSUE TITLE
Blocked commands Are not blocked

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#637]
Hi please help me I have blocked commands in Config of totalfreedommod when i type Reload or any other command it work i dont know why :( i dont have superadmin or another
In mc 1.7 (totalfreedom 4.1 Pre-release 1) it blocket but the actually version in 1.8 its not blocked  Sorry for bad english i am from czech republic

**Comment by PattyToTheWatty** [comment]
Mext time, Restart Your server. /reloading can Lead to unexepected things. Make sure Your typing the roght commands and Yeah, Should be fine from there.

**Comment by WarrioR151** [comment]
I rebooted the server , I still work orders to be blocked work
can you go on my server a try help me? Do u have skype?

PS: i have spigot 1.8.3

**Comment by JeromSar** [comment]
@WarrioR151 Try using the latest source version in the master branch. You'll have to compile it. In the source, a critical bug with CommandBlocker has been fixed. :)

**Comment by WarrioR151** [comment]
Master branch no work on compie for me
Can yo u try to help me please?


Ihave one error  in me.stevenlawson.totalfreedommod.bridge. (TFM_worldeditListener.java)
Do yo know how to fix it olease?

**Comment by JeromSar** [comment]
@WarrioR151 Make a new issue, we'll help you from there.

**Comment by WarrioR151** [comment]
JeromSar i have it now    Thank you very much for your help
You really helped me 
PS: i used bad worldedit :D when i used TF-WorldEdit it works

Thank you
