### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#638]
hi please how can i give someone rank I added in TFM_PlayerRank.java ?

**Comment by xDestroyer217** [comment]
`if (DEVELOPERS.contains(sender.getName()))
        {
            return DEVELOPER;
        }`

Right under that do
`
else if (sender.getName().equals("PLAYER"))
        {
            return SETRANK;
        }
`

Meaning for `PLAYER` as in The IGN of the user. And `SETRANK` as in the setrank here:

`SETRANK("the " + ChatColor.AQUA + "A derpish rank", ChatColor.YELLOW + "[Rank]"),`

If you want add that under `DEVELOPERS`

**Comment by PattyToTheWatty** [comment]
Watch a tutorial :) It should work!

**Comment by AlexFreedomMod** [comment]
HockeyFan had a tutorial but it got removed. @JeromSar should make a tutorial (Or @someone else.)

**Comment by PattyToTheWatty** [comment]
Ikr i was bummed when it was removed. When i get my pc foxed, ill make a tutorial :)

**Comment by AlexFreedomMod** [comment]
I have a computer with netbeans but its focked.

**Comment by PattyToTheWatty** [comment]
My pc is focked too :P palm_tree fock it didnt sork

**Comment by JeromSar** [comment]
@WarrioR151 Do you still need help, or can this issue be closed?

**Comment by PattyToTheWatty** [comment]
Coose, i guess inactivity
