### ISSUE TITLE
ProtectArea restart

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#639]
Hi please help me when i add a protect on area.   And restart server the protect is deleted and i must protect it again.... its still i add protect and one hour ago is automatic server restart when server restart i dont have saved my protects in /protect list .....

Restart= Protect Delete 

Please can u try to fix it?

**Comment by PattyToTheWatty** [comment]
Hm, Can i join your server?

**Comment by Wild1145** [comment]
I didnt realize protect area's were supposed to be kept longer term...

**Comment by PattyToTheWatty** [comment]
Hahahaha ultra fail

**Comment by AlexFreedomMod** [comment]
@Wild1145, yeah restarts do wipe the Protected Area.
[code]
::o:
[/code]
