### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by WarrioR151** [TotalFreedom/TotalFreedomMod#640]
hi again :D
Please owner can you block commands in worldedit?   //set lava //set barricade //hsphere lava etc....

On totalfreedommod server is system when someone write //set lava etc.. get deoped can u make this system here to totalfreedommod?
I need it.  Players destroying my world with lava 

Please

**Comment by PattyToTheWatty** [comment]
Well firstly, Go onto your config for you server. it should be Totalfreedommod.config.yml
Go to block Commands or scroll down.
Copy a copyed command on a new line. Just replace the command as /set lava:'
Can i please join your server?

**Comment by WarrioR151** [comment]
Yes but i dont know if i can post ip here

And i need to block command and when player use //set lava etc get deoped.

**Comment by PattyToTheWatty** [comment]
Do you have skype? I might be able to

**Comment by WarrioR151** [comment]
Skype is dominik.radon

**Comment by PattyToTheWatty** [comment]
Ok!
