### ISSUE TITLE
Op rank thing

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#641]
Hello. Whenever mya ip changes and go on oliversawesomes server im always

IPatty is an OP.

I can do /opall but makes people so confused. They say your a hacker. Its so annoying.
Please fix this.

**Comment by JeromSar** [comment]
@PattyToTheWatty The rank system in TFM is IP-based because TF servers are usually in offline mode, meaning people can log in as you, this won't be changed, sorry.

**Comment by Wild1145** [comment]
This *should* only happen if your username changed and you are still on the same IP... As this normally happens to family members because their IP is supered but username is not.

**Comment by PattyToTheWatty** [comment]
Oh thats ok, ill try to putnup with it.
