### ISSUE TITLE
Imposter

### ISSUE THREAD

**Issue by SlicedCaek** [TotalFreedom/TotalFreedomMod#642]
Well, I was on TotalFreedom and then a imposter tried to join and its successfully worked, it kicked me out saying I have joined in different location, then I have to get a admin to ban that imposter so i can join again.

I am thinking that it might be a bug, it is bit similar to #633

**Comment by PattyToTheWatty** [comment]
Im pretty sure we cant fix this.

**Comment by DaBoyTM** [comment]
@PattyToTheWatty, it's just a 1.8.3 bug, TFM is still updating

**Comment by PattyToTheWatty** [comment]
True but brcause its cracked people can still kick you off. Could still be annoying

**Comment by tylerhyperHD** [comment]
I believe it's either an issue with TFM_AdminList or TFM_UuidManager that is causing this, might wanna look into that specific area.

**Comment by Scuph** [comment]
It is a spigot error @tylerhyperHD, you shouldn't be able to remove a user from the game by logging in has him, It should say 'user is already logged in'.

**Comment by tylerhyperHD** [comment]
Thanks, that would be in TFM_ServerInterface then.
