### ISSUE TITLE
Spigot 1.8.4/1.8.6 Now Out

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#644]
So as this thread says: http://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-8-4.66527/

Spigot 1.8.4 is out and we should implement it soon.

**Comment by Wild1145** [comment]
Doubt it will make a huge deal of difference to be honest. Just the NMS version needs updating more than likely.

**Comment by AlexFreedomMod** [comment]
Spigot 1.8.6 is now out..

**Comment by Wild1145** [comment]
Again, there are no NMS changes, its mostly security fixes so should have no affect on the server.

**Comment by AlexFreedomMod** [comment]
K
