### ISSUE TITLE
Block /title

### ISSUE THREAD

**Issue by zD12** [TotalFreedom/TotalFreedomMod#646]
OPs may abuse such command, therefore, we should block it...

**Comment by Wild1145** [comment]
Should already be blocked.

**Comment by zD12** [comment]
@Wild1145 it should be, but, admins still have access.

**Comment by zD12** [comment]
@Wild1145, no, you were right.  It's blocked for admins only:
 - 's:b:/title:_'

**Comment by OliverDatGuy** [comment]
"OliverDatGuy commented 14 minutes ago
Wrong, tested as an op. It still works."
