### ISSUE TITLE
Ops can do /title

### ISSUE THREAD

**Issue by OliverDatGuy** [TotalFreedom/TotalFreedomMod#648]
Very spammy and annoying, it's apparently for super's only but it still works. Fix ASAP please c:

**Comment by zD12** [comment]
It's not an issue.  See #646

**Comment by OliverDatGuy** [comment]
What're you talking about, it's been blocked but still works.

**Comment by zD12** [comment]
@OliverDatGuy, that's because you're an administrator.  It's allowed for administrators, not for operators.

**Comment by OliverDatGuy** [comment]
Wrong, tested as an op. It still works.

**Comment by BlooStar** [comment]
I can verify that ^

**Comment by PattyToTheWatty** [comment]
Admins should be doing /smite. could be annoying.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/621
