### ISSUE TITLE
/title

### ISSUE THREAD

**Issue by BlooStar** [TotalFreedom/TotalFreedomMod#649]
/title if used correctly can make other people's clients crash. It also can be used to troll other players. Could we block /title?

**Comment by zD12** [comment]
It's not an issue.  See #646

**Comment by Wild1145** [comment]
Duplicate of #648 and #646

**Comment by BlooStar** [comment]
Operator's are able to perform the command...

**Comment by Wild1145** [comment]
I am aware. Its still a duplicate issue of #648 and #646
