### ISSUE TITLE
Spigot 1.8R2 is needed for compilation.

### ISSUE THREAD

**Issue by ArcticHumboldt** [TotalFreedom/TotalFreedomMod#650]
I require spigot 1.8R2, but, running BuildTools, it only gives me R1.

Anywhere I can download it as a jar file?

(Sorry that this isn't entirely related to an issue with TFM itself.)

**Comment by Wild1145** [comment]
I think you had to add an extra argument to the end. If not the version I host might be the one you need: http://gaming.superior-networks.com/jars/Spigot/Spigot-Server/target/

**Comment by ArcticHumboldt** [comment]
The Git command I was using was "java -jar BuildTools.jar --rev 1.8"

**Comment by Wild1145** [comment]
Thats the issue then, it will always build the first 1.8 version if I remember correctly. If you read the latest thread on the home page it tells you, I think its something like --rev 1.8.4

**Comment by JeromSar** [comment]
@Wild1145 got it.
