### ISSUE TITLE
CommandSpy

### ISSUE THREAD

**Issue by ImJustLazyGH** [TotalFreedom/TotalFreedomMod#652]
https://github.com/Superior-Development/IcarusMod/issues/112

I thought we should make commandspy auto enabled and not able to be disabled, like @Wild1145 is doing with IcarusMod

**Comment by Obi2** [comment]
I agree with perhaps auto-enabling it on join, but an option to disable it should be retained in the event of chat spam etc.

**Comment by PattyToTheWatty** [comment]
Make a setting in the config. : Auto-CmdSpy=false

**Comment by AlexFreedomMod** [comment]
Yeah that would be cool

**Comment by Wild1145** [comment]
Superseded by #1830
