### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#657]
When i was building TFM this happend:

(Clicks Picture of Hammer)

LOG INFO:
ant -f C:\\Users\\MC\\Documents\\NetBeansProjects\\AlexFreedomMod -Dnb.internal.action.name=build jar
init:
deps-jar:
Created dir: C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\build
Updating property file: C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\build\built-jar.properties
Created dir: C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\build\classes
Created dir: C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\build\empty
Created dir: C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\build\generated-sources\ap-source-output
Compiling 171 source files to C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\build\classes
warning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:8: error: package net.minecraft.server.v1_8_R2 does not exist
import net.minecraft.server.v1_8_R2.EntityPlayer;
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:9: error: package net.minecraft.server.v1_8_R2 does not exist
import net.minecraft.server.v1_8_R2.MinecraftServer;
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:10: error: package net.minecraft.server.v1_8_R2 does not exist
import net.minecraft.server.v1_8_R2.PropertyManager;
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\Commands\Command_saconfig.java:102: warning: [deprecation] getEntry(String) in TFM_AdminList has been deprecated
                TFM_Admin superadmin = TFM_AdminList.getEntry(args[1].toLowerCase());
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\Commands\Command_saconfig.java:109: warning: [deprecation] getEntry(String) in TFM_AdminList has been deprecated
                        superadmin = TFM_AdminList.getEntry(player.getName().toLowerCase());
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\Commands\Command_saconfig.java:130: warning: [deprecation] getEntry(String) in TFM_AdminList has been deprecated
                    final TFM_Admin superadmin = TFM_AdminList.getEntry(args[1]);
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_PlayerRank.java:75: error: cannot find symbol
        else if (AFM_DEVELOPERS.contains(sender.getName()))
  symbol:   method contains(String)
  location: variable AFM_DEVELOPERS of type TFM_PlayerRank
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:24: error: cannot find symbol
        final PropertyManager manager = MinecraftServer.getServer().getPropertyManager();
  symbol:   class PropertyManager
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:24: error: cannot find symbol
        final PropertyManager manager = MinecraftServer.getServer().getPropertyManager();
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:31: error: cannot find symbol
        String[] whitelisted = MinecraftServer.getServer().getPlayerList().getWhitelisted();
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:33: error: cannot find symbol
        for (EntityPlayer player : MinecraftServer.getServer().getPlayerList().players)
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:33: error: cannot find symbol
        for (EntityPlayer player : MinecraftServer.getServer().getPlayerList().players)
  symbol:   class EntityPlayer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:35: error: cannot find symbol
            MinecraftServer.getServer().getPlayerList().getWhitelist().remove(player.getProfile());
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:40: error: cannot find symbol
            MinecraftServer.getServer().getPlayerList().getWhitelist().save();
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:52: error: cannot find symbol
        return MinecraftServer.getServer().getPlayerList().getHasWhitelist();
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:57: error: cannot find symbol
        return Arrays.asList(MinecraftServer.getServer().getPlayerList().getWhitelisted());
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\src\me\StevenLawson\TotalFreedomMod\TFM_ServerInterface.java:62: error: cannot find symbol
        return MinecraftServer.getServer().getVersion();
  symbol:   variable MinecraftServer
  location: class TFM_ServerInterface
14 errors
4 warnings
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\nbproject\build-impl.xml:900: The following error occurred while executing this line:
C:\Users\MC\Documents\NetBeansProjects\AlexFreedomMod\nbproject\build-impl.xml:265: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 33 seconds)

**Comment by tylerhyperHD** [comment]
This is the classic case of you did not add the correct 1.8 spigot dependency.

**Comment by AlexFreedomMod** [comment]
@tylerhyperHD can you put R2 on dropbox or something so i can get it?

**Comment by JeromSar** [comment]
@AlexFreedomMod That would violate Mojang's copyright, as demonstrated by CraftBukkit's DMCA. Get Spigot yourself: https://spigotmc.org

**Comment by AlexFreedomMod** [comment]
K
