### ISSUE TITLE
TFM_AdminList.isSuperAdmin() and TFM_AdminList.isSeniorAdmin()

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#659]
When i was coding a plugin i was making a command with eclipse (the plugin i coded was not tfm it would be stupid to code tfm with eclipse) so when i put TFM_AdminList.isSeniorAdmin()
it wanted me to change it to TFM_AdminList.isSuperAdmin() then the same thing over and over again
you get the idea.

**Comment by SlicedCaek** [comment]
Retype the whole thing (like copying pasting)
Otherwise just get new one.

**Comment by JeromSar** [comment]
@AlexFreedomMod Could you give some more detail? Do know that isSeniorAdmin(CommandSender, boolean), takes a boolean as a second argument. If the boolean is true, superadmin will be checked first.

**Comment by JeromSar** [comment]
@AlexFreedomMod Please update this issue or it might be closed for inactivity.

**Comment by AlexFreedomMod** [comment]
I'll just close it.
