### ISSUE TITLE
TFM_AdminList.addSuperadmin(player); and TFM_AdminList.removeSuperadmin(player);

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#660]
When i was trying to code another command into my plugin(This happend a few weeks ago, Also it wasnt TotalFreedomMod ) Eclipse wanted me to change TFM_AdminList.addSuperadmin(player); to
TFM_AdminList.removeSuperadmin(player); then after i made it that it wanted me to change it back, etc.

**Comment by JeromSar** [comment]
Duplicate of #659
