### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jjkatz613** [TotalFreedom/TotalFreedomMod#662]
I had a thread on the forum for this and was told to post this by @Wild1145:

I have a server at home for a few friends. (not public rather for a few close people). Anyway I get this error message and I need someway to fix it:

[14:33:18 WARN]: [TotalFreedomMod] TotalFreedomMod is compiled for v1_8_R1 but the server is running version v1_8_R2!
[14:33:18 WARN]: [TotalFreedomMod] This might result in unexpected behaviour!

**Comment by JeromSar** [comment]
@jjkatz613 Either upgrade your TFM version or downgrade your server version.

**Comment by Wild1145** [comment]
This was not the error I said to post, I was referring to the SQL error that was later, as I assumed that was what you were trying to show me.

**Comment by jjkatz613** [comment]
Well how would I upgrade TFM if I am using the latest Version on the
releases page?

On Fri, May 22, 2015 at 3:37 PM, Ryan <notifications@github.com> wrote:

> This was not the error I said to post, I was referring to the SQL error
> that was later, as I assumed that was what you were trying to show me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalFreedom/TotalFreedomMod/issues/662#issuecomment-104750216>
> .
>



-- 
Jonathan Katz
201-541-0585

**Comment by JeromSar** [comment]
@jjkatz613 You could compile from source. :)

**Comment by jjkatz613** [comment]
I don't know how to do any of that. How long does it take?

On Tue, May 26, 2015 at 1:12 PM, Jerom van der Sar <notifications@github.com
> wrote:

> @jjkatz613 <https://github.com/jjkatz613> You could compile from source.
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalFreedom/TotalFreedomMod/issues/662#issuecomment-105606387>
> .
>



-- 
Jonathan Katz
201-541-0585

**Comment by AlexFreedomMod** [comment]
Like 1 minute Or  1 second, depends on your pc.
(took me about 3 minutes to compile TFM for the first time cus i did editing)

**Comment by jjkatz613** [comment]
Then, can someone compile it for me. I need it to be version v1_8_R2. Also,
please read the original post, to see exactly what I need and when finished
please PM me on the forum with a link to the download.


On Tue, May 26, 2015 at 2:48 PM, Alex33856 <notifications@github.com> wrote:

> Like 1 minute Or 1 second, depends on your pc.
> (took me about 3 minutes to compile TFM for the first time cus i did
> editing)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalFreedom/TotalFreedomMod/issues/662#issuecomment-105632345>
> .
>



-- 
Jonathan Katz
201-541-0585

**Comment by Wild1145** [comment]
That would be against the license, and most people here are going to respect that license.

**Comment by jjkatz613** [comment]
Why is there a problem with compiling it for someone? I just need and want
it to work on my server. What is the big problem?

**Comment by AlexFreedomMod** [comment]
@jjkatz613, dont you have a developer for your server?, If so ask them to compile it with the same spigot as your server.

**Comment by jjkatz613** [comment]
It's not a public one. It's a private one for close friends but I would
like to install the latest version of tf on it.

On Tuesday, May 26, 2015, Alex33856 <notifications@github.com> wrote:

> @jjkatz613 <https://github.com/jjkatz613>, dont you have a developer for
> your server?, If so ask them to compile it with the same spigot as your
> server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalFreedom/TotalFreedomMod/issues/662#issuecomment-105700156>
> .
>


-- 
Jonathan Katz
201-541-0585

**Comment by Scuph** [comment]
@jjkatz613 this isn't our problem. If you want a working tfm, download a compiled release or get a developer.
