### ISSUE TITLE
Night Vision command

### ISSUE THREAD

**Issue by ArcticHumboldt** [TotalFreedom/TotalFreedomMod#664]
I've been trying to create a command that enables/disables night vision, but can't figure out how.

if someone could explain how (Just the basics in general), or make this an enhancement, that would be greatly appreciated.

**Comment by Scuph** [comment]
Java and simple bukkitlib/bukkit tutorials, it's not that hard!

**Comment by Wild1145** [comment]
Give the player the night vision potion affect. Shouldnt be too tricky.

**Comment by ArcticHumboldt** [comment]
I figured I'd need to make an array list, so I'm watching tutorials right now.

**Comment by Hockeyfan360** [comment]
@ArcticHumboldt 

if (player.hasPotionEffect(PotionEffect.NIGHT_VISION)
{
player.removePotionEffect(PotionEffect.NIGHT_VISION);
}
else
{
player.addPotionEffect(PotionEffect.NIGHT_VISION);
}

**Comment by ArcticHumboldt** [comment]
@Hockeyfan360 I already made it (https://github.com/TotalFreedom/TotalFreedomMod/pull/669), but thanks anyway.
