### ISSUE TITLE
Not blocking command

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#670]
![image](https://cloud.githubusercontent.com/assets/8379108/7823535/1eaacc9c-03ca-11e5-978b-7ad6de07041f.jpg)

**Comment by ArcticHumboldt** [comment]
You have /tool blocked twice in the config.

**Comment by SlicedCaek** [comment]
@ArcticHumboldt, its actually in TFM

**Comment by SlicedCaek** [comment]
I would say it is a bug, because there is no double of /tool in config.yml :-1:

**Comment by Wild1145** [comment]
We would need a pastebin of the config.yml (Or gist of the config.yml) currently running on that server where the screenshot was taken.

**Comment by AlexFreedomMod** [comment]
@ArcticHumboldt, i didnt do this. This is from TotalFreedom Logs.
