### ISSUE TITLE
New CoreProtect (can) be used

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#681]
Coreprotect just updated to 1.8, so we can now implement coreprotect in the mod, that is, if we want to. Coreprotect allows for us to check who worldedited/griefed something, and can prove so many unresolved worldedit griefs that players constantly complain about on the server. This also prevents players from quitting/leaving the server due to worldedit griefing (as all their work is put to nothing). Now the only question is, if the admins don't become liberal on this, can they finally change their minds?

**Comment by Wild1145** [comment]
There are other problems with using CoreProtect as FOP found out, its not impossible but would require a lot of re-working of how multiple things work. Its also impossible to be used with our current setup of map resets, it would only be made possible by switching to a VPS and a custom control panel where we can erase the Core Protect data on the map reset, otherwise its going to get messy as hell.

**Comment by tylerhyperHD** [comment]
Actually Ryan, due to the way the API works, it is possible to "purge"
coreprotect databases in a map reset. It only requires an API bridge and a
little bit of code to change, and it would simply purge all the logs for
that world. Meaning, it is possible, and it can be done, and we can always
keep the current rollback manager we have as well if we needed to. If you
would like me to code coreprotect for TF, then I will do so.

**Comment by Wild1145** [comment]
I like the idea, the problem that you have is not calling the API to say that the map has been reset, but allowing TFM to tell the difference between a server restart, reload and map reset. The plugin just enables and disables, meaning that if we call the CP API to do a purge of the entire database every time the plugin disables, we are really not doing any sort of major enhancement over the current log stick solution, yes core protect has a nicer logging system, but its adding another plugin and development work for no major gain.

The best solution would be to switch to a VPS with a custom control panel that can call the CP API on a map reset to request a database purge, or even better store the logs in MySQL, then when a map reset is initialized you stop the server, drop the table(s) in the DB for CoreProtect then restore the map, then start the server. The second best solution would be to get Clanforge to somehow call the coreprotect API (If thats even possible to modify how the server starts and stops on clanforge) and wipe the database when a backup is restored. 

Doing it any other way to above is kinda pointless and a bit overkill in my opinion.

**Comment by tylerhyperHD** [comment]
I was thinking to put the API inside a command that if the map is going to
reset it purges coreprotect for that specific world/map. Meaning it won't
have any effect over the server restarting, reloading, or anything in
between, and is only called when the map is going to reset. Basically, I
would have to code a new command that would trigger coreprotect to do this,
and would stop the server for the reason of a map reset, then they can go
ahead and do it. It would require a bit of training for the people that
reset the map, but it would be totally worth doing and would not require a
VPS to perform this function.

**Comment by Wild1145** [comment]
The issue you then have is the human error side of things, and what happens if the map is corrupted. You would need to reset the map, then go in game (or to console to be fair) and execute a command. You also have the issue of people running it randomly (Because there will always be that one idiot that will) and it screw everything up.

If we can do some sort of automated task in Clanforge for when a backup is restored, thats the only viable way I can see this working without migrating to a far more powerful system such as a VPS / Dedicated server and a custom panel to go with it.

**Comment by tylerhyperHD** [comment]
Then that means we would have to create ANOTHER command that if the map was corrupted it would purge coreprotect meaning it adds a step to the equation. It really isn't that hard to add these to the command list, and upgrading the VPS is a stupid idea in this case, and so what if we don't have automated tasks? You really do not need automated tasks to make coreprotect work, yet I know you are trying to create situations on if this happened or that happened, it doesn't make sense to go that far into adding a plugin when you can just create the commands and add them as a step to do and then it would be implemented!

**Comment by Wild1145** [comment]
Your talking utter rubbish. Automated tasks are the best way to do it to remove any sort of human error from the equation, these sorts of things should be fully automated, and not require human interaction of any kind. Upgrading to a VPS would be the sensible option no matter what, it would have been months ago, this is just another good reason to do it. Yes its not a requirement, but I dont see any point in adding commands after commands when we could do it in a far cleaner more efficient way.

**Comment by JeromSar** [comment]
Coreprotect is inherently incompatible with TotalFreedom due to the way player information is stored (UUID based). Rather then try to fix CoreProtect to be compatible with TFM, I think we should improve TFM's anti griefing tool instead.

**Comment by Wild1145** [comment]
I see no reason not to investigate the potential of using Code Protect instead of our in built tools, for the simple reason that it is far more comprehensive and advanced than our in built tools.
