### ISSUE TITLE
Make /ignore work

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#683]
Ever since, I have wanted to ignore players who just would bug me, but since the person is op, essentials doesn't allow you to ignore the player. It would be a great idea if we made it work.

**Comment by Wild1145** [comment]
Already Rejected by @jersomsar

**Comment by tylerhyperHD** [comment]
I believe he just doesn't have the balls to code that many lines.

**Comment by JeromSar** [comment]
I don't think this is a good idea. The chat should be displayed equally for everyone.
