### ISSUE TITLE
Lazer (TNT)  Gun not working.

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#684]
When you hold a carrot (item 141) in your hand, and toggle explosives on, it is supposed to shoot tnt (if you are a senior). After feeling the need to blow my build up, I tried it out. It did not work.

The reason of this is because 141 is a texture, not an actual item that can be eaten, crafted, or used in any way. The item should be moved to item 391 if you want it to stay a carrot.

http://minecraft-ids.grahamedgecombe.com/

**Comment by Wild1145** [comment]
I think this had something to do with them changing some stuff a while ago in the core code, but as its not used often was simply not picked up on.

**Comment by tylerhyperHD** [comment]
It might be cause it's named CARROT instead of CARROT_ITEM in the listener.

**Comment by Hockeyfan360** [comment]
Thank you, tyler.
