### ISSUE TITLE
Yaml Error

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#688]
03.06 16:40:21 [Server] ERROR Could not load configuration file: config.yml
03.06 16:40:21 [Server] ERROR org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
03.06 16:40:21 [Server] INFO in 'string', line 14, column 3:
03.06 16:40:21 [Server] INFO madgeek1450:
03.06 16:40:21 [Server] INFO ^
03.06 16:40:21 [Server] INFO expected <block end>, but found BlockMappingStart
03.06 16:40:21 [Server] INFO in 'string', line 20, column 4:
03.06 16:40:21 [Server] INFO Alex33856:
03.06 16:40:21 [Server] INFO ^
03.06 16:40:21 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57)
03.06 16:40:21 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226)
03.06 16:40:21 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169)
03.06 16:40:21 [Server] INFO at net.pravian.bukkitlib.YamlConfig.load(YamlConfig.java:107)
03.06 16:40:21 [Server] INFO at me.StevenLawson.BukkitTelnet.TelnetConfig.loadConfig(TelnetConfig.java:22)
03.06 16:40:21 [Server] INFO at me.StevenLawson.BukkitTelnet.BukkitTelnet.onEnable(BukkitTelnet.java:26)
03.06 16:40:21 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
03.06 16:40:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
03.06 16:40:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
03.06 16:40:21 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
03.06 16:40:21 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
03.06 16:40:21 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.r(MinecraftServer.java:416)
03.06 16:40:21 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.k(MinecraftServer.java:382)
03.06 16:40:21 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.a(MinecraftServer.java:337)
03.06 16:40:21 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:257)
03.06 16:40:21 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
03.06 16:40:21 [Server] INFO at java.lang.Thread.run(Thread.java:745)
03.06 16:40:21 [Server] INFO Caused by: while parsing a block mapping
03.06 16:40:21 [Server] INFO in 'string', line 14, column 3:
03.06 16:40:21 [Server] INFO madgeek1450:
03.06 16:40:21 [Server] INFO ^
03.06 16:40:21 [Server] INFO expected <block end>, but found BlockMappingStart
03.06 16:40:21 [Server] INFO in 'string', line 20, column 4:
03.06 16:40:21 [Server] INFO Alex33856:
03.06 16:40:21 [Server] INFO ^
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
03.06 16:40:21 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:400)
03.06 16:40:22 [Multicraft] Skipped 11 lines due to rate limit (50/s)

**Comment by JeromSar** [comment]
@AlexFreedomMod You have an invalid config.yml file. Check your YAML here: http://yaml-online-parser.appspot.com/
