### ISSUE TITLE
Work around death potions

### ISSUE THREAD

**Issue by KingDragonRider** [TotalFreedom/TotalFreedomMod#690]
Upon brainstorming ways to resolve the death potion issue that prevents players from respawning, I thought it might be a good idea to heal the player and remove all active potion effects if they're dead when they join.

EDIT: Apologies for the first commit. I've not done this before and realised that when I forked the repository it didn't update my previous fork of the mod from Sept 2014.

**Comment by Wild1145** [comment]
Would make sense. Probably best to clear their potion effects and then heal them.

**Comment by JeromSar** [comment]
@KingDragonRider Healing players is one way to prevent this, but there's simpler solutions. What about simply blocking death potions altogether?

**Comment by Scuph** [comment]
@JeromSar We would have to do a 

CASE {Splash Potion name goes here}

event.setCancelled(true)

In the player listener

Bottled potions aren't a problem

**Comment by KingDragonRider** [comment]
Yes, something like:

ThrownPotion potion = event.getEntity();
Collection<PotionEffect> activePotionEffects = potion.getEffects();
Iterator<PotionEffect> iterator = activePotionEffects.iterator();
while (iterator.hasNext())
{
    PotionEffect effect = iterator.next();
    if (effect.getType().equals(PotionEffectType.HEAL) || effect.getType().equals(PotionEffectType.HEALTH_BOOST) || effect.getType().equals(PotionEffectType.HARM))
    {
        event.setCancelled(true);
    }
}

I'll add it to a pull request when I can add a configuration option to disable it.

**Comment by Scuph** [comment]
@KingDragonRider don't try to get a disable configuration, just use this:

 if (!TFM_AdminList.isSuperAdmin(player))

**Comment by KingDragonRider** [comment]
@Scuph I'm thinking for other servers using TFM, if they wanted to have it disabled on their server. I guess it would be a good idea to give admins access to it, but would they ever have any use for it?

**Comment by Scuph** [comment]
@KingDragonRider If they are doing RP or anything, I guess they would want the option to bypass it, like admins bypass some things blocked for OPs.

**Comment by JeromSar** [comment]
@KingDragonRider @Scuph No need to past bits and pieces of code. That is just an implementation detail. Issues are solely for discussion on how to tackle the problem/issue.

**Comment by ValenciaOrange** [comment]
I have made a pull request regarding a possible way to block this.
#773

**Comment by Elephants111** [comment]
Also new death potion is /give [username] potion 1 16385 {CustomPotionEffects:[{Id:6,Amplifier:253}]}
