### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by jamisen10** [TotalFreedom/TotalFreedomMod#691]
What dependencies are needed for the TotalFreedomMod?

**Comment by Wild1145** [comment]
If you're compiling with Netbeans it should show you when you attempt to open the project.

I think its Spigot Server, WorldEdit, Bukkit Telnet and Essentials, I cant think of any others right now.

**Comment by jamisen10** [comment]
What essentials? SpigotEssentials or the 1.7 essentials?

**Comment by Wild1145** [comment]
I dont know, @JeromSar would have to be the one to answer that.

**Comment by jamisen10** [comment]
I guess we will have to wait c:

**Comment by AlexFreedomMod** [comment]
The essentials, essentials spawn from TF-Essentials and world edit from TF-WorldEdit

**Comment by JeromSar** [comment]
These are the build requirements (NetBeans should tell you this):
* TF-WorldEdit (download on repo)
* TF-Essentials (download on repo)
* BukkitTelnet (download on repo)
* SpigotServer

Only SpigotServer needs to be acquired from another source. :)
