### ISSUE TITLE
Block /fill

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#696]
Anyone that has admin access to TotalFreedom can see the perm-ban request I sent in here:

http://totalfreedom.boards.net/thread/24202/new-crash

Basically, you can bypass all filters and place blocks such as that everywhere, that lag because of particle spam, portal spam, etc.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/634
