### ISSUE TITLE
SelectionChangedEvent & LimitChangedEvent

### ISSUE THREAD

**Issue by Orepheus** [TotalFreedom/TotalFreedomMod#697]
I'm having a problem with the imports for SelectionChangedEvent and LimitChangedEvent. It can't find the packages me.StevenLawson.worldedit.blahblahblah. Anybody else got this problem?

**Comment by JeromSar** [comment]
@Orepheus Try redownloading [TF-Worldedit](https://github.com/TotalFreedom/TF-WorldEdit), updating the library and compiling again. :)

**Comment by Orepheus** [comment]
Thank you very much.
