### ISSUE TITLE
Gtfo params

### ISSUE THREAD

**Issue by ImScoop** [TotalFreedom/TotalFreedomMod#700]
Currently this is the first part of /gtfo

It returns the usage

which is currently /gtfo <partialname>

it needs to be /gtfo <partialname> <reason>

I will make a PR

**Comment by JeromSar** [comment]
@Scuph I'm confused as to what exactly you're trying to say here. Could you be clearer?

**Comment by Scuph** [comment]
@JeromSar If you don't enter enough arguments on gtfo, it shows the parameters, '/gtfo <partialname>'
it should be '/gtfo <partialname> <reason>

**Comment by JeromSar** [comment]
@Scuph Eh?

**Comment by Scuph** [comment]
@JeromSar Stupid github settings, let me fix it

**Comment by Wild1145** [comment]
@JeromSar Its because github formats tags like [ img ] so when he was explaining it they were removed and replaced with empty text.

**Comment by JeromSar** [comment]
Duplicate of #848

**Comment by Wild1145** [comment]
@JeromSar Not sure what the point in creating another issue was?

**Comment by ImScoop** [comment]
Yeah, that's pointless @Wild1145

**Comment by DUFCLiam** [comment]
Not a duplicate @JeromSar

**Comment by JeromSar** [comment]
@Wild1145 @Adaptified @DUFCLiam That issue was made to replace several (10+ literally) issues with (somewhat) the same suggestion. If you were to have actually read the issue (#848), you would have known this.
