### ISSUE TITLE
Block /replacenear

### ISSUE THREAD

**Issue by OnlineRepz** [TotalFreedom/TotalFreedomMod#705]
Well basically the server is crashing by people using /replacenear 6000000 dirt 0

**Comment by SlicedCaek** [comment]
@Robolawrence, it doesn't work as you don't use wand for replace near command!

**Comment by SlicedCaek** [comment]
Maybe you can reduce the number to max of 1000000...

**Comment by JeromSar** [comment]
I think that instead of blocking it, we could impose a few restrictions to the command, including the default block change limit.
