### ISSUE TITLE
Prevent players from teleporting to staff

### ISSUE THREAD

**Issue by Voidjasper** [TotalFreedom/TotalFreedomMod#707]
Since it is a rule, if a player tries to teleport to a staff member they get smited. Why not automate this process and make it easier on the admins? This could be done by checking the players rank before the teleportation is commenced. If the player is not a super admin and they try to teleport to staff member they will be warned and smited.

**Comment by Wild1145** [comment]
I dont think its really necessary, I generally dont get if a player TP's to me and I dont think that many admins do. Yes a player should ask first, and really I would rather we disable the /tp command for players and force them to use /tpa (To ask if they can TP), but I think disabling the ability for a player to TP to an admin is pointless.

**Comment by Voidjasper** [comment]
I was thinking something along those lines, but the amount of work required to rework essentials just to fix a minor "issue" isn't worth it. Thanks for your input WIld
