### ISSUE TITLE
Incorrect /setl discription

### ISSUE THREAD

**Issue by jjkatz613** [TotalFreedom/TotalFreedomMod#708]
I was coding and I came across this line in the code as apposed to another line:

@CommandPermissions(level = AdminLevel.SUPER, source = SourceType.BOTH)
@CommandParameters(description = "Sets everyone's Worldedit block modification limit to 500.", usage = "/<command>")
public class Command_setl extends TFM_Command

 TFM_Util.adminAction(sender.getName(), "Setting everyone's Worldedit block modification limit to 2500.", true);
        for (final Player player : server.getOnlinePlayers())

Read the desctiption and then see what it does.

**Comment by JeromSar** [comment]
@jjkatz613 Thanks, this needs a fix.

**Comment by jjkatz613** [comment]
@JeromSar I wasn't looking for help. I fixed it in my code but I was just saying for a future update this should be fixed

**Comment by JeromSar** [comment]
@jjkatz613 Yes, hence I'm reopening this. :P
