### ISSUE TITLE
Re-add /uall and /dtoggle

### ISSUE THREAD

**Issue by VjGamingUK** [TotalFreedom/TotalFreedomMod#709]
Suggestion to re-add /uall and /dtoggle
We had it last year with DisguiseCraft. LibsDisguise was now added.

If you forgot what they do:
/uall undisguises all players with this message:
"(player) - Undisguising all players" in red.

/dtoggle should toggle LibsDisguise.
"(player) - Disabled LibsDisguise"
"(player) - Enabled LibsDisguise"

**Comment by JeromSar** [comment]
@VjGamingUK LibsDisguise was removed again, it caused errors.

**Comment by Wild1145** [comment]
Why would we want these sorts of plugins, they never bring anything but pain and suffering :(

**Comment by tylerhyperHD** [comment]
The only issue is that there is currently no fun-producing plugins on the server and it does indeed cause pain and suffering with it.

**Comment by VjGamingUK** [comment]
@Wild1145 at least it's better than nothing. :/
Anyway, DisguiseCraft or iDisguise are still good as a replacement for LibsDisguise.

**Comment by Wild1145** [comment]
It would not be better than nothing, this is one of my personal most hated features, and was why I was so happy with TFM dropped all support for them. These plugins cause nothing but shit, and are nothing but a pain in the ass.

**Comment by tylerhyperHD** [comment]
Wild, as it is a matter of opinion, there is always chances that people override that.

**Comment by Wild1145** [comment]
Over-rule what? My opinion, because I hate to break it to you, but here at least I am entitled to my own opinion, so there is nobody on this earth that can "Overrule" it. You can ask any of the developers here, and I am reasonably sure you will get the same response, that its a pain in the ass and brings nothing but trouble. Its a crappy plugin that we should never need and or want to support.

**Comment by tylerhyperHD** [comment]
Let me put it to you this way, if your opinion is voted high, then you win, if it doesn't, then the other admins win.

**Comment by Wild1145** [comment]
I am well aware of how a democracy works, I am pointing out that your incredibly poor wording of your original argument is simply invalid.

**Comment by Robolawrence** [comment]
No. DisguiseCraft is just horrible.

**Comment by Wild1145** [comment]
Superseded by #1793
