### ISSUE TITLE
Change interval of Announcements to 5 minutes

### ISSUE THREAD

**Issue by jjkatz613** [TotalFreedom/TotalFreedomMod#712]
The code saids:

# Interval between announcements, in seconds.
  interval: 600

Rather we can change it to:

# Interval between announcements, in seconds.
  interval: 300 

Because 10 minutes between announcements is quite long.

**Comment by Wild1145** [comment]
I would agree, 5 mins sounds much better to me.

**Comment by Scuph** [comment]
@Wild1145 Agreed.

**Comment by JeromSar** [comment]
I disagree. 10 minutes is fine, especially for players who play quite a bit on TF, 5 minutes is very little.
