### ISSUE TITLE
Muted players can use /emsg

### ISSUE THREAD

**Issue by AlexFreedomMod** [TotalFreedom/TotalFreedomMod#716]
Muted players can use /emsg, /er, /eme  since they are not blocked for muted players.

**Comment by jjkatz613** [comment]
It is an easy fix in the code. There is a place for it.

**Comment by AlexFreedomMod** [comment]
mhm i just wanted to point it out

**Comment by PattyToTheWatty** [comment]
Well, for the mean time just /mute or /stfu them then block all ocmmands. ez

**Comment by looperXD** [comment]
They also could do /w /whisper /ew /ewhisper I believe

**Comment by Scuph** [comment]
@PattyToTheWatty said:
"Well, for the mean time just /mute or /stfu them then block all ocmmands. ez"

Or just make a pull request adding them to the blocked commands while muted section.

**Comment by LegendIsAwesomes** [comment]
Well, This isn't exactly a bug. I'll make a PR sorting this out.

**Comment by UltimaTheHawke** [comment]
Apologies for the kind-of bump, but this can also be used with /action as an alternative to /me. Mind blocking that when muted?
