### ISSUE TITLE
Telnet Clans Don't Show Up on the Website

### ISSUE THREAD

**Issue by Robolawrence** [TotalFreedom/TotalFreedomMod#720]
^ pretty much it. I know it isn't coded in the superadmin.yml, but it would be nice to have some sort of something that makes the TF website (totalfreedom.me) show telnet clans.

**Comment by Wild1145** [comment]
Telnet clan is not a rank, and there in lies the issue. Telnet clan is a "Made up" rank if you will by Mark, so the server doesnt have any knowledge of who is telnet and who is telnet clan, so its not something thats possible without adding it as a rank...

**Comment by Robolawrence** [comment]
Well, not really, because it is pretty real. Just because something was made a little later doesn't mean that, compared to the rest of the ranks, is "made up." People are listed on the forums as telnet clan, I'm just saying why not make them listed on the website as a telnet clan?

**Comment by Wild1145** [comment]
The point is, Telnet clan is simply a telnet admin that Mark has given access to Clan forge, its not technically a rank when you look at it. Its not like they get any additional server based permissions, its just a shiny title and the ability to do limited Clanforge actions. We would have to create an additional rank (And to be honest I am not entirely sure how that would work, the current super admin system storage do hiky is a bit meh already). If its something thats that big of a deal, it should be handled like executive admins are on the website, only being added manually.

**Comment by JeromSar** [comment]
@Robolawrence Keep in mind that the Superadmin/Senioradmin and developer lists are directly pulled from TFM running on TF. Adding Telnet Clans to that list would imply the following:
* A telnet clan rank will need to be created in TFM
* Current Telnet Clans will need to have their rank updated
* More complexity will be added to the already complex admin system.

Or:

* Telnet Clans could be manually added
* The Telnet Clan list will need to be manually updated every time a Telnet Clan leaves the admin team, or one is added.

**Comment by Wild1145** [comment]
@aggelosQQ Is it still the case that Telnet Clans are not listed on the website?

**Comment by aggelosQQ** [comment]
Yes, Telnet Clans cannot be added to the website since it is not an in-game rank.
The list is updated automatically and I can't really be bothered to add them manually.
In the end of the day, they're just telnets with panel access.

**Comment by Wild1145** [comment]
@aggelosQQ Works for me. Wasnt sure if they were manually added. 

As TFM does not differentiate between being a "Telnet" and "Telnet Clan" and there are no plans to change that, im going to close this down im afraid.
