### ISSUE TITLE
Block regen

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#722]
//regen is not blocked anymore. The server has been recently crashed with it (http://totalfreedom.boards.net/thread/24863/itamedragons)

**Comment by Wild1145** [comment]
Limits, not blocking.

**Comment by JeromSar** [comment]
@ChargedCreeper Actually, I changed my mind, sorry. If //regen poses a problem, it should be fixed manually in TF-WorldEdit to avoid server crashing.
