### ISSUE TITLE
hide IPs in /glist unban/ban

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#723]
For admins, it should show IPs banned/unbanned. So for admins, it should look something like this: "Unbanning/banning (name) and ips (ips)" If not admin, it should just say "Unbanning player (name)" etc

**Comment by JeromSar** [comment]
@Hockeyfan360 You mean, we should hide IPs?

**Comment by Hockeyfan360** [comment]
@JeromSar Essentially.

**Comment by Wild1145** [comment]
Hiding IP's are pointless, its public information and should not need to be hidden...

**Comment by PattyToTheWatty** [comment]
^ Our usernames should be blocked by now...

**Comment by looperXD** [comment]
IPs could be seen with /seen playername but only if the player is offline or it is a admin doing /seen

**Comment by JeromSar** [comment]
@looperXD Only admins can see see IPs with /seen.

**Comment by Hockeyfan360** [comment]
@Wild1145 It is more of a security thing than anything. It prevents IP lookups. (even though harmless, it is still somewhat invasive) It is another security layer, etc. It is public information for admins, but not OPs. If an admin has to unban themselves for whatever reason, their IPs are exposed.

**Comment by Wild1145** [comment]
@Hockeyfan360 The bottom line is, your public IP is just that, Public. There is no reason that it should be protected at all costs and this obsession with everyone desperate to hide their IP is just pointless...

**Comment by looperXD** [comment]
@JeromSar ops can see ip with /seen if the target is offline

**Comment by JeromSar** [comment]
@looperXD If that's true, than this is should be a bug report on Essentials.

**Comment by ScuphGamingUK** [comment]
@JeromSar yeah, check if the player is null, check if the sender is a superadmin, and then hide or show the IP.

**Comment by tylerhyperHD** [comment]
What if we changed glist ips to be fuzzy ips?

**Comment by Wild1145** [comment]
I come back to my previous comment:

>The bottom line is, your public IP is just that, Public. There is no reason that it should be protected at all costs and this obsession with everyone desperate to hide their IP is just pointless...

**Comment by JeromSar** [comment]
I agree with Ryan here.
