### ISSUE TITLE
/protectarea

### ISSUE THREAD

**Issue by Elephants111** [TotalFreedom/TotalFreedomMod#726]
/protectarea need blocked ops people about //paste or world edit blocked like worldedit.* permission.

Grief Reason.

**Comment by Scuph** [comment]
What? Please restate this with some sense.

**Comment by SlicedCaek** [comment]
@Scuph, he meant like the worldedit can grief the protect area and he want to make it blocked to ops so they can't grief the protected area!

**Comment by Wild1145** [comment]
Its already been suggested, and I believe it was something along the lines of "Impossible" last time It came up...

**Comment by looperXD** [comment]
Ops can use //paste to paste air and to grief spawn

**Comment by JeromSar** [comment]
Superceded by https://github.com/TotalFreedom/TotalFreedomMod/issues/981
