### ISSUE TITLE
Smite message

### ISSUE THREAD

**Issue by ScuphGamingUK** [TotalFreedom/TotalFreedomMod#734]
'ScuphilinaGamingUK has been a naughty, naughty boy.'
'ScuphilinaGamingUK died'

CHAT: ScuphilinaGamingUK: IM A GIRL U ****

Precisely the problem. We need to change 'boy' to 'player'. I know this has been a tradition in TFM since the start, but it is causing problems since the gender levels of MC players aren't just mostly boys and some girls, it's the same.

**Comment by JeromSar** [comment]
@ScuphGamingUK This has been suggested before: https://github.com/TotalFreedom/TotalFreedomMod/issues/358

**Comment by Wild1145** [comment]
I still think its a valid issue though... I know you and Mad are not as keen on it, but I think we should make it a more general comment...

**Comment by ScuphGamingUK** [comment]
@JeromSar Please consider this.
