### ISSUE TITLE
Make tfm bungeecord compatible

### ISSUE THREAD

**Issue by PattyToTheWatty** [TotalFreedom/TotalFreedomMod#739]
Please make a version which tfm can handle bungeecord server. The issue is when peopke  connect too the freeop server it makes them super admin.

Plz

**Comment by Adaptified** [comment]
What?

**Comment by SlicedCaek** [comment]
@Adaptified, he meant stop people getting SA when joining via Bungeecord Servers

**Comment by AlexFreedomMod** [comment]
Yeah I had my free op server on with my network and it supered everyone

**Comment by Adaptified** [comment]
Why does this happen? @SlicedCaek @AlexFreedomMod 

Give me some details so I can make a fix!

**Comment by PattyToTheWatty** [comment]
My friend (moonzy) ip forwarded his server, it still gave it to them.

**Comment by SlicedCaek** [comment]
@Adaptified, Its basically using the owner's ip to connect.

**Comment by Adaptified** [comment]
@SlicedCaek Ahh, Ok, I can make a fix for this, give me a few minutes.

**Comment by JeromSar** [comment]
@PattyToTheWatty This won't be added in mainstream TFM. As per the contributing guidelines, changes to TFM should be focused on the main TFM server: TotalFreedom. If @Adaptified can provide you with a fix, you could use his change however.

Closed.

**Comment by PattyToTheWatty** [comment]
Awesome. Thanks for that :)

**Comment by Wild1145** [comment]
You do not need to make any modifications to TFM. If you do some research into how Bungee works before trying to jump in at the deepend, you would know that you do not have to force players to end up using Bugnee as a Proxy, you can now send their actual IP's through to the servers under them.
