### ISSUE TITLE
Reporting admin abuse via 'report'

### ISSUE THREAD

**Issue by zD12** [TotalFreedom/TotalFreedomMod#741]
Hi there,
Users whom attempt to report abusing admins aren't referred to the forums, instead, merely told the user was an admin.  Hence, somewhat, promoting administrators abusing...   It isn't likely for an abusing admin to refer a user to the forums, as that admin is rouge...

Anyhow, that should probably be fixed.  Refer them to the forums...

**Comment by Adaptified** [comment]
'You can not report an admin. If they are abusing, please report it on the forums!'

That would be much better..

**Comment by PattyToTheWatty** [comment]
If this is implemented this will cause issues; No proof, spamming of commands etc.

**Comment by Adaptified** [comment]
@PattyToTheWatty No, not really. It just needs some changes.

**Comment by Wild1145** [comment]
This issue has been superseded by #1832
