### ISSUE TITLE
Ops can bypass Tempban

### ISSUE THREAD

**Issue by AvalancheYT** [TotalFreedom/TotalFreedomMod#745]
Title says it all. We have to gtfo the ops when they bypassed it.

![](http://i.gyazo.com/d77f509120f75c47277b9b285be2358f.png)

**Comment by Adaptified** [comment]
It's already been fixed, so no need to post this, the jar just needs to be updated

**Comment by JeromSar** [comment]
@Adaptified Has it, what commit?

**Comment by Adaptified** [comment]
@JeromSar It was the fact that tempban assigns no IP ban, but it was fixed.
