### ISSUE TITLE
Tempban kick message format

### ISSUE THREAD

**Issue by Adaptified** [TotalFreedom/TotalFreedomMod#748]
http://prntscr.com/7quo17

This needs to be fixed.

**Comment by PattyToTheWatty** [comment]
Whats wrong with it?

**Comment by Wild1145** [comment]
Yeah, not seeing a problem here...

**Comment by looperXD** [comment]
Don't see any thing wrong here...

**Comment by Adaptified** [comment]
The kick message, maybe instead of the broadcast message it gives in-game

you say this:

"You have been tempbanned for (time)"
"Reason: (reason) (sender)"

**Comment by TransporterMC** [comment]
Don't see anything wrong.
and plus @Adaptified, what is the point of it???

**Comment by PattyToTheWatty** [comment]
What do you mean? It still looks the same..

**Comment by JeromSar** [comment]
@Adaptified I don't see the issue here? What are you suggesting?

**Comment by Adaptified** [comment]
@JeromSar 
In game it says (sender) - blah blah blah
it says the same thing in the kick message

**Comment by PattyToTheWatty** [comment]
Isnt it supposed too?

**Comment by TransporterMC** [comment]
@PattyToTheWatty No. It is supposed to be like GTFO message but different. Something like Tempban
{Reason} - {Admin name}
