### ISSUE TITLE
Name based player data

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#749]
After some thought, I think it might be a good idea to switch back to using player names for player data. Doing this has a couple of effects:
* We can get rid of a load of UUID complications:
  * UUID spoofing
  * Async UUID polling
  * UUID storage in a database, etc
* It will be easier to purge a specific player's data, as it is easier to see which configuration belongs to who.
* There will be less false-positives with admins flagging up as logging into another admin's account
* Players will be able to change their names and get a new configuration, but since this is an offline-mode server, this can already happen.

What are your thoughts? @StevenLawson @Wild1145

**Comment by PattyToTheWatty** [comment]
YAY! If this happens...

**Comment by TransporterMC** [comment]
What do you mean about it @JeromSar, I am bit confused

**Comment by Adaptified** [comment]
@TransporterMC It's a bit above your knowledge, you will understand soon.

**Comment by Wild1145** [comment]
I dont necessarily think its something we should worry about, UUID Resolving should work just fine for any players with premium accounts (As the requirements for admin at least was)...
