### ISSUE TITLE
Ops complaining about not being opped

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#754]
Whenever a op logs into the server and doesn't get opped till a admin joins all you see is moaning and moaning. I can simply just edit the PlayerJoinEvent to add a player.setOp(true);

**Comment by PattyToTheWatty** [comment]
*facepalm* this a duplicate. And could be usefull for a griefer when they join.

**Comment by TransporterMC** [comment]
@PattyToTheWatty, duplicate to what?

**Comment by Wild1145** [comment]
There is/was a duplicate issue to this, im not sure the number but if you look through you should find it.

**Comment by LegendIsAwesomes** [comment]
@wild1145 I couldn't find it.

**Comment by PattyToTheWatty** [comment]
Its still a duplicate if me and wild still saw it :P

**Comment by Wild1145** [comment]
Its probably closed... Just do some searching through, as I am sure that there is an issue RE this that was already discussed...

**Comment by ReflexxMC** [comment]
Just realized that I made this issue and it got closed (Accepted, I think).

**Comment by ReflexxMC** [comment]
duplicated of #340
