### ISSUE TITLE
OPs with long tags, or tags with &k, &o, etc

### ISSUE THREAD

**Issue by EXPLODINGTNT001** [TotalFreedom/TotalFreedomMod#755]
we should make these commands to manage the OPs with tags with banned characters like &k in them because when a OP puts a tag with &k on, the admins usually do /nickclean (/nc) but it does not clean tags. These suggestions might be helpful and it can prevent OPs from putting troll tags.
/detag - which takes everyone's tags off.
/tagclean (/tc) which is the same as /nickclean (/nc), but it cleans the tags and shows who had the tags.

**Comment by Wild1145** [comment]
Duplicate.

**Comment by PattyToTheWatty** [comment]
*duplicate* Next time maybe have a read through the issue enachement lists :)

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/725
