### ISSUE TITLE
"Who did that?"

### ISSUE THREAD

**Issue by Chaosiity** [TotalFreedom/TotalFreedomMod#761]
Precisely the answer. Telnets should see super commands in commandspy, seniors should see telnet and super commands.

**Comment by AlexFreedomMod** [comment]
And the owner  should see all commands

**Comment by Wild1145** [comment]
We have logviewer for a reason you know...

**Comment by xDestroyer217** [comment]
@Adaptified eww, sounds like what FOPM does, we do have logviewer anyhow.

**Comment by Adaptified** [comment]
@Wild1145 It really is a pain in the ass to use sometimes. It makes it easier.

**Comment by Wild1145** [comment]
@Adaptified That is true... I just dont think there should be a need. If we cannot trust out admins to use commands properly, we need to get rid of our admins...

**Comment by Adaptified** [comment]
@Wild1145 Welcome to TotalFreedom, please use /ai to apply and then dont do your job!

**Comment by xDestroyer217** [comment]
There's no utter need to implement, though..

**Comment by tylerhyperHD** [comment]
We don't need to be stalking other admins, it just seems a bit weird and pointless to do.

**Comment by JeromSar** [comment]
Superseded by https://github.com/TotalFreedom/TotalFreedomMod/issues/913
