### ISSUE TITLE
/list -f

### ISSUE THREAD

**Issue by Elephants111** [TotalFreedom/TotalFreedomMod#764]
/list -f = View Fake famous player list...

Like... Notch, Dan, dinnerbone, etc.

What You think of this?

**Comment by Wild1145** [comment]
Quite a good idea. And shouldn't be too hard if we use our unbannable names
list.

**Comment by LegendIsAwesomes** [comment]
Just need to get the config and get all online players in a /list -f. I could attempt to make a PR about this.

**Comment by Elephants111** [comment]
Added?

**Comment by Adaptified** [comment]
Wait for @JeromSar, @Elephants111.

**Comment by Elephants111** [comment]
Alright, I am waiting for now.

**Comment by Elephants111** [comment]
Jerom Sar, Add it?

**Comment by LegendIsAwesomes** [comment]
@Elephants111 thats not how it works, A developer can rather make the code for this, or @JeromSar will put it in the next release which i am guessing he makes the code for.

**Comment by Wild1145** [comment]
@Elephants111 @LegendIsAwesomes Anyone can now open a PR for this without it just being shut down. But @JeromSar may say that he will just code it himself for the next release.
