### ISSUE TITLE
Warn not showing up for the ops

### ISSUE THREAD

**Issue by Adaptified** [TotalFreedom/TotalFreedomMod#765]
I've been using /warn for minor offenses lately, the warning shows up for the admin, not the op. This is a bug that I hope gets fixed. Let me look over the command.

**Comment by Adaptified** [comment]
After looking over, it looks like it sends the warning to the sender instead of the player.

**Comment by Wild1145** [comment]
Yup, line 49 by the looks of it needs to be changed to a player.sendmessage thing.

**Comment by JeromSar** [comment]
@Adaptified @Wild1145 I believe playerMsg can take another parameter for the sender.

**Comment by Adaptified** [comment]
@JeromSar check recent PRs.

**Comment by Wild1145** [comment]
@JeromSar Im not too sure to be honest, I just know it cant be working now because its just a different message for the admin and player message, so its either both going to the OP or both to the admin that issued the warning.
