### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by Adaptified** [TotalFreedom/TotalFreedomMod#767]
We are gonna have to tackle this sooner or later. This is just an issue for when it happens.

A stable 1.9 will be released soon enough, and we do NOT want to be so late updating like we were from 1.7 to 1.8. We have to prepare for this.

**Comment by Wild1145** [comment]
The 1.7 to 1.8 release was hindered by the legal issues of Bukkit. As such there was not a huge deal we could probably have done to sped things up.

We ultimately have to wait for 1.9 to be released, then Spigot to release their first version, then see whats broken, then fix it, then ideally give Spigot some time to iron out some bugs...

Really there is not anything we can do to prepare ourselves for 1.9, and its probably some way away yet.

**Comment by PattyToTheWatty** [comment]
You will also have to block alot of stuff, AKA explosive arrows, The other portal for the end. etc.
