### ISSUE TITLE
Total FreeDom Unban

### ISSUE THREAD

**Issue by iiD2rk** [TotalFreedom/TotalFreedomMod#769]
Please /unbanip iiD2rk /unban iiD2rk

**Comment by AlexFreedomMod** [comment]
This should be on the forums

**Comment by AlexFreedomMod** [comment]
Please make a ban appeal on forums

**Comment by iiD2rk** [comment]
Please unban me

**Comment by JeromSar** [comment]
@iiD2rk Here's is not the place to ask this. Go view the forums.

**Comment by iiD2rk** [comment]
please un the ban mod ban me agin for me say Can me Buy staff

**Comment by iiD2rk** [comment]
forums 1.8.8

**Comment by entity493** [comment]
unban me user:deathman9879

**Comment by entity493** [comment]
unban entity493

**Comment by ItzLevvie** [comment]
@entity493

Please appeal your ban over at the forums (http://totalfreedom.boards.net)

**Comment by Wild1145** [comment]
I have locked this conversation. Please use the forums, and stop posting here.
