### ISSUE TITLE
Memo to self: add /config command

### ISSUE THREAD

**Issue by StevenLawson** [TotalFreedom/TotalFreedomMod#77]
Add a /config command to manipulate config options from the command line.

**Comment by DUFCLiam** [comment]
@StevenLawson, This is a major bump but do you want this still to be made?

**Comment by DUFCLiam** [comment]
Also can I be the assignee?

**Comment by JeromSar** [comment]
@DUFCLiam This has been closed.

**Comment by DUFCLiam** [comment]
Oh.
