### ISSUE TITLE
Adding optional Reasons with /noob?

### ISSUE THREAD

**Issue by EXPLODINGTNT001** [TotalFreedom/TotalFreedomMod#775]
We should add reasons with /noob because when we /noob someone, it just says they are tempbanned, and if they decide to make a ban appeal, (even though its 5 minutes) or if they think they were banned without reasons, they can know why they are banned if /noob had reasons.
Command syntax: /noob <player> [reason]

**Comment by jjkatz613** [comment]
I vouch for this and would provide code. But where exactly is /noob in tfm.

**Comment by GangSterFlexx** [comment]
In command section/folder

So, me.StevenLawson.TotalFreedomMod.Commands.Command_noob.java

**Comment by jjkatz613** [comment]
@GangSterFlexx  It wasnt clear. I didnt find it in there.

**Comment by GangSterFlexx** [comment]
Strange... Either it been deleted or something going wrong :/

**Comment by Wild1145** [comment]
Its not designed to have a reason, just as a quick tempban for noobs. Maybe we just need to change the kick message?

**Comment by AlexFreedomMod** [comment]
Vouch

**Comment by aggelosQQ** [comment]
@jjkatz613 /noob is the /tban command, it's named tban on tf, and /noob is an aliase.

**Comment by JeromSar** [comment]
Duplicate of #848

**Comment by DUFCLiam** [comment]
@JeromSar Your one would be duplicate so change the message please.
