### ISSUE TITLE
MotD Online/Offline mode Notif

### ISSUE THREAD

**Issue by Rufure** [TotalFreedom/TotalFreedomMod#778]
I was thinking that since the server sometimes goes between the two there could be a notification of some sort saying that it's in online mode.

for example, an unfilled character would represent offlinemode, and a filled one would represent onlinemode (e.g. ○), while still being colored, like normal.

**Comment by ImALuckyGuy** [comment]
Done. I'll see how this goes.

**Comment by JeromSar** [comment]
No, since offline-mode is the default, I don't think this should be implemented.
