### ISSUE TITLE
Revisiting : WorldEdit spawn

### ISSUE THREAD

**Issue by falceso** [TotalFreedom/TotalFreedomMod#780]
Kind of grief report but I'll post that on the forums later..
OP can worldedit spawn and destroy it while it is "protectarea" . I recommend a way to clear their selection when they try to worldedit in a protected area.
I know that SilverCraftFreedom has that feature but I was not smart to know how to do it..

Btw I hope there is no dupe of this issue... *Edited I just found out this (check down)*
I just found the following issues
/up #777 
/protectarea #726 
Question about disabled blocks. #6

**Comment by GangSterFlexx** [comment]
Already suggested, Came along with "Impossible".

**Comment by falceso** [comment]
"I know that SilverCraftFreedom has that feature but I was not smart to know how to do it.."

**Comment by Obi2** [comment]
@falceso WorldEdit selections of non-admins are already cleared if they contain a protected area. Either the spawn wasn't protected, or one of certain commands that can be used within protected areas was used.

**Comment by falceso** [comment]
@obi2 Are you sure because I just use worldedit to fix the greif in a protected area

**Comment by JeromSar** [comment]
Superseded by https://github.com/TotalFreedom/TotalFreedomMod/issues/981
