### ISSUE TITLE
Server lags severely or crashed when turning onlinemode off. 

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#784]
When onlinemode is disabled, the server severely lags, or crashes, This hasn't happened in the past but is starting all of a suddon, This issue started about a month ago. @JeromSar

**Comment by tylerhyperHD** [comment]
It could be due to the fact we have more plugins on the server than we had before.

**Comment by Wild1145** [comment]
It shouldnt cause any lag...

**Comment by JeromSar** [comment]
Has to do with the UUID system. :/
