### ISSUE TITLE
Make cmdspy remember if an admin toggled itself

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#785]
So instead of just doing /cmdspy over and over again whenever the server restarts or you log into it, what if we made it so that in the playerdata it will remember if you toggled commandspy previously or not and if you toggled it on it would stay on until you toggled it off.

**Comment by Wild1145** [comment]
Sounds like a good idea.

**Comment by Wild1145** [comment]
Wrapping this into #1830
