### ISSUE TITLE
Make protectarea remember that it protected an area

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#786]
Whenever the server is restarted and an area "was" protected, it becomes unprotected due to it not being remembered somewhere that it was originally protected. We should definitely make it so that protectarea will remember that it did protect that area. This causes griefers to have an advantage and should be solved very quickly.

**Comment by Obi2** [comment]
Presumably protected areas are already saved after creation in protectedareas.dat. Perhaps they aren't being saved when the server stops or crashes abruptly.

**Comment by tylerhyperHD** [comment]
That is very true. If the plugin can read the protected areas that it has and apply them without wiping them if the server crashed, then it would be solved.

**Comment by Wild1145** [comment]
As I remember the protect area's are only saved in memory, so once we reload the server, it purges that. Its the only way to do it without us saving the protected area data into the map folder its self so that when the map is then reset, the protected area's are as well.

**Comment by ValenciaOrange** [comment]
After map wipe (wipeflatlands), they map will be empty, there's no need to protect empty.
They should be a line in wipeflatnads that removes the protectareas. (Now, its not needed, if this issue gets thru and protect areas are saved wipeflatlands should also wipe protect areas)

**Comment by JeromSar** [comment]
Superseded by https://github.com/TotalFreedom/TotalFreedomMod/issues/981
