### ISSUE TITLE
Project compiles with Java 6 JDK

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#789]
TFM doesn't compile with Java 8 JDK yet, which needs to be fixed. (it's a pretty easy one)

**Comment by jjkatz613** [comment]
It does. It works fine for me

**Comment by JeromSar** [comment]
@tylerhyperHD TFM currently compiles with JDK 7 (Java 7), but uses JDK 6 source. We don't want/need to change this.
