### ISSUE TITLE
Superadmin list Glitched

### ISSUE THREAD

**Issue by jjjaguar2000** [TotalFreedom/TotalFreedomMod#791]
For some reason,

Some admins are appearing as 'Op' my suggestion is to completely delete their admindata from the config then resuper them.

**Comment by PattyToTheWatty** [comment]
It doesnt really matter, since if you have been impostored, and you login as an 'op' with the login msg. It doesnt matter. You have same perms and etc.

**Comment by Wild1145** [comment]
Its just the way TFM authenticates. It likely means it cant match your UUID but can match your IP.

**Comment by tylerhyperHD** [comment]
It might be due to false deadbeef UUID's that aren't really deadbeef and then glitch them out.

**Comment by jjjaguar2000** [comment]
Just a recap- the superadmin list is bugged again, this time every admin is super instead of being senior/telnet when you do /saconfig info it says
Is senior admin: false when it should be true

**Comment by GangSterFlexx** [comment]
@jjjaguar2000, Check a thread that markbyron made in Super Admin Lounge, he said that he reset the uuid thingy.

**Comment by Wild1145** [comment]
The UUID's were reset, not the fault of TFM, but just the way that TFM has decided to resolve UUID's.
