### ISSUE TITLE
/coal

### ISSUE THREAD

**Issue by Elephants111** [TotalFreedom/TotalFreedomMod#792]
I thinking /coal act like /cake...

Here's http://totalfreedom.boards.net/thread/27292/coal?page=1&scrollTo=300758

and

http://prntscr.com/872ij3

**Comment by PattyToTheWatty** [comment]
Okay?

**Comment by jjkatz613** [comment]
No need for a stupid command

**Comment by JeromSar** [comment]
@Elephants111 After some thought, I don't think we want/need this.
