### ISSUE TITLE
Personal /toggle

### ISSUE THREAD

**Issue by aggelosQQ** [TotalFreedom/TotalFreedomMod#795]
Can we get a personal /toggle? like /ptoggle? For example. when admins need water for personal use, won't enable it for the entire server, just for theirselves.

**Comment by Wild1145** [comment]
Its a great idea.

**Comment by tylerhyperHD** [comment]
That could be something that would involve messing around with playerdata and other things.

**Comment by ChargedCreeper** [comment]
I dont think this is really needed though. Admins can WorldEdit in water.

**Comment by JeromSar** [comment]
@aggelosQQ I think this is too much of a hassle to implement. As @ChargedCreeper said, you could easily set water with worldedit. :)
