### ISSUE TITLE
Limit /tpo and /tpohere to admin

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#797]
/tpo and /tpohere are identical to /tp and /tphere except that the o is override, and bypasses tptoggle. IMO only admins should be able to bypass someone's teleport setting. 

Mark seems to agree also:
http://totalfreedom.boards.net/post/302169

**Comment by tylerhyperHD** [comment]
Since teleporting others is against the rules, this needs to be dealt with, either by making /tpo and /tpohere blocked or making them the same as /tp and /tphere

**Comment by ValenciaOrange** [comment]
If someone had they tp disabled, they mean they do not want to be disturbed. However, the op can still use /coords (Valencia_Orange) then /tppos

**Comment by aggelosQQ** [comment]
You can still tp others to you using /tp <name> <yourname>

**Comment by LegendIsAwesomes** [comment]
@aggelosQQ If it is blocked for SA only, ops could do /tptoggle so ops can't TP to others when they have tptoggle on.

**Comment by aggelosQQ** [comment]
Yep, but I object to this suggest as it is not a big deal, plus, it will reduce the freedom of the server.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/713
