### ISSUE TITLE
Create a command that makes Barriers appear to yourself

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#799]
I was thinking if we had a command that makes Barriers become visible to you if you turn the command on, and doesn't have a view radius of only where you look, and doesn't require you to have a barrier in your hand.

**Comment by Wild1145** [comment]
Barriers render client side when the barrier is in your hand, I dont think we could force the client side to render barriers without either putting a barrier in their hand, or client side mods.

**Comment by JeromSar** [comment]
@Wild1145 is right.
