### ISSUE TITLE
Why is /rules not a thing?

### ISSUE THREAD

**Issue by tylerhyperHD** [TotalFreedom/TotalFreedomMod#800]
Ops don't know right from wrong a ton, and that is due to the fact they think that there is no rules, which if /rules was made into the mod or at least defined, we would not have some of these rule breakers.

**Comment by tylerhyperHD** [comment]
BTW congrats TotalFreedom on having 800 issues on github!

**Comment by Wild1145** [comment]
Its an essentials command, @JeromSar or someone with FTP needs to just change the essentials config...

**Comment by tylerhyperHD** [comment]
The essentials command can simply be overridden as well.

On Tue, Aug 25, 2015 at 12:31 PM Ryan <notifications@github.com> wrote:

> Its an essentials command, @JeromSar <https://github.com/JeromSar> or
> someone with FTP needs to just change the essentials config...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalFreedom/TotalFreedomMod/issues/800#issuecomment-134662801>
> .
>
-- 

Thanks!
Tyler Wrenn
Rising Senior at Deep Run High School

**Comment by Wild1145** [comment]
@tylerhyperHD (Might want to clean up the response when you get on a laptop btw)

While true, it makes no sense to create additional commands for the sake of it, unless you plan to do what I wanted to do with IcarusMod where you would run that as the main plugin, removing the need for essentials or additional plugins all together.

**Comment by tylerhyperHD** [comment]
This additional command isn't for the sake of it, as I said, players usual
first thing going on a server is doing /rules. Meaning if this isn't
configured, we have a problem that has to be fixed.

On Tue, Aug 25, 2015 at 12:34 PM Ryan <notifications@github.com> wrote:

> @tylerhyperHD <https://github.com/tylerhyperHD> (Might want to clean up
> the response when you get on a laptop btw)
>
> While true, it makes no sense to create additional commands for the sake
> of it, unless you plan to do what I wanted to do with IcarusMod where you
> would run that as the main plugin, removing the need for essentials or
> additional plugins all together.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TotalFreedom/TotalFreedomMod/issues/800#issuecomment-134664189>
> .
>
-- 

Thanks!
Tyler Wrenn
Rising Senior at Deep Run High School

**Comment by Wild1145** [comment]
@tylerhyperHD So we just configure it, instead of writing a brand new command.
