### ISSUE TITLE
Super Admin Color Name

### ISSUE THREAD

**Issue by jjkatz613** [TotalFreedom/TotalFreedomMod#802]
If you look at an SUPER ADMIN's name it isnt the blue rather it is yellow:

<a href="http://imgur.com/slY9LTn"><img src="http://i.imgur.com/slY9LTn.png" title="source: imgur.com" /></a>

**Comment by tylerhyperHD** [comment]
The color is specified as blue for the player list name, and since no one I have spoken with says it's this color, that is a false claim.

**Comment by JeromSar** [comment]
@jjkatz613 The superadmin admin display name is yellow, as it should be.
