### ISSUE TITLE
/permban list crashes you

### ISSUE THREAD

**Issue by OxLemonxO** [TotalFreedom/TotalFreedomMod#805]
If you do /permban list on the server, it crashes you with the error:
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)

**Comment by CrafterSmith12** [comment]
I can support this. It does the same for me.

**Comment by OxLemonxO** [comment]
Logs: [04:42:02] [Server thread/INFO]: [PLAYER_COMMAND] OxLemonxO ( OxLemonxO): /permban list
[04:42:03] [Netty Server IO #3/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 80063 bytes encoded, max 32767)
[04:42:03] [Server thread/INFO]: OxLemonxO lost connection: Disconnected
[04:42:03] [Server thread/INFO]: [EXIT] OxLemonxO left the game.
[04:42:03] [Server thread/INFO]: OxLemonxO left the game.

**Comment by aggelosQQ** [comment]
http://totalfreedom.boards.net/thread/27661/permban-list-glitch

**Comment by tylerhyperHD** [comment]
When it says string is too big, that means the permban list is too big. We might need to hardcode some of these or something to free up some space.

**Comment by Hockeyfan360** [comment]
@JeromSar There is honestly no point in having the permban list command. Players can easily view permbans through the website.

**Comment by Wild1145** [comment]
Would suggest moving this to a SQL based system... Then you dont have this problem either way...

**Comment by Hockeyfan360** [comment]
@Wild1145 It may be a bit impractical, seeing that we get spam-bot attacked so frequently. It would definitely slow performance down if we had to make a connection/query each time someone tried to join. That is, unless the values are stored locally.

**Comment by Wild1145** [comment]
@Hockeyfan360 Goes back to the fact that we shouldnt be wasting our time banning spambot IP's, nor should we be range banning. It simply serves no valid purpose, as hackers will just find more proxies anyway. The more we ban the more file space we take up, and the more range bans that are associated just means that you are banning entire ISP's at a time... Moving to SQL shouldnt even be needed if we just made who / what is added to the permban list a stricter criteria.
