### ISSUE TITLE
/ro air

### ISSUE THREAD

**Issue by ValenciaOrange** [TotalFreedom/TotalFreedomMod#809]
/ro air basically does nothing. Well you could use it to calculate how many air is around  ¯\_(ツ)_/¯

**Comment by Wild1145** [comment]
It'd probably end up causing lag if anything...

**Comment by ValenciaOrange** [comment]
No, actually the server response immediately, the lag is probably cause by blocking editing/removing, since there is no real blocks removed, there is no lag. I have already tested out on my other server, it does nothing, no lag, no blocks removed.

**Comment by ChargedCreeper** [comment]
@Wild1145 yes it does cause lag. One of the supers did it a few days ago...

**Comment by DarkGamingDronze** [comment]
tbh, we need to block it to prevent serious lag/crash to the server

**Comment by JeromSar** [comment]
It should be blocked.
