### ISSUE TITLE
Limit Rcon

### ISSUE THREAD

**Issue by JeromSar** [TotalFreedom/TotalFreedomMod#811]
Due to a recent incident, we've come to the conclusion it might be a good idea to limit Rcon senders to the bare minimum.

Rcon senders would no longer be able to use wildcard, kick and banning commands.

**Comment by Explosives** [comment]
Seems like a good idea.

Really, the only intended purpouse of rcon is for adding and removing people from the SA list. Maybe opping as well.

**Comment by Wild1145** [comment]
Quite a shame really, I'd like to think those with RCON would be mature enough to use this without abuse...
