### ISSUE TITLE
Reasons in /doom

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#812]
I know this command is mainly used to quickly get rogues/abusers off the server, But i thought if we added reasons a doomed admin could understand why he was being doomed. So <doom> <player> <reason>, If a rogue admin was doomed, the senior who doomed him could supply a reason for example: /doom rogueadmin You have been suspended/doomed for griefing.

**Comment by JeromSar** [comment]
@LegendIsAwesomes No, I don't think we need this. /doom is only for excessive and severe rule breaking. If a senior admin dooms a player, it should be for a really good reason, and that o
 player, it should be for a really good reason, and that admin should know this already.

**Comment by Wild1145** [comment]
No...
