### ISSUE TITLE
Block /tool and /floodfill command

### ISSUE THREAD

**Issue by SixtyFourWarrior** [TotalFreedom/TotalFreedomMod#821]
Pls add TFM to block /floodfill command its using for grief,troll etc. /tool has /floodfill too pls block these commands
![2015-09-15_00 29 52](https://cloud.githubusercontent.com/assets/14282937/9862356/03f576bc-5b41-11e5-8612-bcaeaa6eb1a8.png)

**Comment by JeromSar** [comment]
@SixtyFourWarrior There are also legitimate usages for these commands, we won't be blocking them, sorry.
