### ISSUE TITLE
Prevent creative pvp.

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#825]
I am making this issue because my PR is in need of one and i already have the code.

https://github.com/TotalFreedom/TotalFreedomMod/pull/824 is the PR. @JeromSar

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/287

**Comment by LegendIsAwesomes** [comment]
Oh okay, there's a PR ready anyways.
