### ISSUE TITLE
Get rid of Chairs Plugin

### ISSUE THREAD

**Issue by jjkatz613** [TotalFreedom/TotalFreedomMod#836]
It has been a year and three days since the chairs plugin was installed and it has seemed to become less popular and I havent seen anyone using them lately. I think it is time to say goodbye.

**Comment by ShadowArmadyl** [comment]
You want to remove a plugin because you haven't seen someone use it? No.

**Comment by ValenciaOrange** [comment]
@jjkatz613 This is the TotalFreedomMod github, You are talking about Chairs mod. Talk about it in the fourm -.-

**Comment by ImScoop** [comment]
It also makes building anything with stairs complete fuckall.

**Comment by ShadowArmadyl** [comment]
You can disable chairs for your client with the plugin command. @ImScoop

**Comment by ValenciaOrange** [comment]
@Imscopp do /chairs off to toggle stairs for you

**Comment by xDestroyer217** [comment]
Just, close this. It has bene handled.
