### ISSUE TITLE
Overlord is not working.

### ISSUE THREAD

**Issue by xDestroyer217** [TotalFreedom/TotalFreedomMod#839]
I added myself to the overlord_ips list and to the Owners list, I tried it, and it still denies the command and as setting it as an unknown command.

**Comment by ValenciaOrange** [comment]
if you do /ov nothing happens, its like a hidden command, try /ov addme it should say ok.

**Comment by JeromSar** [comment]
It's not meant for your use.

**Comment by PacksGamingHD** [comment]
Then whats the purpose of the command @JeromSar

**Comment by JeromSar** [comment]
@PacksGamingHD An emergency backdoor to gain admin level access.

**Comment by SnowGamerMC** [comment]
CooL!
