### ISSUE TITLE
BukkitTelnet listener

### ISSUE THREAD

**Issue by OutOfYourMind** [TotalFreedom/TotalFreedomMod#842]
If a player lets say logins to telnet, it should say a message like, "(Admin) has connected to telnet."

**Comment by Wild1145** [comment]
Defeats the object of Telnet... Something that admins can use to oversee the server without those not on telnet being aware of.

**Comment by xDestroyer217** [comment]
I'd agree with @Wild1145. This isn't useful at all.

**Comment by JeromSar** [comment]
Perhaps in admin chat, at least?

**Comment by tylerhyperHD** [comment]
What I did on my server is created a new isTelnetAdmin method, which would check to see if the person is telnet or higher, then it would show to ONLY them without defeating the secrecy of telnet.

**Comment by Wild1145** [comment]
I disagree with it being broadcast at all in server, if you are keeping an eye on a potentially troubling admin you dont want to let them know you are watching.

**Comment by Wild1145** [comment]
I am going to close this down, I don't think its a great idea or will work for the server. If anyone has anything else to add, just poke.
