### ISSUE TITLE
Command Suggestions - /adminmsg

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#845]
What about a command (/adminmsg) that will message all current online players. If you wanted to talk to all the admins about something specific/non-rulebreaking you could. (/report is used for rule breakers.)

**Comment by JeromSar** [comment]
I'm confused. Is this something along the lines of /say or /broadcast?

**Comment by LegendIsAwesomes** [comment]
Kind off, Except /say or /broadcast broadcast's it over the whole server, while this would only message current online admins.

**Comment by JeromSar** [comment]
So it messages online admins? I see several issues with this approach:
* Admins cannot directly message back
* Potential spamming tool
* Very little use / no use at all.

**Comment by LegendIsAwesomes** [comment]
Admins cannot directly message back, You could dispatch a command allowing admins to reply back to it. Spamming would result in a /smite.

**Comment by JeromSar** [comment]
@LegendIsAwesomes What exactly do you mean "dispatch a command"?

**Comment by LegendIsAwesomes** [comment]
Force the player to message a admin (Ofcourse they did /adminmsg to msg them anyway), This could be used for example: A imposter was not supered (but had verified), they could do /adminmsg I have verified bla bla bla super me, to also message online staff about stuff, for example, a op built a new spawn etc.

**Comment by xDestroyer217** [comment]
No, I wouldn't allow this for a enhancement. Doesn't seem useful. @JeromSar from seeing this comment, I don't think this will help anything...

**Comment by xDestroyer217** [comment]
Also too much work on this implementation, for example in a simpler way.
/adminmsg
- Notify ops built new spawns (almost impossible)
- Message online staff about stuff, well, we can just like revamp /helpop to TFM's ways
- Also they could just like do /w for you haven't supered or something, an admins job is kinda to look at the chat majority of the time.
