### ISSUE TITLE
/smite fix

### ISSUE THREAD

**Issue by AlphaGaming** [TotalFreedom/TotalFreedomMod#846]
I really think that it would be useful to add this command enhancement to TFM "/smite [playername] [reason]"

[snip code doesn't go here]

**Comment by JeromSar** [comment]
@AlphaGaming I've removed your code from this issues. If you wish to contribute code, please make a PR. :)

**Comment by JeromSar** [comment]
Duplicate of #848

**Comment by DUFCLiam** [comment]
Not a duplicate @JeromSar

**Comment by JeromSar** [comment]
@DUFCLiam Yes it is.

**Comment by Adaptified** [comment]
@DUFCLiam You need to stop, honestly.
