### ISSUE TITLE
/glist

### ISSUE THREAD

**Issue by AlphaGaming** [TotalFreedom/TotalFreedomMod#847]
I have a thought of a command even though someone else made this and it got accepted but it look better and cleaner
"/command [banhistory] [today, lastweek, lastmonth] So if I wanted to use it I would do /glist banhistory today

User's you haved banned today: user1, user2, user3 and user4

**Comment by AlphaGaming** [comment]
Bumpity bump bump

**Comment by Pluteno95** [comment]
vouch

**Comment by mysteriace** [comment]
vouch

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/808
