### ISSUE TITLE
Can not not use /creative or /survival

### ISSUE THREAD

**Issue by Hockeyfan360** [TotalFreedom/TotalFreedomMod#851]
I ran TotalFreedomMod on a server, and one of the bugs I encountered was where I was told I could not use /gamemode, etc, and that I had to use /creative or /survival, even though I was using /creative and /survival. This was fixed with a tfm reload, but a normal reload would break it again. I suspect this has to do with the way that commands are blocked in general.

The other bug I encountered was players not being flagged as an imposter. No idea what causes this.

**Comment by PacksGamingHD** [comment]
Yeah, that happened to me

**Comment by JeromSar** [comment]
I'm confused. /gamemode is a different command, and can not be used. Does using /creative and /survival lead to problems?

What kind of problems do you have, being flagged as an impostor? I can't fix any bugs without sufficient information on how to reproduce the problem.

**Comment by Hockeyfan360** [comment]
You cannot use /creative or /survival, it gives you the "Please use /creative and /survival" message. This can be fixed by using /tfm reload. However, if someone of authority isn't online, it is a major problem. As well as that, players aren't being flagged all the time. I can't tell you how to reproduce it, but it just happens.

**Comment by xDestroyer217** [comment]
When I probably implemented /gmc or /gms over a year ago, it probs broke something in the process. But no one uses /creative or /survival...

**Comment by tylerhyperHD** [comment]
I think the real picture is we should make /gamemode as an overridden vanilla command and see what happens.

**Comment by JeromSar** [comment]
Either the bug has been fixed, or I am unable to reproduce it. Either way, I've no-one else about it.

**Comment by PacksGamingHD** [comment]
It depends if your using Essentials-TF I believe

On Tue, Mar 15, 2016 at 9:47 AM, Jerom van der Sar <notifications@github.com

**Comment by AvalancheYT** [comment]
@PacksGamingHD is correct, you must use TF Essentials.
