### ISSUE TITLE
Implement /spectator and /gmsp

### ISSUE THREAD

**Issue by RobinGall2910** [TotalFreedom/TotalFreedomMod#856]
@OxLemonxO can probably do that for you, but I want to implement this because _FOR ADMINS_, it can be useful and try to trick the player on that we arent really there and him get caught and & banned for griefing. It's also useful to just check on players instead of them saying "GO AWAY" on you.

**Comment by OutOfYourMind** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/pull/816

**Comment by OxLemonxO** [comment]
Why am I here?

**Comment by OxLemonxO** [comment]
also, what's the difference between gmsp and spectator?

**Comment by ValenciaOrange** [comment]
I don't think we could use commands in spectator mode, you would have to switch into gmc or gms to execute commands.

**Comment by JeromSar** [comment]
@ValenciaOrange Is that a vanilla feature, having all commands blocked? I don't recall that being the case.

**Comment by xDestroyer217** [comment]
@JeromSar it isn't.

**Comment by JeromSar** [comment]
This should be admin only, IMO.

**Comment by Wild1145** [comment]
^ I Agree
