### ISSUE TITLE
Command Suggestion: /saconfig verify [name]

### ISSUE THREAD

**Issue by Scribbles4321** [TotalFreedom/TotalFreedomMod#858]
I think this command should be added ingame.
When someone is marked imposter and they Verified , An admin can just /verify [Name]

Then they will be verified and supered like normal. Also it is not possible to add people who are NOT marked imposter so admins don't add random people.

This command should be available to all admins. So super admins don't need telnet to add other admins
(I know people might object cause someone might verify an imposter by accident but I still think its a good idea)

**Comment by mysteriace** [comment]
Vouuuuuuuuuuchhhhhhhhhhhhh

**Comment by Wild1145** [comment]
This completely defeats the point of telnts... I don't think this should be
implemented.

**Comment by tylerhyperHD** [comment]
I agree that it defeats the purpose of telnet yet it would allow people to verify in a quicker manner. For example if a telnet wasn't online, he/she would still be able to verify.

**Comment by ValenciaOrange** [comment]
Super is more like a trusted rank, We have many active telnets, just tell the telnets to add the admin.

**Comment by PacksGamingHD** [comment]
https://github.com/TotalFreedom/TotalFreedomMod/tree/verify

**Comment by JeromSar** [comment]
@PacksGamingHD That /verify does something different than what is suggested here.

I like the idea, but it'll have to come under a different name. Maybe /saconfig verify [name]?

**Comment by mysteriace** [comment]
@JeromSar I actually agree with @Wild1145 on this one, this would defeat the point of telnet administration.

**Comment by JeromSar** [comment]
After some point I can see your point. We need to think this through.

**Comment by mysteriace** [comment]
Exactly, if we were to add this command, what else do we need? Maybe we could provide something else in Telnet that players/supers need in-game. Honestly without adding another command, adding this would ruin the balance between the ranks. Honestly, this command seems useful, yet again, in my opinion: it would ruin the balance without adding another command. At the moment, without anyone coming up with an idea that would add a whole new, innovative, addition to telnet. Either way, I have talked enough. So yes, this is my opinion.

**Comment by Wild1145** [comment]
I think that with issues like #1727 and #164 This probably is not really needed, but I am open to further discussion if people feel this really is necessary.
