### ISSUE TITLE
Suggestion : /glist ban with reasons

### ISSUE THREAD

**Issue by Scribbles4321** [TotalFreedom/TotalFreedomMod#859]
Forum Thread : http://totalfreedom.boards.net/thread/29967/suggestion-glist-ban-reasons

I don't see anything wrong if this got added.

So , when someone gets banned offline they might not know why they got banned , Also if they want to make a ban appeal , They don't know WHO banned them.

Sooo... There should be a /glist ban with REASONS.

Command : /glist ban [Player] [Reason]

**Comment by OutOfYourMind** [comment]
Vouch.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848
