### ISSUE TITLE
Change /blockcmd Message

### ISSUE THREAD

**Issue by Rufure** [TotalFreedom/TotalFreedomMod#860]
For a while now, it's just been bugging me, the message "Blocking all commands", it just doesn't sound right. Instead, I was thinking it could be "Blocking all command input". While they should get the message in general, this is much more understandable and better looking.

**Comment by Wild1145** [comment]
I agree, re-wording the message would be a good idea.

**Comment by mysteriace** [comment]
YESH

**Comment by AlexFreedomMod** [comment]
Vouch

**Comment by JeromSar** [comment]
@AlexFreedomMod Please stop spamming 'vouch' everywhere. This is not a vouching platform, this is a development platform.

**Comment by AlexFreedomMod** [comment]
ok.

**Comment by JeromSar** [comment]
After some consideration, I think it's best the way it is at the moment.
