### ISSUE TITLE
Add multi-line MOTD support

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#868]
Putting "\n" in the MOTD should separate everything after it into a second line, instead of having to use spaces to achieve a multi-line MOTD.

**Comment by JeromSar** [comment]
@ShadowArmadyl Isn't this a feature already? Could you test this?

**Comment by OnlineRepz** [comment]
@JeromSar, I have tested it and it's working.

**Comment by DUFCLiam** [comment]
@JeromSar, Can I ask something quickly

**Comment by JeromSar** [comment]
@DUFCLiam Go ahead! :)

**Comment by DUFCLiam** [comment]
Say an issue is like #70 then how is that a duplicate? As that one can be forgotten about, and the current issue is like #9999.

**Comment by DUFCLiam** [comment]
Would that still count?

**Comment by JeromSar** [comment]
@DUFCLiam Perhaps. But mostly, when an idea is abandoned, it is abandoned forever. Issues aren't deleted so you can always search for them in the issue browser. :)

**Comment by DUFCLiam** [comment]
Thanks @JeromSar thats how most of my ones are duplicates :P

**Comment by ShadowArmadyl** [comment]
This is only a feature for the Minecraft config - not the TFM config, @JeromSar

**Comment by JeromSar** [comment]
@ShadowArmadyl Pretty sure TFM supports this out-of-the-box.

**Comment by Wild1145** [comment]
This *should* be supported in both TFM and Minecraft by default as I believe its just the way that the YAML file is parsed... Regardless of the implementation of it.

**Comment by ShadowArmadyl** [comment]
TFM does not support this out of the box, because I've tried it before on one of my previous TFM-based servers. @JeromSar

**Comment by Wild1145** [comment]
@ShadowArmadyl Please share the MOTD config you tried to use because this is something that vanilla minecraft supports out of the box...

**Comment by ShadowArmadyl** [comment]
Bump - I took a picture of what happens when you enter this into TFM config.
https://i.gyazo.com/ffd0927dd443bda30ab3215b4672a486.png

**Comment by AvalancheYT** [comment]
You can't do it in TFM Configuration. You can code it in TFM_ServerListener.java and add first motd and 2nd motd in motd

**Comment by ShadowArmadyl** [comment]
^ my point is made. I'd like this to be opened back up as this is a valid issue.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/747
