### ISSUE TITLE
Change world names

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#869]
Add a YML file in the TotalFreedomMod plugins folder titled "worlds", which allows you to change the names of the default worlds, such as "world_the_end, world_the_nether, adminworld", etc.

**Comment by jjkatz613** [comment]
Or put it in CONFIG

**Comment by ShadowArmadyl** [comment]
You'd need to regenerate the config file if you already have TFM, that just makes it annoying to do.

**Comment by Wild1145** [comment]
I see no point.. .

**Comment by ShadowArmadyl** [comment]
Elaborate?

**Comment by Wild1145** [comment]
I see no reason to duplicate both vanilla and Clanforge functionality... Its utterly pointless.

**Comment by ShadowArmadyl** [comment]
Changing world names in vanilla is overridden by TFM.

**Comment by Wild1145** [comment]
Again, why do we need to override the world names though? Clanforge does a good job of map management and this system would screw that up. Vanilla also has map management, and this just makes life **far** more difficult for everything...
