### ISSUE TITLE
Add telnet listing

### ISSUE THREAD

**Issue by ShadowArmadyl** [TotalFreedom/TotalFreedomMod#870]
Add a telnet+ feature, "/who -t", which lists all players using telnet.
Telnet users will not be listed by simply doing "/who".

**Comment by LifeAsStranger** [comment]
No, this is not a good idea.

**Comment by Wild1145** [comment]
Duplicate.

**Comment by OxLemonxO** [comment]
@LifeAsStranger Why?
This is not for telnet admins in-game,
It's for admins who are using the telnet console at the moment.

**Comment by JeromSar** [comment]
Telnet is frequently used to spy on players and admins. Hence, I don't think it's a good idea if the currently online telnet list should be public.
