### ISSUE TITLE
New "/glist" usages

### ISSUE THREAD

**Issue by ir1x** [TotalFreedom/TotalFreedomMod#871]
Add "/glist banip" and "/glist unbanip".
Managing IP bans is hard, adding this will resolve that.
This is good if you want to ban a username and unban a specific IP the username had.

**Comment by OutOfYourMind** [comment]
Glist ban and unban automatically manages the player's IP address. This is not needed.

**Comment by ShadowArmadyl** [comment]
Not if you want to unban a specific IP or ban a specific IP without it banning the username.

**Comment by OutOfYourMind** [comment]
Ahh, I see what you mean. I vouch on this.

**Comment by mysteriace** [comment]
Definatly a vouch, when wanting to ban a griefer under the name like "SkythekidRS" and "ZexyZek
" we can simply van the IP

**Comment by AlexFreedomMod** [comment]
Vouch on Ip bans

**Comment by Wild1145** [comment]
This issue has been superseded by #2031
