### ISSUE TITLE
Block /pp barrier

### ISSUE THREAD

**Issue by mysteriace** [TotalFreedom/TotalFreedomMod#876]
As said by iDelRay. This command should be blocked. It makes it hard to monitor/spy on players.

/pp barrier
/pp largeexplode

**Comment by mysteriace** [comment]
YAY!

**Comment by Wild1145** [comment]
This should be blocked within the plugin its self and not TFM.

**Comment by ValenciaOrange** [comment]
/pp hugeexplosion also acts like the barrier but more particles and aggressive
