### ISSUE TITLE
/seen shows IPs

### ISSUE THREAD

**Issue by Tigermca** [TotalFreedom/TotalFreedomMod#881]
I see no reason for OPs to get other peoples' IPs. The only sensible reason is submitting a permban request. We could get the IP in that case. This would increase players' and admins' safety.

**Comment by LifeAsStranger** [comment]
The IP is already removed in game to OPs. The only time the Ops can see the ip is when the player is offline...

**Comment by Tigermca** [comment]
Yes, thats the problem, they can get it once the player leaves.

**Comment by JeromSar** [comment]
@Tigermca This is actually more of a bug. The IP should not be visible for offline players too. However, this issue should be handled in the https://github.com/TotalFreedom/TotalFreedomMod Essentials Repository.

**Comment by Wild1145** [comment]
IP's are not "Private information" and from a legal and common sense stand point do not need to be hidden as they are in the public domain. I see no reason to block anyone viewing IP's full stop.
