### ISSUE TITLE
Freezing imposters

### ISSUE THREAD

**Issue by Adaptified** [TotalFreedom/TotalFreedomMod#883]
It seems that whenever someone is frozen after being marked as an imposter, they get unfrozen by rcon 5 minutes later. This needs to be fixed.

**Comment by Wild1145** [comment]
Its fully intentional... Its a TFM Feature.

**Comment by Chaosiity** [comment]
@Wild1145, if you aren't the said admin, no matter how long your on, you shouldn't be able to move as the admin.

**Comment by JeromSar** [comment]
@Chaosiity is right. Admin impostors should never be unfrozen until they're verified.
