### ISSUE TITLE
Enhance /report

### ISSUE THREAD

**Issue by jjkatz613** [TotalFreedom/TotalFreedomMod#884]
I think that we can enhance /report by making it that when there are no admins online that it gives you the message to report it on the forum.

**Comment by JacobMathBoy** [comment]
This looks like a good idea! :thumbsup: I have done /report many times when no admin was online!
```java
public static void reportAction(Player reporter, Player reported, String report)
{
    boolean adminOnline = false;
    for (Player player : Bukkit.getOnlinePlayers())
    {
        if (TFM_AdminList.isSuperAdmin(player))
        {
            playerMsg(player, ChatColor.RED + "[REPORTS] " + ChatColor.GOLD + reporter.getName() + " has reported " + reported.getName() + " for " + report);
            adminOnline = true;
        }
    }
    if (!adminOnline) {
        reporter.sendMessage("Please report on forums: http://totalfreedom.boards.net");
    }
}
```
Whether that's 100% accurate (if it is, it replaces the reportAction in TFM_Util) is a question.

**Comment by OxLemonxO** [comment]
actually, to the above post, you should change it to 
<code>
public static void reportAction(Player reporter, Player reported, String report)
{
    for (Player player : Bukkit.getOnlinePlayers())
    {
        if (TFM_AdminList.isSuperAdmin(player))
        {
            playerMsg(player, ChatColor.RED + "[REPORTS] " + ChatColor.GOLD + reporter.getName() + " has reported " + reported.getName() + " for " + report);
            adminOnline = true;
        }
         else 
         {
        reporter.sendMessage("Please report on forums: http://totalfreedom.boards.net");
    }
}
<code>

**Comment by Verdon-Online** [comment]
@JacobMathBoy, if you want to make commitments, please make Pull Request and follow the Contributing guidelines.

**Comment by JeromSar** [comment]
Good idea.

**Comment by Wild1145** [comment]
This issue has been superseded by #1832
