### ISSUE TITLE
/overlord block message fail

### ISSUE THREAD

**Issue by mysteriace** [TotalFreedom/TotalFreedomMod#886]
When you do /overlord it fails to block it correctly and says Unknown Command do "help" for more information or whatever. The problem is it says "help" instead of "/help"

**Comment by tylerhyperHD** [comment]
If you don't understand how TFM works, you should know that when TFM blocks a command it would block it in that form without the slash. Not to be condescending but that's a pretty stupid issue that you happened to write.

**Comment by PacksGamingHD** [comment]
It should be \"/help"\ I believe

**Comment by JeromSar** [comment]
Overlord is not meant for your use.
