### ISSUE TITLE
Disallow opping already opped players

### ISSUE THREAD

**Issue by aggelosQQ** [TotalFreedom/TotalFreedomMod#887]
To avoid the spam caused by trollers spamming /op, we should made a restriction to the /op command and not allow people OP players that are already opped.

I have this feature on my server: 
https://github.com/ImmaFreedom-Dev/ImmaFreedomMod/blob/master/src/me/StevenLawson/TotalFreedomMod/Commands/Command_op.java#L59-#L66

**Comment by xItsNickHD** [comment]
Sounds like a epic idea.

**Comment by Scribbles4321** [comment]
Vouch

**Comment by OutOfYourMind** [comment]
Apology, I didn't see the first pull request go through so I made a second.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/538
