### ISSUE TITLE
Telnet Clan. Rank IG.

### ISSUE THREAD

**Issue by RedEastWood** [TotalFreedom/TotalFreedomMod#892]
Wouldn't it be great if we could actually differentiate Telnet Clan and Telnet Admins in game?

I'm making this request to ask if TF could get a Telnet Clan Admin rank.

The prefix would be the lime color.

They would get access to all telnet and super commands plus /start, /stop and /restart.

Thanks,

Red

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/857
