### ISSUE TITLE
/prem for OPs

### ISSUE THREAD

**Issue by Scribbles4321** [TotalFreedom/TotalFreedomMod#893]
I don't know why /prem is for admins only. /prem should also be available for OPs. OPs can find out who is premium and who isn't.

**Comment by LifeAsStranger** [comment]
Unblocking /perm to ops will be just pointless.

**Comment by JeromSar** [comment]
@LifeAsStranger Unblocking a command is never pointless.
@Scribbles4321 I believe the command is blocked because it creates an async request to the Mojang API. OPs spamming the command could potentially create lag, but I'm not certain that this is really the case. Will look into this.

**Comment by JacobMathBoy** [comment]
@JeromSar I looked at the code, I thought /prem just asked if the user that's online **right now** is premium. After I looked, I was like "WOW!" :+1:

**Comment by JeromSar** [comment]
After some though, I don't think we should be doing this. OP could potentially create lag as described above.
