### ISSUE TITLE
Container item drops

### ISSUE THREAD

**Issue by ChargedCreeper** [TotalFreedom/TotalFreedomMod#901]
Currently when someone breaks a container with items in it, it drops the contents. People have been abusing this to cause lag, and give people troll items. I suggest container drops to be cancelled, or go directly into the inventory of whoever breaks the chest to stop this. If a player wants to give a friend say a customized set of armor, they could just have the friend open a chest to get it.

**Comment by JeromSar** [comment]
Don't we have an  drop feature?

**Comment by ChargedCreeper** [comment]
@JeromSar yes but it doesn't prevent the initial drop of container entities. Thus it is still useful for trolls.

**Comment by JeromSar** [comment]
@ChargedCreeper Alright, good call. I think this would be a good addition to the entity wiper.
