### ISSUE TITLE
Checking protected areas.

### ISSUE THREAD

**Issue by Scribbles4321** [TotalFreedom/TotalFreedomMod#902]
I think that when you get string an break a block , The block would come back (Just like the logstick) and give information like if the area is protected or not or who protected it and what is the protected area's name.

**Comment by JeromSar** [comment]
@Scribbles4321 I was thinking about this earlier too, and it seemed like a good idea. Thanks!

**Comment by Wild1145** [comment]
Can OP's protect areas then? or am I missing something here??

**Comment by JeromSar** [comment]
Superceded by https://github.com/TotalFreedom/TotalFreedomMod/issues/981
