### ISSUE TITLE
CommandSpy hierarchy

### ISSUE THREAD

**Issue by LegendIsAwesomes** [TotalFreedom/TotalFreedomMod#913]
What about is super admins saw ops commands (As usual), though telnet admins and telnet.Clan admins see Super Admin commands, and seniors see Super Admin, Telnet and Telnet.Clan Admin commands, and mark (Or the owner) see's all commands.

**Comment by JeromSar** [comment]
Good thinking!

**Comment by DUFCLiam** [comment]
I was thinking that for my server haha

**Comment by xItsNickHD** [comment]
Already added to UFM!

**Comment by OnlineRepz** [comment]
@xItsNickHD, what the hell are you talking about... This is TotalFreedomMod not UFM (UnlimitedFreedomMod)

**Comment by LegendIsAwesomes** [comment]
And who gives a fuck? TFM wants it, TFM gets if.

**Comment by xItsNickHD** [comment]
@OnlineRepz, I said I added it to ufm, I know this is about TFM, but I was saying it's in UFM now...

**Comment by PacksGamingHD** [comment]
@xItsNickHD no its not

**Comment by xItsNickHD** [comment]
@PacksGamingHD ofc it's not your ufm, but it's ofc mine.

**Comment by PacksGamingHD** [comment]
@xItsNickHD ok back on topic now anyways i personally think all admins should be able to see all admins commands regardless of their rank

**Comment by JeromSar** [comment]
After some thinking, I've decided that this won't be a good idea the implement for several reasons. Firstly, all commands are visible to all admins looking at the log viewer. Having a logviewer defeats the purpose of a hierarchy. Additionally, superadmins should be trusted on a certain level. Senior admins shouldn't have to review every command executed by other (non senior) admins.
