### ISSUE TITLE
More security

### ISSUE THREAD

**Issue by CreeperSeth** [TotalFreedom/TotalFreedomMod#917]
I suggest that commands like /spawnentity should be blocked. I also think that splash potions should also be blocked. This prevents people from spawn killing with death pots. Also commands like //pos1 //pos2 //sphere etc. etc. should be blocked in protected regions to prevent grief

**Comment by ReelPattytothewatty** [comment]
Splash potions can be blocked, but that's taking away peoples 'Pvp Freedom'.

**Comment by xItsNickHD** [comment]
What @ReelPattytothewatty said. It limits our 'Freedom' to players on the server.

**Comment by JeromSar** [comment]
I don't think we should. These commands are useful to TFM players. WorldEdits are already prevented in protected regions.
