### ISSUE TITLE
How to stop DeathPotions (Maybe)

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#918]
You can maybe block items being spawned in as "KillerPotion" or "TrollPotion"

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/690

**Comment by DUFCLiam** [comment]
No, This is not a Duplicate as I am wanting to block the spawning of KillerPotions and TrollPotions they where saying to heal on join.

**Comment by JeromSar** [comment]
@DUFCLiam This is a duplicate because the issue (cause) is the same. Whether the solution to that problem is different is irrelevant.

**Comment by DUFCLiam** [comment]
Ok, And can you make a Video on how to Compile TFM please.

**Comment by Wild1145** [comment]
@DUFCLiam There are about a million tutorials on how to compile TFM. If you are unable to compile it on your own then you probably should stick to using just the releases as compiling is a fairly simple step in the Java Language.
