### ISSUE TITLE
Compiling error {FIXED}

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#920]
I try to compile TFM in netbeans but it does not work is there any way to compile TFM in Eclipse?

**Comment by ReelPattytothewatty** [comment]
If you downloaded spigot from a mirroring site, it will NOT work.
You actually have to compile it with buildtools and git.

**Comment by OnlineRepz** [comment]
Patty, what the f..k are you talking about.

@DUFCLiam, please tell me which plugins you added to TFM lib

**Comment by ReelPattytothewatty** [comment]
Yeah, what the fuck am i talking about?

**Comment by OnlineRepz** [comment]
Patty, I am deadly serious, stop with that immature.

**Comment by JeromSar** [comment]
@OnlineRepz @ReelPattytothewatty I removed your comments. You are to behave on this repository or face a ban.

**Comment by Wild1145** [comment]
The TFM Project is a netbeans project. While there is the possibility that you will get it working in Eclipse it really is not the ideal solution. Netbeans is a free download and you should definitely consider using it.
