### ISSUE TITLE
Command suggestion: /suspend <Admins name>

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#921]
I have thought of a good command called **/suspend <Admins name>**

First it would broadcast <Sender> is suspending <Admins name>

And then it would go on to a command like doom except it does not ban them.

Things in []'s are optional

Things in <> need to be there

**Comment by xItsNickHD** [comment]
@DUFCLiam, this could come in handy. Basically for SNR+ it could work!

Great thinking!

**Comment by DUFCLiam** [comment]
Thanks @xItsNickHD

**Comment by ReelPattytothewatty** [comment]
No.. What if a SNR abuses? No way!

**Comment by JeromSar** [comment]
@ReelPattytothewatty What do you mean by SNR?

**Comment by OnlineRepz** [comment]
@JeromSar, he meant Seniors...

Sound a good idea, but I don't think we'll need it, our system works just fine.

**Comment by DUFCLiam** [comment]
@ReelPattytothewatty, Then why are they Senior admin? If they are not trusted?

**Comment by ReelPattytothewatty** [comment]
Liam, the command /suspend is useless.
If it's only for mark, then no. It's quicker for mark to go into console and type /saconfig delete *example name*.

**Comment by OnlineRepz** [comment]
@ReelPattytothewatty, seniors can do that aswell...

**Comment by PacksGamingHD** [comment]
we already have /doom

**Comment by Wild1145** [comment]
Duplicate functionality of doom.

**Comment by DUFCLiam** [comment]
But I changed the messages so as I could have an idea on how to make it as I was coding it with the online no Javadoc

**Comment by vladvilcu2006** [comment]
this is just /doom command

**Comment by DUFCLiam** [comment]
That is changed a bit...

**Comment by JeromSar** [comment]
Honestly, I don't think we need this. All admins who have the ability to suspend (SrA+) can simply remove admins through console with /saconfig delete. This seems like a command with very little use.
