### ISSUE TITLE
Command suggestion: /clearchat

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#922]
It can clear chat it can run an if loop like this

`[snip source]`

And this can be a Super Admin+ command  as people can say things like peoples address and we may want to hide that.

**Comment by JeromSar** [comment]
@DUFCLiam As with your other two issues, I removed the source from this issue.

**Comment by JeromSar** [comment]
This was suggested before: https://github.com/TotalFreedom/TotalFreedomMod/issues/191

Won't fix.
