### ISSUE TITLE
Command suggestion: /vanish

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#923]
It will be a Super Admin+ command so we do not get potion removed when we are trying to spot people rule breaking without them noticing we are there the code can be:

`[snip sourcecode]`

**Comment by JeromSar** [comment]
@DUFCLiam I removed to the java from this issue, please post sourcecode as a PR, not as an issue.

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/506
