### ISSUE TITLE
Fun command suggestion: /dance

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#924]
This will be for OP+ 
This uses an if loop and it makes then shift 50 times they can jump around and party.

`[snip code]`

**Comment by JeromSar** [comment]
@DUFCLiam As with your other issue, I removed the source from this issue.

**Comment by DUFCLiam** [comment]
So do I post suggestion in Pull request? With the code? @JeromSar

**Comment by JeromSar** [comment]
@DUFCLiam An open issue for a PR is required.

**Comment by JeromSar** [comment]
@DUFCLiam I don't think the minecraft server can force the player to shift, can it?

**Comment by JeromSar** [comment]
After some review, no the minecraft server can't do that. Closing.
