### ISSUE TITLE
Wow good job guys wow >:(

### ISSUE THREAD

**Issue by LunerLord** [TotalFreedom/TotalFreedomMod#927]
LOOK AT THIS >:( 

`[snip code]`

I AM USING NETBEANS 

AND WHAT I HAVE IN THE LABRRYS ARE

spigot_server
Essentials
commons-io-24.jar
BossTelnet (BukkitTelnet)
worldedit-bukkit-6.1.jar

WHAT IS WRONG!!!

**Comment by OnlineRepz** [comment]
You are using wrong version of WorldEdit, the correct WorldEdit can be found in ToalFreedom organisation.

**Comment by ReelPattytothewatty** [comment]
The title is misleading, your using the wrong type of worldedit, that was your fault. not ours.

**Comment by BossFreedom** [comment]
Oh Sorry :(
