### ISSUE TITLE
/Creative

### ISSUE THREAD

**Issue by happydude0000** [TotalFreedom/TotalFreedomMod#929]
So I compiled TotalFreedomMod and I made it to where it said HappyFreedomMod. Before I could use /gmc /creative ect.. now after I installed essentials spigot, it does not work. I do /gmc or /creative and it just says to use /creative to go into creative ect..

What I have in my library are: 
spigot.jar 
commons-io.2.4.jar
freedomtelnetclient.jar
bukkittelnet.jar
tf-worldedit.jar
totalfreedommod.jar
essentials-tf-.jar

**Comment by DUFCLiam** [comment]
This is because /gmc is a plugin specific command you have TotalFredomMod so it blocks plugin specific commands you have got to use /creative ans /survival

**Comment by ReelPattytothewatty** [comment]
Simply do /tfm reload. This will be (hopefully) fixed in TFM 5.0!

**Comment by OnlineRepz** [comment]
@DUFCLiam, no, gmc comes with TFM, you're thinking about game mode command.

**Comment by vladvilcu2006** [comment]
Remove the n:b:/gmc:Use /creative..etc  and the n:b:/gms:Use /survival...etc

**Comment by OutOfYourMind** [comment]
@OnlineRepz Yes it does, it is an aliases with /creative
