### ISSUE TITLE
Mail without sendall

### ISSUE THREAD

**Issue by supergameplayer** [TotalFreedom/TotalFreedomMod#932]
This is another simple idea to add a mail system to TFM without /mail sendall.

**Comment by DUFCLiam** [comment]
This could work or they could just block sending messages to everyone.

So block the commands for sending messages to all.

**Comment by ReelPattytothewatty** [comment]
Thats why we have admins, liam.

**Comment by OnlineRepz** [comment]
@ReelPattytothewatty, please re-read, you are on something else.

Sound great idea, revamp mail system.

**Comment by supergameplayer** [comment]
@OnlineRepz I may not be a dev, but I actually know how to delete /mail sendall myself.

**Comment by OnlineRepz** [comment]
@supergameplayer, I can do it as well.

But it's better if we block this on Essentials side instead blocking/re-creating the mail system here.

**Comment by Wild1145** [comment]
Create this issue as part of the TF-Essentials projects issues. It can be blocked on that project by modifying how essentials works with mail. Far easier way to do it.x

**Comment by JeromSar** [comment]
@Wild1145 I actually support recreating the mail system in TFM.

**Comment by supergameplayer** [comment]
A pull request was made in TF-Essentials. Continue any discussion here: https://github.com/TotalFreedom/TF-Essentials/pull/13

**Comment by JeromSar** [comment]
@supergameplayer You should read what I said. I think it'd be better if the mail system was recreated in TFM.
