### ISSUE TITLE
New ranks

### ISSUE THREAD

**Issue by LightU** [TotalFreedom/TotalFreedomMod#933]
I Got An Idea To Make New Ranks Head Reporter And Reporter please read it all .
Head Reporter Would Have Permission To Use Log Stick . And Also Use /Rollback, /jail and /smite
Reporter Would Use Log Stick and /smite But Not /rollback and /jail  
That Idea For Reporter Was Made Because That Would Be Useful like A Little Police That Would Find Out Griefers Easily And Report Them To Admins If There Not admin online They would Use command /jail
To Stop Players From Griefing . if there's not Head Reporter ON Only Reporter and no admins Reporter Could Just /smite Griefer     My nick in game Play.totalFreedom.me Is LightUk  I would like to Become Head Reporter . I Am Trying To Stop Griefers in server by /report but when no admins on it sucks and its also harder to find out griefers . Thanks for reading my idea :D I believe You Add This update To TotalFreeDomMod :DD
Sorry For my hand writing I dont really come from england So my english isnt really good :DD

**Comment by DUFCLiam** [comment]
"Would have permission to use log stick. And Also Use /rollback, /cage and /smite
Reporter can use the log stick and /smite but cannot use /rollback or /cage" - Is what us should be.

And my input:

I think this could be easy to add make it like /saconfig add <Name> except like this /griefstopper add <Name> they would have a rank in config so when they are added they get the rank they should/

**Comment by LightU** [comment]
Okay :DD So Will be This Rank Added Or not ?? :DD

**Comment by Wild1145** [comment]
Sounds very micro-management like to me... Not a huge fan.

**Comment by OnlineRepz** [comment]
No thanks,

If this exists, then what could SA do when Reporter/Head Reporter got most ability to do stuff....

**Comment by ReelPattytothewatty** [comment]
Nope.

**Comment by vladvilcu2006** [comment]
This would make the server non-freedom. Think about if someone earned that rank, he got rouge, and starting to put everyone in jails. I don't this this should be added.

**Comment by JeromSar** [comment]
I've had a very similar idea a while ago. Certain trusted players would automatically be selected by TFM, and they would get some basic moderation access. I don't quite like your version of that same idea, and I'll repost mine at a later date. Thanks for contributing.
