### ISSUE TITLE
Command suggestion: /glist banip <ip>

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#935]
It should let use admins ban IP's in the event we find an IP but not username.

**Comment by Wild1145** [comment]
I am 99% Certain this is a duplicate...

**Comment by ReelPattytothewatty** [comment]
Yes, @Wild1145. It certainly is. This has been suggested before and denied.

**Comment by Wild1145** [comment]
@ReelPattytothewatty No... The issue is already open... Its a good valid issue, but I believe its been duplicated.

**Comment by Wild1145** [comment]
Confirmed. Duplicate of #871
