### ISSUE TITLE
Block /tpo to admins

### ISSUE THREAD

**Issue by OnlineRepz** [TotalFreedom/TotalFreedomMod#936]
https://github.com/TotalFreedom/TF-Essentials/issues/12

I think it's a good idea to limit it to admins only.

**Comment by PacksGamingHD** [comment]
no

**Comment by DUFCLiam** [comment]
Give a reason why? We smite for it why not just block it to admins

**Comment by ReelPattytothewatty** [comment]
Total'Freedom',

**Comment by DUFCLiam** [comment]
Well, we can just limit it to Admin so people do not bypass /tptoggle and abuse it to grief and much more.

**Comment by Wild1145** [comment]
Please open this issue on the Essentials Github so the Essentials PR has a corresponding issue. While a valid issue it needs to be raised on that project.

**Comment by JeromSar** [comment]
I think we aren't discussing whether it should be removed completely, but rather if it should be limited to admins. Therefore, this discussion should take place on this repository, as it is a suggestion for TFM's command blocker.

**Comment by vladvilcu2006** [comment]
Blocking /tpo would limit the Freedom

**Comment by Wild1145** [comment]
@JeromSar I am reasonably confident you can restrict commands within Essentials to admins only, surly we are better off editing the command its self and not just adding more things to the blocked config for the sake of it? If not just to make it easier to navigate the TFM config?

**Comment by JeromSar** [comment]
@Wild1145 It's possible, but currently, we only partially block commands in TFM. Some extreme commands (like /nuke) are completely blocked from Essentials by commenting them out in the plugin description file. Overall, though, we mostly use TFM's command blocker.

**Comment by Wild1145** [comment]
@JeromSar Okay, makes sense.

**Comment by JeromSar** [comment]
I don't think we should. Players should be given the freedom to teleport where they would like to.
