### ISSUE TITLE
Automatic placement of name after ban

### ISSUE THREAD

**Issue by FilezPlays** [TotalFreedom/TotalFreedomMod#943]
I'm not sure if it's been suggested before but...
Presently, it is required to write your name after a ban.

eg. /ban coolguy Death pots - Filez
After they try to log in:
You are banned: Death pots - Filez

My suggestion is it automatically places the name in the ban reason when you go 
to remove someone from the server without placing the name in manually.

eg. /ban coolguy Death pots
Ban reason: Death pots (xfilez)

Hope you can think it over!
Thanks, Filez.

**Comment by ReelPattytothewatty** [comment]
I'm suprised we never thought of this.
Vouch

**Comment by DUFCLiam** [comment]
I will go and make a Pull request for this :100:

**Comment by JeromSar** [comment]
This has been implemented in TFM 5.0:
https://github.com/TotalFreedom/TotalFreedomMod/blob/tfm50/src/main/java/me/totalfreedom/totalfreedommod/commands/Command_glist.java#L86
