### ISSUE TITLE
Add /clearchat and /clearparticles

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#944]
I've got a suggestion to add /clearchat with /cc alias  and
/clearparticles It clear all particles

I put a pull request

**Comment by AlphaTZ** [comment]
/clearchat was already discussed on the forums and denied

**Comment by DUFCLiam** [comment]
Clear chat has been denied in #922 

And "clearparticals" can fall under /purgeall

**Comment by Adamx120** [comment]
It can't

**Comment by DUFCLiam** [comment]
[code]
        // Purge entities
        TFM_Util.TFM_EntityWiper.wipeEntities(true, true);
[/code]

**Comment by Adamx120** [comment]
I checked it online
It isn't

**Comment by JeromSar** [comment]
If I'm not mistaken, particles are client side only, and can not be wiped. /clearchat has been suggested and denied before.
