### ISSUE TITLE
Limit "/deopall" to senior

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#951]
#952

**Comment by JeromSar** [comment]
@DUFCLiam I don't think we should do this.

**Comment by Wild1145** [comment]
To be honest I always thought it was a senior only command...

**Comment by vladvilcu2006** [comment]
I don't even know why /deopall was added... lol

**Comment by JeromSar** [comment]
/deopall can be useful to superadmins in certain scenarios. It's use is limited, but I've never seen any abuse with it, and I think super should be granted this permission since they can impose greater sanctions (banning).
