### ISSUE TITLE
Prevent spam with /op

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#953]
#954

**Comment by JeromSar** [comment]
@DUFCLiam What exactly is the issue here?

**Comment by Wild1145** [comment]
Looks like just to have an associated issue with the PR... Kinda completely pointless...

**Comment by OnlineRepz** [comment]
Duplicate to some issue.
He wants to prevent people opping opped players

**Comment by JeromSar** [comment]
Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/538
