### ISSUE TITLE
Add reasons to /smite

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#955]
#956

**Comment by aggelosQQ** [comment]
Besides the smite reason, you've changed some other files that I would not want to see changed.

**Comment by JeromSar** [comment]
@DUFCLiam This is the third time I found you making a duplicate issue. I insist you read the [Contributing Guidelines](https://github.com/TotalFreedom/TotalFreedomMod/blob/master/CONTRIBUTING.md) and refrain from making any more issues before you understand what you're doing. 

Duplicate of https://github.com/TotalFreedom/TotalFreedomMod/issues/848
