### ISSUE TITLE
New logo (FOR GITHUB)

### ISSUE THREAD

**Issue by DUFCLiam** [TotalFreedom/TotalFreedomMod#958]
Good logo for the organisation
![tf github logo](https://cloud.githubusercontent.com/assets/16085790/11915249/cc6c993c-a695-11e5-817a-670d58b98a69.png)

**Comment by WillieGameYT** [comment]
Am hi suppose to vouch or something on these

**Comment by zD12** [comment]
@DUFCLiam, how does this involve TFM?

**Comment by DUFCLiam** [comment]
Title fixed

**Comment by rsajeey** [comment]
No.

**Comment by JeromSar** [comment]
No thank you.

**Comment by DUFCLiam** [comment]
Jerom I know hahaha
