### ISSUE TITLE
Config Annocuements Not Contains Troll/Death pots

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#972]
config.yml/Annocuer
 Messages not contains
- Death and Troll potions are not allowed!

**Comment by mysteriace** [comment]
:+1: :dancer: :accept: Accepted Issue! :accept: :dancer: :+1:

**Comment by JeromSar** [comment]
This was implemented some time ago. I cannot find the actual commit.
