### ISSUE TITLE
Add clear function to invis

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#978]
Invis smite, smiting all invis players

Invis clear, clearing all invis potion from all players

Note: It ain't a duplicate cause #959 is for removing invis smite
And it is an addition /invis clear

**Comment by OnlineRepz** [comment]
Duplicate of Issue #959

**Comment by Adamx120** [comment]
It isn't you said REPLACE smite with clear

**Comment by OnlineRepz** [comment]
@Adamx120, but it's similar to this issue.

**Comment by Adamx120** [comment]
But it is problem?

**Comment by Adamx120** [comment]
If i make a PR for adding function invis clear, Prozza will say, there are not a pair for my PR, so i created another PR.

**Comment by Wild1145** [comment]
This issue likely should be merged with issue #959

**Comment by JeromSar** [comment]
The issue is a duplicate. The problem is the same. Wether the solution is different is irrelevant. Closing as duplicate to https://github.com/TotalFreedom/TotalFreedomMod/issues/959
