### ISSUE TITLE
/a

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#982]
/a would mainly contact all superadmins as /a (text).
This possibly can be very useful if there are griefers possibly, so people don't spam it and a staff can come and see who it is without them saying it if they are invisible.

**Comment by ReelPattytothewatty** [comment]
Not really needed :/. We have /report. Admins should see it straight away.

**Comment by DUFCLiam** [comment]
I agree with @ReelPattytothewatty

**Comment by Wild1145** [comment]
This functionality does overlap heavily with /report and would likely be better as an option.

**Comment by rovertdude** [comment]
I mean for /a a bit if someone is griefing invis or as a spawn without having to message, /report requires a user, but it can help if a staff doesn't respawn that you contact them all easily. If something is wrong with this with /report somehow, I don't mind if you deny it. Maybe make it so /a isn't for reporting, or you can do /a as to ask things mainly.

**Comment by ReelPattytothewatty** [comment]
@rovertdude If it's /a and there abusing it, how will we know?

**Comment by rovertdude** [comment]
It would message all online superadmins/be seen by telnet. That's maybe what I thought might help.
btw, I didn't realize but I put respawn instead of respond.

**Comment by xDestroyer217** [comment]
@rovertdude its basically destroying the purpose of /report, this is pretty seeming useless if we have this.

**Comment by JeromSar** [comment]
Also see: http://totalfreedom.boards.net/thread/26588/totalfreedommod-feature-request?page=2

**Comment by Wild1145** [comment]
Superseded by #1804
