### ISSUE TITLE
Re-add smite while an OP want to access /saconfig

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#983]
Re-Add Smite when an op do /saconfig

I remember years ago this was in the TFM

**Comment by rsajeey** [comment]
How will OPs be able to do /saconfig list then?

**Comment by ReelPattytothewatty** [comment]
This is useless :P the command denies it straight away. so its not needed.

**Comment by Wild1145** [comment]
I don't see a point in punishing players for experimenting with commands... We have command blocking functionality for that reason.

**Comment by JeromSar** [comment]
No thank you. Only dangerous commands (like /stop) result in smiting like this.
