### ISSUE TITLE
Command "/oblivion"

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#989]
It does same like doom but without:
 - Remove target from the super admin list
 - Explosion

With:
- Rollbacks player
 - Super Admin Access

**Comment by ReelPattytothewatty** [comment]
Super admin acces + Roughness = crash the server forever.

**Comment by Wild1145** [comment]
Duplicate functionality of doom.

**Comment by Sabermc7** [comment]
Command is not needed

**Comment by xDestroyer217** [comment]
Basically what Wild said, this really should be closed.

**Comment by JeromSar** [comment]
@Wild1145 is correct. This really is a command very similar to /doom, and as the contributing guidelines say, we're not interested in very similar commands.
