### ISSUE TITLE
Fix Nicknames

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#991]
Problem with: Essentials Config

 Without nick: [SA] Adamx120

 With nick: [SA]  Adamx120 - There's the problem with the space [SA] [PROBLEM]Adamx120

So, /nick adding a space before your nickname

 Please fix it in the Essentials/config.yml/EssentialsGlobal
Set nickname-prefix: " " value to nickname-prefix: ''"

**Comment by rsajeey** [comment]
I like it how it is.

**Comment by OnlineRepz** [comment]
They put here for a reason, so they know if they are using nicks or not.

**Comment by Wild1145** [comment]
Yeah, its actually just an essentials config option, we have it as a space instead of the ~ default symbol.

**Comment by JeromSar** [comment]
We have a space to differentiate a player with a nickname from a player without one. It serves a purpose.
