### ISSUE TITLE
/kick command

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#992]
Example:

You:
 Input: /kick Adamx120

TFM:
 Sender - Kicking Adamx120 from the server

 Player:
 You have been kicked from the server
                 Reason: %reason

**Comment by xDestroyer217** [comment]
no. it already says most of the time kicking someone by Spigot itself

and it says the reason as well.

**Comment by JeromSar** [comment]
After some thought, I don't see any problems with a /kick command in TFM.

**Comment by Sabermc7** [comment]
Done, view the forked source code here:
https://github.com/TotalFreedom/TotalFreedomMod/compare/master...Sabermc7:patch-3

**Comment by JeromSar** [comment]
@Sabermc7 Please read the contributing guidelines and then make a PR. :)
