### ISSUE TITLE
How to save builds

### ISSUE THREAD

**Issue by Adamx120** [TotalFreedom/TotalFreedomMod#995]
I have a suggestion for command
/helpsavebuilds for OPs to help they: How to save their builds

I'll make a pull request soon for this command

**Comment by ReelPattytothewatty** [comment]
Why not just ask an admin?

**Comment by Wild1145** [comment]
This would go against the contributing guidelines under the whole "no walls of text commands"

**Comment by JeromSar** [comment]
This is covered by https://github.com/TotalFreedom/TotalFreedomMod/issues/423
