### ISSUE TITLE
/chatcooldown

### ISSUE THREAD

**Issue by rovertdude** [TotalFreedom/TotalFreedomMod#996]
I think something like /chatcooldown could be good. It might be only be able to be used by Super Admin+. It would add a chat cooldown that maybe Super Admin+ only can bypass. It might be useful when people are spamming or chat chaos or if the server's being botted.

**Comment by Adamx120** [comment]
Total'Freedom'

**Comment by ReelPattytothewatty** [comment]
Thats why we have senior and telnet admins for?

**Comment by Wild1145** [comment]
I think there should be the option to enforce a cooldown period. It would be handy when you are getting spambots, however TFM should auto kick them. I like the idea as an administrative tool that can be toggled for short amounts of time as necessary.

**Comment by OnlineRepz** [comment]
I am pretty sure that this is a duplicate.

**Comment by DUFCLiam** [comment]
Duplicate of #677

**Comment by JeromSar** [comment]
Also of https://github.com/TotalFreedom/TotalFreedomMod/issues/798
